### ISSUE TITLE
Subchart within a subchart

### ISSUE THREAD

**Issue by TagHaendler** [louisnw01/lightweight-charts-python#10]
Hi,

I was wondering how I can create a subchart within a subchart. If we take both of your examples, I would want to create a 4x4 layout, so 4 charts and all of them should have a 0.2 height subchart for RSI. Is this possible as of now or how could I do this? I was thinking maybe 4x8 chart, but this didn't work.

On a note, is there a way to change the color of lines?

Thanks!

**Comment by louisnw01** [comment]
This is possible; if you read the docs' section on `create_subchart`, there is a section on its `sync` parameter, which allows the `SubChart` to be linked to any other chart specified with its `id` attribute.

As for changing line colours, this is possible within the `create_line` method.

**Comment by TagHaendler** [comment]
Thanks for your reply. I really missed the color part in the documentation. Could you please elaborate on the sync parameter. I am trying to use it but it somehow has no effect for my charts and subcharts. I tried the same as in the docs and different versions in my code.

I have a further question regarding the horizontal lines. They work perfectly so far, but I want to plot pivot points for a session and then new pivot points for the next. But I didn't manage to start a horizontal line at timestamp x and stop it at timestamp y. Is there a way to do this?

**Comment by louisnw01** [comment]
All the sync parameter does is subscribe the `Subchart` that is being created to the parent chart or given chart's UUID to the declaring charts visible time range.

For example, if you subscribe chart2 to chart1, (`chart2 = chart1.create_subchart(sync=True)`), now when you move chart1's time scale by scrolling or clicking, chart2's time scale will follow this movement. 

This is useful for specific indicators like MACD and RSI, where they exist on a separate pane.

**Comment by louisnw01** [comment]
In your specific use case, of having 4 charts all with RSI/MACD, you would need to create a total of 7 `SubChart` objects, not including the main `Chart`. You should define the first `SubChart`, which would fill out the top row, then two more `SubChart`s, acting as the MACD for the two above, then two more `SubCharts` as candlestick charts and finally two more `SubCharts` acting as the MACD for the previous 2.

**Comment by TagHaendler** [comment]
It worked perfectly, thank you very much! I still have many questions but will first work on my code and maybe will solve some issues along the way. You're doing great work!
