### ISSUE TITLE
Drawings based on Line show up in the legend + Legend float position

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#101]
This is an example of long only trades. The eyes with no values reflect all the trendlines showing where the entry took place and where it exited. I am wondering if legend visibility should be on indicator, line, ray, trendline level and not on the chart level as it is now....

Is there is a possibility to "Name Legend Group" and then add lines/trendlines/indicators to them so they can be toggle on/off, visible/not-visible 

Also is there any ability to create ncols or float legend to the right for indicators....

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/53246aed-a975-42a9-99dd-28121c7782ff)

**Comment by louisnw01** [comment]
Hey @karunkrishna,
 
Yea this shouldn't be happening. Will fix in the next version.

Louis

**Comment by louisnw01** [comment]
I'll also look into legend float position.

**Comment by louisnw01** [comment]
Drawings will no longer show up in legend.

Louis
