### ISSUE TITLE
Implementing histogram on subcharts for pnl distribution analysis and indicators

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#104]
Much like you are able to see volume on the main chart possible to implement histogram on subchart? Not sure if this api already exists 
Here are the benefits: 
1. MACD indicator and a few other indicators use histograms
2. When a trade exits, you can plot the PNL on a sub chart
3. Users can use it for plotting Trade PNL distribution on a separate chart

I think tradingview lightweight charts have the api: available https://tradingview.github.io/lightweight-charts/docs/api/interfaces/HistogramData

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/d5ee5abd-bba2-4b0b-9386-9f285b2eb4d0)
![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/ad90cba7-7794-4724-a529-4524029b2071)

Would be nice to be able to color bars above and below 0 line different colors

**Comment by louisnw01** [comment]
Hey,

At the moment this is possible to implement by providing a dataframe to `set` with ohlcv columns, but only containing data in the volume and time columns. You can then play with `volume_config` to get the scaling correct.

However, I do think a `create_histogram` is needed. Will look to implement in the future.

Louis

**Comment by louisnw01** [comment]
Added the `create_histogram` method in the latest version.

Louis
