### ISSUE TITLE
Resize main and subchart at the same time

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#105]
Reference to https://github.com/louisnw01/lightweight-charts-python/issues/92

Trying to implement hide/show indicator feature to free up real-estate 

topbar is actually applied to a chart or subchart, It does not have a reference to main chart
How do I go about identifying the main chart vs subchart so I can set the resize on that object?
Does chart expose a list of chart windows I can get the object from and apply resize based on what button was clicked?

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/ed01f3cf-311f-4b2e-9461-0832df4a2b01)

Also when I set a height to 0; I would almost expect the window to collapse and only leave the topbar if defined for that subchart...

Alternatively if I apply the topbar on main chart. It does not affect subchart... 
Setting main chart to be height=1 results in it expanding but hidden behind the sub chart
And height=1 results in chart disappearing but still taking up space

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/7764b7b1-d43b-426d-bdb3-4079c8b820f0)

**Comment by louisnw01** [comment]
> How do I go about identifying the main chart vs subchart so I can set the resize on that object?

```python
def on_something(chart_obj):
   # use subchart variable from before:
   subchart.resize(0, 0.1)
   # or if you want to indentify the chart which was given:
   if chart_obj == chart:
      ...
   elif chart_obj == subchart:
      ...

if __name__ == '__main__':
   chart = Chart()
   subchart = chart.create_subchart()
   # topbar/event code
```


> Also when I set a height to 0; I would almost expect the window to collapse and only leave the topbar if defined for that subchart...

Heights are not relative to each pane unfortunately, so you have to change the size of all charts/subcharts in order to change the layout within the window.

Let me know if you need any more help.

Louis

p.s in the future provide the code in a code block rather than a screenshot!

**Comment by karunkrishna** [comment]
That helped point me in the right direction....However ran into another issue. I think if you want to show or hide a subchart you might also need the ability to reorder the subchart sequence 

For example hiding RSI-subchart and setting main chart to overlap it resulted in RSI chart being hidden. However if tried to hide MACD-subchart which is after RSI the resize still overlaps the still visible RSI

Thoughts? 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/aaafd273-a124-4938-8398-c27fbcabfed0)

**Comment by louisnw01** [comment]
This appears to be a bug; i'll look to fix in the next update.

Louis

**Comment by louisnw01** [comment]
Fixed in the latest version.

Louis
