### ISSUE TITLE
Enhancing the topbar 

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#106]
1. Is there a way to remove a button/element from topbar?
2. For buttons Is it possible to pass in func *arg and **kwargs  or event details so that the on_button_press event has additional context of what the topbar element  triggered the event? This way we can have a common function that can transform to different action based on state 
3. Is it possible to update the function of a button? Right now only see example for setting value of button

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/27040059-1ee2-43aa-a923-35523ad73b5c)

For example say your chart had multiple indicators to show/hide, you would need to implement multiple func to support which button triggered the event 

        "Hide RSI" if chart.topbar['rsi_indicator'] == 'Show RSI'
        "Hide MACD" if chart.topbar['macd_indictor'] == 'Show MACD'

Possible to also include an option for dropdown in topbar?
- This will allow users to be explicit with options; for example only select symbols or indicators that have been implemented 
- Multiselect would also be excellent addition to be able to show many overlays (indicators, trade markers, trendlines, subcharts)

**Comment by louisnw01** [comment]
Use `lambda` functions to pass arguments:

```python
def on_button(chart, button):
   if button == 'button_1':
      ...
   elif button == 'button_2':
      ...

chart.topbar.button('button_1', 'Off', func=lambda c: on_button(c, 'button_1'))
chart.topbar.button('button_2', 'Off', func=lambda c: on_button(c, 'button_2'))
```

Dropdown is not planned at the moment (same functionality can be achieved with switchers).

Multiselect can be achieved using multiple buttons.

Louis

**Comment by louisnw01** [comment]
Edit: Actually I will implement dropdown as it would make sense to include. 

Louis
