### ISSUE TITLE
Resize chart does not fix legend

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#107]
Looks like #105  chart resizing works now.
However there is an issue on the legend not disappearing when chart height is set to 0 for that chart

You  can see that the RSI 2 is overlay the MACD

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/40c4644a-3b9f-476d-861c-ae323b5e6d84)

**Comment by karunkrishna** [comment]
```
import pandas as pd
from lightweight_charts import Chart


def calculate_sma(df, period: int = 50):
    return pd.DataFrame({
        'time': df['date'],
        f'SMA {period}': df['close'].rolling(window=period).mean()
    }).dropna()


if __name__ == '__main__':
    chart = Chart(inner_height=0.5)
    chart.legend(visible=True)

    df = pd.read_csv('ohlcv.csv')
    chart.set(df)

    subchart = chart.create_subchart(position='bottom', height=0.25, width=1)
    subchart.legend(visible=True)
    line = subchart.create_line('SMA 20')
    sma_data = calculate_sma(df, period=20)
    line.set(sma_data)

    subchart_2 = chart.create_subchart(position='bottom', height=0.25, width=1)
    subchart_2.legend(visible=True)
    line_2 = subchart_2.create_line('SMA 100')
    sma_data = calculate_sma(df, period=100)
    line_2.set(sma_data)

    def _hide(chart):
        chart.resize(height=0)


    subchart.topbar.button('hide_subchart1', 'Hide Me', func=_hide)

    chart.show(block=True)

```

**Comment by louisnw01** [comment]
Thanks. This is a bug and will be fixed next update.

(btw, I didn't see your sponsor until now; thank you!)

**Comment by louisnw01** [comment]
Hey,

Latest version of the github repo should have fixed this issue; let me know if it works, and I will release in a new version soon.

**Comment by karunkrishna** [comment]
main branch fixed the legend issue. I don't see overlap of legend anymore on hide

There are a few things I need to go back and implement but not sure if there are any examples or docs out yet for those features. You've been knocking a lot of the open items too fast....lol

Things I need to test
- Verify downtown feature and mutate chart and subcharts based on selection 
- Verify histogram is able to generated bar plot
- "Table" row on_click  to setVisibleRange of main and subchart for trade start and end time

I'll be traveling for a few days, so may only get to this in a weeks time.

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/d8a5ec9b-d22c-4984-a2db-162ddee1edde)

**Comment by louisnw01** [comment]
No worries; and yea I've had a quiet few weeks!

New version has all of these implementations.

Louis
