### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by GabinTB** [louisnw01/lightweight-charts-python#108]
### Expected Behavior

```Python
import pandas as pd
from lightweight_charts import Chart

if __name__ == '__main__':

    # Columns: time | open | high | low | close | volume 
    df = pd.read_csv('ohlcv.csv')
    chart = Chart()
    chart.set(df)
    chart.show(block=True)
```

### Current Behaviour

When I run the simple 'get started' code to show the example chart, I get this error:

`webview.util.WebViewException: You must have either QT or GTK with Python extensions installed in order to use pywebview.`

### Reproducible Example

```python
running `python3.11 main.py`
```

### Environment

```markdown
- OS: Linux
- IDE: Visual Code Studio
- Python version: 3.11
```

**Comment by louisnw01** [comment]
https://pywebview.flowrl.com/guide/installation.html

**Comment by GabinTB** [comment]
I already installed and checked library versions (Qt and GTK)

**Comment by louisnw01** [comment]
does this produce the same error?

```python
import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/')
webview.start()
```

**Comment by GabinTB** [comment]
Yes!

**Comment by louisnw01** [comment]
Well the error message suggests you don't have Qt or GTK installed.

If that doesn't work I'd reread the installation guide on pywebview's website, and if still nothing then raise an issue to their devs.

Louis

**Comment by GabinTB** [comment]
I did, i am waiting for their reply now, thanks for your help and great job for this repo :)
