### ISSUE TITLE
[BUG] Toolbox don't work with QtChart

### ISSUE THREAD

**Issue by mcanavarros** [louisnw01/lightweight-charts-python#111]
### Expected Behavior

Enabling toolbox on QtChart should work the same as when using Chart.

### Current Behaviour

When running the PyQt example from the documentation (https://lightweight-charts-python.readthedocs.io/en/latest/examples/gui_examples.html) and enabling the toolbox flag on the QtChart declaration, you will get the following error when trying to draw anything:
`AttributeError: 'QtChart' object has no attribute 'handlers`

Since the main issue is the fact that the Bridge is declared with self and the QtChart does not declare the handlers attribute as a simple workaround, I've been doing:
```
chart = QtChart(widget, toolbox = True)
chart.handlers = chart.win.handlers
```

### Reproducible Example

```python
import pandas as pd
from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget
from lightweight_charts.widgets import QtChart

app = QApplication([])
window = QMainWindow()
layout = QVBoxLayout()
widget = QWidget()
widget.setLayout(layout)

window.resize(800, 500)
layout.setContentsMargins(0, 0, 0, 0)

chart = QtChart(widget, toolbox=True)

df = pd.read_csv('ohlcv.csv')
chart.set(df)

layout.addWidget(chart.get_webview())

window.setCentralWidget(widget)
window.show()

app.exec_()
```

### Environment

```markdown
- OS: Windows 10 19045
- Library: 1.0.17.4
```

**Comment by louisnw01** [comment]
Hey @mcanavarros, 

Thanks for pointing this out. This bug affects Qt and Wx, will fix in the next update.

Louis

**Comment by louisnw01** [comment]
Fixed in the latest version.
