### ISSUE TITLE
Tweak implemetation of `hotkey` method

### ISSUE THREAD

**Issue by jamesbaber1** [louisnw01/lightweight-charts-python#113]
### Description

I would like to add support for more hotkey events. I have been digging through 
https://github.com/louisnw01/lightweight-charts-python/blob/8f65a7fc964c9fb54162925e1e5fae417c421a9a/lightweight_charts/abstract.py#L851

And it it is prefixing every string with `Key`. This is great for simplifing adding number and letter hotkeys, but I dont think it is possible for some of the other keys like space bar and arrow keys.

### Code example

Here is my code example
```python
chart.hotkey('shift', 'Space', pause_event)
```

This generates this is javascript
```javascript
window.obpbhfcp.commandFunctions.unshift((event) => {
                if (event.shiftKey && event.code === 'KeySPACE') {
                    event.preventDefault()
                    window.callbackFunction(`('shift', ('space',))_~_space`)
                    return true
                }
                else return false
            })
```

This issue is the js keycode for space is `Space` not `KeySPACE`.

### Method of implementation

Here is a spacebar event for example
![image](https://github.com/louisnw01/lightweight-charts-python/assets/31859220/6b180f4a-a5e6-4a4e-8387-70087a2c28bb)

What are your thoughts on letting the user pass an explict js key code? Also what are your thoughts on allowing the user to not have to specify a modifier key?

I could volunteer to help with this, I just want to make sure I am taking the right approach out of the 2:
1. Add in a `js_keycode=False` kwarg and handle no modifier and the js_keycode accordingly. Would help not introduce breaking api changes.
2. refactor the hotkey method and update the examples and docs

What would you reccomend? Thanks

**Comment by jamesbaber1** [comment]
Well actually, I dont think I can do what I am saying without change the order of the function signature to make the modifier keys optional

**Comment by louisnw01** [comment]
Merged; I also made a few modifications myself to allow for key commands which involve a modifier key and a non alphanumeric key (eg `alt`+`]`).

Let me know what you think!

**Comment by jamesbaber1** [comment]
Awesome!
