### ISSUE TITLE
Ability to change background color for given time ranges 

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#115]
### Description

By applying overlay color it may be possible to indicate when a trade conditon is active, or visually indicate chart conditon

Something similar to this 
https://www.tradingview.com/pine-script-docs/en/v4/annotations/Background_coloring_with_bgcolor.html

**Comment by louisnw01** [comment]
Hey @karunkrishna,

You would have to use `vertical_span` to achieve this, as there is no way to color individual sections of the chart background in Lightweight Charts.

Louis
