### ISSUE TITLE
How to highlight the indicator (like moving averages) in different colour?

### ISSUE THREAD

**Issue by mtech2008** [louisnw01/lightweight-charts-python#116]
### Question: How to hightlight the indicators in different colors?

First of all many thanks for such a wonderful work. I have tried many things in the past but none gone so smooth as with your this package. 

Say, I want to add a indicator to a chart, but want to show it i mixed colors. Say for instance if MA is increasing then I'll change the color to green, if decreasing then in red and black if last vaue of MA equls to Current MA value. How to achieve this?

I came across some of the discussions at following URLs which is related to this:
 Custom color for items of candlestick and line series #195 @
https://github.com/tradingview/lightweight-charts/issues/195
![](https://user-images.githubusercontent.com/17275314/64414888-70adce80-d0a9-11e9-8f9c-c6d1c5e8fee2.png)
nd line series #881 @
 Added support for custom colors for candlestick, bar a
https://github.com/tradingview/lightweight-charts/pull/881

**Comment by louisnw01** [comment]
Hey @mtech2008,

Glad your enjoying it!

You can add another column to the line dataframe, `color`, with a css/html color.

Louis

**Comment by mtech2008** [comment]
Thank you so much.
