### ISSUE TITLE
How to get time and OHLC series of a current bar?

### ISSUE THREAD

**Issue by mtech2008** [louisnw01/lightweight-charts-python#117]
### Question

I was experimenting with your following code:
import asyncio
import pandas as pd
from lightweight_charts import Chart

async def data_loop(chart):
    ticks = pd.read_csv('ticks.csv')
    
    for i, tick in ticks.iterrows():
        if not chart.is_alive:
            return
        chart.update_from_tick(ticks.iloc[i])
        await asyncio.sleep(0.03)
        i += 1
        
        
def on_new_bar(chart):
    print('New bar event!')
    
    
def on_timeframe_selection(chart):
    print(f'Selected timeframe of {chart.topbar["timeframe"].value}')

async def main():
    chart = Chart()
    chart.events.new_bar += on_new_bar
    
    chart.topbar.switcher('timeframe', ('1min', '5min'), func=on_timeframe_selection)
    
    df = pd.read_csv('ohlc.csv')
    
    chart.set(df)
    await asyncio.gather(chart.show_async(block=True), data_loop(chart))
    

if __name__ == '__main__':
    asyncio.run(main())

Say in live updating of the chart on tick I want to calculate the new value of an indicator so that I can update the line chart. I can see that in the above code in **_on_new_bar event_** we can get the OHLC series using _**chart._last_bar**_ but I am not sure what could be the best way to calculate the new value of indicator and update the line chart. I pinescript of treding view we can get OHLC of a current live bar. Is it possible to get current bars OHLC say like **_chart._current_bar_**?

**Comment by louisnw01** [comment]
Hey @mtech2008,

`chart._last_bar` is the latest bar, so the same thing as current bar. You can also use `chart.candle_data` to get all candle data up to the present.

**Comment by mtech2008** [comment]
def on_new_bar(chart):
  print(chart._last_bar)

Yes it gives the values of the latest bar. But of the bar which has been rendered completely and not of the live bar which is rendering.  I want the OHLC of the current bar which is rendering from the tick data and not completely rendered.

**Comment by louisnw01** [comment]
`new_bar` emits right before the the timeframe changes, when data has not been rendered within the bar at the next time interval.

May i ask why you need this functionality? It would be possible to do, but the open, high, low and close datapoints would be identical as only one tick would have loaded into that bar.

**Comment by mtech2008** [comment]
Yes it is possible to do by using Pandas resampling the dataframe like: `resample_LTP = data['LTP'].resample('1min').ohlc()` but I do not want it that way.
Here is what I am doing.
I have developed a strategy and an indicator using pine script in trading view and I want to implement it a fresh in python. 
1. I am loding historical data for a time frame say "1Min" and rendered it.
2. Calculated indicator values and highlighting the trends using different colors using line chart.
3. next I am rendering the live candlesticks using tick data ( Here the `new_bar` event is fired) in this event call I want to calculate the new value of the indicator which will keep changing as live bars OHLC will keep changing. 
4. Based on some conditions on the indicator values I can add a marker now to  displayva buy or sell signal.

We already have all the historical data and and Tick data with us which can be used for processing. But if we can get candlestick OHLC date-time data on event. in this case `new_bar` I think it would make processing easier. In pine script we can get live bar data usine `open close low high` and previous bar as `open[1]  close[1]` etc. simillarly `close[n] ` for `n th` bar back. 

Please suggest me how I can go about it.

**Comment by louisnw01** [comment]
>  in this event call I want to calculate the new value of the indicator which will keep changing as live bars OHLC will keep changing.

`new_bar` only fires at the beginning of each new bar. If you need a continuously updating indicator, then you can update it within your code which recieves the tick data.

Both `chart._last_bar` and `chart.candle_data` are updated in real-time as ticks are added through `update_from_tick`.

**Comment by mtech2008** [comment]
[Add API to get chart values (data, markers, etc) #414](https://github.com/tradingview/lightweight-charts/issues/414)
  
[Api methods for getting data by index #934](https://github.com/tradingview/lightweight-charts/pull/934)

**Comment by mtech2008** [comment]
> `new_bar` emits right before the the timeframe changes, when data has not been rendered within the bar at the next time interval.
> 
> May i ask why you need this functionality? It would be possible to do, but the open, high, low and close datapoints would be identical as only one tick would have loaded into that bar.

Once I update the chart from tick data. Logically 'chart_data' should return the all the bardata including the live bar which is currently updating by the tick. What I have realised is that it will solve many problems.  Can't we have assign candle_data so that it returns the data like this?
