### ISSUE TITLE
chart.update_from_tick(tick) creates a new bar, instead of updating the same bar.

### ISSUE THREAD

**Issue by mtech2008** [louisnw01/lightweight-charts-python#118]
### Question

I am initializing the chart by loading hourly historical data from NSE stock exchange (India). The first candle starts at 9.15 am IST. After loading the historical data I am updating the chart using tick using `chart.update_from_tick(tick)`. What I have noticed is as follows.
1. After rendering the historial data and load chart for 1min, 3min, 5min, 10min, 15min and 30 min data and then updating the chart by tick is working as expected.
2. But when I bring data for 60min and then updating the chart to render new bar by tick creates a new bar which is not a expected behaviour.
3. When I load MCX's exchange historical data (which starts at 9:00 am IST) and updating by tick creates no issue.
4. What I mean is that suppose if I am requesting the for NSE exchange hourly data at 11.55 am then new hourly bar should start at 12.15 but in my case it is starting at 12 noon.

How can I resolve it?

**Comment by louisnw01** [comment]
Hey @mtech2008,

This sounds like a data issue. To resolve, I'll need a minimal example based on `examples/3_tick_data` with an `ohlc.csv` and `ticks.csv` that reproduces the same issue.

Louis

**Comment by mtech2008** [comment]
```
import pandas as pd
from time import sleep
from lightweight_charts import Chart

if __name__ == '__main__':

    df1 = pd.read_csv('ohlc1hr.csv', parse_dates=['date'])

    # Columns: time | price
    df2 = pd.read_csv('ticks1hr.csv', parse_dates=['time'])

    chart = Chart()

    chart.set(df1)

    chart.show()

    for i, tick in df2.iterrows():
        chart.update_from_tick(tick)
        sleep(0.8)
```
[ohlc1hr.csv](https://github.com/louisnw01/lightweight-charts-python/files/12650094/ohlc1hr.csv)
[ticks1hr.csv](https://github.com/louisnw01/lightweight-charts-python/files/12650095/ticks1hr.csv)

**Comment by louisnw01** [comment]
Thanks for the example; I understand now.

At the moment, the library calculates the interval by pulling the most common interval within the inital dataset; but this does pose an issue if you are using an offsetted timeframe, as the chart thinks the next bar should be on the hour.

I'll look into storing an 'offset' in addition to the interval, which is added to the tick's time when it is rounded.

Louis

**Comment by louisnw01** [comment]
Implemented in the latest version.

Thanks,
Louis
