### ISSUE TITLE
Can't seem to create histogram bars

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#119]
### Question

Was going to use the histogram to create PNL bar chart, but can't see to get it working. 
Not sure If I an calling the method correctly

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/22f20db3-11b8-4faf-a73c-14ec0ecb7915)

### Code example

```python
import pandas as pd
from lightweight_charts import Chart

if __name__ == '__main__':
    chart = Chart(inner_height=0.5)
    chart.legend(visible=True)

    df = pd.read_csv('ohlcv.csv')
    chart.set(df)

    hist_chart = chart.create_subchart(position='bottom', height=0.5, width=1)
    hist_chart = hist_chart.create_histogram()
    hist_chart.set(df[['date', 'volume']])

    chart.show(block=True)

```

**Comment by louisnw01** [comment]
Hey @karunkrishna,

Looking at your code, you are redefining `hist_chart`, overwriting the second chart you defined with `create_subchart`. This won't cause errors, but its bad practice considering you no longer have access to that chart object.

The `set` method for histograms is more similar to the `Line` object than volume, which means you need to either rename the `volume` column to `value`, or you need to pass a `name` parameter to `create_histogram` and use that name as the `value` column name.

Louis

**Comment by karunkrishna** [comment]
Got it. 
Is there an utility that converts the numbers similar to the number for volume above? 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/80bc6bc5-383c-4e50-9d89-a0c9d91c4454)

**Comment by louisnw01** [comment]
At the moment no, but I think a `shorthand` parameter in create_histogram is a great idea. I'll add in the next update.

Louis
