### ISSUE TITLE
Empty window on win machine

### ISSUE THREAD

**Issue by surajrimal07** [louisnw01/lightweight-charts-python#12]
Hi, Thank you so much for providing this. This is exactly what i was searching for. Unfortunately for some reason i could not get it working. I only get blank window with no plotting.  Any solution?  haven't changed any code so far.
![errrrr](https://github.com/louisnw01/lightweight-charts-python/assets/16741094/9220ab47-ee85-443c-bf62-18e6f9546646)

**Comment by louisnw01** [comment]
Hi!

Have you checked out #2?

**Comment by surajrimal07** [comment]
Hello, I managed to solve this issue by installing edge webview. Thank you.
