### ISSUE TITLE
set_visible_range does not work in realtime rendering mode

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#120]
### Expected Behavior

To reproduce set the variable IS_REALTIME

IS_REALTIME = False make the chart.show(block=True)
- In this mode you can see that the buttons for Period 1 and Period 2 changes the chart to the correct visible range
- Button Real time is not implemented because I am unsure how we can move it back to "lastest" time period and remove fixed visible range

IS_REALTIME=True results in  chart.show()
- In this mode the realtime chart always updates, but the buttons to move to Period 1 or Period 2 no longer work

Is there a way to remove the set_visible_range back to the latest Realtime bar during live trading?

### Current Behaviour

Currently in Realtime mode, set_visible_range does not move the chart to the desired visible period
Users should have the ability to use a callback to go to a period of their choice (last trade(s)) and then be able to get back to the Realtime trading period

### Reproducible Example

```python
    import pandas as pd
    from time import sleep
    from lightweight_charts import Chart

    IS_REALTIME = False

    chart = Chart()

    df1 = pd.read_csv(f'{os.getenv("PATH_DIR")}/data/ohlcv.csv')
    df2 = pd.read_csv(f'{os.getenv("PATH_DIR")}/data/next_ohlcv.csv')

    chart.set(df1)

    period_1 = df1.iloc[-1000]['date'], df1.iloc[-900]['date']
    period_2 = df1.iloc[-800]['date'], df1.iloc[-300]['date']

    print(f'Period 1 start and end dates are: {period_1}')
    print(f'Period 2 start and end dates are: {period_2}')

    chart.topbar.button('prd1', button_text='Period 1',
                        func=lambda x: x.set_visible_range(start_time=period_1[0], end_time=period_1[1]))
    chart.topbar.button('prd2', button_text='Period 2',
                        func=lambda x: x.set_visible_range(start_time=period_2[0], end_time=period_2[1]))

    # TODO: Not sure if it is possible currently to remove the set_visible range so realtime works
    chart.topbar.button('latest_time', button_text='Real time', func=lambda x: x.set_visible_range())

    chart.show(block=(not IS_REALTIME))

    for i, series in df2.iterrows():
        chart.update(series)
        sleep(0.1)
```

### Environment

```markdown
- OS: Windows 10 Pro
- Library: 1.0.17.5
```

**Comment by louisnw01** [comment]
Hey @karunkrishna:

This appears to be an issue with your implementation of callbacks rather than set_visble_range.

From [Topbar & Events]():

> When using show rather than show_async, block should be set to True (`chart.show(block=True)`).

As you are using `block=False`, no events can be processed within python as the event loop is not running.

The same page in the documentation includes multiple examples showing how to run your own code whilst keeping the event loop running.

Louis

**Comment by karunkrishna** [comment]
Will take a look;
Any thought on removing the set_visible_range so that it goes back to the latest bar?
