### ISSUE TITLE
Enable Y-Axis tick for Historgram

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#122]
### Description

Currently Y-Axis is blank for Histogram, but not sure how easy it would be to add crosshair to show the Y-value on the right side or have equidistant ticks on the right side 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/b63ffbb1-6ec5-40fd-9c54-a51db262e473)

### Code example

```python
N/A
```

**Comment by louisnw01** [comment]
Unfortuntately Lightweight Charts offers no crosshair functionality for histograms; all you can get is the final value line.
