### ISSUE TITLE
histogram feature enhancements and observations 

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#124]
### Description

Creating this ticket to consolidate possible feature request for histogram
1. Shorthand notation of y-axis value like main chart (84119.84 vs. 84.12M)
2. Legend is not appearing to indicated what the histogram indicator is, or the ability to show/hide the indicator (macd example)
3. [Not possible based on lightweight library] Horizonal Crosshair of Histogram, but bringing this up for below point. Maybe it's possible to hack this my overlaying a hidden line chart that follows this histogram?
4. Tick Y-axis missing. Without a horizontal crosshair make it difficult to understand the magnitude of these bars if used on it's own to represent PNL. But when paired with line chart of equal magnitude, ticks show-up 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/81d9d402-e5b6-43b9-bbfa-19f202c56877)

### Code example

```python
    import pandas as pd
    from lightweight_charts import Chart
    import numpy as np
    import pandas_ta as ta

    np.random.seed(42)

    chart = Chart(inner_height=0.5, height=800)
    chart.legend(visible=True)

    df = pd.read_csv('ohlcv.csv')
    df[['macd', 'macd_hist', 'macd_signal']] = ta.macd(df.close, 20, 50, 10)
    df = df.tail(120).reset_index(drop=True)

    volume_df = df[['date', 'volume']]
    volume_df = pd.concat([volume_df, pd.Series(np.random.choice([-1, 1], size=len(volume_df)), name='factor')], axis=1)
    volume_df['pnl_value'] = volume_df['volume'] * volume_df['factor'].div(1_000)

    volume_df['color'] = np.where(volume_df.pnl_value >= 0, 'rgba(0,114,54,255)', 'rgba(201,29,35,255)')

    vol_chart = chart.create_subchart(position='bottom', width=1, height=0.25, sync=True)
    vol_chart = vol_chart.create_histogram(name='pnl_value')

    chart.set(df[['date', 'open', 'high', 'low', 'close', 'volume']])
    vol_chart.set(volume_df[['date', 'pnl_value', 'color']])
    vol_chart.horizontal_line(85_000.0, text='Outlier Wins')
    vol_chart.horizontal_line(-85_000.0, text='Outlier Losses')

    macd_chart = chart.create_subchart(position='bottom', width=1, height=0.25, sync=True)
    macd_chart.legend(visible=True)

    macd_line = macd_chart.create_line(name='macd', width=1)
    macd_signal = macd_chart.create_line(name='macd_signal', width=1, style='dotted')
    macd_hist = macd_chart.create_histogram(name='macd_hist')

    macd_df = df[['date', 'macd', 'macd_signal', 'macd_hist']]

    macd_line.set(macd_df[['date', 'macd']])
    macd_signal.set(macd_df[['date', 'macd_signal']])
    macd_hist.set(macd_df[['date', 'macd_hist']])

    chart.show(block=True)
```

**Comment by louisnw01** [comment]
Hey @karunkrishna,

Shorthand will be implemented in the next update. As for Histogram showing up in the legend, i'll add this in a later update most likely.

You could do the hidden line with the current version of the library; just set the color of the line to `'transparent'`. Let me know if it works!

Louis

**Comment by DmitryAkDev** [comment]
Btw, histogram can be none-scaled zero-based (example: logic True/False). ltw-charts allow it with autoscaleInfoProvider option.

For this feature i use dirty hack, may be you will do it better:
```
class Histogram(SeriesCommon):
    def __init__(self, chart, name, color, price_line, price_label, scale_margin_top, scale_margin_bottom,set_auto_scale=False):
        super().__init__(chart, name)
        self.color = color
        fautoscale=''
        fpricescale=''
        if set_auto_scale:
            fautoscale = f'''autoscaleInfoProvider: () => ({{
                        priceRange: {{
                            minValue: {scale_margin_bottom},
                            maxValue: {scale_margin_top},
                            }},
                        }}),'''
        else:
            fpricescale='''{self.id}.series.priceScale().applyOptions({{
                        scaleMargins: {{top: {scale_margin_top}, bottom: {scale_margin_bottom}}}
                        }})'''

        self.run_script(f'''
        {self.id} = {{
            series: {chart.id}.chart.addHistogramSeries({{
                color: '{color}',
                lastValueVisible: {jbool(price_label)},
                priceLineVisible: {jbool(price_line)},
                priceScaleId: '{self.id}'
            }}),
            {fautoscale}
            markers: [],
            horizontal_lines: [],
            name: '{name}',
            color: '{color}',
            precision: 2,
            }}
            {fpricescale}
        ''')
```

**Comment by louisnw01** [comment]
@karunkrishna, 1 and 2 have been implemented in the latest version.

@DmitryAkDev, I'm not entirely sure what your histogram implementation is indended to do?

Thanks,
Louis

**Comment by DmitryAkDev** [comment]
> @DmitryAkDev, I'm not entirely sure what your histogram implementation is indended to do?

Show histogram with hard visible range (-scale_margin_bottom, scale_margin_top).
Default behavior for True, False histogram after scale in:

![изображение](https://github.com/louisnw01/lightweight-charts-python/assets/25522773/93c58b17-6499-4a73-8f9f-5d6ae933afbb)

![изображение](https://github.com/louisnw01/lightweight-charts-python/assets/25522773/88288487-4a4e-4f4b-84b9-d30b2339f0ed)

Modified
`   {self.id} = {{
                series: {chart.id}.chart.addHistogramSeries({{
                    color: '{color}',
                    lastValueVisible: {jbool(price_label)},
                    priceLineVisible: {jbool(price_line)},
                    priceScaleId: '{self.id}',
                    priceFormat: {{type: "volume"}},
                    autoscaleInfoProvider: () => ({{
                        priceRange: {{
                            minValue: {scale_margin_bottom},
                            maxValue: {scale_margin_top},
                            }},
                        }}),
                }}),
                markers: [],
                horizontal_lines: [],
                name: '{name}',
                color: '{color}',
                precision: 2,
                }}`
![изображение](https://github.com/louisnw01/lightweight-charts-python/assets/25522773/0f40a610-1c71-441b-aa47-b42c24b6cd3d)
![изображение](https://github.com/louisnw01/lightweight-charts-python/assets/25522773/e70cd7f2-c71b-48f4-b6f2-80add293a409)

**Comment by karunkrishna** [comment]
> Hey @karunkrishna,
> 
> Shorthand will be implemented in the next update. As for Histogram showing up in the legend, i'll add this in a later update most likely.
> 
> You could do the hidden line with the current version of the library; just set the color of the line to `'transparent'`. Let me know if it works!
> 
> Louis

Yeah don't think it's possible I think the histogram when it get's created always shifts the placement in relationship to the line chart

The line and the histogram is the same value (which is the volume) so it can only ever be above 0. and the histogram get's shifted and almost implies negative numbers. My assumption was that it would overlay on top of each other

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/74afa60a-e249-4c40-842f-ae69d7aa5be6)

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/53eaa54a-122a-4a85-81a4-05ce6d3cbaaf)

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/8f27dcc4-7aa0-499a-b43b-ffb1af20a4b4)
