### ISSUE TITLE
setting z-order for vertical span

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#125]
### Question

Any way to control the z-order of the vertical_span? so that we can keep the chart in focus but only affect the background color?

alpha set to 0.4 in rgba

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/a62c40cc-5d4e-46c0-b530-ede6ff7fccdf)

alpha set to 1 in rgba
![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/ee501932-91fe-4851-bdbd-e78ad336ceae)

**Comment by louisnw01** [comment]
Unfortunately Lightweight Charts offers no implementation for z index order, but the feature has been requested so it will potentially be possible in the future.

Louis

**Comment by denisprovost** [comment]
This has been added since v5

**Comment by jamesbal2015** [comment]
Do you have an example of Op clock
