### ISSUE TITLE
ImportError: cannot import name 'Chart' from partially initialized module 'lightweight_charts'

### ISSUE THREAD

**Issue by jverhei** [louisnw01/lightweight-charts-python#126]
### Question

ImportError: cannot import name 'Chart' from partially initialized module 'lightweight_charts' (most likely due to a circular import)

On a fresh environment installs, (3.11, 3.9, 3.7) I'm getting this error. No matter what I do, I can't seem to get past this issue on the basic chart example. Is there a specific version of python this works best with? 

I noticed that all the examples I could find are Mac based. Does this code not work with PC's?

### Code example

```python
import pandas as pd
from lightweight_charts import Chart


if __name__ == '__main__':
    
    chart = Chart()
    
    # Columns: time | open | high | low | close | volume 
    df = pd.read_csv('ohlcv.csv')
    chart.set(df)
    
    chart.show(block=True)


ImportError: cannot import name 'Chart' from partially initialized module 'lightweight_charts' (most likely due to a circular import)
```

**Comment by louisnw01** [comment]
Hey @jverhei,

Never seen this error before; have you tried the pywebview hello world script?

```python
import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/')
webview.start()
```

If you get the same error with this, then it's probably to do with your system.

Louis

**Comment by jverhei** [comment]
Thanks @louisnw01.

tried installing webview and got the following error:
C:\Users\jverh\AppData\Local\Temp\pip-install-jxsf70rd\webview_83b464694424438b86f588e9dcd51c7f\webview\webview.h(1085): warning C4477: 'sscanf' : format string '%02x' requires an argument of type 'unsigned int *', but variadic argument 1 has type 'char *'
 
 Bummer. I was so excited to run the lightweight charts for my trades.

**Comment by daladaysoft** [comment]
Hey @jverhei,
I suggest to show chart in asyncio, not sure, but... 
From your example:
``
import asyncio
import pandas as pd
from lightweight_charts import Chart

async def main():
    
    chart = Chart()
    
    # Columns: time | open | high | low | close | volume 
    df = pd.read_csv('ohlcv.csv')
    chart.set(df)
    
    await chart.show_async(block=True)

if __name__ == '__main__':
    asyncio.run(main())**
``

**Comment by louisnw01** [comment]
> Thanks @louisnw01.
> 
> tried installing webview and got the following error: C:\Users\jverh\AppData\Local\Temp\pip-install-jxsf70rd\webview_83b464694424438b86f588e9dcd51c7f\webview\webview.h(1085): warning C4477: 'sscanf' : format string '%02x' requires an argument of type 'unsigned int *', but variadic argument 1 has type 'char *'
> 
> Bummer. I was so excited to run the lightweight charts for my trades.

This would be an issue to raise over at the pywebview repo. Hopefully they can help you!

Louis

**Comment by VicRejkia** [comment]
I stumbled upon the same error. The reason for this was that the name of my Python script matched that of the package. So **don't name your script lightweigt_charts.py**
