### ISSUE TITLE
Topbar not working in Jupyter Notebook in VSCode

### ISSUE THREAD

**Issue by bezoar17** [louisnw01/lightweight-charts-python#128]
### Expected Behavior

I should see the banner as i can see in a normal Jupyter Notebook like below

![image](https://github.com/louisnw01/lightweight-charts-python/assets/7189210/689f48bb-9391-4560-bb3f-85b43f30d6f1)

### Current Behaviour

The cell output with the graph is huge, never ending in height and vs code simply hangs even if a simple topbar textbox is added.

debug=True is not supported in JupyterChart, so could not provide a screenshot with that. 

Code used in the screenshot is given in reproducible example.

![image](https://github.com/louisnw01/lightweight-charts-python/assets/7189210/32f1d7c7-7d52-4eee-ae2a-59ffb12f61a7)

### Reproducible Example

```python
from lightweight_charts import JupyterChart
chart = JupyterChart()
chart.topbar.textbox('symbol', 'AAPL')
df = pd.read_csv('ohlcv.csv')
chart.set(df)
chart.load()
```

### Environment

```markdown
- OS: macOS Ventura 13.3
- Library: 1.0.17.5
- VS Code: 1.82.2


- Following VS Code extension used
Name: Jupyter
https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
v2023.8.1002501831
```

**Comment by louisnw01** [comment]
Hey @bezoar17,

As callbacks/events are not possible in notebooks, there doesnt appear to be a reason for the topbar to be available in notebooks.

Louis
