### ISSUE TITLE
How do we create tick.csv? 

### ISSUE THREAD

**Issue by surajrimal07** [louisnw01/lightweight-charts-python#13]
Hello sir thank you for this. I am trying to get tick chart working. Here is my setup.

Here is what i am trying to do.
Get live current data from selenium. 
save tick data in CSV. (trying to avoid this) 

tick_now - holds  5 seconds interval tick data with tick time.
is it possible to pass tick_now as a tick source for tick chart along with historical csv?

I am finding hard to understand how tick plot works, it is possible to plot using historical data and supplying live tick data from above selenium without saving tick data to CSV and loading data from CSV.

My goal is to plot intraday ( 1 min candle), in this case do my historical  ohlc data has to be 1 min ohlc as well?

What is the exact time format required for tick data?  - 2023-05-04 15:15:17.630544+00:00
do datetime.now() work?

Sorry for dumb question. Thank you for this awesome project.

**Comment by louisnw01** [comment]
Hi, and thank you!

If you have any code that you've tried to get working and a snippet of the data you are attempting to use it would be great if you could add it here.

It is possible to plot using historical data, and plot ticks without saving them. I assume you have looked at this example:
```python
import pandas as pd
from time import sleep
from lightweight_charts import Chart


if __name__ == '__main__':
    
    df1 = pd.read_csv('ohlc.csv')
    
    # Columns: | time | price | volume (if volume is enabled) |
    df2 = pd.read_csv('ticks.csv')
    
    chart = Chart(volume_enabled=False)
    
    chart.set(df1)
    
    chart.show()
    
    for i, tick in df2.iterrows():
        chart.update_from_tick(tick)
            
        sleep(0.3)
```
As you can see, the chart is updated by looping through each row in the csv file, which returns a `pd.Series` object, containing one tick, with the labels time, volume, and price.

`update_from_tick` takes a single series object; if you are getting your ticks as a dictionary, you can convert it to a series object very easily by just passing it in:

```python
tick = {'time': '2023-05-04 15:15:17.630544+00:00', 'price': '193.59', 'volume': '25000'}
chart.update_from_tick(pd.Series(tick))
```

As for your other questions:
* If you want the chart to be 1min, then your historical data should be 1min bars. The library will automatically convert the ticks to this interval.
* `datetime.now()` does work, however if the ticks you are pulling from Selenium contain time info it will probably result in a more accurate plot if you use those times instead. The library isnt too fussy about the format you give it, and the one you suggested will work just fine.

Louis
