### ISSUE TITLE
[BUG] : On a windows system with screen 0 inactive/off the chart window will not show

### ISSUE THREAD

**Issue by scholz** [louisnw01/lightweight-charts-python#130]
### Expected Behavior

When running the examples on a system with multiple screens it is expected that the window opens on the active screen not on the screen with id ==0. This worked in previous version (1.0.13.4) and can be worked around by setting the screen var to -1 then it will display on the active screen ie. Chart(screen=-1).

### Current Behaviour

The window opens on the screen 0 as default (see chart.py:72). In my case this was on a disabled screen and hence the window was not visible.

### Reproducible Example

```python
- Win10
- Multiscreen configuration with screen with id == 0 off
- run any of the examples
```

### Environment

```markdown
- OS: Win10
- Library: 1.0.17.6
```

**Comment by louisnw01** [comment]
Hey @scholz,

I'll make `screen` default to `None` in the next version.

Louis

**Comment by scholz** [comment]
Great @louisnw01 : however, None at least as default doesnt seem to work for me (throws some iteration exception), while -1 works. Haven't digged into it further though.

**Comment by louisnw01** [comment]
> Great @louisnw01 : however, None at least as default doesnt seem to work for me (throws error below), while -1 works. Haven't digged into it further though.
> 
> 
> 
> ```python
> 
> Traceback (most recent call last):
> 
>   File "C:\Python39\lib\multiprocessing\process.py", line 315, in _bootstrap
> 
>     self.run()
> 
>   File "C:\Python39\lib\multiprocessing\process.py", line 108, in run
> 
>     self._target(*self._args, **self._kwargs)
> 
>   File "F:\Documents\Firma\Projekte\Metirionic\code\crypto-experiments\crypto\.venv\lib\site-packages\lightweight_charts\chart.py", line 28, in __init__
> 
>     self.create_window(width, height, x, y, screen, on_top, maximize)
> 
>   File "F:\Documents\Firma\Projekte\Metirionic\code\crypto-experiments\crypto\.venv\lib\site-packages\lightweight_charts\chart.py", line 35, in create_window
> 
>     screen = webview.screens[screen]
> 
>   File "F:\Documents\Firma\Projekte\Metirionic\code\crypto-experiments\crypto\.venv\lib\site-packages\proxy_tools\__init__.py", line 133, in <lambda>
> 
>     __getitem__ = lambda x, i: x._get_current_object()[i]
> 
> TypeError: list indices must be integers or slices, not NoneType
> 
> ``` 

My code doesn't accept `None` in its current form, however pywebview can support this. 

Louis

**Comment by louisnw01** [comment]
Fixed in the latest version.

Louis
