### ISSUE TITLE
displaying empty candles or gaps in OHLC series

### ISSUE THREAD

**Issue by c-harish** [louisnw01/lightweight-charts-python#131]
### Description

If the df has empty values or np.nan values, we get blank chart with no candles. 
Illiquid instruments tend to have empty OHLCV candle, which can be interpolated as blank candle or with backfill or with forwardfill. 
Would be nice to have interpolation of NaN in df as whitespace.

### Code example

```python
const data = [
    { time: '2018-12-03', value: 27.02 },
    { time: '2018-12-04' }, // whitespace
    { time: '2018-12-05' }, // whitespace
    { time: '2018-12-06' }, // whitespace
    { time: '2018-12-07' }, // whitespace
    { time: '2018-12-08', value: 23.92 },
    { time: '2018-12-13', value: 30.74 },
];
```

**Comment by louisnw01** [comment]
Hey @ c-harish,

Have you tried filling empty spaces with `None`? It should switch those values to `null`. 

Louis

**Comment by c-harish** [comment]
> Hey @ c-harish,
> 
> Have you tried filling empty spaces with `None`? It should switch those values to `null`.
> 
> Louis

Have tried `None`,  `np.nan`,  `' '`. df loading fails with all above three values.

**Comment by MateKristof** [comment]
Show similar behaviour if I try to leave a gap in the indicator (like Supertrend low and high line)
A small example of this:
`import pandas as pd
import numpy as np
from lightweight_charts import Chart


def calculate_sma(df, period: int = 50):
    return pd.DataFrame({'time': df['date'], f'SMA {period}': df['close'].rolling(window=period).mean()}).dropna()
```python
import pandas as pd
import numpy as np
from lightweight_charts import Chart


def calculate_sma(df, period: int = 50):
    return pd.DataFrame({'time': df['date'], f'SMA {period}': df['close'].rolling(window=period).mean()}).dropna()

if __name__ == '__main__':
    chart = Chart()

    df = pd.read_csv('ohlcv.csv')
    chart.set(df)

    line = chart.create_line('SMA 50')
    sma_data = calculate_sma(df, period=50)
    line.set(sma_data)

    # sma_data["SMA 50"][-400:-50] = None
    sma_data["SMA 50"][-400:-50] = np.nan
    # sma_data.dropna(inplace=True)

    line_nan = chart.create_line('SMA 50', color='rgba(255, 0, 0, 1)')
    line_nan.set(sma_data)

    chart.show(block=True)

```
With np.nan the indicator value will be zero and if I drop nan lines the indicator will be connected by a straight line.

Another observation is that in [widget.py](https://github.com/louisnw01/lightweight-charts-python/blob/d43e7c24e7565d1d333bfa4ad2618d851860f6a5/lightweight_charts/widgets.py#L14) there is an import error when using Qt5, import Qt is missing:
```python
from PyQt5.QtCore import Qt, QObject, pyqtSlot as Slot
```

Thank you for your work!

**Comment by louisnw01** [comment]
null/Nan/None values will be replaced with whitespace in the latest version.

Louis
