### ISSUE TITLE
Marker appearing with one days offset?

### ISSUE THREAD

**Issue by teeling** [louisnw01/lightweight-charts-python#133]
Hi,
First I must say - what a great package! Love LW Charts and this implementation seems just perfect for what I need.

I did run in to a problem though, not sure if it's a bug or if it's just me, but markers I make seem to plot one day offsetted in the chart.

Here's my code:
```
lw_df['date'] = pd.to_datetime(lw_df.index).date

chart = JupyterChart(width=1500, height=600, toolbox=True)

chart.set(lw_df)

for k,v in lw_df[['pivot','date']].query('pivot in [1,2]').iterrows():
    chart.marker(time=v.date, position=('above' if v.pivot == 2 else 'below'), text=v.date)

chart.load()
```

![Screenshot 2023-09-27 at 17 51 34](https://github.com/louisnw01/lightweight-charts-python/assets/25309834/4a7329a6-6fce-4d34-acfc-bebab74fdd74)

It looks as if self.offset gets added in the following line, is that correct, or am I missing anything else?

https://github.com/louisnw01/lightweight-charts-python/blob/d43e7c24e7565d1d333bfa4ad2618d851860f6a5/lightweight_charts/abstract.py#L207C78-L207C78

**Comment by louisnw01** [comment]
Hey @teeling,

You'll need to provide a minimal reproducible example; preferably based on one of the examples using `ohlcv.csv` data.

Thanks,
Louis

**Comment by teeling** [comment]
Hey
Of course, sorry, here's an example:

```
import pandas as pd
from lightweight_charts import JupyterChart
lw_df = pd.read_csv('ohlcv.csv')

# This line, cropping out just a part of the df, makes the markers slip one bar.
# If commenting just this line out, it works as expected
lw_df = lw_df.query('date >= "2020-05-01" and date <= "2020-08-01"')

# Add a column for the markers
lw_df['pivot'] = 0
# Add some markers to specific index locations
lw_df.loc[2290, 'pivot'] = 1
lw_df.loc[2292, 'pivot'] = 2
lw_df.loc[2294, 'pivot'] = 1
# Add to specific dates
lw_df.loc[lw_df['date'] == '2020-07-28', 'pivot'] = 1
lw_df.loc[lw_df['date'] == '2020-07-30', 'pivot'] = 2

chart2 = JupyterChart(width=1500, height=600, toolbox=True)
chart2.set(lw_df)
chart2.legend(True)

for k,v in lw_df[['pivot','date']].query('pivot in [1,2]').iterrows():
    chart2.marker(time=v.date, position=('above' if v.pivot == 2 else 'below'), text=v.date)

chart2.load()
```

For some reason, the self.offset in the abstract.py linked above is 86400 when cropping the df, but it's 0 when the df is kept in its original length.

**Comment by louisnw01** [comment]
Should be fixed in the latest version. let me know!

Louis
