### ISSUE TITLE
create_table cosmetic feature request

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#136]
### Description

May not be worth doing... but will make it more robust for users to control the cosmetic nature of Tables

1. Ability to add header option like there is a footer option, could be used as title for the table
2. Ability to add topbar to table so you can create pagination, etc
3. Ability to set column-header background_color and text_color
4. Ability to add callback to footer/header for possible pagination, etc. 
5. Ability to add default background color for negative space between table rows and footer
6. Ability to adjust the cell border color and line width
7. callback function on row provides the row that was clicked but not the column/cell coordinate. This will allow specific re-rendering of view and open up the possibility of drilling down into a chart/table etc..  

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/0d1c2b3d-2735-4418-be66-5f4a21efd62f)

**Comment by louisnw01** [comment]
Hey @karunkrishna,

Would it be better to add a `header` which operates similarly to the `footer`, however allow the use of buttons within both? I think a fully featured topbar might not be nessecary, but simple buttons that can emit to python would be useful (in both the header and footer). Either way, I'll look into these features for a future update.

**Comment by karunkrishna** [comment]
When you click on a cell (i.e. row and column) is it possible to get the column name. Right now it only provides the row that was clicked....it would open up a lot of capabilities

**Comment by louisnw01** [comment]
At the moment this is not possible, but i'll look to implement.

Louis

**Comment by karunkrishna** [comment]
Is it possible to left, center and right justify the columns and cell?
- I tried to hacking it by adding left spaces with fixed width, but those leading spaces are being stripped 

dict(title='Net Profit', format='$ {: >10,.0f}')

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/e828353b-fd2a-40e8-b667-a6689d1acd3d)

**Comment by louisnw01** [comment]
Hey @karunkrishna,

I've implemented a few of these in the latest version of the github repo. If you get a chance to test it out, let me know if you have any issues with it!

Louis

**Comment by karunkrishna** [comment]
Issue 1:  For header, I don't think the table should be set to align to the bottom

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/5ae23d37-5f8e-4ad9-98a2-0e64c58b9988)

**Comment by louisnw01** [comment]
Thanks, i'll take a look at that.

For header/footer callbacks, as they are going to be simpler they need a slightly different syntax which is still a work in progress. Im leaning toward:

```python
table.footer(3, func=on_footer_click)
```

Which automatically turns each footer item into a button, being accessed as:

```python
def on_footer_click(chart, index):
    print(f"Footer textbox {index+1} was clicked.")
```

What do you think?

Louis

**Comment by karunkrishna** [comment]
Yes this would work! 
Since you are explicitly labeling the footer by index, you the user can be explicit with what the on_footer_click(...) executes

Also there is no change to the footer/header api by adding the the kwarg func=

**Comment by louisnw01** [comment]
All implemented in the latest version.

Louis
