### ISSUE TITLE
Price Axis Alignment with SubCharts

### ISSUE THREAD

**Issue by mash420** [louisnw01/lightweight-charts-python#138]
### Question

Is it possible to set a pixel width for the price axis levels?
Would be easier than converting the data to fit.

![image](https://github.com/louisnw01/lightweight-charts-python/assets/81828831/0ae9cd7f-406d-4e39-9d26-597ff946f91a)

**Comment by louisnw01** [comment]
Hey @mash420,

Unfortunately Lightweight Charts does not offer this capability. I'll leave this open as a documentation issue as this has been asked before.

Thanks,
Louis
