### ISSUE TITLE
table heading should be frozen

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#139]
### Description

Right now if you have a large table and the scroll wheel is enabled the header disappears. 
heading should be frozen for readability 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/26c32963-ae9f-4f4b-9e69-17e7f6ec7bd3)

**Comment by louisnw01** [comment]
Also implemented in the latest version of the repo.

Louis

**Comment by karunkrishna** [comment]
![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/0900d881-452f-472b-8ac9-27c2f9a7b5da)

Works as expected! Thanks
