### ISSUE TITLE
Can ChartAsync currently be used in conjunction with StreamlitChart?

### ISSUE THREAD

**Issue by hanxuanliang** [louisnw01/lightweight-charts-python#14]
As the title suggests, I want to be able to render minute-level data and display changes in StreamlitChart.

**Comment by louisnw01** [comment]
Hi!

As Streamlit communicates with python through websockets and is hosted on a server, it is not possible to display anything dynamic with the current codebase.

**Comment by hanxuanliang** [comment]
Understood. It seems that we need to use static data and add buttons on the page to switch between minute-level data.……
But may I ask if it can display the rise and fall range of K-line?

![image](https://github.com/louisnw01/lightweight-charts-python/assets/29874640/a18ca56c-f41e-4d2c-8ce3-70583ef36b60)

**Comment by louisnw01** [comment]
Do you mean being able to see created Lines within the legend? If so, I agree, and this will be implemented.

**Comment by hanxuanliang** [comment]
I mean to be able to display the high, low, and price change rate of K-line in the upper left corner like ChartAsync.

**Comment by louisnw01** [comment]
This feature is accessible with the `legend` method
