### ISSUE TITLE
Save the chart to jpg

### ISSUE THREAD

**Issue by changyonghu** [louisnw01/lightweight-charts-python#140]
### Question

Is it possible to save the chart to jpg?

**Comment by louisnw01** [comment]
Hey @changyonghu,

This is possible using the [screenshot](https://lightweight-charts-python.readthedocs.io/en/latest/reference/charts.html#Chart.screenshot) method. I'll leave this open as a documentation issue, and add a screenshot example to make this clearer.

Louis
