### ISSUE TITLE
Adding new tools to Toolbox

### ISSUE THREAD

**Issue by brlocky** [louisnw01/lightweight-charts-python#141]
### Question

It is possible to add new custom tools to the toolbox ? 

I would love to have some more tools like Fibonacci retracements

**Comment by louisnw01** [comment]
Hey @brlocky,

Would you be open to implementing this?

Louis

**Comment by brlocky** [comment]
> Hey @brlocky,
> 
> Would you be open to implementing this?
> 
> If you take a look at `toolbox.js`, it would certainly be possible.
> 
> Louis

I just did not jump on it due to the wrapping of js inside python.

I will take a look

Thank you for the reply
