### ISSUE TITLE
Multi-line text for series marker

### ISSUE THREAD

**Issue by matthewjarman** [louisnw01/lightweight-charts-python#142]
### Question

Hi Louis!

Is is possible to add a newline in the text attribute of a series marker, to create a multi-line marker or note on the chart?

I've tried several possibilities like \n, \r, \r\n - but all cause the marker to not render.  When I pull any of those chars out of the text attribute, the marker then renders again.

Thanks!
Matt

**Comment by louisnw01** [comment]
Hi Matt,

Unfortunately Lightweight Charts renders text within markers as plain, meaning there is no way to add line breaks.

Louis

**Comment by matthewjarman** [comment]
Hi Louis,

Appreciate the quick response.

If Trading View were to allow for this, would there be a way to use the scripting trick to make it happen?  Asking in case there is a way to get the feature included on their end.

Thanks!
Matt

**Comment by louisnw01** [comment]
If they were to implement it would likely involve allowing HTML tags within marker text, so a line break would be represented as `<br>`.

Louis

**Comment by matthewjarman** [comment]
Interesting.  I'll keep this in mind in case I see them make an API update like this.  Thanks again!
