### ISSUE TITLE
[BUG] This library is not showing prices in higher decimal place.

### ISSUE THREAD

**Issue by EncryptMan** [louisnw01/lightweight-charts-python#143]
### Expected Behavior

<img width="1075" alt="Screenshot 2023-10-05 at 3 36 28 PM" src="https://github.com/louisnw01/lightweight-charts-python/assets/136573652/581e89ac-b309-439d-b3de-ed0e4636db31">

### Current Behaviour

![chart](https://github.com/louisnw01/lightweight-charts-python/assets/136573652/13879a3b-bb49-4ada-a71c-fb6ebc47dacb)
![chart2](https://github.com/louisnw01/lightweight-charts-python/assets/136573652/18e6f882-6565-4db2-b145-a17002b78a0a)

### Reproducible Example

```python
import pandas as pd
from lightweight_charts import Chart
import requests

if __name__ == '__main__':
    chart = Chart()

    api = 'https://api.binance.com/api/v3/uiKlines?symbol=ETHBTC&interval=4h'
    price_data = requests.get(api).json()

    for d in price_data:
        d[0] = pd.to_datetime(d[0] / 1000, unit='s')

    columns = [
        'Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'CloseTime',
        'QuoteVolume', 'NumTrades', 'TakerBuyBaseVolume', 'TakerBuyQuoteVolume', 'Ignore'
    ]
    df = pd.DataFrame(price_data, columns=columns)
    df.set_index('Date', inplace=True)
    df = df.apply(pd.to_numeric, errors='ignore')

    chart.set(df)

    chart.show(block=True)
```

### Environment

```markdown
- OS: macOS Sonoma 14.0
- Library:1.0.17.7
```

**Comment by louisnw01** [comment]
Hey @EncryptMan,

Use the precision method (RTD!).

Louis
