### ISSUE TITLE
Add static legend with asset, interval and source label.

### ISSUE THREAD

**Issue by EncryptMan** [louisnw01/lightweight-charts-python#144]
### Description

Currently legend is very basic and only shows dynamic values based on mouse position on chart.
<img width="450" alt="Screenshot 2023-10-05 at 7 39 13 PM" src="https://github.com/louisnw01/lightweight-charts-python/assets/136573652/edbd0bd8-406e-468b-ab4a-13e14098f309">

It should also show static information about the asset like real trading view chart ⤵️
<img width="756" alt="Screenshot 2023-10-05 at 7 36 06 PM" src="https://github.com/louisnw01/lightweight-charts-python/assets/136573652/65ce3325-1eb5-468b-b1d3-caf2cad2c3be">

### Code example

```python
chart.legend(base_asset='Ethereum', quote_asset='Bitcoin', interval='4h', source='BINANCE')
```

**Comment by louisnw01** [comment]
Hey @EncryptMan,

Cool idea! But I do think that the implementation you provided is too specific to asset pairs; perhaps a simple `info_text` or `text` parameter added to `legend` would be more flexible, and then you can format the text however you'd like:


```python
base_asset = 'Ethereum'
quote_asset = 'Bitcoin'
interval = '4h'
source = 'BINANCE'

chart.legend(True, text=f'{quote_asset} / {base_asset} • {interval} • {source}'
```

Louis

**Comment by EncryptMan** [comment]
Yes please add

**Comment by louisnw01** [comment]
Added the `text` parameter in the latest version.

Louis

**Comment by EncryptMan** [comment]
Thanks
