### ISSUE TITLE
Table reszie feature

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#145]
### Description

Much like the charts/subchart where you can resize the width and height on callbacks
Tables should implement the same feature

This will allow buttons/row/cell clicks to change what is rendered dynamically 

Add Table.resize(height, width) with similar behavior as chart

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/63c501ce-6295-4d27-a160-38b244067b24)

**Comment by louisnw01** [comment]
Hey @karunkrishna,

i'll look to implement in a future update. 

Louis

**Comment by louisnw01** [comment]
Added in the latest version.

Louis
