### ISSUE TITLE
Qt is not defined on pyqt5

### ISSUE THREAD

**Issue by Dino-Other** [louisnw01/lightweight-charts-python#146]
### Question

Don't know if this is a bug or  I'm missing something. I tried to run the example  below  using standalone pyqt5 module then it shows
> 'QWebEngineView was not found, and must be installed to use QtChart.'

so i installed PyQtWebEngine and it shows the following error after running the code again
![pic](https://github.com/louisnw01/lightweight-charts-python/assets/145942711/85bcb58b-a891-4919-b55b-bdae147c6219)

version
lightweight-charts==1.0.17.7
PyQtWebEngine==5.15.6
PyQtWebEngine-Qt5==5.15.2

### Code example

```python
import pandas as pd
from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget

from lightweight_charts.widgets import QtChart

app = QApplication([])
window = QMainWindow()
layout = QVBoxLayout()
widget = QWidget()
widget.setLayout(layout)

window.resize(800, 500)
layout.setContentsMargins(0, 0, 0, 0)

chart = QtChart(widget)

df = pd.read_csv('ohlcv.csv')
chart.set(df)

layout.addWidget(chart.get_webview())

window.setCentralWidget(widget)
window.show()

app.exec_()
```

**Comment by louisnw01** [comment]
Hey @Dino-Other,

That is a bug; the code throwing the error is only relevant to PySide6. Will fix for the next update.

Louis

**Comment by louisnw01** [comment]
Fixed in the latest version.
