### ISSUE TITLE
Subchart sync based on timestamp index

### ISSUE THREAD

**Issue by c-harish** [louisnw01/lightweight-charts-python#147]
### Description

`sync` feature in subcharts works well when the main and sub chart have the same timeframe and index. 

Can we have `sync` crosshair tracking based on the available timestamps in charts where sub-chart pans and moves automagically based on where we are in main chart irrespective of timeframes or available timestamp indexes?

**Comment by louisnw01** [comment]
Hey @c-harish,

This has been requested quite a few times, however I have been unable to create a consistent and smooth implementation.

Despite this, I do believe it is possible, so I'll leave this issue open so others are aware it is being worked on!

Louis

**Comment by krema** [comment]
Is this issue linked to following problem?


<img width="810" alt="image" src="https://github.com/louisnw01/lightweight-charts-python/assets/1336504/4464fece-9568-472c-8ea3-4a75bac123dd">

**Comment by neodawn** [comment]
@louisnw01 Thanks for the amazing library. I understand that syncing visually when the candlestick and the indicators are of different timeframe is not a trivial problem.
However, the indicators are mostly used are of the same timeframe as the candlestick. The major reason for the deviation under this scenario is that the right axis and labels are of different length and that causes the misalignment. 

A suggestion: Can we measure the right axis/label length of the main chart and all the indicators and set the maximum value of all the margin/axis to the main chart and all indicators? If this is a simple implementable solution, we can have it as an intermediate solution while we work on the final solution. If this is not a simple solution, please don’t bother.

**Comment by louisnw01** [comment]
Hey @neodawn,

Originally this was not possible, however I believe in the latest update of Lightweight Charts there is an option to set a minimum width for price scales, which whilst it is not exactly the same functionality you are looking for I think it would serve the same purpose.

If you think this would be good then if you could open an issue in relation to it that would be great!

Louis

**Comment by louisnw01** [comment]
> Is this issue linked to following problem?
> 
> 
> 
> 
> 
> <img width="810" alt="image" src="https://github.com/louisnw01/lightweight-charts-python/assets/1336504/4464fece-9568-472c-8ea3-4a75bac123dd">
> 
> 

Hey @krema, 
My last post and the post by @neodawn are both related to your issue

Louis
