### ISSUE TITLE
How can we get line data just like chart.candle_data()?

### ISSUE THREAD

**Issue by anilwarbhe** [louisnw01/lightweight-charts-python#150]
### Question

Is there a way to get a line chart data?

```
smaline = chart.create_line('SMA')
smaline.set(sma_df)
```

is it possible to extract/get line data like, `smaline.line_data()`

**Comment by louisnw01** [comment]
At the moment this is not possible, but i'll look to add in a future update.

Louis

**Comment by anilwarbhe** [comment]
I really appreciate. Thank you so much for coming up with such a wondurful library. Kudows to you.

**Comment by louisnw01** [comment]
Hey @anilwarbhe,

Fixed in the latest version (1.0.18.2).

Louis
