### ISSUE TITLE
Is there a way to delete a subchart with all the indicators (hist, line, candle)  associated to them?

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#155]
### Question

For example say you create multiple subplots
- is it possible to delete the subplot given an index number or the subchart object by running something like subchart.delete()
- It would clear out the indicators (lines, histogram, etc) attached to that chart

I am trying to recreate different subplots based on a row selection. Can't figure out how to delete an existing subchart with all the indicators associated with them. 

Alternatively I guess I can keep track of all the indicators attached to the subchart and remove it one by one. And instead of deleting the subplot, I just add the new indicators to it instead. Thoughts? 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/06087beb-9271-4718-9158-ae091f2591c8)

**Comment by louisnw01** [comment]
Hey @karunkrishna,

`chart.lines()` will return a list of all the lines associated with the chart or subchart. As for histograms, you would have to keep track of these manually in the current version.

Candle data can be cleared with `chart.set(None)`

Louis

**Comment by karunkrishna** [comment]
Worked thanks
