### ISSUE TITLE
marker position

### ISSUE THREAD

**Issue by QuantFreedom1022** [louisnw01/lightweight-charts-python#157]
### Question

is it possible to say specifically where we would want to put a marker ... like i want to put a marker at 27000 and 26000 and 27500 to represent the take profit ... stop loss and entry 

also i would like to know of a way to contact you ... because i am building a backtester and could really really really use what you have built because its either i use what you have and add to it or i build exactly what you have ... and i would rather use what you have built and help you add features and become a regular contributor

**Comment by louisnw01** [comment]
Hey @QuantFreedom1022,

Unfortunately markers are placed next to the line or candle that the marker was placed on, and lightweight charts does not offer a way to achieve this functionality.

You could use the `ray_line` method, or the `trend_line` method for placing lines at a specific price and time level.

As for contacting me, my email is listed at the bottom of the README.md. I'd love contributions!

Louis

**Comment by QuantFreedom1022** [comment]
@louisnw01 damn that is terrible ... have you ever thought about using https://nightvision.dev/guide/intro/10-basic-examples.html#_1-first-real-data-chart ... this seems like it is tradingview but made for coders ... the limitations of trading view are so annoying
