### ISSUE TITLE
[BUG] RuntimeError:          An attempt has been made to start a new process before the         current process has finished its bootstrapping phase.          This probably means that you are not using fork to start your         child processes and you have forgotten to use the proper idiom         in the main module:              if __name__ == '__main__':                 freeze_support()                 ...          The "freeze_support()" line can be omitted if the program         is not going to be frozen to produce an executable. /Users/yanghualei/miniconda3/envs/market-analy-39/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 69 leaked semaphore objects to clean up at shutdown   warnings.warn('resource_tracker: There appear to be %d '

### ISSUE THREAD

**Issue by yyqq188** [louisnw01/lightweight-charts-python#158]
### Expected Behavior

chart = Chart() 出现error

### Current Behaviour

chart = Chart() 出现error

### Reproducible Example

```python
chart = Chart() 出现error
```

### Environment

```markdown
- OS:
- Library:
```

**Comment by yyqq188** [comment]
RuntimeError:          An attempt has been made to start a new process before the         current process has finished its bootstrapping phase.          This probably means that you are not using fork to start your         child processes and you have forgotten to use the proper idiom         in the main module:              if __name__ == '__main__':                 freeze_support()                 ...          The "freeze_support()" line can be omitted if the program         is not going to be frozen to produce an executable. /Users/yanghualei/miniconda3/envs/market-analy-39/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 69 leaked semaphore objects to clean up at shutdown   warnings.warn('resource_tracker: There appear to be %d '

**Comment by louisnw01** [comment]
Just for clarity for others who may experience the same issue:

You must encapsulate the `Chart` object within an `if __name__ == '__main__'` block.

Louis
