### ISSUE TITLE
[BUG] Loading qtcharts using pyqt5 successfully causes variable not to be defined

### ISSUE THREAD

**Issue by Dino-Other** [louisnw01/lightweight-charts-python#159]
### Expected Behavior

Using pyqt5 qtcharts and loading successfully does not define the variable 'PyQt5'.

Tried commenting below out and it works otherwise.

> if not PyQt5:
            self.webview.setContextMenuPolicy(Qt.ContextMenuPolicy.NoContextMenu)

### Current Behaviour

![Screenshot 2023-10-12 114849](https://github.com/louisnw01/lightweight-charts-python/assets/145942711/7674b739-70b9-46f1-b28b-c4f61b69fba3)

### Reproducible Example

```python
import pandas as pd
from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget

from lightweight_charts.widgets import QtChart

app = QApplication([])
window = QMainWindow()
layout = QVBoxLayout()
widget = QWidget()
widget.setLayout(layout)

window.resize(800, 500)
layout.setContentsMargins(0, 0, 0, 0)

chart = QtChart(widget)

df = pd.read_csv("ohlcv.csv")
chart.set(df)

layout.addWidget(chart.get_webview())

window.setCentralWidget(widget)
window.show()

app.exec_()
```

### Environment

```markdown
- OS:win10
- Library:1.0.18
```

**Comment by louisnw01** [comment]
Hey @Dino-Other,

Apologies; I'll publish a hotfix asap.

Louis

**Comment by louisnw01** [comment]
Fixed in latest version.

Louis
