### ISSUE TITLE
Suggestions, enhancements etc.

### ISSUE THREAD

**Issue by emma-uw** [louisnw01/lightweight-charts-python#16]
Hey. Some suggestions after playing with the library for a bit.
1.  An option to remove lines when switching between charts (**removeSeries()** by id or just chart method to remove all of them). My workaround (adding remove method to Line):  `self.run_script(f'{self._parent.id}.chart.removeSeries({self.id}.series)')`. And then keeping track of lines I've added.
2. Judging by issues and suggestions on official github I think **fitContent()** option is very popular
3. Option to set **priceLineVisible: false**, **lastValueVisible: false** is good to have when adding a lot of lines programmatically since it becomes a bit messy. Example: 
![qq2](https://github.com/louisnw01/lightweight-charts-python/assets/135511356/3ebe2983-4037-416e-af8e-d4c9abd29b1d)
4. A little syncing bug when creating subchart line. Line is far to the left on initial creation (top picture). Fixes itself after scrolling once or maximizing the chart. ![qq](https://github.com/louisnw01/lightweight-charts-python/assets/135511356/e88c629c-90d9-4903-977d-d5fae8f2b108)

Thank you.

**Comment by louisnw01** [comment]
Hi! 

Thanks for your suggestions; all of these should be implemented.

As for your second suggestion about `fillContent`, do you mean being able to have empty gaps in data?

Thanks,
Louis

**Comment by emma-uw** [comment]
@louisnw01 It scales the chart to fit as much data as possible on the initial load. Max zoom out basically. `chart.timeScale().fitContent();`

**Comment by louisnw01** [comment]
Oh fitContent! Yes that should accessible, potentially by default.

I'll update this issue once all have been implemented.

Thanks for the suggestions!

**Comment by louisnw01** [comment]
Hi again,

All of these features and improvements have now been implemented in the latest version (1.0.11).

Let me know what you think!

Louis

**Comment by Zartexo** [comment]
Hi,

I think it would be nice to have the options "label_visible" and "line_visible" upon line (or chart) creation.

I changed the js.py for myself like this (using price_label and price_line):

`    def create_line(self, color: str = 'rgba(214, 237, 255, 0.6)', width: int = 2, price_label: bool = True, price_line: bool = True) -> Line:
        """
        Creates and returns a Line object.)\n
        """
        self._lines.append(Line(self, color, width, price_line, price_label))
        return self._lines[-1]`

Line class also needs adjustment for this:

`class Line(SeriesCommon):
    def __init__(self, parent, color, width, price_label, price_line):
        self._parent = parent
        self._rand = self._parent._rand
        self.id = f'window.{self._rand.generate()}'
        self.run_script = self._parent.run_script

        self._parent.run_script(f'''
            {self.id} = {{
                series: {self._parent.id}.chart.addLineSeries({{
                    color: '{color}',
                    lineWidth: {width},
                }}),
                markers: [],
                horizontal_lines: [],
            }}
        ''')
        self.run_script(f'''
        {self.id}.series.applyOptions({{
            lastValueVisible: {_js_bool(price_label)},
            priceLineVisible: {_js_bool(price_line)},
        }})''')`

I think it is more intuitive to have this as an argument upon creation.

BR

**Comment by louisnw01** [comment]
I agree; I will add them as parameters to `create_line`, however I do think the `price_line` method should be used for `Chart` and `Subchart`, so I won't add them as parameters for charts.

**Comment by louisnw01** [comment]
> I agree; I will add them as parameters to `create_line`, however I do think the `price_line` method should be used for `Chart` and `Subchart`, so I won't add them as parameters for charts.

Just a note, the SubChart sync bug has not been fixed; on it now!

**Comment by louisnw01** [comment]
> Hi,
> 
> I think it would be nice to have the options "label_visible" and "line_visible" upon line (or chart) creation.

This has been implemented in the latest version.

**Comment by emma-uw** [comment]
@louisnw01 Thanks for the update! 

I think I found a small issue regarding removing the lines in a loop. For example if you add 8 lines and iterate through them with simple `for line in chart.lines():
    line.delete()`. It will only remove 4 lines since delete() will update the list itself. And after first 4 are removed loop will stop. Obvious solution is to copy the list before instead of referencing with `copy(chart.lines())`, but prob it's better to find a workaround on the lib level. What do you think?

On the other note, things I was experimenting last week that can be added.
1. Line extrapolation. Basically pass amount of days with `extrapolate` parameter to create_line(). Detect candle interval, add extra data and then fill nans with

**Comment by louisnw01** [comment]
Hi,

`line.delete` runs `del self` which is the issue. If i remove this code then a shallow copy will work just fine.

I do have plans for a `trend_line` method within the common methods which will be used as:

```python
chart.trend_line(point1=(dt.datetime(2023, 01, 23), 184.25), point2=(dt.datetime(2023, 02, 15), 205.23))
```

I have figured this out; the tricky part is being able to draw them directly onto the canvas, which is how most people would want to use them. Animating them as they are drawn is difficult!

As extrapolate and interpolate are affecting data given by the user, I probably won't implement this as it would make more sense for the user to modify their own data before passing it to the library.

**Comment by emma-uw** [comment]
`as it would make more sense for the user to modify their own data before passing it to the library.`
Agreed. Thanks again for the adjustments.
