### ISSUE TITLE
[BUG] How to save all charts' screenshot into one file?

### ISSUE THREAD

**Issue by likewaterg** [louisnw01/lightweight-charts-python#163]
### Expected Behavior

chart = Chart(inner_height=0.5, inner_width=1)
chart2 = chart.create_subchart(position='bottom', width=1, height=0.5,sync=True)

img = chart.screenshot()
with open('screenshot.png', 'wb') as f:
    f.write(img)

### Current Behaviour

this will only save the chart's screenshot, excluding chart2.
is it possible to save all charts into one file?

### Reproducible Example

```python
N
```

### Environment

```markdown
- OS:MAC
- Library:
```

**Comment by louisnw01** [comment]
Hey @likewaterg,

Unfortunately this is not directly built into the library; however you could use something like Pillow to stitch all the screenshots together into one afterward.

Louis

**Comment by likewaterg** [comment]
just to notice that the problem was solved.
`    img = chart.screenshot()
    img2 = chart2.screenshot()
    img1 = Image.open(io.BytesIO(img))
    img2 = Image.open(io.BytesIO(img2))

    width, height = img1.size

    new_img = Image.new('RGB', (width, height * 2))

    new_img.paste(img1, (0, 0))
    new_img.paste(img2, (0, height))

    new_img.save("output.png")`
