### ISSUE TITLE
[BUG] chart.fit() does not work all the time.

### ISSUE THREAD

**Issue by likewaterg** [louisnw01/lightweight-charts-python#167]
### Expected Behavior

chart = Chart(inner_height=0.5, inner_width=1, width=3000)
chart.watermark(symbol)
chart.legend(visible=True, font_size=14)
chart.precision(8)
chart.fit()

chart.fit() works when it works, but it's not guaranteed.

### Current Behaviour

I was opening multiple charts one by one, all with 1 subchart.
By repeating the process I found that the failure occurred randomly.

I tried to run the script directly by:
chart.run_script(f'{chart.id}.chart.timeScale().fitContent()')
also tried chart.set_visible_range(start=x,end=x), 
the problem still exists.

So I am wondering is there any requirement to trigger chart.fit() so it will work all the time?

### Reproducible Example

```python
`
chart = Chart(inner_height=0.5, inner_width=1, width=3000)
chart.watermark(symbol)
chart.legend(visible=True, font_size=14)
chart.precision(8)
chart.fit()

chart2 = chart.create_subchart(position='bottom', width=1, height=0.5, sync=True)
chart2.legend(visible=True, font_size=14)
chart2.precision(8)
chart.set(df1)
chart2.set(df2)

chart.show()
`
```

### Environment

```markdown
- OS: macos 13.5
- Library:
```

**Comment by louisnw01** [comment]
Hey @likewaterg,

`fit` attempts to fit as much of the currently displayed data within the viewport. As such, you need to call `fit` after setting the data.

Louis
