### ISSUE TITLE
save the crosshair coordinates into a variable

### ISSUE THREAD

**Issue by NikolayNelubov** [louisnw01/lightweight-charts-python#169]
### Question

Hello. Thank you very much for your excellent work. Please answer --> When you click the mouse, save the crosshair coordinates into a variable? Preferably real-time updates. And is it possible to set an event (for example, drawing a horizontal line) when you click on the mouse button (needed for real trading). Thank you.

**Comment by louisnw01** [comment]
Hey,

Drawing lines can be achieved with the toolbox.

Louis

**Comment by sancau** [comment]
Hi @NikolayNelubov, here's a snippet that does the job. I've ran into this limitation myself and this is what I've came up with... The code kinda smells but might help as a quick solution. =) For mouse clicks a simillar approach can be used.
```python
def watch_crosshair_moves(chart):
    chart.crosshair_position = {}

    def on_crosshair_move(point):
        # assigning a new field to an existing object is an anti-pattern
        # but here it's convenient (at least for my use case)
        new_position = json.loads(point)
        if chart.crosshair_position != new_position:
            chart.crosshair_position = new_position
            print(chart.crosshair_position)

    crosshair_script = (
        'function onCrosshairMove(param) {'
            'if (!param.point) {'
                'return;'
            '}'
            f'const time = {chart.id}.chart.timeScale().coordinateToTime(param.point.x);'
            f'const price = {chart.id}.series.coordinateToPrice(param.point.y);'
            'const data = JSON.stringify({time: time, price: price});'
            'window.callbackFunction(`on_crosshair_move_~_${data}`);'
        '}'
        f'{chart.id}.chart.subscribeCrosshairMove(onCrosshairMove);'
    )

    chart.win.handlers['on_crosshair_move'] = on_crosshair_move
    chart.win.run_script(crosshair_script)
```

P.S. @louisnw01 Thank you for what you're doing! It's a nice framework to build on top..

**Comment by esteban2006** [comment]
@sancau thank you for sharing, would you share a more detail example of your implementation?

**Comment by NikolayNelubov** [comment]
@sancau, thank you very much, this is exactly what i need. Now i can try to write do fibonacci and ruler-measure. You are a good person, God bless you with health and success!

In return, i also want to share kindness. I hope someone will be interested. Simplest code async update data on a chart in **real time** --> for Binance.

```
import pandas as pd
from lightweight_charts import Chart
import threading
import requests

def get_realtime_candles(symbol, interval, limit):
    params = {
        "symbol": symbol,
        "interval": interval,
        "limit": limit  # Number of data points to retrieve
    }
    response = requests.get(BASE_URL, params=params)
    data = response.json()
    candles = []
    for candle in data:
        timestamp = pd.to_datetime(candle[0], unit='ms')
        open_price = float(candle[1])
        high_price = float(candle[2])
        low_price = float(candle[3])
        close_price = float(candle[4])
        volume = float(candle[5])
        candles.append({
            'Date': timestamp,
            'open': open_price,
            'high': high_price,
            'low': low_price,
            'close': close_price,
            'volume': volume
        })
    dfs = pd.DataFrame(candles)
    dfs.set_index('Date', inplace=True)
    return dfs

def async_chart_update(chart, timer_update):
    df_update = get_realtime_candles(symbol, timeframe, 10)
    chart.update(df_update.iloc[-1])
    threading.Timer(timer_update, async_chart_update, [chart, timer_update]).start()

if __name__ == '__main__':
    chart = Chart()

    #BASE_URL = "https://fapi.binance.com/fapi/v1/klines"  # for API BINANCE-FUTURES
    BASE_URL = "https://api.binance.com/api/v3/klines"    # for API BINANCE-SPOT
    symbol = "BTCUSDT"
    timeframe = '5m'  # Kline interval: 1m, 5m, 15m, 30m, 1h, 1d
    limit = 1000  # 1000 - Downloads 1000 last сandles
    timer_update = 0.25  # Update datas-chart every(timer_update = seconds)
    chart.set(get_realtime_candles(symbol, timeframe, limit))

    async_chart_update(chart, timer_update)  # FUNC Async update datas
    chart.show(block=True)
```

**Comment by sancau** [comment]
> @sancau thank you for sharing, would you share a more detail example of your implementation?

It's all usual bootstrap code but you need to also invoke the watcher. Works the same also for async use case.

Simple example.
```python
def demo():
    chart = Chart()
    chart.precision(5)
    chart.set(pd.read_csv('test.csv'))
    watch_crosshair_moves(chart)
    chart.show(block=True)

if __name__ == '__main__':
    demo()
```

![image](https://github.com/louisnw01/lightweight-charts-python/assets/16306443/03458353-adcf-4200-a0f7-84101664fe05)

**Comment by NikolayNelubov** [comment]
@sancau Please forgive me for my arrogance, but i have to ask if you happen to have an implementation of the **mouse click counter function**. I see that to get to the core of the library --> need to understand the Java script. I don't know him very well.

For example, you can implement a ruler-measurement using your function --> watch_crosshair_moves(chart) and the function chart.hotkey('shift', '1', coordinate_point_1), chart.hotkey('shift', '2', coordinate_point_2). But it's inconvenient. It would be more appropriate to press the hot keys = which will determine that a ruler-measurement will be drawn. And when click the mouse, a click counter is triggered, where the first value of the counter is the first coordinates of the point, the second click is the second coordinate of the line point, and the third click resets the counter.

If you can’t implement a mouse click counter, then you’ll have to work only through --> hotkeys.

**Comment by sancau** [comment]
@NikolayNelubov 

On click handler can be implemented like this, similar to crosshair move handler.

Here's a complete snippet:

```python
import json

import pandas as pd
from lightweight_charts import Chart


def on_chart_click(data):
    print(data)


def subscribe_click(chart, *, callback):
    js = (
        'function clickHandler(param) {'
            'if (!param.point) {'
            'return;'
            '}'
            f'const time = {chart.id}.chart.timeScale().coordinateToTime(param.point.x);'
            f'const price = {chart.id}.series.coordinateToPrice(param.point.y);'
            'const data = JSON.stringify({time: time, price: price, event_time: param.time});'
            'window.callbackFunction(`on_click_~_${data}`);'
        '}'
        f'{chart.id}.chart.subscribeClick(clickHandler);'
    )

    def decorated_callback(data):
        # add some preprocessing
        data = json.loads(data)
        data = {
            'click_time': pd.to_datetime(data['event_time'], unit='s'),
            'click_position': {
                'timestamp': pd.to_datetime(data['time'], unit='s'),
                'price': data['price'],
            }
        }
        return callback(data)

    chart.win.handlers['on_click'] = decorated_callback
    chart.win.run_script(js)


def main():
    chart = Chart()
    chart.precision(5)
    chart.set(pd.read_csv('test.csv'))
    subscribe_click(chart, callback=on_chart_click)
    chart.show(block=True)


if __name__ == '__main__':
    main()

```

![image](https://github.com/louisnw01/lightweight-charts-python/assets/16306443/8a0143ba-27e4-432f-a054-9ee605dd1e15)

@louisnw01 What you think? This is probably a useful feature for building custom workflows. Should I consider a PR? It would be nice IMO if `Chart` will get `.subscribe_click` method for such use cases.

**Comment by NikolayNelubov** [comment]
@sancau - Perfect! My bow to you and great gratitude. Thanks to your two functions + Hotkeys, it is now possible to implement a lot of things.

I am sure many will find your feature useful. All the best to you - Thank you!

**Comment by esteban2006** [comment]
@sancau thank you for your response. 

this response : It's all usual bootstrap code but you need to also invoke the watcher. Works the same for async use case
it is what i need it to understand, implementation,

what i am trying to achive is that when a right click, on the background a menu should appear something similar to the menu that appears when you click on a line 

example 


![image](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/5cdd792d-a065-40a4-9fae-723693c3422a)

each of this options will have it own method implementation 


@louisnw01 this would be good to apply a seetings menu button next to the hide and unhide option of the line 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/837dd911-a0ea-47fc-ac82-95fc964d6f6c)

**Comment by esteban2006** [comment]
@sancau this function def watch_crosshair_moves(chart): needs an exit method, python thread remains open when closing the window

**Comment by sancau** [comment]
@NikolayNelubov  I'm glad it helped you :) 

@esteban2006 I'll look into it later (threading issue). Thx for the tip! As for the right clicks I didn't found such an event in LWTV charts API. But it's probably can be solved by capturing right click in Python, given you know the position of the crosshair.

**Comment by esteban2006** [comment]
@sancau i belive right click has be disabled by API, but my approache is to subscribe a JS function to add more option on a line via subscribeHoverMove, so basically use the line as a clickable body that can be used to lauch other optios 

something like this 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/bb04c3a6-86a0-4eed-bf89-4ec0d6067ffb)


@louisnw01 is there a way to subscribe more options to the menu options ?- on the fly options?

**Comment by esteban2006** [comment]
@sancau I believe that the solution for most of devleopers will be your initial approach subscribe_click, when are you able to subscribe right click to display a menu will be the top solution, this is something that could give you a hit,




```
# Define buy callback function
def on_buy(data):
    print("Buy option clicked. Data:", data)

# Define sell callback function
def on_sell(data):
    print("Sell option clicked. Data:", data)


def subscribe_right_click(myChart, *, buy_callback, sell_callback):
        js = (
            'function rightClickHandler(param) {'
                'if (!param.point) {'
                'return;'
                '}'
                f'const time = {self.chart.id}.chart.timeScale().coordinateToTime(param.point.x);'
                f'const price = {self.chart.id}.series.coordinateToPrice(param.point.y);'
                'const data = JSON.stringify({time: time, price: price});'
                'window.rightClickCallback(`on_right_click_~_${data}`);'
            '}'
            f'{self.chart.id}.chart.subscribeCrosshairMove(rightClickHandler);'
        )

        def handle_right_click(data):
            data = json.loads(data)
            timestamp = pd.to_datetime(data['time'], unit='s')
            price = data['price']
            print("Right-clicked data - Timestamp:", timestamp, "Price:", price)

            option = input("Enter 'buy' or 'sell': ")
            if option.lower() == 'buy':
                buy_callback(data)
            elif option.lower() == 'sell':
                sell_callback(data)
            else:
                print("Invalid option.")

        self.chart.win.handlers['on_right_click'] = handle_right_click
        self.chart.win.run_script(js)

subscribe_right_click(myChart, buy_callback=on_buy, sell_callback=on_sell)
```


thank you for sharing 
cheers

**Comment by linqingfan** [comment]
> @NikolayNelubov
> 
> On click handler can be implemented like this, similar to crosshair move handler.
> 
> Here's a complete snippet:
> 
> ```python
> def on_chart_click(data):
>     print(data)
> 
> 
> def subscribe_click(chart, *, callback):
>     js = (
>         'function clickHandler(param) {'
>             'if (!param.point) {'
>             'return;'
>             '}'
>             f'const time = {chart.id}.chart.timeScale().coordinateToTime(param.point.x);'
>             f'const price = {chart.id}.series.coordinateToPrice(param.point.y);'
>             'const data = JSON.stringify({time: time, price: price});'
>             'window.callbackFunction(`on_click_~_${data}`);'
>         '}'
>         f'{chart.id}.chart.subscribeClick(clickHandler);'
>     )
> 
>     def decorated_callback(data):
>         # add some preprocessing
>         data = json.loads(data)
>         data = {
>             'timestamp': pd.to_datetime(data['time'], unit='s'),
>             'price': data['price'],
>         }
>         return callback(data)
> 
>     chart.win.handlers['on_click'] = decorated_callback
>     chart.win.run_script(js)
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/16306443/278330103-efebff66-270b-4b49-a0b2-a658d20313b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4NTI1NDUsIm5iZiI6MTczNDg1MjI0NSwicGF0aCI6Ii8xNjMwNjQ0My8yNzgzMzAxMDMtZWZlYmZmNjYtMjcwYi00YjQ5LWEwYjItYTY1OGQyMDMxM2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDA3MjQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYjZhODQwYzU3MmI0ZmU2ODY5NmMzYmYwZDFkMDMxMmY1ZTc0NmJjYmJhNjM0OTFlOWYwOGU1OTkzNzgwZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MSFeaWyKzY3AH8AFTfzNpHfNQlq88A8jghrO0s1a1RI)
> 
> @louisnw01 What you think? This is probably a useful feature for building custom workflows. Should I consider a PR? It would be nice IMO if `Chart` will get `.subscribe_click` method for such use cases.

@sancau, perhaps this is some basic, I notice that the print will print quite a lot of time, is it because when clicking, it generates more than 1 mouse click event? How do we prevent this multiple call?
