### ISSUE TITLE
Sync crosshairs between Subcharts

### ISSUE THREAD

**Issue by Zartexo** [louisnw01/lightweight-charts-python#17]
Hi,
thank your for sharing this project. Great work!

i am using a subchart to have some indicators below the ohcl chart. In the subchart I use lines to display the indicator values. Is it possible to have the view of the two charts synced and show the current value of the line subchart?
Example:
![Unnamed](https://github.com/louisnw01/lightweight-charts-python/assets/104310309/e5d6eadd-f133-4189-a08f-07b8ca0ff177)

**Comment by louisnw01** [comment]
Hi!

Whilst crosshair syncing is not currently a feature in Lightweight Charts, it appears it is possible to change the source code to implement this. 

I will respond to this thread when I have a definitive answer!

Louis

**Comment by louisnw01** [comment]
Hi!

After messing around with the source code, I have been able to implement this feature by using a custom build of Lightweight Charts. 

It will automatically be enabled upon using the `sync` paramter.

Thanks for the suggestion!
