### ISSUE TITLE
countdown to bar close

### ISSUE THREAD

**Issue by NikolayNelubov** [louisnw01/lightweight-charts-python#170]
### Description

Hello again. Sorry to bother you, but I need your help. How to display countdown to bar close. 
![cd_close](https://github.com/louisnw01/lightweight-charts-python/assets/47115620/5d84aaa8-2506-43e1-bcf1-d4c05aab339c)

I need it for real time trading. But it is possible even in static mode (chart.show(block=True)). Perhaps need to create a function whose parameters will be 1) current price (with an offset of 0.1% from the current price) and 2) time (pre-calculated from a given timeframe).

example --> **chart.timePriceScale(price, time)**

thank you in advance for your help.

**Comment by louisnw01** [comment]
Hey,

This can be achieved by modifying the price line title.


Louis
