### ISSUE TITLE
[BUG] python Thread remains open after closing window - live data only

### ISSUE THREAD

**Issue by esteban2006** [louisnw01/lightweight-charts-python#172]
### Expected Behavior

When closing a Window the python thread should also close,  works well with all of the example but live_data.py example 

### Current Behaviour

when closing window for live chart the python thread keeps alive in windows manager

### Reproducible Example

```python
run 
lightweight-charts-python\examples\2_live_data\live_data.py
close the window 
python thread keeps open 
confirm it on task manager
```

### Environment

```markdown
- OS: Window
- Library: lightweight-charts-python
```

**Comment by louisnw01** [comment]
Hey @esteban2006,

Whilst this is unexpected behavior, there is no direct way to amend this to automagically quit the thread. My recommendation would always be to use `chart.show_async` for a live chart setup, and then use the `chart.is_alive` attribute to check within your loop if the window has been closed.

If you don't want to use asyncio, you could add this statement inside the for loop:

```python
if chart._exit.is_set():
    break
```

Louis

**Comment by esteban2006** [comment]
resoved,

thank you @louisnw01 for you response,
