### ISSUE TITLE
changing time frams will break initial display of the chart [BUG] 

### ISSUE THREAD

**Issue by esteban2006** [louisnw01/lightweight-charts-python#175]
### Expected Behavior

First of all congratulations on your development, it is outstandnig 🥇 

I have noticed the following behavior :

when change time frames the displays of the bars should remain the same, this is the init state of the chart working on 5 min with a Henki Ashi style live ticking from MT5

![image](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/93b226bb-501b-40eb-92dc-34356045f9f0)

now this is the bar after changing to 2H or to any other time frame 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/ccfcdcee-72d5-4851-86de-4344ed5680fc)

please notice that the separation of the bars only happen in the space the the windows is initially rendered 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/65c14542-aa09-48d9-961b-7bbe0724a72a)

### Current Behaviour

When changing from betweeen times frames the bars in the chart will change their sizes padding and spacing, only in the window space that the data has initially rendered 

### Reproducible Example

```python
create an instace of chart 
add time frame switchers 
load data accordingly 
set data 
and wait the magic
```

### Environment

```markdown
- OS: window 11
- Library:
```

**Comment by jlixfeld** [comment]
Can you provide reproducible example code using the ohlc CSVs in the repo?

Otherwise, print the chart data out on a timeframe switch and see that you get the datapoints you expect.

For what it's worth, it's up to you to provide the `Chart()` instance the OHLC data it needs for each timeframe you need it on.  The library won't do that for you.

**Comment by louisnw01** [comment]
Hey @esteban2006,

Seems to render fine, you just need to change the timeframe of the line data as well as the candle data.

Louis

**Comment by esteban2006** [comment]
@louisnw01  thank you, when code runs the first time : will load the default market and the default time 

market, 5m and it will produce the following df 
```

                   time         open         high          low        close
0   2023-10-22 19:05:00 436166.86875 436294.85000 435667.55000 436099.16750
1   2023-10-22 19:10:00 435865.54250 436273.39000 434862.21000 435631.91750
2   2023-10-22 19:15:00 435540.25625 435850.33000 435139.33000 435448.59500
3   2023-10-22 19:20:00 435434.36250 435762.95000 434714.46000 435420.13000
```


this is my code switcher function 
```

def getNewTimeFrame(myChart):
    thisTime = self.chart.topbar['timeframe'].value
    symbol = self.chart.topbar['symbol'].value
    rawData = self.adviser.getOHLC(symbol, thisTime, thisLen)
    df1 = rawData

    if self.settings['chart']['type'] == "HA":
        df1 = self.convertToHeikinAshi(rawData)
        print (df1)

    self.applyGraphLayout()
    self.applyGraphCandleSettings()
    self.applyGraphVolSettings()
    self.applyGraphCrosshairSettings()
    self.runIndicators(df1)
    self.chart.set(df1, render_drawings=True)  


```

after switching 
```

                   time         open         high          low        close
0   2023-09-12 22:00:00 531596.38000 536164.56000 529698.17000 532460.56000
1   2023-09-13 00:00:00 531997.73000 533479.62000 527568.22000 531534.90000
2   2023-09-13 02:00:00 531338.12625 532787.92000 528652.85000 531141.35250
3   2023-09-13 04:00:00 530615.18750 532253.12000 527176.52000 530089.02250

```

i belive the timeframe of the line has been updated ??? I am right ??
or do i need reset 

```

self.chart.time_scale(
        right_offset: int, 
        min_bar_spacing: float, 
        visible: bool, 
        time_visible: bool, 
        seconds_visible = True, 
        border_visible = True, 
        border_color = '#fff000'
    )
```

thank you in advance

**Comment by louisnw01** [comment]
The candle data is fine, but you didn't provide any line data.

Louis
