### ISSUE TITLE
Plot a simple graph with the price of a stock

### ISSUE THREAD

**Issue by homerokzam** [louisnw01/lightweight-charts-python#177]
### Question

How do I plot a simple graph with the value of a stock?

This simple code below doesn't work.

Thanks

### Code example

```python
import pandas as pd
import yfinance as yf
from lightweight_charts import Chart, JupyterChart

df_ticker = yf.download('MSFT')['Close'].to_frame()
tvchart = JupyterChart()
tvchart.set(df_ticker)
tvchart.load()

# line = tvchart.create_line(df_ticker.columns[0])
# line.set(df_ticker)
# tvchart.add_line(line)
# tvchart.load()
```

**Comment by karunkrishna** [comment]
The column names and order matter I believe 

Make sure your datarame has ['date', 'open', 'high','low','close'] in that order when your use tvchart.set(df_ticker)

Best to start with the working example and then make sure the input you are supplying the the exact same

**Comment by homerokzam** [comment]
Thank you for your comment. But this way the chart is a candlestick (OHLC), but I just want a line with the stock price. The code below works, but it's not what I want.

import pandas as pd
import yfinance as yf
from lightweight_charts import Chart, JupyterChart

df_ticker = yf.download('MSFT')
tvchart = JupyterChart()
tvchart.set(df_ticker)
tvchart.load()

**Comment by karunkrishna** [comment]
You need to look at the create_overlay example I think 

tvchart = JupyterChart()
line = tvchart .create_line(name='Close')
line.set(df_ticker[['Close']])

df_ticker index must be date or datetime index

**Comment by homerokzam** [comment]
The code below worked. Thank you very much @karunkrishna !


import pandas as pd
import yfinance as yf
from lightweight_charts import Chart, JupyterChart

df_ticker = yf.download('MSFT')

tvchart = JupyterChart()
line = tvchart.create_line(name='Close')
line.set(df_ticker['Close'].to_frame())
tvchart.load()

**Comment by homerokzam** [comment]
The code below worked. Thank you very much @karunkrishna !


import pandas as pd
import yfinance as yf
from lightweight_charts import Chart, JupyterChart

df_ticker = yf.download('MSFT')

tvchart = JupyterChart()
line = tvchart.create_line(name='Close')
line.set(df_ticker['Close'].to_frame())
tvchart.load()
