### ISSUE TITLE
two bugs with rays [BUG] 

### ISSUE THREAD

**Issue by NikolayNelubov** [louisnw01/lightweight-charts-python#178]
### Expected Behavior

Hello. The rays do not update position and if (**toolbox=True**) the entire graph is drawn incorrectly.
![bb](https://github.com/louisnw01/lightweight-charts-python/assets/47115620/03f5b361-7250-48c5-9a1e-26dac87e0bb0)

example data --> 
[ohlc.csv](https://github.com/louisnw01/lightweight-charts-python/files/13180373/ohlc.csv)

### Current Behaviour

This bug do not produces no errors in Python. 
![sd](https://github.com/louisnw01/lightweight-charts-python/assets/47115620/c3ca8f61-5efc-462e-8006-c6ec36929dd9)

### Reproducible Example

```python
import pandas as pd
from lightweight_charts import Chart

if __name__ == '__main__':
    chart = Chart(toolbox=True)
    chart.legend(True)

    df = pd.read_csv('ohlc.csv')
    chart.set(df)

    rayLine = chart.ray_line(df['date'].iloc[-30], df['close'].iloc[-30])
    
    new_position = pd.Series({'time': df['date'].iloc[-50], 'value': 162})
    rayLine.update(new_position)    # <---- NO UPDATE RAY-LINE


    chart.show(block=True)
```

### Environment

```markdown
- OS: Windows 10 22H2 
- Library: 1.0.18.1
```

**Comment by louisnw01** [comment]
Hey @NikolayNelubov,

Do you get the same issue if you use the `ohlcv.csv` data provided in the examples?

Louis

**Comment by NikolayNelubov** [comment]
With `ohlcv.csv` the rayline is displayed correctly. But still does not  `rayLine.update(new_position)` his position.

**Comment by louisnw01** [comment]
Hey @NikolayNelubov,

As raylines are essentially a subclass of the `Line` object, there is no way to update them using the update method. At present, you will have to delete the previous ray line and create a new one.

**Comment by NikolayNelubov** [comment]
I see, thank you. I hope in a future version there will be a method for updating the position for rays. Good luck to you in all your endeavors!
