### ISSUE TITLE
Enhancement request- save chart as html

### ISSUE THREAD

**Issue by sbgmicromax** [louisnw01/lightweight-charts-python#18]
Can you please add an enhancement to save the chart as html with all displayed values. 

Thanks

**Comment by louisnw01** [comment]
Hi!

Thanks for the suggestion. Would the chart be saved after the data has been updated by `update_from_tick` or `update`, or is this idea for static data (with markers, lines, horizontal lines etc.)

**Comment by sbgmicromax** [comment]
Hi,
Idea is for static data with markers, lines, horizontal lines etc.

**Comment by louisnw01** [comment]
I see, I'll look into it!

For the time being, this is actually possible with the `JupyterChart` and `StreamlitChart` objects; as they can only display static data, they save all the HTML necessary to re-create the chart. So if you swapped out your `Chart` object with a `JupyterChart` like this:

```python
chart = JupyterChart()

# Add all configurations etc
chart.set('ohlcv.csv')
chart.horizontal_line(200)

print(f'{self._html}</script></body></html>')
```

That print statement would contain all the HTML neccessary to to use the chart as a standalone webpage.

Let me know if this works, but I will look into implementing this directly!

Louis

**Comment by mrxz44** [comment]
Hi @louisnw01 awesome project btw! 
Please tell if there a way to export chart image as png or jpeg? That would be quite a useful feature

**Comment by louisnw01** [comment]
> Hi @louisnw01 awesome project btw!
> Please tell if there a way to export chart image as png or jpeg? That would be quite a useful feature

Thank you!

I have noticed Lightweight Charts has a `takeScreenshot()` method, which I am working to include in the library.

Should be released next week!

Louis

**Comment by hari3118** [comment]
Hi @louisnw01, 

I successfully saved the chart as html page. But when i tried opening the html, chart is not showing to full window.

`if __name__ == '__main__':
    chart = JupyterChart()
    chart.set(df)

output = f'{chart._html}</script></body></html>' 
with open('chart_output.html', 'w', encoding='utf-8') as file:
    file.write(output)`

![image](https://github.com/louisnw01/lightweight-charts-python/assets/136995364/3ec1489c-c060-4e1f-8654-3ca13306d7c6)


Could you please help me to set the output chart to browser window. Thanks for your help in advance.

**Comment by louisnw01** [comment]
> Hi @louisnw01, 
> 
> 
> 
> I successfully saved the chart as html page. But when i tried opening the html, chart is not showing to full window.
> 
> 
> 
> `if __name__ == '__main__':
> 
>     chart = JupyterChart()
> 
>     chart.set(df)
> 
> 
> 
> output = f'{chart._html}</script></body></html>' 
> 
> with open('chart_output.html', 'w', encoding='utf-8') as file:
> 
>     file.write(output)`
> 
> 
> 
> ![image](https://github.com/louisnw01/lightweight-charts-python/assets/136995364/76e56791-82dd-4b96-9568-b81b865e8172)
> 
> 
> 
> Could you please help me to set the output chart to browser window. Thanks for your help in advance.

Hi,

Have you tried setting the width and height to `'100%'`

**Comment by louisnw01** [comment]
I'm referring to the width parameter of the class.

If that doesn't work, try the same code with the `StreamlitChart` object instead.

**Comment by louisnw01** [comment]
Hi again,

In regards to a built in method to retrieve the html, I am not planning on implementing this at the moment; It will require a significant refactoring of the codebase.

I'll never say never, but im taking it off my list for the moment. So if my fix works, continue to use that for the time being.

Thanks!
Louis

**Comment by Fougl** [comment]
Hi, is it possible to have timeframe switching in html? I am struggling to implement where the get_data_bar will fetch the data. I am not knowlagable in html, so not sure how it will know which data to switch. I am using the Streamlit chart object
![image](https://github.com/louisnw01/lightweight-charts-python/assets/21178929/55bcbb61-98ca-4175-a3dd-98e33a6cdbd4)
