### ISSUE TITLE
Upgrade to Lightweight Charts 4.1 to allow plugin support

### ISSUE THREAD

**Issue by dogaince** [louisnw01/lightweight-charts-python#180]
### Description

A new Method just like the create_horizontalline but draws a box/rectangle. 

### Code example

```python
chart.create_rectangle(startpoint, endpoint, color, transparancy) 
or 
chart.create_rectangle(startpoint, width, height, color, transparancy) etc.
```

### Method of implementation

Since lightweigtcharts 4.1 there is plugin support and a an example for drawing a rectangle with the toolbox.

**Comment by louisnw01** [comment]
Hey @dogaince,

Plugin support will allow for this and much more (real vertical lines, VRVP etc) and I'm excited to get this library up to date!

I'm working on upgrading to 4.1, but as I am using a custom build of version 4 I'll need to do a merge. Hopefully i'll release in the coming weeks!

p.s 've renamed this post accordingly

Louis

**Comment by louisnw01** [comment]
Additionally, the rectangle plugin currently provided by Lightweight Charts is not sufficient as it does not allow you to draw rectangles past the last data point; I am aware that someone created a custom build for this a while ago, but until it is remade as a plugin this won't be possible.

Louis

**Comment by AbdurrahimBalta** [comment]
We wait you louis 👯

**Comment by louisnw01** [comment]
Just to update, I still haven't seen an implementation of boxes/lines that takes into account the interval so that they can be drawn past the last datapoint, so I'll have to hold off on this for now.

In the future I may get time to cross over my implementation to plugins, but I cannot promise anything. Here's to hoping 

Louis

**Comment by louisnw01** [comment]
Implemented!

Louis
