### ISSUE TITLE
[BUG] Histogram legend does not get removed when histogram is deleted

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#181]
### Expected Behavior

The legend should be removed like the current behavior for line overlay indicators
When a histogram is deleted the legend should also be removed

### Current Behaviour

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/7c715cc8-3ec4-4ee0-b20c-7fe72f8be9f5)

### Reproducible Example

```python
import pandas as pd
import pandas_ta
from lightweight_charts import Chart
import importlib.metadata


if __name__ == '__main__':
    chart = Chart(inner_height=0.6)
    chart.legend(visible=True)

    df = pd.read_csv('ohlcv.csv')
    df.date = pd.to_datetime(df.date, format='%Y-%m-%d')
    df = df['date open high low close volume'.split()]
    df = df.set_index('date')

    df[['macd','hist','signal']] =  pandas_ta.macd(df.close, slow=14, fast=7, signal=2)
    df = df.dropna()
    chart.set(df)

    subplot = chart.create_subchart(height=0.4, width=1)
    subplot.legend(visible=True)
    hist = subplot.create_histogram(name='hist')
    hist.set(df[['hist']])

    hist.delete()       # DELETE SHOULD REMOVE LEGEND

    hist2 = subplot.create_histogram(name='hist')
    hist2.set(df[['hist']])

    chart.topbar.textbox('version', f'v{importlib.metadata.version("lightweight_charts")}')
    chart.show(block=True)
```

### Environment

```markdown
- OS:Win10
- Library:1.0.18.2
```

**Comment by karunkrishna** [comment]
It looks these like delete doesn't completely removed the histogram either. 
So the data is still present

So in this image here, it shows both the 1Min and 1 Hour data, even though the 1Min data should have been deleted 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/dd959678-c622-4779-b762-3916f7defcc6)

**Comment by louisnw01** [comment]
Hey @karunkrishna,

Will fix for the next update.

Louis

**Comment by karunkrishna** [comment]
The legend is fixed, but I don't think the underlying data is being deleted. 
When I start off with a 5Minute histogram and then switch to 30 minute histogram....the 5 Minute histogram is still persistent, I will try to create an example and raise a separate bug

**Comment by karunkrishna** [comment]
Actually nvm. I deleted my  earlier comment.  Used the wrong dataframe.....looks and behaves as expected. Thanks
