### ISSUE TITLE
price bar-scale is buggy [BUG] 

### ISSUE THREAD

**Issue by NikolayNelubov** [louisnw01/lightweight-charts-python#182]
### Expected Behavior

When I scroll the price on one currency and then select another currency, the price chart disappears. Please help fix this problem. 
![s1](https://github.com/louisnw01/lightweight-charts-python/assets/47115620/de4af1e8-9fd1-4b9a-9f8e-9890e4a09ea5)

after, using the function def **on_search(chart, searched_string)**, using the F key i select the ADA, but the chart does not show candles. 

![s2](https://github.com/louisnw01/lightweight-charts-python/assets/47115620/23f01bb8-3990-4492-bd42-9bfa85f8a9e5)

the name changes in the menu, but the graph is not updated with new data... 

files example 
[BTC.csv](https://github.com/louisnw01/lightweight-charts-python/files/13207363/BTC.csv)
[ADA.csv](https://github.com/louisnw01/lightweight-charts-python/files/13207364/ADA.csv)

### Current Behaviour

Chart(debug=True)  This bug do not produces no errors in Python.

### Reproducible Example

```python
import pandas as pd
from lightweight_charts import Chart


def get_bar_data(symbol, timeframe):
    if symbol not in ('BTC', 'ADA'):
        print(f'No data for "{symbol}"')
        return pd.DataFrame()
    return pd.read_csv(f'{symbol}.csv')

def on_search(chart, searched_string):  # Called when the user searches.
    new_data = get_bar_data(searched_string, '1h')
    if new_data.empty:
        return
    chart.topbar['symbol'].set(searched_string)
    if searched_string == 'BTC':
        chart.precision(1)
    if searched_string == 'ADA':
        chart.precision(4)
    chart.set(new_data)

if __name__ == '__main__':
    chart = Chart(width=1200, height=800, toolbox=False)
    chart.legend(True)

    chart.events.search += on_search
    chart.topbar.textbox('symbol', 'BTC')

    df = get_bar_data('BTC', '1h')
    chart.set(df)

    chart.show(block=True)
```

### Environment

```markdown
- OS: Windows 10 22H2 
- Library: 1.0.18.1
```

**Comment by louisnw01** [comment]
Fixed in the latest version.

Louis
