### ISSUE TITLE
Question about having multiple vertical span objects

### ISSUE THREAD

**Issue by longtu02** [louisnw01/lightweight-charts-python#183]
### Question

Hi Louis, I have a dummy question. Is there a way to have multiple VerticalSpan objects for different vertical spans with different colors? Thanks!

**Comment by karunkrishna** [comment]
You can apply multiple spans on the same chart/subchart, but if they overlay best to set the alpha <1

**Comment by longtu02** [comment]
> You can apply multiple spans on the same chart/subchart, but if they overlay best to set the alpha <1

Thanks @karunkrishna, I am able to have multiple spans on the same chart. However, I do not know how to reference in order to delete the spans. Do you have a suggestion? Very much appreciated!!!

**Comment by karunkrishna** [comment]
Assign each vertical span to a variable (for example span1). 
When you create a vertical_span, it returns the object VerticalSpan
You can then do delete on said variable 

for example:

span1.delete()
...
span3.delete()


therefore you need to keep track of the span programmatically 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/c1acea53-f205-4ced-88bb-49f881d7d204)

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/066b4d0f-de44-4741-8635-81055bd5a618)

**Comment by longtu02** [comment]
@karunkrishna Very much appreciated your sugestion!!!
