### ISSUE TITLE
How can I add or change the title of a chart window?

### ISSUE THREAD

**Issue by anilwarbhe** [louisnw01/lightweight-charts-python#184]
### Question

It would be good if  can name the chart window by giving it a title. How can I add it?

`chart = Chart(title='Candle Stick Chart', debug=True) `
OR
Something like `chart.add_title('Candle Stick Chart')`

**Comment by louisnw01** [comment]
Hey @anilwarbhe,

I'll look to add this in a future update.

Louis

**Comment by louisnw01** [comment]
Added the title parameter in the latest version.

Louis
