### ISSUE TITLE
Is there a way to add Marker/Annotation

### ISSUE THREAD

**Issue by koollobana69** [louisnw01/lightweight-charts-python#185]
### Description

E.g When showing Buy or Sell signals on the chart, is it possible to add Markers or Annotations at particular time.

e.g
 {
                    'time': enter_date,
                    'position': 'aboveBar',
                    'color': '#068410',
                    'shape': 'circle',
                    'text': 'Buy',
                    'size': 2
                }

**Comment by emma-uw** [comment]
chart.marker(time, position='above', shape='circle', text='Buy', color='#FFFFFF')
