### ISSUE TITLE
line legends are not showing after last update [BUG] 

### ISSUE THREAD

**Issue by esteban2006** [louisnw01/lightweight-charts-python#186]
### Expected Behavior

all lines legend should be display (name)

![image](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/5cc7415d-7bd2-4d6c-a169-bfd8e93f5cfc)

### Current Behaviour

not displaying info since recent update

### Reproducible Example

```python
load chart as expected, before the update was working but now it is not. any hint ??
```

### Environment

```markdown
- OS:windows 11 
- Library:
```

**Comment by louisnw01** [comment]
Just published a hotfix. Apologies!

**Comment by esteban2006** [comment]
No worries mate, thank you, it worked on my side
