### ISSUE TITLE
How can I make this?

### ISSUE THREAD

**Issue by 95ge** [louisnw01/lightweight-charts-python#188]
### Question

Hello,I am very thinkful to use this project.Now,I have a question,how can I make this plot by lightweight-charts-python。I read the TUTORIALS but I didn't find how to make it.Can you show me a demo ?Thinks very much!!!
![图片](https://github.com/louisnw01/lightweight-charts-python/assets/92923254/a4934113-69fa-4b65-89c2-e18c357ff03f)

**Comment by louisnw01** [comment]
Hey @95ge,

Please read the docs on [Synced Line Charts](https://lightweight-charts-python.readthedocs.io/en/latest/examples/subchart.html#synced-line-chart) for info on how to implement MACD.

Louis

**Comment by 95ge** [comment]
hello!,I read the Link,But I still can not understand it ,can show make a example code in the examples florder? thank you!
