### ISSUE TITLE
Throws error after updating to the latest version 1.0.18.3 and 1.0.18.4

### ISSUE THREAD

**Issue by anilwarbhe** [louisnw01/lightweight-charts-python#189]
### Question

I am receiving the following error after updating to the versions higher than 1.0.18.2.

chart._lines[0].update(sma_tick)
  File "/home/anil/pyprojects/trado/venv/lib/python3.11/site-packages/lightweight_charts/abstract.py", line 236, in update
    if self._last_bar and series['time'] != self._last_bar['time']:

Please Help.

**Comment by esteban2006** [comment]
@anilwarbhe I believe you need to update your pandas lib, I faced the same problem but fixed it with pip install --upgrade pandas

this will cause you to fix your pandas implementation, in some parts if the pandas version is not the lates

regards,

**Comment by anilwarbhe** [comment]
Pandas library was of already a latest version. But still tried reinstalling but still receving the same error. 

  File "/home/anil/pyprojects/trado/venv/lib/python3.11/site-packages/lightweight_charts/abstract.py", line 236, in update
    if self._last_bar and series['time'] != self._last_bar['time']:
  File "/home/anil/pyprojects/trado/venv/lib/python3.11/site-packages/pandas/core/generic.py", line 1519, in __nonzero__
    raise ValueError(
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by esteban2006** [comment]
Your pandas implementation has one problem, are you using df.at ? To select values or how are you selecting values ? You must use df.Olof to avoid this problem of yours

**Comment by louisnw01** [comment]
Hey @anilwarbhe,

Appeared to be an ambigous check issue; should be fixed in the latest hotfix.

Louis

**Comment by anilwarbhe** [comment]
I am using iloc to access the values. I checked out the data types and its'

self._last_bar['time']
1698796800
<class 'numpy.int64'>

series['time']
1698796800.0
self._last_bar['time']

**Comment by anilwarbhe** [comment]
Thank you so much for the hotfix!
