### ISSUE TITLE
Decrease margins of price scale for candlesticks

### ISSUE THREAD

**Issue by TagHaendler** [louisnw01/lightweight-charts-python#19]
Hi there,

I have a question regarding the horizontal price line that gets automatically created when creating a line (e.g. for an indicator).

Is it possible to remove or disable this feature? I looked through the documentation and also in the js.py file but can't figure out how to do this. 

Also how do I scale the y-axis so that it shows the lowest candle in the viewport at the bottom and the highest at the top and ignores all indicators? Is this somehow possible? Currently I have to manually adjust the y-axis to achieve this.

Thanks!

**Comment by louisnw01** [comment]
Hi,

The first part of your issue was raised in #16; I am adding an option to disable this line in the next update.

For the second part of your issue, could you drop a screenshot here of the output your getting on the chart, and the output that you would like to happen automatically? That way I can understand exactly what you mean.

Thanks!

**Comment by emma-uw** [comment]
`Is it possible to remove or disable this feature? I looked through the documentation and also in the js.py file but can't figure out how to do this.`
Can add 2 line like this if you need a workaround while waiting for the new version
![изображение](https://github.com/louisnw01/lightweight-charts-python/assets/135511356/5ee1fec5-be39-4e87-a85f-09411ab8d760)

**Comment by TagHaendler** [comment]
> 
Hi and thanks for your quick reply. Thank for adding the option in the next version can't wait!

As for the second point. Maybe it is what emma-uw mentioned in #16 with the fitContent(). So when I create a chart this is what my default screen looks like: Everything is centered but the candles are small due to the large y-axis spread.
![final](https://github.com/louisnw01/lightweight-charts-python/assets/76731382/c528eb40-387e-4ef7-912e-43d554e5d9a4)

This is what I want. So essentially I want the bottom of the y-axis to be the lowest wick of the viewport and the top to be the highest wick of the viewport (I circled the two candles white) and also +- an offset would be ideal. I managed to achieve this with other packages but always struggled with ignoring the indicators in the viewport (I circled them red). In other packages the y-axis would always fit to the highest and lowest value of the viewport, so this also includes the indicators and not only the candlestick series. Hope this helps to understand what I would want ideally. Basically a way to fit the y-axis to the high/low of the candlestick series in the viewport. 
![default](https://github.com/louisnw01/lightweight-charts-python/assets/76731382/ab1c6c73-6add-4cb2-92f0-61ebd67f0155)

**Comment by TagHaendler** [comment]
> `Is it possible to remove or disable this feature? I looked through the documentation and also in the js.py file but can't figure out how to do this.` Can add 2 lines like this if you need a workaround while waiting for the new version ![изображение](https://user-images.githubusercontent.com/135511356/244806806-5ee1fec5-be39-4e87-a85f-09411ab8d760.png)

This worked perfectly, thank you very much! Gotta try more things now. :)

**Comment by louisnw01** [comment]
Just to update; the first part of your issue has been implemented in the latest version (1.0.11).

I'll take a look into adding price scale margins!

Louis

**Comment by TagHaendler** [comment]
> Just to update; the first part of your issue has been implemented in the latest version (1.0.11).
> 
> I'll take a look into adding price scale margins!
> 
> Louis

It works perfectly, thank you very much. And the lines common method is also really useful. I am currently storing all the lines in a dictionary for a specific ticker but thanks to the new update I can adjust my code.

Btw. are you also thinking about implementing the series compare? I will give it a try later and see if it works.

**Comment by louisnw01** [comment]
> > Just to update; the first part of your issue has been implemented in the latest version (1.0.11).
> > I'll take a look into adding price scale margins!
> > Louis
> 
> It works perfectly, thank you very much. And the lines common method is also really useful. I am currently storing all the lines in a dictionary for a specific ticker but thanks to the new update I can adjust my code.
> 
> Btw. are you also thinking about implementing the series compare? I will give it a try later and see if it works.

Glad I could help!

Technically the series compare example is already possible, by just using `create_line` and not setting any candle data.

**Comment by TagHaendler** [comment]
I will give it a try and will let you know.

If you open TradingView and right click on the y-axis, it says 'scale price chart only'. So basically this is the second request. I think this makes it easier to understand.

Btw. Can you add a feature to disable the x-axis on subcharts? I did it like this: 

    def create_subchart(self, volume_enabled: bool = True, position: Literal['left', 'right', 'top', 'bottom'] = 'left',
                        width: float = 0.5, height: float = 0.5, sync: Union[bool, str] = False,
                        topbar: bool = False, searchbox: bool = False, timescale_enabled: bool = False):
        subchart = SubChart(self, volume_enabled, position, width, height, sync, topbar, searchbox,timescale_enabled)
        self._charts[subchart.id] = subchart
        return subchart

And then self.run_script(f'''
                            {self.id}.chart.applyOptions({{
                                timeScale: {{
                                    visible: {_js_bool(timescale_enabled)},
                                    timeVisible: {_js_bool(timescale_enabled)}
                                }}
                            }})''')
within the init of SubChart(LWC). I disabled it by default for me now since I don't need the x-axis for subcharts.

**Comment by louisnw01** [comment]
Hi,

This should already be possible with `subchart.time_scale(visible=False)`

**Comment by louisnw01** [comment]
The latest version of the library now has `scale_margin_top` and `scale_margin_bottom` parameters within the `price_scale` method, so you can directly change the margins from there.

As for the 'scale price chart only' option you mentioned in TradingView, I don't believe it has been implemented in Lightweight Charts.

**Comment by louisnw01** [comment]
Hey @TagHaendler,

Just to update, The 'scale price chart only' option you mentioned will be implemented in the next update.
