### ISSUE TITLE
not updating price from tick - when price scale changes[BUG] 

### ISSUE THREAD

**Issue by esteban2006** [louisnw01/lightweight-charts-python#190]
### Expected Behavior

After the last update, this account (broker : Deriv demo account) is updating well, as it was before 

![liveUpdateFromTick](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/9707b7be-91a3-4cfe-b620-ce6eca12322e)

### Current Behaviour

when changing to another Company and DEMO account (ThinkMarkets) the update from tick function will  not behave as expected please notice that the update values are the same yet, the candle bar does not update, methods are all the same as above 

1. the update reaches the function and update_from_tick in abstract.py
2. it run update under class Candlestick
3. chart will not show the update ticks 
4. chart WILL update bar minute changes 

![candleNotUpdatingFromTick](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/a84e2c50-d3ac-412a-9609-5f7919a95051)

### Reproducible Example

```python
1. the update reaches the function and update_from_tick in abstract.py
2. it run update under class Candlestick
3. chart will not show the update ticks 
4. chart WILL update bar minute changes
```

### Environment

```markdown
- OS: windows 11
- Library:
```

**Comment by louisnw01** [comment]
Hey @esteban2006,

Please provide a minimal reproducible example using `ohlcv.csv` data.

Louis

**Comment by esteban2006** [comment]
hey @louisnw01 here is a minimal 



```
import pandas as pd
from time import sleep
from lightweight_charts import Chart

if __name__ == '__main__':

    chart = Chart()

    df1 = pd.read_csv('ohlcEx.csv')
    df2 = pd.read_csv('data.csv')

    chart.set(df1)

    chart.show()

    last_close = (df1.iloc[-1])


    for i, series in df2.iterrows():
        chart.update(series)
        last_close = series['close']
        sleep(0.1)


```

[data.csv](https://github.com/louisnw01/lightweight-charts-python/files/13231471/data.csv)
[ohlcEx.csv](https://github.com/louisnw01/lightweight-charts-python/files/13231472/ohlcEx.csv)


I am also adding a quick view of my end 


![minimalRun](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/8abc14c8-facb-4c55-9c3a-f86ca6b2a3a2)


thank you,

**Comment by louisnw01** [comment]
Hey again,

It appears your tick data is timestamped 3 hours behind the initial data you set; this will most likely be the reason why it is failing.

Louis

**Comment by esteban2006** [comment]
Hello @louisnw01, thank you for coming back, I have check my implementation, and you are right the data frame initially loaded is  comming with diff time zone, 

Regards,

**Comment by esteban2006** [comment]
@louisnw01 you were right about the time dif in my df and updates, now I have to share that for developer building live tick update we need to  take into account daylight saving so the updates match the current df time as most exchanges will us Z time 

now remember the 2 digits problem?, the chart is updating the bar but the scale price is limited to 2 digits 

is there a way to set scale price float(5)

data bein passed :

```

********************************************************************************

Last Bar recorded : 2023-11-03 17:58:00
Calling method: dayLightSaving
                                0
time   2023-11-03 17:03:26.963000
price                     1.07200

```

1.07 is the only that the graph is showing 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/c4bb2a78-ec92-4177-88c6-38a3f9c7ec72)

![twoDigits](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/a09baba0-39a5-4a52-a21d-f3bd71ea0b8d)

**Comment by louisnw01** [comment]
There is, use `chart.precision`

Louis

**Comment by esteban2006** [comment]
oh thank you @louisnw01 ! 

I have this question for you have you thougt of creating a settings buttons under the ray line icon so you user can select 

- line settings 
- chart settings 
- event readjust drawing.json coordinates 
- create a file name (makers.json and  control de markers from there )

Do you think is possible ?

I have created a local file that before lauching the graph I modify, so i get the my configuration, but that would be not optimal as i need to be going outside  the chart frame to set settings and the rendered in the chart, I would suggest a settings buttons to change all these options on the fly. 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/10a68c33-573b-4bfb-9914-f3d8248fbf61)

Esteban
regards,
