### ISSUE TITLE
Positions (Trades) overlay plotting on chart

### ISSUE THREAD

**Issue by blazerr1313** [louisnw01/lightweight-charts-python#191]
### Question

Hello, iˇm very exited with your project. Big thanx. 
Iˇm hobby coder :) 

Iˇm using python for backtesting my strategys on crypto. 
How i can easily overlay plot my position entry and exit points. 
And how i can easily overlay plot on chart  special line that i use in my backtest algo,  my algo calculate  for each candle and generate  Y  axis coordinates for my line, how i can plot this line with my coordinates ? 

Big thanx )

**Comment by louisnw01** [comment]
Hey @blazerr1313,
`chart.marker` for entry exit, and either `chart.create_line` or `chart.horizontal_line` line for indicators/marking levels.

Louis
