### ISSUE TITLE
Chart from full candle data

### ISSUE THREAD

**Issue by blazerr1313** [louisnw01/lightweight-charts-python#193]
### Question

Hello!

I use for my backtest candlestick data from Binance that combined to numpy massive

My massive contain in each row more data than ochlv 

example : 

1696377600000,0.25900000,0.25900000,0.25520000,0.25610000,247323.00000000,1696378499999,63405.80237000,454,85335.50000000,21869.07337000,0

How i can ignore can ingnore columns that your script not use to draw the chart.

Thanx

**Comment by louisnw01** [comment]
Hey @blazerr1313,

convert to dataframe, and label the ones you want to use as ohlcv.

Louis
