### ISSUE TITLE
Set interval directly instead of calculating it from DataFrame

### ISSUE THREAD

**Issue by gnuhel** [louisnw01/lightweight-charts-python#195]
### Question

When changing the timeframe and there is no data or only 1 bar for this timeframe then the interval is calculated incorrectly. 
e.g. your data contains one 1min bar and you change to 5min timeframe. The interval of the 5min timeframe is still 1secs. It should be 300secs.

Can we set the interval directly?

**Comment by louisnw01** [comment]
Hey @gnuhel,

A timeframe selector is just a switcher which lets you run functions in python by pressing a button on the chart.

You will have to implement you own functionality for timeframe switching; there is a basic example of this in the examples folder.

Louis

**Comment by gnuhel** [comment]
I know I need to implement the functionality by myself, like fetching data, group them into intervals and use `chart.set(df)` to show the right candles.

Not sure if this is relevant, but if the data/candles are not enough, `chart._interval` will return a false value. e.g. on my 1H Timeframe `chart._interval` will return `1secs` which obviously is not correct. 

do you use `chart._interval` for any other calculation? if not then forget my question. I can save the value on my side.

**Comment by louisnw01** [comment]
Ah, I misunderstood. Do you have a code example showing `_interval` not changing?

Louis

**Comment by louisnw01** [comment]
To answer your question, yes; `_interval` is quite crucial for things like `update_from_tick`, raylines and trendlines.

If you are using an irregular set of data you can manually set `_interval`, just be sure to set `offset` if your data starts at an offsetted time. e.g. 5min interval which is stamped `1:01, 1:06, 1:11, 1:16` etc would have an offset of 60 seconds.
