### ISSUE TITLE
To be able to upate a row value and  set table location - MULTIPLE TABLES

### ISSUE THREAD

**Issue by esteban2006** [louisnw01/lightweight-charts-python#196]
### Description

- Description: To set up a table location will allow users to pre-determine a table position when having multiple tables like up, down, right, left
- What would it do: Will provide the ability to set individual ids for a specific table, by to doing so the table will be able to be display independantly
- Will solve: Lib is currentrly unable to display two tables at the same time in diff locations of the window

### Code example

```python
positionsTable = chart.create_table(
        width=1, 
        height=0.2,
        window_position= "left", /////////////////////////////////////////
        headings=(heads),
        widths=tuple(1 / len(heads) for _ in heads),
        alignments=tuple(aligment for _ in heads),
        position=aligment, 
        func=onRowClicked
    )
```

### Method of implementation

more than a mothod of implementation I am sharing a minimal so you can see that window loads well with one table:

![image](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/5c23f5a0-2e11-4525-ae8b-e4d882f9a8ef)

but when you uncomment the firts table the result is that the first table will display but the second will not 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/12733e25-e1c1-4a74-9517-f4be56647299)

```

import pandas as pd
from time import sleep
from lightweight_charts import Chart

def onRowClicked(row):
    pass

if __name__ == '__main__':

    openOrderData={
            "account_info": {
                "name": "Esteban" ,
                "number": 333.1,
                "currency": "USD",
                "leverage": 500,
                "free_margin": 5999.46,
                "balance": 6000.32,
                "equity": 6008.47
            },
            "orders": {
                "3526057705": {
                    "isPosition": 1,
                    "magic": 0,
                    "symbol": "Volatility 10 Index",
                    "lots": 0.50,
                    "type": "buy",
                    "open_price": 6893.55400,
                    "price_current": 6893.39100,
                    "open_time": "2023.10.15 21:51:00",
                    "SL": 0.00000,
                    "TP": 0.00000,
                    "pnl": -0.08,
                    "swap": 0.00,
                    "comment": ""
                },
                "3525783217": {
                    "isPosition": 1,
                    "magic": 452164759,
                    "symbol": "Volatility 10 Index",
                    "lots": 0.50,
                    "type": "sell",
                    "open_price": 6910.01800,
                    "price_current": 6893.55800,
                    "open_time": "2023.10.15 18:24:19",
                    "SL": 6979.28700,
                    "TP": 0.00000,
                    "pnl": 8.23,
                    "swap": 0.00,
                    "comment": ""
                }
            }
        }
    aligment = 'center'
    chartWith = 0.8
    chartHeight = 0.8

    chart = Chart(
        toolbox=True, 
        width=1200, 
        inner_width=chartWith, 
        inner_height=chartHeight
    )
    df1 = pd.read_csv('ohlcEx.csv')
    chart.set(df1)

    # positions info Table 
    heads = ["SYMBOL","ID","LOTS","TYPE","OPEN PRICE","PRICE","SL","TP","SWAP","PNL"] 
    # positionsTable = chart.create_table(
    #     width=1, 
    #     height=0.2,
    #     # window_position = "left",
    #     headings=(heads),
    #     widths=tuple(1 / len(heads) for _ in heads),
    #     alignments=tuple(aligment for _ in heads),
    #     position=aligment, 
    #     func=onRowClicked
    # )

    # for orderId, orderData in openOrderData['orders'].items():
    #     positionsTable.new_row(
    #         orderData["symbol"],
    #         orderId,
    #         orderData["lots"],
    #         orderData["type"],
    #         orderData["open_price"],
    #         orderData["price_current"],
    #         orderData["SL"],
    #         orderData["TP"],
    #         orderData["swap"],
    #         orderData["pnl"]
    #     )

    # positionsTable.footer(2)
    # positionsTable.footer[0] = 'Selected:'

    # market info table 
    headsTwo = ["SPREAD","DIGITS","SWAP","TYPE"] 
    subAccountTable = chart.create_table(
        width=0.2, 
        height=1,
        # window_position = "left",
        headings=(headsTwo),
        widths=tuple(1 / len(headsTwo) for _ in headsTwo),
        alignments=tuple(aligment for _ in headsTwo),
        position=aligment, 
        func=onRowClicked
    )

    for orderId, orderData in openOrderData['orders'].items():
        subAccountTable.new_row(
            orderData["symbol"],
            orderId,
            orderData["lots"],
            orderData["type"]
        )

    subAccountTable.footer(2)
    subAccountTable.footer[0] = 'Selected:'

    chart.show(block=True)

```

[ohlcEx.csv](https://github.com/louisnw01/lightweight-charts-python/files/13262003/ohlcEx.csv)

point two I would like to ask if you can create a method to update specific row values (PNL ) in my minimal example

**Comment by louisnw01** [comment]
Hey @esteban2006,

The position parameter sets how the table floats in the window, not it's explicit location. Tables location work similar to subcharts, and are placed left to right until there is no space.

You also need make sure you are giving the tables enough space within the window by lowering the size of other charts/windows.

Louis

**Comment by esteban2006** [comment]
@louisnw01 thank you for the hint, for some reason the first table will always float the to right right of the corner, so I just inverted the  order of the  tables when running the code and it worked 

thank you
Esteban,

![image](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/533e3558-8ff7-44c9-9837-872ff80376b1)

**Comment by esteban2006** [comment]
@louisnw01 

Is there a way to do this now ?

point two I would like to ask if you can create a method to update specific row values (PNL ) in my minimal example

if not then I would like to request a Feature

Regards,

**Comment by louisnw01** [comment]
> @louisnw01 
> 
> 
> 
> Is there a way to do this now ?
> 
> 
> 
> point two I would like to ask if you can create a method to update specific row values (PNL ) in my minimal example
> 
> 
> 
> if not then I would like to request a Feature
> 
> 
> 
> Regards,

This is possible; see the table example in the docs.

Louis

**Comment by esteban2006** [comment]
thank you @louisnw01  I have gone thru the docs, and I have been able to update values when I click on the row, but my approach is to iterate over the rows of the table and update just the value, could you give me a hint how to iterate of the rows of the given table ?

Esteban

**Comment by louisnw01** [comment]
Tables are essentially just a dictionary of dictionaries (rows), so you could use something like `for row in table.values()`

**Comment by esteban2006** [comment]
billiant, I really apprecited,

 thank you very much.
