### ISSUE TITLE
Is there a way to compile it ?

### ISSUE THREAD

**Issue by esteban2006** [louisnw01/lightweight-charts-python#197]
### Question

@louisnw01, 

Do you have a example of how to compile it with pyinstaller or any other ??

i have tried this method and I will not work, 
```

if __name__ == '__main__':
    deo=Main()
    deo.applyDecoratorToAllMethods()
    goLive = True
    autoLogin = True
    run = 0
    
    if goLive :
        
        if deo.loginW():
            if deo.softwareVersion == 333:
                threading.Thread(target=deo.start).start()
                deo.openGraph(None, None, 200)

```

then based on your suggestion 
![image](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/ca84c43f-4903-4254-ac51-9ed91a92efcd)

i tried the complete minimal in the main incapsulation, but it did not work, what happens is that the softare will open the login screen ...

```

if __name__ == '__main__':
    deo=Main()
    deo.applyDecoratorToAllMethods()
    goLive = True
    autoLogin = True
    run = 0
    
    if goLive :
        
        if deo.loginW():
            if deo.softwareVersion == 333:

                openOrderData={
                        "account_info": {
                            "name": "Esteban Gilberto Gutierrez Jandres",
                            "number": 30865238,
                            "currency": "USD",
                            "leverage": 500,
                            "free_margin": 5999.46,
                            "balance": 6000.32,
                            "equity": 6008.47
                        },
                        "orders": {
                            "3526057705": {
                                "isPosition": 1,
                                "magic": 0,
                                "symbol": "Volatility 10 Index",
                                "lots": 0.50,
                                "type": "buy",
                                "open_price": 6893.55400,
                                "price_current": 6893.39100,
                                "open_time": "2023.10.15 21:51:00",
                                "SL": 0.00000,
                                "TP": 0.00000,
                                "pnl": -0.08,
                                "swap": 0.00,
                                "comment": ""
                            },
                            "3525783217": {
                                "isPosition": 1,
                                "magic": 452164759,
                                "symbol": "Volatility 10 Index",
                                "lots": 0.50,
                                "type": "sell",
                                "open_price": 6910.01800,
                                "price_current": 6893.55800,
                                "open_time": "2023.10.15 18:24:19",
                                "SL": 6979.28700,
                                "TP": 0.00000,
                                "pnl": 8.23,
                                "swap": 0.00,
                                "comment": ""
                            }
                        }
                    }
                aligment = 'center'
                chartWith = 0.8
                chartHeight = 0.8

                chart = Chart(
                    toolbox=True, 
                    width=1200, 
                    inner_width=chartWith, 
                    inner_height=chartHeight
                )

                df1 = pd.read_csv('ohlcEx.csv')
                chart.set(df1)
                # market info table 
                headsTwo = ["SPREAD","DIGITS","SWAP","TYPE"] 
                subAccountTable = chart.create_table(
                    width=0.2, 
                    height=0.5,
                    # window_position = "left",
                    headings=(headsTwo),
                    widths=tuple(1 / len(headsTwo) for _ in headsTwo),
                    alignments=tuple(aligment for _ in headsTwo),
                    position=aligment, 
                    func=onRowClicked
                )

                for orderId, orderData in openOrderData['orders'].items():
                    subAccountTable.new_row(
                        orderData["symbol"],
                        orderId,
                        orderData["lots"],
                        orderData["type"]
                    )

                subAccountTable.footer(2)
                subAccountTable.footer[0] = 'Selected:'

                # positions info Table 
                heads = ["SYMBOL","ID","LOTS","TYPE","OPEN PRICE","PRICE","SL","TP","SWAP","PNL"] 
                positionsTable = chart.create_table(
                    width=1, 
                    height=0.2,
                    # window_position = "left",
                    headings=(heads),
                    widths=tuple(1 / len(heads) for _ in heads),
                    alignments=tuple(aligment for _ in heads),
                    position=aligment, 
                    func=onRowClicked
                )

                for orderId, orderData in openOrderData['orders'].items():
                    positionsTable.new_row(
                        orderData["symbol"],
                        orderId,
                        orderData["lots"],
                        orderData["type"],
                        orderData["open_price"],
                        orderData["price_current"],
                        orderData["SL"],
                        orderData["TP"],
                        orderData["swap"],
                        orderData["pnl"]
                    )

                positionsTable.footer(2)
                positionsTable.footer[0] = 'Selected:'

                chart.show(block=True)
                deo.deleteTracerDir()


```

### Code example

```python
N/A
```

**Comment by louisnw01** [comment]
Hey @esteban2006,

I've never tried to compile the library with lightweight-charts-python; perhaps start with one of the basic examples and provide the MRE?

Louis

**Comment by esteban2006** [comment]
@louisnw01 Ok, I will create a very small software so we can have an MRE

**Comment by cilindro5432** [comment]
I would like to compile the chart but for people with little knowledge of Python like me it is impossible. It is not easy to follow the documentation at https://lightweight-charts-python.readthedocs.io/en/latest/tutorials/getting_started.html
I've been trying to get live data for weeks, days without sleep and the most I've achieved is obtaining a static image. Now I'm trying the polygon api but I don't think I'll get far.

Louisnw01 any chance to get some help? please

**Comment by louisnw01** [comment]
> I would like to compile the chart but for people with little knowledge of Python like me it is impossible. It is not easy to follow the documentation at https://lightweight-charts-python.readthedocs.io/en/latest/tutorials/getting_started.html I've been trying to get live data for weeks, days without sleep and the most I've achieved is obtaining a static image. Now I'm trying the polygon api but I don't think I'll get far.
> 
> Louisnw01 any chance to get some help? please

In which case maybe start by following an example given by pyinstaller and get that to work first!

**Comment by cilindro5432** [comment]
I started compiling poligon and I found that I can't add forex or crypto currencies, the example says it is EUR-USD but I can't add it somehow. QUESTION
poligon is a completely different arrangement than the static examples, or if the tick data in real-time example in poligon is used.

**Comment by louisnw01** [comment]
> I started compiling poligon and I found that I can't add forex or crypto currencies, the example says it is EUR-USD but I can't add it somehow. QUESTION
> 
> poligon is a completely different arrangement than the static examples, or if the tick data in real-time example in poligon is used.

You'll need a subscription to Polygon in order to use their market data.

**Comment by cilindro5432** [comment]
I know i already have a free account with the free key i just want to setup the chart. I have stocks and index tab set,  but if i try to set forex and crypto  like example says (EUR-USD) or ('EUR-USD') or ("EUR-USD") or without () not allow me to add to the top bar. I dont know what i am doing wrong.

**Comment by louisnw01** [comment]
> I know i already have a free account with the free key i just want to setup the chart. I have stocks and index tab set, but if i try to set forex and crypto like example says (EUR-USD) or ('EUR-USD') or ("EUR-USD") or without () not allow me to add to the top bar. I dont know what i am doing wrong. chart.polygon.forex(symbol='EUR-USD', timeframe=('1min', '5min', '15min', '30min'), start_date='2022-06-09') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: PolygonAPI.forex() got an unexpected keyword argument 'symbol'

Unexpected keyword argument means that parameter does not exist within the method; if you take a look at the reference in the documentation, you can see that the arguments are named `fiat_pair` and `crypto_pair` respectively, rather than `symbol`.

Louis

**Comment by cilindro5432** [comment]
Thankyou louis that solve my problem
