### ISSUE TITLE
[BUG] Unable to Draw Trendline in SubChart

### ISSUE THREAD

**Issue by mash420** [louisnw01/lightweight-charts-python#198]
### Expected Behavior

`
if 'oi' == indicator:
    oi = await self.fetch_oi_history()

    # Select the last 100 candles
    oi_last_100 = oi.tail(100)

    # Find the index of the highest and lowest points in the last 100 candles of the oi DataFrame
    highest_index = oi_last_100['high'].idxmax()
    lowest_index = oi_last_100['low'].idxmin()

    highest_row = oi_last_100.loc[highest_index]
    lowest_row = oi_last_100.loc[lowest_index]

    # Draw the trendline
    chart2.trend_line(start_time=highest_row['time'], start_value=highest_row['high'], 
                    end_time=lowest_row['time'], end_value=lowest_row['low'],
                    color='green', width=2, style='solid', round=False)

    chart2.set(oi_last_100)
    chart2.price_scale(scale_margin_top=0.03, scale_margin_bottom=0.03)
`

### Current Behaviour

The trendline will not appear in chart2. If I change the code to chart.trend_line() the line will appear in the correct time/values.

### Reproducible Example

```python
if 'oi' == indicator:
    oi = await self.fetch_oi_history()

    # Select the last 100 candles
    oi_last_100 = oi.tail(100)

    # Find the index of the highest and lowest points in the last 100 candles of the oi DataFrame
    highest_index = oi_last_100['high'].idxmax()
    lowest_index = oi_last_100['low'].idxmin()

    highest_row = oi_last_100.loc[highest_index]
    lowest_row = oi_last_100.loc[lowest_index]

    # Draw the trendline
    chart2.trend_line(start_time=highest_row['time'], start_value=highest_row['high'], 
                    end_time=lowest_row['time'], end_value=lowest_row['low'],
                    color='green', width=2, style='solid', round=False)

    chart2.set(oi_last_100)
    chart2.price_scale(scale_margin_top=0.03, scale_margin_bottom=0.03)
```

### Environment

```markdown
- OS:Windows 11
- Library:1.0.18.5
```

**Comment by louisnw01** [comment]
Hey @mash420,

Please provide a minimal reproducible example.

Louis

**Comment by mash420** [comment]
Can close it, I just needed to set the data for drawing the trendline.
