### ISSUE TITLE
Make horizontal line dragable

### ISSUE THREAD

**Issue by esteban2006** [louisnw01/lightweight-charts-python#199]
### Description

Would like to request the ability to drag horizotal lines within the chart

this would increase the ability control order placmente such 
limit orders 
TP and SL

![dragableMarker](https://github.com/louisnw01/lightweight-charts-python/assets/11742223/47eda41f-e1aa-40bb-b90f-fcb9c6755f48)

### Code example

```python
this would be similar to trend line i tracks the drags and saves data in drawings.json
```

### Method of implementation

as trend line

**Comment by emma-uw** [comment]
`If a func is given, the horizontal line can be edited on the chart. Upon its movement a callback will also be emitted to the callable given, containing the HorizontalLine object. The toolbox should be enabled during its usage. It is designed to be used to update an order (limit, stop, etc.) directly on the chart.`

**Comment by esteban2006** [comment]
@emma-uw thank you very much.
