### ISSUE TITLE
White screen on windows

### ISSUE THREAD

**Issue by llvm-x86** [louisnw01/lightweight-charts-python#2]
```python
import pandas as pd
from lightweight_charts import Chart


if __name__ == '__main__':
    
    chart = Chart()
    
    # Columns: | time | open | high | low | close | volume (if volume is enabled) |
    df = pd.read_csv('ohlcv.csv', index_col=0).iloc[:100]
    print(df)
    chart.set(df)
    
    chart.show(block=True)
```

python version 3.9.13

after running the chart is completely blank, here's an image for reference:
![image](https://github.com/louisnw01/lightweight-charts-python/assets/113465213/434029c0-6190-43ad-a1ee-076431eb1c6d)

**Comment by anurag-py** [comment]
i have had the same issue on linux as well.

**Comment by louisnw01** [comment]
Hi!

Just to narrow down this issue could you run the following code and let me know what you see?

```python
import webview

webview.create_window('', 'https://www.google.com')
webview.start()
```
It should produce an error similar to this: 
`2023-05-16 23:56:17.961 Python[85726:12383346] PyObjC: Exception during dealloc of proxy: Completion handler passed to -[BrowserDelegate webView:didReceiveAuthenticationChallenge:completionHandler:] was not called`

It seems that the latest version of pywebview is causing some issues with the library. A quick fix is to downgrade to pywebview version 4.0.2, but I will be releasing a proper fix tommorrow.

Thank you for bringing this to my attention!

**Comment by anurag-py** [comment]
I have ran the code

`import webview

webview.create_window('', 'https://www.google.com')
webview.start()`

The output is still. Thanks for your help. Really looking forward to this package.

![image](https://github.com/louisnw01/lightweight-charts-python/assets/53002981/37f54fea-fd70-483f-86da-738f92ee4012)

**Comment by anurag-py** [comment]
Hi, 

I solved it for Manjaro linux. All you gotta do is :

`export QTWEBENGINE_DISABLE_SANDBOX=1`

now it works fine. Thanks

**Comment by louisnw01** [comment]
> Hi,
> 
> I solved it for Manjaro linux. All you gotta do is :
> 
> `export QTWEBENGINE_DISABLE_SANDBOX=1`
> 
> now it works fine. Thanks

Very strange behaviour, especially if you are only using the `Chart` object, which doesn't import anything related to Qt.

I'll have another look and see if I can stop this issue happening automatically.

@shusei-kagari, on windows the command would be:

`set QTWEBENGINE_DISABLE_SANDBOX=1`

Let me know if this fixes it, thanks @anurag-py for the solution!

**Comment by anurag-py** [comment]
@louisnw01 thanks to you for the package. Though i am still looking for solution on the other issue i opened. How to add another technical indicator pane.
