### ISSUE TITLE
Chart width depends on value length

### ISSUE THREAD

**Issue by Zartexo** [louisnw01/lightweight-charts-python#20]
Hi,

I noticed that in a chart with a synced subchart both charts can have different width if for ex. the chart has values from 1000-2000 and the subchart 1,000,000 - 2,000,000.

This code does show the problem:

```
import pandas as pd
from lightweight_charts import Chart

if __name__ == '__main__':
    chart = Chart(inner_width=1, inner_height=0.8)

    chart2 = chart.create_subchart(sync=True, position='bottom', width=1, height=0.2)
    line1 = chart2.create_line()

    chart.watermark('1')
    chart2.watermark('2')

    df = pd.read_csv('ohlcv.csv')
    df2 = df[['date']]
    df2['value'] = df['volume']
    pd.DataFrame()
    chart.set(df)

    line1.set(df2)

    chart.show(block=True)
```

or in this picture:

![Screenshot 2023-06-10 184130](https://github.com/louisnw01/lightweight-charts-python/assets/104310309/7eea94fb-af0c-4470-a4b6-e5035f69e164)

**Comment by louisnw01** [comment]
Hi,

This has been a common request for the original Lightweight Charts library; unfortunately there is not way to fix the width of the price scales, as they vary depending on the size of the prices within them.

There are a couple (albeit janky) workarounds:
* lower/raise the font size until they align `(chart.layout(font_size=x))`
* Round your prices down, or round them up

Not ideal, but let me know if this helps!

**Comment by Zartexo** [comment]
thank you for the suggestions for workarounds. Both were not suitable for me, so I adjusted the width from the subchart upon subchart creation a little to nearly fit the main charts width.
It's not ideal but with crosshair syncing (#17) this problem here becomes negligible for me.

Very happy with the latest update @louisnw01 !
