### ISSUE TITLE
Anything in the lightweight chart api that would address this histogram offset

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#200]
### Question

Say you have two histograms that rotates around 0. Any reason why the second histogram get's offset. 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/27868d87-0ad4-4eb0-b169-ef2fd48a34d8)

**Comment by louisnw01** [comment]
Hey @karunkrishna,

Are you using the `scale` method of the histogram?

Louis
