### ISSUE TITLE
date time to US Eastern Time

### ISSUE THREAD

**Issue by ahmedacoding** [louisnw01/lightweight-charts-python#201]
### Question

Hi, I get my data from eodhd API service and the time received is in UTC time as most of the API data service. when I convert the date time to  US Eastern Time to match the stock market time in the chart it doesn't work. I tried everything changing datetime column, created separate date column with EST , I even changed epoch to be in EST time nothing work, the chart insist to show it in UTC time. I am not sure what I am missing here.  Thanks

**Comment by louisnw01** [comment]
Hey @ahmedacoding,

Could you provide a csv copy of the data you are using before and after conversion.

Louis

**Comment by ahmedacoding** [comment]
Sure, attached a csv's files, "1hour_intraday_raw.csv" sample of the raw data coming from the API. 
 "1hour_intraday_dataframe.csv"  Sample after converting it to data frame using Panda.
"1hour_intraday_dataframe_EST.csv" and here is a file after changing the time zone to Eastern time EST . 
in the picture attached you can see APPL chart start on 13:30 even though "1hour_intraday_dataframe_EST.csv" file have it start on 9:30 am 

Also, in a side note in a different issue "Tick" data attached is "websocket_realtime.csv" output file for WebSocket Realtime data which if I try to apply the "Tick" data example on it after converting it to data frame it doesn't chart at all.   Thanks for taking the time to reply and checking them.
[1hour_intraday_dataframe.csv](https://github.com/louisnw01/lightweight-charts-python/files/13340961/1hour_intraday_dataframe.csv)
[1hour_intraday_dataframe_EST.csv](https://github.com/louisnw01/lightweight-charts-python/files/13340962/1hour_intraday_dataframe_EST.csv)
[1hour_intraday_raw.csv](https://github.com/louisnw01/lightweight-charts-python/files/13340963/1hour_intraday_raw.csv)
[websocket_realtime.csv](https://github.com/louisnw01/lightweight-charts-python/files/13340964/websocket_realtime.csv)


Thanks

**Comment by ahmedacoding** [comment]
forgot to attach the pictures ... 
![AAPL_7_17_time_start](https://github.com/louisnw01/lightweight-charts-python/assets/86085585/8f54c5c2-c16b-4687-bc4b-291b7680a19e)
![AAPL_7_17_time_start_EXCEL](https://github.com/louisnw01/lightweight-charts-python/assets/86085585/3e72a85f-31a2-4e0d-8b0a-1e7f6bdeef43)

**Comment by ahmedacoding** [comment]
I found the issue and fixed it in the csv file.  the 'date' column had extra digits after the seconds I guess it's for time off set after EST conversion. I removed them and the chart worked.

However the issue with plotting "Tick" data (file attached) from WebSocket Realtime is the one I couldn't fix so far.

[websocket_realtime.csv](https://github.com/louisnw01/lightweight-charts-python/files/13343602/websocket_realtime.csv)


Thanks

**Comment by louisnw01** [comment]
> I found the issue and fixed it in the csv file. the 'date' column had extra digits after the seconds I guess it's for time off set after EST conversion. I removed them and the chart worked.
> 
> However the issue with plotting "Tick" data (file attached) from WebSocket Realtime is the one I couldn't fix so far.
> 
> [websocket_realtime.csv](https://github.com/louisnw01/lightweight-charts-python/files/13343602/websocket_realtime.csv)
> 
> Thanks

Typically this issue occurs when the tick data has timestamps that are chronologically before the last data point.

Louis
