### ISSUE TITLE
Set x-axis with seconds 

### ISSUE THREAD

**Issue by Tirbo06** [louisnw01/lightweight-charts-python#202]
### Description

Hi thanks you for this lib ! 

I'd like to know if it is possible to display the x-axis (time) with the seconds ( HH:MM -> HH:MM:SS) 
I tried passing the datetime series to ```Chart(x=dtSerie)``` but i am not sure why 'x' is for. Maybe i missed something in the doc ?

**Comment by louisnw01** [comment]
Hey @Tirbo06,

You can use the `seconds_visible` parameter of `time_scale` to achieve this.

Louis
