### ISSUE TITLE
Advanced volume data

### ISSUE THREAD

**Issue by blazerr1313** [louisnw01/lightweight-charts-python#203]
### Question

Hello, and big thanx aigain for your nice work!!

Have a question, it is possible to realize?

1. I use advanced volume data (calculated in my script) , i have 3 params  taker buy vol ; sell vol ; buy sell domination in % .

It is possible to show this advanced volume data in lightweight charts in example below :

1. Volume bar total height  based on total vol buy+sell
2. Volumebar color green for buy and red for sell vol. One bar consist of  buy and sell vol together 
3. Buy vol area filled green, Sell vol area filled red 
4. If buy vol dominate,  sell vol red area overlay buy vol are with red color, and with sell dominate same buy buy vol green area overlay.

Or it poasible to modify overall vol are for example:

Vol area separated by horisontal line in middle,  buyvol bars green and above the hor. line ; sell vol bars red and below the hor. line .

Thanx so much

**Comment by louisnw01** [comment]
Hey @blazerr1313,

Unfortunately split volume bars (ie two volume bars for the same timestamp) is not possible.

A compromise could be to create multiple histograms for the chart which seperate out the buy/sell volume however.

Louis
