### ISSUE TITLE
Updating Lines and Markers in real time

### ISSUE THREAD

**Issue by blazerr1313** [louisnw01/lightweight-charts-python#206]
### Question

Hello!

It is possible  to create and update lines and markers in 
Realtime update from tick data.

Thanx!

**Comment by blazerr1313** [comment]
Genrally my idea is :

1) I have websocket stream  tick data from Binance
2) I have hiatorical ohlcv data in my DB 
3) When i run python script i want chart to be shown with histprival data and new data to be updated in live with tick data and my script calcuöates ema lines , and i want to be udated emas in live too.

Tjanx

**Comment by louisnw01** [comment]
You can update lines with their `update` method, but markers will have to be deleted and re-created.

Louis

**Comment by blazerr1313** [comment]
Thanx!

Can you show a little example of code for line update in  live data updating.

Big thanx
