### ISSUE TITLE
Change chart's percentage legend colour with each candle

### ISSUE THREAD

**Issue by litoco** [louisnw01/lightweight-charts-python#210]
### Description

I was thinking to change colour of % move for a particular candle in chart legend but I wasn't able to find out any help regarding that. Currently we can only change colour of all legends open, high, close, low and percentage. And this change can be done before starting the chart. I wanted it to change colour with the candle that the crosshair is on. But I can't do that.

Is this feature already available? If not is there any workaround?

### Code example

```
import pandas as pd
from lightweight_charts import Chart


if __name__ == '__main__':
    
    chart = Chart()

    df = pd.read_csv('ohlcv.csv')

    chart.layout(background_color='#090008', text_color='#FFFFFF', font_size=16,
                 font_family='Helvetica')

    chart.candle_style(up_color='#00ff55', down_color='#ed4807',
                       border_up_color='#FFFFFF', border_down_color='#FFFFFF',
                       wick_up_color='#FFFFFF', wick_down_color='#FFFFFF')

    chart.crosshair(mode='normal', vert_color='#FFFFFF', vert_style='dotted',
                    horz_color='#FFFFFF', horz_style='dotted')

    chart.legend(visible=True, font_size=14)

    chart.set(df)

    chart.show(block=True)

```

Now I wanted to change the colour of `percentage move` legend according to the candle that the crosshair is pointing to, but I am not able to do it currently.

**Comment by louisnw01** [comment]
The latest version contains the `color_based_on_candle` parameter, which implements this feature.

Louis
