### ISSUE TITLE
NiceGui support

### ISSUE THREAD

**Issue by xylophoneengine** [louisnw01/lightweight-charts-python#211]
### Description

Hi!

I really like your project! I wanted to use it with streamlit, however, updating the chart from python is not possible without reloading the whole component.
I read here: #49 that streamlit is not able to update JavaScript.
I am now considering [NiceGUI](https://nicegui.io/) as a possible frontend with which interacting with the JavaScript seems to be possible.

Would it be possible to add support for NiceGUI?
If help is needed I can try to help. However, I have no experience next to Python and would need your guidance.

With best regards,
Xylo

**Comment by louisnw01** [comment]
Hey @xylophoneengine,

I can't seem to find any examples of how JavaScript is handled in NiceGUI; do you have any information on this?

Louis
