### ISSUE TITLE
How do I get a title for the window in lightweight charts using python?

### ISSUE THREAD

**Issue by AltePfeife** [louisnw01/lightweight-charts-python#215]
### Question

I have the following python code that gives me the following window:

![goog](https://github.com/louisnw01/lightweight-charts-python/assets/72685817/2393a705-8f35-4c42-8889-43b0fcc37970)

But unfortunately the chart doesn't have a title, which I absolutely need for pyautogui. Is there an easy way to give the lightweight chart a title (as in the following image WINDOWS 1 inserted using Photoshop)?

![window1](https://github.com/louisnw01/lightweight-charts-python/assets/72685817/55439f30-d755-4703-b7da-75d4614c6c11)

### Code example

```python
import pandas as pd
from lightweight_charts import Chart

SYMBOL = 'GOOGL'

def get_bar_data(symbol, timeframe):
    if symbol not in ('AAPL', 'GOOGL', 'TSLA'):
        print(f'No data for "{symbol}"')
        return pd.DataFrame()
    return pd.read_csv(f'parttime_larry/lightweight-chart/bar_data/{symbol}_{timeframe}.csv')

if __name__ == '__main__':
    chart = Chart(toolbox=True)
    chart.legend(True)   

    chart.topbar.textbox('symbol', SYMBOL)   
    df = get_bar_data(SYMBOL, '5min')
    chart.set(df)   

    chart.show(block=True)
```

**Comment by anilwarbhe** [comment]
You can do it by instantiating a Chart as follows: 

`chart = Chart(title='Your Window Title', toolbox=True)`

**Comment by AltePfeife** [comment]
unfortunately I get the following error: TypeError: Chart.__init__() got an unexpected keyword argument 'title'

**Comment by anilwarbhe** [comment]
Which version you are using? You need to install the latest version of the package:
pip install lightweight-charts==1.0.18.6

**Comment by AltePfeife** [comment]
You are my hero. With version 1.0.18.6 it works. Thanks
