### ISSUE TITLE
[BUG] Cannot turn off legend for lines

### ISSUE THREAD

**Issue by krazatchu** [louisnw01/lightweight-charts-python#216]
### Expected Behavior

Turning off lines in the legend call should maintain after a window resize.

### Current Behaviour

I'm using both pyside6 and the native chart.
And I'm trying to figure out what's causing some chart flicker on pyside6 while using update_from_tick.

I turned off the legend lines - then resized the window and it comes back.
Then I set visible to False and the lines legend returns after a window resize.

Both pyside6 and native have this behavior.

### Reproducible Example

```python
import pandas as pd
from lightweight_charts import Chart

def calculate_sma(df, period: int = 50):
    return pd.DataFrame({
        'time': df['date'],
        f'SMA {period}': df['close'].rolling(window=period).mean()
    }).dropna()


if __name__ == '__main__':
    chart = Chart()
    chart.legend(visible=True)

    # df = pd.read_csv('ohlcv.csv')
    df = pd.read_csv('lw_charts_data/ohlc.csv')
    chart.set(df)

    line = chart.create_line('SMA 50')
    # line = chart.create_line('SMA 50', price_line=False, price_label=False) # same behavior

    sma_data = calculate_sma(df, period=50)
    line.set(sma_data)

    chart.legend(visible=False)   # turns off everything - comes back on resize
    # chart.legend(visible=True, lines=False)     # doesn't turn off legend for lines

    chart.show(block=True)


-- resize window with mouse --
```

### Environment

```markdown
- OS: win 11
- Library: 1.0.18.5
```

**Comment by louisnw01** [comment]
Hey @krazatchu,

This is a bug and it will be fixed in the next version.

Louis

**Comment by louisnw01** [comment]
Fixed in the latest version.

Louis
