### ISSUE TITLE
[BUG] chart don t update

### ISSUE THREAD

**Issue by brusand** [louisnw01/lightweight-charts-python#217]
### Expected Behavior

here is a sample that don t update the ui . i get all candlesticks . and want to display last candle twice (to illustrate my issue)
    def update_historical_candles(self, df):
        self.df = df
        self.dfTest = pd.DataFrame(columns = ['timestamp','open', 'high','low','close','volume', 'date'])
        self.dfTest.set_index(self.dfTest['timestamp'])
        #self.chart.set(self.dfTest)
        for i, candle in self.df.iterrows():
            print(i, candle)
            self.dfTest = self.dfTest._append(candle, ignore_index=True)
        self.chart.set(self.dfTest)
        candle = self.dfTest.iloc[-1]
        self.dfTest = self.dfTest._append(candle, ignore_index=True)
        self.chart.update(self.dfTest)

the last chart.update don t display last candle twice.

### Current Behaviour

  File "/Users/bruno/lightweight-charts-python/tdvapp.py", line 198, in update_candle_chart
    self.chart.update(self.df)
  File "/Users/bruno/lightweight-charts-python/lightweight_charts/js.py", line 142, in update
    series = self._series_datetime_format(series) if not from_tick else series
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bruno/lightweight-charts-python/lightweight_charts/js.py", line 92, in _series_datetime_format
    series['time'] = self._datetime_format(series['time'])

display only candles of the.chart.set(df)

dont display same last candle on set.chart.update(df)

### Reproducible Example

```python
def update_historical_candles(self, df):
        self.df = df
        self.dfTest = pd.DataFrame(columns = ['timestamp','open', 'high','low','close','volume', 'date'])
        self.dfTest.set_index(self.dfTest['timestamp'])
        #self.chart.set(self.dfTest)
        for i, candle in self.df.iterrows():
            print(i, candle)
            self.dfTest = self.dfTest._append(candle, ignore_index=True)
        self.chart.set(self.dfTest)
        candle = self.dfTest.iloc[-1]
        self.dfTest = self.dfTest._append(candle, ignore_index=True)
        self.chart.update(self.dfTest)
```

### Environment

```markdown
- OS: mac
- Library:
. pyside6
. last version of lightweight_charts
```

**Comment by louisnw01** [comment]
Hey,
The update function take a series, not a dataframe.

Louis

**Comment by brusand** [comment]
so how to update the new closed candle ? chart.set() ?

**Comment by brusand** [comment]
this line is very strange    File "/Users/bruno/lightweight-charts-python/tdvapp.py", line 211, in _datetime_format
    string = self.interval.total_seconds() * (string // self.interval.total_seconds())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'total_seconds'

**Comment by brusand** [comment]
all works fine, the date col must be the frist col now i update in realtime with websocket api (now i ll link with dask ...)
