### ISSUE TITLE
Save canvas.

### ISSUE THREAD

**Issue by AbdurrahimBalta** [louisnw01/lightweight-charts-python#219]
### Description

I want to save the canvas to pass the charts through a model. So in order to do image processing, I have to save the canvas. How do I do this?

**Comment by louisnw01** [comment]
Hey @AbdurrahimBalta,

Use the `screenshot` method (RTD).

Louis

**Comment by AbdurrahimBalta** [comment]
I don't know how I missed it. I'm sorry. I have another question, how can I draw a box at any point I want on the canvas created in this Chart() object?
