### ISSUE TITLE
Add arrays to chart along with magnet

### ISSUE THREAD

**Issue by litoco** [louisnw01/lightweight-charts-python#221]
### Question

I wanted to add an array to mark the exact high and lows of the candles like tradingview. With magnet feature of tradingview we can hover with the crosshair and the magnet feature pulls the pointer of the crosshair to the exact low or the high of any candle?
Can it be implemented, with the latest version of this library?

Following is the tradingview implementation of what I was trying achieve:

![Tradingview example](https://d2luddxp0py34j.cloudfront.net/m74fam%2Fpreview%2F54787648%2Fmain_full.gif?response-content-disposition=inline%3Bfilename%3D%22main_full.gif%22%3B&response-content-type=image%2Fgif&Expires=1702042413&Signature=ZMyU3QXSuyOdN99-6eSpByp~NS-4A5463DxE6yrOgNO68VQncszDBv3MX86GO2M4H7r7DWXYUgR-BwwmlPtRG~YlJ6eSi450Wf-5PDkzg9pvDwe49DM-GIeqrthENBbt1T3FqyvSDjo89jF354dknUcLyFmQqZcAbxCzLYGa~15nWocHP2Ea5u~GCCCvAa8MKrepHvwFuZnwMs0yNucI-4lPiG1P3Df~d9zAm~KZab3EMdfp281Ti4P9ErRdM8E80ka3lSbU4aArOs~3uOK56c1~iYWZ~iHTsWzqdSp~X-N16~8F-Cl~lfZipJbqPPEwF63ighG3NvEGfCMv~8ssDA__&Key-Pair-Id=APKAJT5WQLLEOADKLHBQ)

**Comment by louisnw01** [comment]
Hey @litoco,

Magnet drawing is not a currently planned feature; if you need to draw lines which are exactly in line with a candle then its best to draw them programatically using `trend_line` or `ray_line`.

Louis
