### ISSUE TITLE
Input field

### ISSUE THREAD

**Issue by neodino** [louisnw01/lightweight-charts-python#224]
### Question

Hello, Is there any suggestion on how to enable input fields?
Trying to figure out how to enable textbox value to be entered on frontend. Maybe another parameter to enable editing?
 Thanks!

### Code example

```python
chart.topbar.textbox('symbol', '7181.T',align='right',edit=True)
```

**Comment by neodino** [comment]
Actually having the tables cells to be editable with be more useful. Any pointer how to do this. Thanks

**Comment by louisnw01** [comment]
Hey @neodino,

At the moment neither input fields or editable cells are available, however I will look to implement both in a future update.

I'm assuming you would expect changing the values of a cell to also update the python data; would it also be beneficial to have an event that fires anytime a cell is changed?

Louis

**Comment by neodino** [comment]
Right. Cell events will be great. My intention is to use this as a form. My target is to build something that will have a function of order entry . Similarly to what below offers
![image](https://github.com/louisnw01/lightweight-charts-python/assets/28005257/5d414bf1-842f-4499-93c3-8ad448da50bf)

**Comment by Iss-in** [comment]
yes, i would really like it textboxes can be editable , will be really useful in loading option strike price csv , since date and strike price will also be a parameter in csv name.
as of now we have to enter the entire name at once

**Comment by sefgit** [comment]
You might want to try this pull request [Text edit support #374](https://github.com/louisnw01/lightweight-charts-python/pull/374)

**Comment by louisnw01** [comment]
Implemented in latest version.

Louis
