### ISSUE TITLE
New WebView windows with custom url

### ISSUE THREAD

**Issue by neodino** [louisnw01/lightweight-charts-python#229]
### Question

Is there a way to create another window and load custom url. The idea is to load Tradingview on the custom window and make sure that my charts are accurate....
I found and tested https://gist.githubusercontent.com/trumad/75a4013ace429c3854e967d6bbe1c6fc/raw/4fc80cdab0ef6ff7aaf11b2bf2f416e548f45097/tradingViewMultipleWindows.py and it seems to work ok, but could not figure out how to "webview.create_window" .
Any guidance will be helpful. 
Thanks!

**Comment by louisnw01** [comment]
Hey @neodino,

You can display any webpage using pywebview: 

```python
import webview

window = webview.create_window('tradingview', 'https://tradingview.com')
webview.start()
```
