### ISSUE TITLE
Any interest in custom development

### ISSUE THREAD

**Issue by blueoceancruiser** [louisnw01/lightweight-charts-python#23]
@louisnw01 This is a wonderful package and I applaud your work!  Would you be interested in building a more expansive version that adds broker trading (via Alpaca)? I'm wanting something for my personal trading and can provide some financial support.

**Comment by louisnw01** [comment]
Hi!

This library actually came from a personal development of my own trading software based around the IB API; so I would be interested!

Shoot me a message on Reddit (u/SuppressiveOG) and we'll go from there. 

Thanks,
Louis

**Comment by louisnw01** [comment]
Hey @blueoceancruiser,

Just wanted to check if you were still interested in a custom development?

Thanks,
Louis
