### ISSUE TITLE
why I receive the follwing error whenever I use a 10 minute timeframe? 

### ISSUE THREAD

**Issue by anilwarbhe** [louisnw01/lightweight-charts-python#231]
### Question

I am using various timeframes to display the chart candle and it is working perfectly fine. But whenever I switch to 10 minute timeframe I receive the following error.(It happens only when I switch to 10 minute timeframe)

I have also noticed that it happens only when the stock trading(Indian national stock exchange) timing is from 9.15 IST. and not with (MCX exchange) which starts at 9 am IST.

Traceback (most recent call last):
  File "/home/anil/pyprojects/trado/venv/lib/python3.11/site-packages/webview/platforms/gtk.py", line 473, in _callback
    value = webview.run_javascript_finish(task)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: WebKitJavascriptError: about:blank:12:146829: Error: Cannot update oldest data, last time=[object Object], new time=[object Object] (699)

**Comment by louisnw01** [comment]
Hey @anilwarbhe,

This error means that you are trying to set new data (with `set`/`update`/`update_from_tick`) that occurs chronologically before the timestamp of the last candle shown on the chart.

Louis

**Comment by anilwarbhe** [comment]
Yes, that is true. But I have checked all the things including timing during debugging. the same code works for all the timeframe but only does not for 10 minutes. I think there is a bug somewhere. I have debugged it and the markers timing are in chronological order.

**Comment by louisnw01** [comment]
Hey,

I would need an ohlcv.csv and a ticks.csv which produce the same error to help you debug.

Louis
