### ISSUE TITLE
[BUG]  .veritical_span(...) should have a round parameter similar to .trend_line(...)

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#234]
### Expected Behavior

Most of the parameters between .trend_line and .vertical_span are the same

I think taking the logic that is applied to trend_line (paramter=round) and applying it to vertical span will get the desired result
Would make for a smoother user experience. 

### Current Behaviour

The veridical span does not draw  if the start_time and end_time falls between a bar 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/e565fbf0-08c1-4ab1-9f1d-d99f999e7bed)

### Reproducible Example

```python
N/A
```

### Environment

```markdown
- OS: Win10
- Library:Latest 1.0.18.9
```

**Comment by karunkrishna** [comment]
Sorry meant to mark it as a feature request....

**Comment by louisnw01** [comment]
Added in the latest version.

Louis
