### ISSUE TITLE
Run application on web server( start inbuilt http server)

### ISSUE THREAD

**Issue by neodino** [louisnw01/lightweight-charts-python#235]
### Description

Was trying to figure out if you can run  it web server? Seems there is a inbuilt `bottle` server we can use.There is a parameters you can set i.e 

`webview.start(debug=debug,http_server=True,http_port=8888)`

Any idea how to go about it?

**Comment by arotabi** [comment]
Hey did you every figure out if this is possible?
It'd be quite a nice option.

**Comment by neodino** [comment]
Not really. Not yet. I could get it to listen by  but cannot figure out the routing. Was going by this example working https://github.com/r0x0r/pywebview/issues/1264

**Comment by MateKristof** [comment]
[https://pywebview.flowrl.com/guide/usage.html#http-server](url)
I tried this, but it always throws error 500. "Internal server error" 
Is it possible that this is a bug in the bottle ?

**Comment by louisnw01** [comment]
Hey @neodino,

I took a look into this and it seems that pywebview cannot virtually create a http server without an `index.html`, which would pose a lot of challenges due to the way I have built this library, so i'm marking this as not planned for now.

Louis
