### ISSUE TITLE
Implementation of arrow and dot-like plots

### ISSUE THREAD

**Issue by artaasd95** [louisnw01/lightweight-charts-python#239]
### Description

Hi, Thanks for this useful library!
I wanted to add Fractals indicator and I understand that this is not possible.
I mean plotting dots, triangles and small arrows like the Parabolic SAR and Fractals indicator is not possible.
So if it is possible please explain how, or if it is not possible, I request adding it.
This library is very useful for me and right now I really need this feature.
Thanks in advance!
Arta

**Comment by artadp** [comment]
I just do it using marker but I believe it does need some special implementation for this purppose.

**Comment by cilindro5432** [comment]
are some libraries that you can add any indicator

**Comment by artadp** [comment]
what?
I do not having problem with indicators calculation, the problem is for plotting indicators like dots(parabolic SAR) and spark icons like fractals!!!!

**Comment by cilindro5432** [comment]
well shapes are necesary i only need a rectangule and i am happy i dont need indicators for trade.

**Comment by louisnw01** [comment]
Hey @artaasd95,

You can plot arrows and dots using the `marker` method.

Louis
