### ISSUE TITLE
Legend function for lines

### ISSUE THREAD

**Issue by Zartexo** [louisnw01/lightweight-charts-python#24]
Is it possible to add legends for lines? Would be nice to see both the main charts values and the lines values in the legend at the same time.

**Comment by louisnw01** [comment]
Yea I want to implement this but I could do with some advice on the best way to implement this; should there be a `name` parameter when creating a line to identify it? Or just use 'Line 1', 'Line 2' etc.

**Comment by louisnw01** [comment]
Hi,

This has been implemented in the latest version (1.0.13).

Check [here](https://lightweight-charts-python.readthedocs.io/en/latest/docs.html#id1) for an example of usage.

Thanks!
Louis
