### ISSUE TITLE
Subchart sync - Align the right axis/labels of the main chart and the indicators to the maximum axis/labels width value among them

### ISSUE THREAD

**Issue by neodawn** [louisnw01/lightweight-charts-python#240]
### Description

This issue is related to [issue 147](https://github.com/louisnw01/lightweight-charts-python/issues/147). The most common use case is that the indicators are mostly used with the same time frame as the main candlestick chart. The major reason for the deviation under this scenario is that the right axis and labels are of different length and that causes the misalignment.

I have created this new issue (https://github.com/louisnw01/lightweight-charts-python/issues/147#issuecomment-1868062497) to explore an interim solution for this particular use case to set the right axis and labels of the main chart and the indicators with the maximum axis/label width of the main chart and the indicators.

**Comment by P-Lamont** [comment]
If you  don't care much about the beginning of the chart, you could cut it off after calculating the indicators so that they are of the same length. Then render both.

**Comment by konstantinosftw** [comment]
Hello @louisnw01, I am struggling with a similar issue. I tried the trick and kept same indexes for both chart and indicator, both dataframes start and end on the same dates, but the chart and the subchart are still offset. Using `timescale(right_offset=70)` did not seem to have any effect. Any ideas?

![image](https://github.com/louisnw01/lightweight-charts-python/assets/23435302/bbe74990-b7c0-4790-921c-5d208f271648)
