### ISSUE TITLE
Nice GUI support

### ISSUE THREAD

**Issue by matthewjarman** [louisnw01/lightweight-charts-python#241]
### Description

Hi Louis,

I saw request #211 and wondered if the following link is what you were looking for before the issue was closed:
https://nicegui.io/documentation/run_javascript#run_javascript

If this info makes it possible to support NiceGUI, that would be very cool!

Cheers!
Matt

**Comment by louisnw01** [comment]
Hey @matthewjarman,

I took a look into this and it seems Nice GUI does allow you to modify and access the DOM with `ui.run_javascript`, but as I am not familiar with the library and it uses its own framework I wont be implementing this. Feel free to contribute!

Louis
