### ISSUE TITLE
Adding pointer anywhere on the chart

### ISSUE THREAD

**Issue by artadp** [louisnw01/lightweight-charts-python#243]
### Description

Consider I want to put a pointer to show entering, exiting a trade or just drawing a very little line for multiple Take profit, Stop loss entry and exit prices. There is not any pointer or marker that can be put on a positions different from the candles(for example multiple pips above or below a candle).
I request to add a feature for this purpose.
thanks in advance

**Comment by louisnw01** [comment]
Hey @artadp,

You can draw a line between two points using the `trend_line` method.

Louis
