### ISSUE TITLE
Problem with chart.show()

### ISSUE THREAD

**Issue by matthewjarman** [louisnw01/lightweight-charts-python#247]
### Question

Hi Louis,

Really appreciate the work you're putting into this library!  It's really great!

I am getting the below error (pycharm debugger output) when my code gets to chart.show().  Code works perfectly up to that point:

***
Process Process-1:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/lightweight_charts/chart.py", line 34, in __init__
    webview.start(debug=debug)
  File "/opt/anaconda3/lib/python3.9/site-packages/webview/__init__.py", line 155, in start
    guilib = initialize(gui)
  File "/opt/anaconda3/lib/python3.9/site-packages/webview/guilib.py", line 97, in initialize
    if not try_import(guis):
  File "/opt/anaconda3/lib/python3.9/site-packages/webview/guilib.py", line 71, in try_import
    if import_func():
  File "/opt/anaconda3/lib/python3.9/site-packages/webview/guilib.py", line 48, in import_cocoa
    import webview.platforms.cocoa as guilib
  File "/opt/anaconda3/lib/python3.9/site-packages/webview/platforms/cocoa.py", line 12, in <module>
    import WebKit
  File "/opt/anaconda3/lib/python3.9/site-packages/WebKit/__init__.py", line 39, in <module>
    globals().pop("_setup")()
  File "/opt/anaconda3/lib/python3.9/site-packages/WebKit/__init__.py", line 14, in _setup
    from . import _metadata, _WebKit
RuntimeError: Wrong struct-size of PyObjC C API (got 288, expected 296)
***

I am struggling to find any documentation for this particular error.

For context, I started today on lightweight-charts-python 1.0.16, did a pip upgrade to 1.0.18.9, but didn't like some new/weird behavior with the cursor and legend interaction across multiple subcharts.  So I did "pip install 'lightweight-charts==1.0.16' --force-reinstall" to go back to the previous version.  In the process of doing this the pywebview version stayed the same (v4.4.1), but the pyobjc-core, pyobjc-framework-Cocoa, pyobjc-framework-WebKit, pyobjc-framework-security went from v9.2 to v10.1.  Only other changes from my own troubleshooting efforts are numpy from 1.21.5 to 1.26.3 to 1.26.2; and pandas from 1.4.2 to 2.1.4.  Tried running other workflows using numpy and pandas and there are no issues.

Any ideas on what to look at or try next?

Really appreciate any insight you can provide,
Matt

**Comment by louisnw01** [comment]
Hey @matthewjarman,

Have you tried reinstalling pywebview/python alltogether?

Louis

**Comment by matthewjarman** [comment]
Hi Louis,

Appreciate the help!

I re-installed the current anaconda distribution.  It looks like I now have pywebview versions 9 & 10 installed side-by-side when I look at directory in Finder.  I still get the same error as above.

Both Anaconda Navigator and PyCharm say I'm using version 9, but I cannot figure out a way to confirm that with something like  print(pd.__version__) - how I check which version of pandas is running at run-time when needed.  webview does not have a __version__ attribute or similar that I can use.

Digging into the python environment config is not something I'm familiar with (beyond using Navigator which does not see v10 of pywebview), so I'm a little stuck until I can find some documentation on how to do this properly and what to look for.

For fun I tried running the following from https://github.com/r0x0r/pywebview ...
import webview
webview.create_window('Hello world', 'https://pywebview.flowrl.com/hello')
webview.start()

... and also got the exact same error as above.

Unless you have a better idea, I might just try "pip install --upgrade lightweight-charts" again to see if I can get it working again.  If successful, I can create a new issue if the odd subchart behavior I noticed with the prior upgrade persists.

Appreciate the help!
Matt

**Comment by louisnw01** [comment]
Having 2 versions in your venv would make sense; `RuntimeError: Wrong struct-size of PyObjC C` suggests that part of the backend C code is accessing an older/newer version of a struct which has different fields between versions.

If a reinstall of `pyobjc` doesnt work, it might be worth clearing your venv and making a new one.

Louis
