### ISSUE TITLE
Are these features exists: Area, vline, go-to, style specific candle.

### ISSUE THREAD

**Issue by yakir4123** [louisnw01/lightweight-charts-python#248]
### Question

After try to implement similar thing with plotly or altair for personal use I found this package and I love the speed of it but ihave few questions that couldn't find in the docs:

1. Can I plot an area between 2 lines?
2. Can I plot a vertical line between prices at a specific date?
3. Can I style candles at specific dates? (such as big volume or to note something happened in here( have enough markers already)
4. Goto data, lets say i have a chart of 30min for 2 years. how can i move easily between dates?(can i integrate a dynamic buttons for such functionality (for example where my trades were made?)

Ty very much!

**Comment by louisnw01** [comment]
Hey @yakir4123,

1. Not possible at the moment.
2. Yes, use the `vertical_line` method.
3. Yes, you can add a `color` column to your dataset before calling `set`.
4. You can use the `set_visible_range` method to do this, and the topbar.

Louis

**Comment by yakir4123** [comment]
hey @louisnw01 Thank you for the response.

2. Couldn't find this function in the docs or in the repo itself :(
3. I will try that, but again this isn't documented, with all the respect I believe it can be very helpfull.
4. Thank you that seems will do the trick!

**Comment by Fougl** [comment]
I tried using chart.vertical_line
but doesnt exist @louisnw01

**Comment by louisnw01** [comment]
> I tried using chart.vertical_line but doesnt exist @louisnw01

~`vertical_line`~ `vertical_span`

**Comment by Fougl** [comment]
yeah, i posted a question regarding vertical_span, is it possible to remove it once declared? @louisnw01

**Comment by Fougl** [comment]
@louisnw01 any chanec i get a quick answer? its kind of urgent. i need those lines or anyything that gives me bands all over the historic data, or live data, but i need to be able to delete it or remove it or reset it as well. otherwise it polutes my charts even when i want see only a part of the historic data
