### ISSUE TITLE
Reading ohlc from MySql - can't get date format right  

### ISSUE THREAD

**Issue by errorreplicator** [louisnw01/lightweight-charts-python#249]
### Question

Guys,
I'm reading my ohlc data from MySql . After I read the table say 15m candle I'm loading it to Pandas resulting in following  DataFrame:

opendatetime     open     high      low    close    volume
0 2023-12-31 23:45:00  42539.8  42539.9  42096.0  42300.7  2856.220
1 2023-12-31 23:30:00  42616.5  42638.0  42536.1  42539.8   220.034
2 2023-12-31 23:15:00  42559.5  42616.6  42449.9  42616.5   465.445
3 2023-12-31 23:00:00  42561.1  42622.3  42517.7  42559.5   680.991
4 2023-12-31 22:45:00  42641.5  42641.5  42561.0  42561.1   266.373

dtypes ->
opendatetime    datetime64[ns]
open                   float64
high                   float64
low                    float64
close                  float64
volume                 float64

when trying to plot simple chart 
chart = Chart()
chart.set(ohlc)
chart.show(block=True)
I'm getting error:
"Object of type Timestamp is not JSON serializable"
So I try to apply every solution I could find to overcome this e.g.:

ohlc['opendatetime'] = ohlc['opendatetime'].astype(str)
ohlc['opendatetime'] = ohlc['opendatetime'].dt.strftime('%Y-%m-%d %H:%M:%S') 
ohlc['opendatetime'] = ohlc['opendatetime'].apply(lambda x: pd.Timestamp.isoformat(x.tz_localize('UTC')))
ohlc['opendatetime'] = ohlc['opendatetime'].dt.strftime('%Y-%m-%dT%H:%M:%S.%fZ')
ohlc['opendatetime'] = ohlc['opendatetime'].apply(lambda x: pd.Timestamp.isoformat(x.tz_localize('CET')))

which after any of the above code applied, Dataframe ohlc dtype looks exactly the same as the basic sample  
    df = pd.read_csv('ohlcv.csv')
    chart.set(df)
    chart.show(block=True)
in both cases my ohlc and df ftypes:
opendatetime     object
open            float64
high            float64
low             float64
close           float64
volume          float64

... BUT none of this works for ohlc DataFrame as I'm keep getting chart with only one candle (or rather overlapping candle in one position time 00:00).
Please see attachment. 
![ohlc](https://github.com/louisnw01/lightweight-charts-python/assets/20097737/bb78ad60-23c7-472e-be11-14da7431de4a)
(df from read_csv basic sample csv provided works just fine)
So obviously I'm doing something incorrect and it must be silly easy to fix but I just can't get it after (sad to admit) whole evening scratching my head on this. 
Can someone point me into the right direction ? 
Thanks in advance
E

**Comment by CodexLink** [comment]
Hi @errorreplicator .

You gotta make sure that your `opendatetime` column must be renamed to `date` in your pandas DataFrame, as we don't have the functionality to adapt on the column names that we gave to the library.

See reference: https://lightweight-charts-python.readthedocs.io/en/latest/tutorials/getting_started.html.

**Comment by errorreplicator** [comment]
Thanks @CodexLink .
I've renamed the column but I was still getting incorrect chart. While focusing on date format I overlooked the obvious thing, which is my dataframe 'date' was in incorrect (descending) order. 
So 
ohlc = ohlc.reindex(index=ohlc.index[::-1])
did the trick.
Thanks again.
E
