### ISSUE TITLE
Show chart maximized

### ISSUE THREAD

**Issue by Zartexo** [louisnw01/lightweight-charts-python#25]
Hi,

i suggest to add an argument to the `show()` function which will display the chart window maximized.

**Comment by louisnw01** [comment]
Hi, just to clarify you mean maximised but not full screen? 

Thanks!

**Comment by Zartexo** [comment]
Yes, maximized but window mode.

**Comment by louisnw01** [comment]
Hi,

The `maximize` parameter has been added to the `Chart` object in the latest version (1.0.13)

Thanks!
Louis
