### ISSUE TITLE
[BUG]  Not able to run Chart twice

### ISSUE THREAD

**Issue by jmauler** [louisnw01/lightweight-charts-python#250]
### Expected Behavior

I expected to be able to instance several times Chart(), as I have a tree window where I select the file I want to see. 

### Current Behaviour

First time it shows ok, but second time it crashes in a infinite loop. That happened both in PyCharm env and also in notebook(conda). I tried using exit() to kill instance, hide(), using a global variable to store chart, so I don´t have to instance anymore, but nothing worked. Maybe I´m not using something as I should.

### Reproducible Example

```python
from lightweight_charts import Chart

def calculate_player(df,aTitle):
    return pd.DataFrame({
        'time': df.index,
        aTitle: df['close']
    }).dropna()


def plot_chart_new(aData, aPlayers,aTitle):

    if __name__ == '__main__':

        chart = Chart(inner_width=1, inner_height=0.8, title=aTitle)

            # Columns: | time | open | high | low | close | volume |
        chart2 = chart.create_subchart(width=1, height=0.2, sync=True)
        chart2.legend(True)
        chart.set(aData["price"])
        pPlayer= {}
        for n in aPlayers:
            line = chart2.create_line(f'{n}')
            pPlayer[n] = calculate_player(aData[n],n)
            line.set(pPlayer[n])
        chart.show(block=True)
        chart.exit()

## CODE that  calls plot_chart_new based on other data selected in a tree window....
```

### Environment

```markdown
- OS: Windows 11
- Library:v1.0.18.8
```

**Comment by louisnw01** [comment]
Hey @jmauler,

So you want to be able to make a new instance of a chart after manually closing it? If so, then not calling `chart.exit` should work as the class internally calls that method upon exit.

Louis

**Comment by jmauler** [comment]
Thanks, it´s working now.
