### ISSUE TITLE
[BUG] Chart - Subchart layout issue

### ISSUE THREAD

**Issue by traderjoe1968** [louisnw01/lightweight-charts-python#253]
### Expected Behavior

Layout out main Chart with position= 'Right' OR any of ['Left', 'Right', 'Top', 'Bottom']. 

eg. mchart  = Chart(position='Right', width=self.width , height=self.height, inner_width=0.50, inner_height=1.0)

### Current Behaviour

Main chart default to position='Left' as AbstractChart has position: FLOAT = 'left' and this value CANNOT be overridden from class Chart

Chart __init__() method does not support position='' argument. 

### Reproducible Example

```python
from lightweight_charts import Chart

mchart  = Chart(width=self.width , height=self.height, inner_width=0.50, inner_height=1.0)
schart2 = mchart.create_subchart(position='left', width=0.50, height=0.5, sync=False)
schart3 = mchart.create_subchart(position='left', width=0.50, height=0.5, sync=False)

chart.show()
```

### Environment

```markdown
- OS:macOS 14.2.1
- Library: 2.1.0
```

fix: [#251](https://github.com/louisnw01/lightweight-charts-python/pull/251)

**Comment by cilindro5432** [comment]
post a picture

**Comment by traderjoe1968** [comment]
Before Fix
![2024-01-09_19-27-28](https://github.com/louisnw01/lightweight-charts-python/assets/56706564/88d94fd8-fd04-4e2e-a544-14237893c478)

**Comment by traderjoe1968** [comment]
After Fix 
![2024-01-09_19-28-01](https://github.com/louisnw01/lightweight-charts-python/assets/56706564/c2f9175d-607e-4f0b-9797-e6e471c39a16)

**Comment by traderjoe1968** [comment]
And
```python
mchart  = Chart(position='right', width=self.width , height=self.height, inner_width=0.50, inner_height=1.0)
schart2 = mchart.create_subchart(position='left', width=0.50, height=0.5, sync=False)
schart3 = mchart.create_subchart(position='left', width=0.50, height=0.5, sync=False)
```

![2024-01-09_19-39-19](https://github.com/louisnw01/lightweight-charts-python/assets/56706564/958b7fb6-21f3-4738-a169-3c345adb57eb)

**Comment by louisnw01** [comment]
Merged into main.
Louis
