### ISSUE TITLE
Chart appears, but no candles.

### ISSUE THREAD

**Issue by konstantinosftw** [louisnw01/lightweight-charts-python#254]
### Question

Hello and happy new year!

I am trying to replicate the first example of the `README` file with my own dataframe. My df is formatted exactly as the `ohlcv.csv`, but while I am seeing correct prices, correct dates and crosshairs, no candles are drawn. Yet it works fine with the provided `ohlcv.csv` on my machine.

Here is a visual guide to what I am seeing. The only thing I am changing to the boilerplate code is reading `ohlcv2.csv` instead of `ohlcv.csv`.

My df:
![image](https://github.com/louisnw01/lightweight-charts-python/assets/23435302/78318e1e-bc20-49e4-8121-545dc206eabe)

The chart with debugging enabled:
![image](https://github.com/louisnw01/lightweight-charts-python/assets/23435302/502100d4-c39c-47d2-9519-330303b3f3cb)

I am getting the same behaviour running the code both from jupyter and .py.

Thank you for your time :)

**Comment by konstantinosftw** [comment]
Thank you for the reply.
Unfortunately, still no candles. Even if I remove the `Unnamed` column you see there.

![image](https://github.com/louisnw01/lightweight-charts-python/assets/23435302/259fe25d-003c-4216-8773-6f20daeb4e69)

The df column `types` are also the exact same as the original `ohlcv.csv`. Quite a riddle.

**Comment by arotabi** [comment]
Have you tried it without the unnamed column, or moving unnamed to after volume?
I'm quite sure if it uses fixed column positions for ohlcv data.
My dataframes have ts_index,o,h,l,c,v followed by a whole host of indicator columns and it plots fine.

**Comment by louisnw01** [comment]
Hey @konstantinosftw,

Your data is in reverse (needs to be chronological).

Louis

**Comment by konstantinosftw** [comment]
@arotabi @louisnw01 Thank you both, it was a sorting problem indeed. I concatenated the two requests of the ohlcv data inversely.

`pyplot` and `pyplotly` libraries drew the dataframe correctly despite the confused dates, so I would never notice that in row 1000 the dates went backwards. Good catch.

Throwing a relevant error when dates are unsorted could be a helpful addition since in larger dataframes this can be hard to notice.

Take care and great job on the library!
