### ISSUE TITLE
Simulating the addition and deletion of indicators on subcharts returns blank subchart

### ISSUE THREAD

**Issue by P-Lamont** [louisnw01/lightweight-charts-python#255]
### Question

The subchart returns blank instead of a line.
The subchart is indeed created as with the height ratio of 8:2 instead of 6:4 in first addition of subchart.
Can anyone help
windows 11
lightweight-charts==1.0.18.9

![Screenshot 2024-01-11 100040](https://github.com/louisnw01/lightweight-charts-python/assets/99668684/7fc296bb-3d27-4ff8-9639-027821caf620)

### Code example

```python
import pandas as pd
import pandas_ta
from lightweight_charts import Chart
import time

if __name__ == '__main__':
    chart = Chart(inner_height=0.6,debug=True)
    chart.legend(visible=True)

    df = pd.read_csv("ohlcv.csv")
    df.date = pd.to_datetime(df.date, dayfirst=True)
    df = df['date open high low close volume'.split()]
    df = df.set_index('date')

    df[['macd','hist','signal']] =  pandas_ta.macd(df.close, slow=14, fast=7, signal=2)
    df = df.dropna()
    chart.set(df)
    #add indicator
    subplot = chart.create_subchart(height=0.4, width=1)
    subplot.legend(visible=True)
    hist = subplot.create_line(name='macd')
    hist.set(df[['macd']])
    #delete indicator with subplot
    hist.delete()
    del subplot
    chart.resize(height=1.0,width=1)
    #add indicator again
    chart.resize(height=0.8,width=1)
    subplot = chart.create_subchart(height=0.2, width=1)
    hist2 = subplot.create_line(name='macd')
    hist2.set(df[['macd']])
    chart.show(block=True)
```

**Comment by louisnw01** [comment]
Hey @P-Lamont,

`del subplot` only deletes the reference to the class object; it has no effect on the actual instance.

What is happening in your example is the first subplot persists, and the second one is placed underneath the first (off the screen).

You could resize the subplot to 0, 0 when you want to hide it, and then make it bigger again when you want to use it.

Louis
