### ISSUE TITLE
Not able to see chart

### ISSUE THREAD

**Issue by Dhawal97** [louisnw01/lightweight-charts-python#258]
### Question

I can load data if i am using data from repo but if i use my custom ohlc data which has same characteristics I am unable to see the chart 
This is what i get as output when i run code with my data
![image](https://github.com/louisnw01/lightweight-charts-python/assets/132455180/ddf656bc-ba1a-4895-82e1-b8cd2189e623)
![image](https://github.com/louisnw01/lightweight-charts-python/assets/132455180/b4a8e100-6474-4dfb-b28a-9ed5839ff078)

if i run the code with repo data I am able to see the results
this is the repo's data info
![image](https://github.com/louisnw01/lightweight-charts-python/assets/132455180/15abf9d7-aee4-4d99-8e3b-3d867816444e)
this is my data's info
![image](https://github.com/louisnw01/lightweight-charts-python/assets/132455180/5b8d7b8a-76ae-4661-b19f-0fd5c87861dd)
I am unable to understand what is wrong 

please help!

### Code example

```python
from lightweight_charts import Chart
import asyncio
import nest_asyncio
import pandas as pd
nest_asyncio.apply()

ohlc = future_data[['OPEN', 'HIGH', 'LOW', 'CLOSE', 'VAL_INLAKH']]
ohlc.reset_index(inplace = True)
ohlc.drop('EXPIRY_DT', axis =1 , inplace = True)
ohlc['TIMESTAMP'] = ohlc['TIMESTAMP'].astype(str)
ohlc.rename(columns = {'TIMESTAMP':'time', 'OPEN':'open', 'HIGH':'high', 'LOW':'low', 'CLOSE':'close',
                      'VAL_INLAKH':'volume'}, inplace = True)
ohlc = ohlc.iloc[-500:]
ohlc.reset_index(inplace = True)
ohlc.drop('index', axis =1 , inplace = True)

if __name__ == '__main__':
    chart = Chart(debug = True)
    chart.set(ohlc)
    chart.show(block = True)
```

**Comment by cilindro5432** [comment]
try this version works perfect for me.

**Comment by Dhawal97** [comment]
> [lightweightcharts copy.zip](https://github.com/louisnw01/lightweight-charts-python/files/13910310/lightweightcharts.copy.zip) try this version works perfect for me.
I installed your version now I am getting this error can you guide me
![image](https://github.com/louisnw01/lightweight-charts-python/assets/132455180/7d032269-0b0b-484c-8c8d-2894ed09b796)

**Comment by arotabi** [comment]
Can you save and attach your dataframe as a csv file (just before you call chart.set(...))

**Comment by CodexLink** [comment]
As seen from the screenshot, you need to rename your `time` column into `date` column, despite it having a type of `datetime`. I think we need to document this properly on the "Getting Started" page as I scanned through it and found nothing about the columns' names.

It would be better if we could remove the requirement of restricting ourselves to the column's names by ignoring of columns' names and assume based on the order of the data. For instance, the 0th index assumes to be the datetime, the 1st index assumes to be the high, and so much so forth...

**Comment by louisnw01** [comment]
> Hi @Dhawal97,
> 
> As seen from the screenshot, you need to rename your `time` column into `date` column, despite it having a type of `datetime`. I think we need to document this properly on the "Getting Started" page as I scanned through it and found nothing about the columns' names.
> 
> It would be better if we could remove the requirement of complying with the column's names and assume based on the order of the data. For instance, the 0th index assumes to be the datetime, the 1st index assumes to be the high, and so much so forth... But just by looking at the source code, I think it will take time, therefore documentation can be the solution if we wanna enforce strict column names instead of adding flexibility for now.

This is incorrect; the column can be named either `date` or `time`, or it can be the index of the dataframe.

**Comment by Dhawal97** [comment]
Hello @louisnw01, please can you tell me what the problem is then because when I am using sample data I able to see charts but with my csv I am not when the data types are same.

**Comment by Dhawal97** [comment]
Hello @arotabi, @louisnw01, please find attached the csv 
[ohlc.csv](https://github.com/louisnw01/lightweight-charts-python/files/13945085/ohlc.csv)
please assist.

**Comment by louisnw01** [comment]
You have rows with duplicate times.
Louis

**Comment by Dhawal97** [comment]
Thank you so much @louisnw01 , It solved my issue
