### ISSUE TITLE
Ray Line [BUG] 

### ISSUE THREAD

**Issue by cilindro5432** [louisnw01/lightweight-charts-python#259]
### Expected Behavior

Creating a ray line and then wanting to delete it when it is deleted visually takes you back in time. If I try to use live data when creating the ray line the candles start to run with space between candles and when removing the line it goes to the past visually. This is an example of the behavior.

https://github.com/louisnw01/lightweight-charts-python/assets/150294229/923fbda8-0c85-46e9-b39c-6cfbb643211c

### Current Behaviour

i explain

### Reproducible Example

```python
N/A
```

### Environment

```markdown
OS: macOS 13.2
Library: 1.0.16.2
```

**Comment by cilindro5432** [comment]
https://github.com/louisnw01/lightweight-charts-python/assets/150294229/9464ce2b-07f2-4e71-9fb6-dc0885162719

**Comment by cilindro5432** [comment]
And also     chart.grid(False)
is not working can see horizontal lines in background.

**Comment by louisnw01** [comment]
Fixed in the latest version.

Louis
