### ISSUE TITLE
How to remove the unwanted horizontal lines getting displayed while the code is continuously updating and displaying the line chart using 2_live_data.py ?

### ISSUE THREAD

**Issue by qarampage** [louisnw01/lightweight-charts-python#262]
### Question

I am getting unwanted horizontal line for each EMA_20 being displayed. Please review the recording and the code that I have . It is a minor change on top of your existing code.

https://github.com/louisnw01/lightweight-charts-python/assets/16265665/e9edc97f-1fe3-4404-874e-d8a8a91b9a3e

how to remove th unwanted horizontal lines. I just want to load the latest from dataframew and display . My Datatframe will have the OHLCV including all the EMAs. I just want to display them on the live chart using you 2_live_data.py file.

### Code example

```python
# I have latest updates of your codebase , lightweight charts and pandas.

import pandas as pd
from time import sleep
from lightweight_charts import Chart

if __name__ == '__main__':
    chart = Chart()

    df1 = pd.read_csv('NIFTY2411822500CE_p1.csv')
    df2 = pd.read_csv('NIFTY2411822500CE_p2.csv')
    df1['time'] = pd.to_datetime(df1['datetime'], format='%Y-%m-%d %H:%M:%S')
    df2['time'] = pd.to_datetime(df2['datetime'], format='%Y-%m-%d %H:%M:%S')

    chart.set(df1)
    chart.show()

    for i, series in df2.iterrows():
        chart.update(series)

        line = chart.create_line('EMA_20')
        sma_data = df2[['time', 'EMA_20']].loc[:i].set_index('time')
        line.set(sma_data)

        sleep(0.1)
```

**Comment by cilindro5432** [comment]
nice question. every ema you create is a line "line.set(sma_data)" is anoing but worst in live data create a new line every single candle.

**Comment by GK4444** [comment]
> > nice question. every ema you create is a line "line.set(sma_data)" is anoing but worst in live data create a new line every single candle.
> 
> @louisnw01 : ok. so which mans I have to use the chart.set(df) instead !

@qarampage can u pls share the code snippet used to resolve the unwanted horizontal lines issue.
