### ISSUE TITLE
New Charting tools

### ISSUE THREAD

**Issue by cilindro5432** [louisnw01/lightweight-charts-python#263]
### Question

hi MR. Louisw01 

Thank you for such extraordinary work. I know it hasn't been easy to make this possible. I've had time to play with the toolbox.js and abstract scripts. I am not the best developer, I do not have much experience but I would like to integrate more tool charting such as a curved line, a resizable rectangle or even a Fibonacci. At the moment I have toolbox.js with a curved line integration and I have another file with an integration for 1 straight line. In the abstract I tried to integrate it but in Python I am limited. When the graph starts, the toolbox is not visible. You will be able to inspect the files perhaps you
 can be integrated into a future version if possible. I know it is not easy and requires a lot of time to put together the puzzle, but if I can make your life easier in some way I would like to collaborate.

[toolboxx.js.zip](https://github.com/louisnw01/lightweight-charts-python/files/13941762/toolboxx.js.zip)

**Comment by louisnw01** [comment]
Closing as duplicate and code doesnt build.

Please follow the normal pull request route for contributing!

Louis
