### ISSUE TITLE
Setting the title for the web version of a chart 

### ISSUE THREAD

**Issue by arotabi** [louisnw01/lightweight-charts-python#268]
### Description

Related to:  https://github.com/louisnw01/lightweight-charts-python/issues/184

Hi,

It would be great if the 'title' parameter can also be added to the web version of the chart (StreamlitChart & JupyterChart)?

JupyterChart(title='PageTitle'...
StreamlitChart(title='PageTitle'...

Thanks :)

**Comment by cilindro5432** [comment]
chart = Chart(title='your_project')
wont work?

**Comment by louisnw01** [comment]
Hey @arotabi,

How do you set a title in Streamlit/Jupyter?

Louis

**Comment by cilindro5432** [comment]
Is there a way to get the buttons to work in StreamlitChart & JupyterChart because I can't change symbols and timeframe with chart.topbar.menu. If there is any way I will be grateful if you can tell me how.

**Comment by louisnw01** [comment]
> Hey @louisnw01,
> 
> Sorry, I missed a little detail. I'm using the JupyterChart to save a large number of chart snapshots as HTML. It gets tricky to keep track without the tab title set.
> 
> Anyway, this is what I've done locally to get around it.
> 
> ```
>   title=f'{exchange}:{asset_code}'
>   # chart = Chart(title=title, width=2000, height=1000, toolbox=True)
>   chart = JupyterChart(title=title, width=2000, height=1000, toolbox=True)
> ```
> 
>  ```
> class JupyterChart(StaticLWC):
>     def __init__(self, title: str = '', width: int = 800, height=350, inner_width=1, inner_height=1, scale_candles_only: bool = False, toolbox: bool = False):
>         super().__init__(width, height, inner_width, inner_height, scale_candles_only, toolbox, False)
> 
>         self.run_script(f'''
>             for (var i = 0; i < document.getElementsByClassName("tv-lightweight-charts").length; i++) {{
>                     var element = document.getElementsByClassName("tv-lightweight-charts")[i];
>                     element.style.overflow = "visible"
>                 }}
>             document.getElementById('wrapper').style.overflow = 'hidden'
>             document.getElementById('wrapper').style.borderRadius = '10px'
>             document.getElementById('wrapper').style.width = '{self.width}px'
>             document.getElementById('wrapper').style.height = '100%'
>             document.title = '{title}'
>             ''')
>         self.run_script(f'{self.id}.chart.resize({width}, {height})')
> ```
> 
> AR

As this is for HTML and not strictly for Jupyter Charts, I think I will leave this feature for now.

Louis
