### ISSUE TITLE
Only plots when saving an re-reading the csv from pandas

### ISSUE THREAD

**Issue by gigasurgeon** [louisnw01/lightweight-charts-python#269]
### Question

I have a CSV of binance tick data. I am plotting first 2k candles. The problem is that if use df directly, I am getting black screen with errors on the debug console **Error: Value is null**. But if I save the df to a csv and then read the csv, the candles are plotted and no errors.

Both the df and the re-read df have the same datatype in all the columns. Its puzzling me.

**Comment by louisnw01** [comment]
Hey @gigasurgeon,

Strange, and annoying because I cant directly see the data. Could you provide print statements of both the dataframe which works and the one which doesnt?

**Comment by gigasurgeon** [comment]
sure 
![image](https://github.com/louisnw01/lightweight-charts-python/assets/22231261/01e0de5c-c8e3-495f-86bd-a62ab0b8dd66)

**Comment by gigasurgeon** [comment]
and here's the df.dtypes
**NOTE:** Even after changing the timestamp column to the same type (string), still the the first one doesn't work.


![image](https://github.com/louisnw01/lightweight-charts-python/assets/22231261/59d6e1e1-3e55-4b57-855a-9cbc48bf58f1)

**Comment by louisnw01** [comment]
The date/time column in your data should be named `date` or `time`, and you have both a `time` and `timestamp` column; im assuming that you are trying to use the `timestamp` column, so I suggest deleting the `time` column and renaming `timestamp` to `time`. 

Louis

**Comment by gigasurgeon** [comment]
> The date/time column in your data should be named `date` or `time`, and you have both a `time` and `timestamp` column; im assuming that you are trying to use the `timestamp` column, so I suggest deleting the `time` column and renaming `timestamp` to `time`.
> 
> Louis

This one worked. As soon as I renamed the timestamp to time, it worked like a charm. Many thanks 😀
