### ISSUE TITLE
save chart as img

### ISSUE THREAD

**Issue by behdad097** [louisnw01/lightweight-charts-python#27]
Is there any way to save the charts as a image file with for eg png format ?

**Comment by emma-uw** [comment]
Hey, @behdad097. Check this comment https://github.com/louisnw01/lightweight-charts-python/issues/26#issuecomment-1605713448

`next update will include a screenshot method, which will allow a screenshot of the chart window to be taken after it has been loaded`

**Comment by louisnw01** [comment]
Hi,

The `screenshot` method has been implemented in the latest version (1.0.13)

Thanks!

Louis

**Comment by behdad097** [comment]
Thaanks good job 
can you create a example for it?
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\lightweight_charts\\js\\pkg.js'

I got above error

**Comment by louisnw01** [comment]
Hi,

Version is bugged, my bad.

Will fix in the next few mins.

Louis

**Comment by louisnw01** [comment]
> Thaanks good job can you create a example for it? FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\lightweight_charts\js\pkg.js'
> 
> I got above error

Fixed in v1.0.13.1
Apologies!

**Comment by behdad097** [comment]
Very nice thanks bro... 
May you create an example for saving chart as img?

**Comment by louisnw01** [comment]
@behdad097 your welcome! Check the docs [here.](https://lightweight-charts-python.readthedocs.io/en/latest/docs.html#screenshot)
