### ISSUE TITLE
How to get a measure tool like TV

### ISSUE THREAD

**Issue by gigasurgeon** [louisnw01/lightweight-charts-python#270]
### Question

I want to measure price % change with mouse. I do that using measure tool(shift + click) on tradingview website. How to achieve it in lightweight-charts?

![image](https://github.com/louisnw01/lightweight-charts-python/assets/22231261/245bd35d-06f4-465a-a90e-ec0907aea890)

**Comment by louisnw01** [comment]
Hey @gigasurgeon,

This is not possible in the library at the moment.

Louis

**Comment by 80sVectorz** [comment]
I would like to vouch for this feature and hope that it'll be reconsidered. I've seen forks of the project implement measure tools, so it must be possible. I'm sure many people will agree with me that it would be great to have.
@louisnw01 would you please give this feature another look?
