### ISSUE TITLE
[BUG] horizontal grid lines can not be disabled 

### ISSUE THREAD

**Issue by Iss-in** [louisnw01/lightweight-charts-python#272]
### Expected Behavior

setting chart.grid(False) should remove both vertical and horizontal grid lines. but as of now only vertical grid lines can be removed,

### Current Behaviour

 horizontal grid lines still persist  

### Reproducible Example

```python
set  chart.grid(False) and open any csv
```

### Environment

```markdown
- OS:Linux
- Library:  lightweight_charts==1.0.19
```

**Comment by louisnw01** [comment]
Hey,

`chart.grid(False, False)`.

Louis
