### ISSUE TITLE
Will this work on Colab?

### ISSUE THREAD

**Issue by xemltil** [louisnw01/lightweight-charts-python#275]
### Question

Is there an example of deploying this library in Google Colab?  I have previously worked with this packge and I want to use it, but not sure if it will have issues.  Anyone work thru deployment yet? Many thanks.

**Comment by louisnw01** [comment]
Hey @xemltil,

The library is untested on Google Colab, but i'd be happy to hear if it works fine or if you run into any issues.

Louis
