### ISSUE TITLE
QtChart(PyQt5) method shown in gui_examples.md isn't working

### ISSUE THREAD

**Issue by milind-k** [louisnw01/lightweight-charts-python#276]
### Question

![Screenshot from 2024-01-24 22-48-12](https://github.com/louisnw01/lightweight-charts-python/assets/33188876/c809d93c-aa44-45ac-b248-62d38fdaefff)

My code stopped working after I reinstalled Ubuntu 22.04. I was using QtChart. The attached image shows the blank window when I run the code.

### Code example

```python
import pandas as pd
from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget

from lightweight_charts.widgets import QtChart

app = QApplication([])
window = QMainWindow()
layout = QVBoxLayout()
widget = QWidget()
widget.setLayout(layout)

window.resize(800, 500)
layout.setContentsMargins(0, 0, 0, 0)

chart = QtChart(widget)

df = pd.read_csv('ohlcv.csv')
chart.set(df)

layout.addWidget(chart.get_webview())

window.setCentralWidget(widget)
window.show()

app.exec_()
```

**Comment by louisnw01** [comment]
Hey @milind-k,

Try reinstalling/updating Qt. If that doesn't work try a general Qt example rather than one specific to this library, as it doesn't sound related to lightweight charts.

Louis

**Comment by milind-k** [comment]
I reinstalled Qt, but it didn't work. The app I am building using
PyQt5(v5.15.10) is running fine. So I am stuck now because the rest of the
app is fine, only the chart isn't showing. I don't know what to do. Please
lead my way to possible solutions.
