### ISSUE TITLE
How to draw a line from one index to another index?

### ISSUE THREAD

**Issue by NijanJ** [louisnw01/lightweight-charts-python#277]
### Question

Hellow Sir, 
How to draw a line from one index to another index?

**Comment by arotabi** [comment]
Hey - you can use chart.trend_line() method

**Comment by NijanJ** [comment]
Hello, sir. Thank you for the reply. I wanted to ask if we can plot a rectangle or any kind of box?

**Comment by arotabi** [comment]
I don't think there's an option to draw rectangles but you could draw one with four separate lines.
Perhaps a utility method draw_box(start_x, start_y, end_x, end_y) which then calculates and adds the four lines to the chart?

**Comment by NijanJ** [comment]
Thank You for your Help Sir
