### ISSUE TITLE
Could marker object point to correct level on the y axis (with positioning inBar)?

### ISSUE THREAD

**Issue by maximbelyayev** [louisnw01/lightweight-charts-python#283]
First of all, thank you for creating this python framework for the javascript TV library. I'm a hobby coder and this has made my life much easier.

### Description

The feature/enhancement would be to have an implementation for a marker with y-coordinates, or a line series where marker data (time, value, color, etc.) could be set by the user, and the line would be invisible and markers visible. This is discussed in the below forum:

https://github.com/tradingview/lightweight-charts/issues/127

In the below screenshot, the current behavior sets markers relative to the bar position, which can be inaccurate for use case of tracking events.
 Ideally, if a transaction or event occurred within the bar at some y-value / price (e.g., @ 540.59). The marker should be anchored to that y-value.

![Screenshot 2024-02-01 at 10 56 58 AM](https://github.com/louisnw01/lightweight-charts-python/assets/105830732/48434381-5305-4f85-b243-ca4b850b9627)

Thank you for your continued work in this framework!

**Comment by louisnw01** [comment]
Hey @maximbelyayev,

As the issue you linked references plugins in relation to implementing this feature, I'm marking this as a duplicate.

Louis
