### ISSUE TITLE
[BUG] Text Disappears from Chart when Zoomed In

### ISSUE THREAD

**Issue by NijanJ** [louisnw01/lightweight-charts-python#285]
### Expected Behavior

Text labels and annotations should remain visible and legible even when the chart is zoomed in

### Current Behaviour

When zooming in on the chart, the text labels and annotations disappears

https://github.com/louisnw01/lightweight-charts-python/assets/93983733/0260852f-497e-4710-b04a-19673d9f2a54

### Reproducible Example

```python
HI
```

### Environment

```markdown
- OS: macOS
- Library:
```

**Comment by NijanJ** [comment]
https://github.com/louisnw01/lightweight-charts-python/assets/93983733/89b40fac-80a4-4e5d-be0f-5d134da84443

**Comment by louisnw01** [comment]
Not a bug; all markers shhould be in chronological order.

Louis

**Comment by NijanJ** [comment]
`def Text_List_TV(chart, Dataframe, Index, Text, font_color, position ):
    for idx in np.sort(Index) :
        chart.marker( time = Dataframe.at[idx, "Datetime"], position = position,
               color = font_color, text = Text)`
               
'm currently using this function to plot the index in the list. There is no problem when only one list is used, as the single list is synchronized. However, when attempting to plot multiple lists, each with its own index, the synchronization is not maintained, leading to misaligned data points on the chart.

Could you please advise on the best approach to ensure proper synchronization of indices when plotting multiple lists using the chart.marker function or any custom function designed for this purpose? I would greatly appreciate any insights or suggestions you can provide to address this issue.

**Comment by amitbuyo2020** [comment]
@louisnw01 @NijanJ  I am also facing the same issue. The texts disappear when i try to zoom in the chart and reappears when zoom out.
