### ISSUE TITLE
StreamLit persistent drawings not working

### ISSUE THREAD

**Issue by metph86** [louisnw01/lightweight-charts-python#286]
### Question

Hi,

when using `chart.toolbox.save_drawings_under()`  and `chart.toolbox.export_drawings('drawings.json')` with the normal Python wrapper there is no issue but when using with StreamLit the drawings are not saved at all. Could this be because SL refreshes the chart before it can actually gather and save the drawings ? Loading drawings from the json works fine but saving doesn't.

**Comment by louisnw01** [comment]
Hey @metph86,

As mentioned in the documentation streamlit charts are static, meaning that there can be no communication between Streamlit and python. This means callbacks (which saving drawings relies upon) is not possible.

Louis

**Comment by metph86** [comment]
Oh right yeah that makes sense, thanks for clarifying and thank you so much
for your work on this !
