### ISSUE TITLE
issue in sync for multi timeframe

### ISSUE THREAD

**Issue by gigasurgeon** [louisnw01/lightweight-charts-python#293]
### Question

I am creating subcharts with different timeframes. The issue is that the crosshairs sync properly, but the charts are not independent. If I slide a low timeframe chart, the higher TF chart gets dragged with it. This makes the charts unusable for MTF analysis. Here's a screenshot. Ideally I would want the crosshairs to sync but I should be able to slide or drag both the charts independently.

![image](https://github.com/louisnw01/lightweight-charts-python/assets/22231261/93a01fc6-b233-49d7-978e-72cefa369eae)

**Comment by louisnw01** [comment]
Hey @gigasurgeon,

Are you asking for timescales to sync on multiple timeframes (which would be a dupe issue) or the ability to just sync crosshairs rather than ranges?

Louis

**Comment by gigasurgeon** [comment]
I want just the crosshairs to sync.

**Comment by gigasurgeon** [comment]
thank you
