### ISSUE TITLE
Chart not displaying after running code

### ISSUE THREAD

**Issue by NijanJ** [louisnw01/lightweight-charts-python#30]
I am experiencing an issue where the chart is not displaying after running the code. I have followed the necessary steps and reviewed the documentation, but I'm unable to resolve the problem. 

Code Snippet:
```
import pandas as pd
from lightweight_charts import Chart
import yfinance as yf



data = yf.download("AWL.NS", period= "50d" , interval= "15m")
data["time"] = data.index
data = data.reset_index(drop = True)

data.rename(columns={'Open': 'open', 'High': 'high', 'Low': 'low', 'Close': 'close', 'Volume' : 'volume'}, inplace=True)



if __name__ == '__main__':
    
    chart = Chart()
    
    # Columns: | time | open | high | low | close | volume (if volume is enabled) |
    df = data
    chart.set(df)
    
    chart.show(block=True)
```

**Comment by Zartexo** [comment]
I can run your code snipped without problems

**Comment by emma-uw** [comment]
Same 
![изображение](https://github.com/louisnw01/lightweight-charts-python/assets/135511356/d640ee13-7ff7-4cbf-b8aa-edd5c7557d96)

**Comment by louisnw01** [comment]
Hey @NijanJ,

Are there any errors when you try to display the chart?

Does the chart window load but not show anything, or not load at all?

**Comment by NijanJ** [comment]
I encountered an issue where the chart does not load at all. The chart window fails to appear, preventing me from visualizing any data. I have not been able to observe any errors or receive any feedback indicating the cause of this problem.

**Comment by louisnw01** [comment]
Have you tried running the examples like `1_setting_data`?

If that still doesn't work, try running the following code:

```python

import webview

webview.create_window('Test', html='Test')
webview.start()
```

**Comment by molon** [comment]
I think this question should be opened again. I ran into the same problem.
I run `python ./callbacks.py` with `iTerm2` or `Vscode`. Nothing will be displayed.
Then I tried to use the `Terminal` of `MacOS` to run the command, and the display can be loaded normally, but the keyboard focus cannot be obtained.

I think this is a issue of `pywebview`, maybe in the `MacOS` environment, the adaptation of this library is not very good, or because of some other reasons.

**Comment by louisnw01** [comment]
> I think this question should be opened again. I ran into the same problem. I run `python ./callbacks.py` with `iTerm2` or `Vscode`. Nothing will be displayed. Then I tried to use the `Terminal` of `MacOS` to run the command, and the display can be loaded normally, but the keyboard focus cannot be obtained.
> 
> I think this is a issue of `pywebview`, maybe in the `MacOS` environment, the adaptation of this library is not very good, or because of some other reasons.

Hi! Could you confirm you have tried this:

> Have you tried running the examples like `1_setting_data`?
> 
> If that still doesn't work, try running the following code:
> 
> ```python
> import webview
> 
> webview.create_window('Test', html='Test')
> webview.start()
> ```

**Comment by molon** [comment]
> 

It has been solved so far, known conclusions:
- Using `cond`, not available.
- Using `pyenv without version system`, not available.
- Using `pyenv with version system`, available.
- Using `venv`, available.

I don't know the specific reason, but it must be related to `pywebview`, currently I use `venv`, it works fine.
