### ISSUE TITLE
option to disable line studies to fit on the chart

### ISSUE THREAD

**Issue by pranavladkat** [louisnw01/lightweight-charts-python#301]
### Description

Hi,

Is it possible to override settings where lines created using `chart.create_line()` API avoids fitting on the chart? e.g. When zooming in the chart, the zoom is restricted to include the line (unless manually scaling the axis). This can make candles a lot smaller if the line drawn in far out than current prices (e.g. see the image below). It'll be great to have an option to disable `fit studies` option. Thanks!

<img width="904" alt="image" src="https://github.com/louisnw01/lightweight-charts-python/assets/9426781/7d189d82-5d39-4532-857e-082fa6527c5a">

**Comment by louisnw01** [comment]
Hey @pranavladkat,

Try the `scale_candles_only` parameter of `Chart`.

Louis
