### ISSUE TITLE
NaN values in Lines series are showing up on Screen instead of blank.

### ISSUE THREAD

**Issue by zephyr-git** [louisnw01/lightweight-charts-python#304]
### Description

Hi,
While adding a line series, if there are NaN values are present then there should be a gap seen on the chart. However, It joins the gaps with a straight line. This has been marked with blue arrow in below screenshot. Can  there be a feature similar to **plot.style_linebr of Pinescript** when when we expect gaps represented by NaN values?

longStopPlot = plot(dir == 1 ? longStop : na, title='Long Stop', style=plot.style_linebr, linewidth=2, color=color.new(longColor, 0))

### Method of implementation

![image](https://github.com/louisnw01/lightweight-charts-python/assets/157400692/339fbbed-1997-4ae0-a108-84de63c30846)

**Comment by louisnw01** [comment]
Hey @zephyr-git,

Could you provide a MRE with a csv?

Louis

**Comment by zephyr-git** [comment]
Hi Louis,

Here I am calculating stop loss based upon whether the system is long or short in 2 different columns **CHE_LE** (stop loss for long) and **CHE_SE** (stop loss for short). Trying to draw 2 different lines with color 'green' and 'red' for each. So, whenever **CHE_LE**  has a value, **CHE_SE** is set to np.nan and vice versa. Please find attached the csv file for the data.
Also, I am using below code to set the two line lines for long and short stop loss.

line_CHE_L = chart.create_line(name='CHE_LE', color='rgba(66, 245, 66, 0.65)', width=1, style='dashed',price_line=False)
line_CHE_L.set(df_CE_5min)

line_CHE_S = chart.create_line(name='CHE_SE', color='rgba(217, 36, 24, 0.65)', width=1, style='dashed',price_line=False)
line_CHE_S.set(df_CE_5min)

I am trying achieve something as shown in below screenshot. I hope I was able to provide enough information. Thanks for your efforts.

[BNF_5_Min_o.csv](https://github.com/louisnw01/lightweight-charts-python/files/14395267/BNF_5_Min_o.csv)


![image](https://github.com/louisnw01/lightweight-charts-python/assets/157400692/d03d7f63-eeaa-459b-a4c2-046a8ac9d0c5)

**Comment by louisnw01** [comment]
Hey @zephyr-git,

I don't believe Lightweight Charts offers this functionality unfortunately.

Louis

**Comment by zephyr-git** [comment]
Just one question, why would Nan values in a series be still shown in the same color as valid data? Will this be treated as a "bug " and resolved in any future version? Thanks.
