### ISSUE TITLE
Toggle visibility of indicators from the chart window

### ISSUE THREAD

**Issue by dysai1234** [louisnw01/lightweight-charts-python#31]
I want to use it similar to tradingview Indicators. So If I can able to hide and un-hide  indicators that would be great.

**Comment by louisnw01** [comment]
Hey @dysai1234,

I am planning to allow for drawings (trendlines, horizontal lines, ray lines etc.) to be made from within the chart window.

I hadn't considered this yet, but great suggestion, i'll look into implementing this.

**Comment by dysai1234** [comment]
I am able to draw indicators on the chart but How can I remove them similar to indicators visible and not visible in tradingview

**Comment by louisnw01** [comment]
> I am able to draw indicators on the chart but How can I remove them similar to indicators visible and not visible in tradingview

At the moment you can use the `hide_data` and `show_data` methods of `Line`.

If you wanted to do this from the chart directly, it would be possible using Callbacks.

**Comment by hanxuanliang** [comment]
Currently, I am drawing indicator lines in Streamlit. Using the most brute-force method: re-rendering the page.

According to what was mentioned above, is the "hide" method also applicable in Streamlit?

However, it seems that the callback method is not compatible with Streamlit.

**Comment by louisnw01** [comment]
> Currently, I am drawing indicator lines in Streamlit. Using the most brute-force method: re-rendering the page.
> 
> According to what was mentioned above, is the "hide" method also applicable in Streamlit?
> 
> However, it seems that the callback method is not compatible with Streamlit.

Hey @hanxuanliang,

The methods mentioned above won't work with Streamlit, as it would require communication between Python and the Flask server which isn't possible with the library at the moment.

However, I do think a direct way to hide and unhide indicators on the Chart would be a great addition for the next update, and that will be purely Javascript so it would work with streamlit.

Louis

**Comment by hanxuanliang** [comment]
> 

Sounds great, this is a huge help for the users.

**Comment by louisnw01** [comment]
Hey @hanxuanliang, @dysai1234,

In the latest update (1.0.14) the legend now has a visibility selector next to each line displayed within it.

Great idea!

Louis

**Comment by dysai1234** [comment]
Do you have any example code

**Comment by louisnw01** [comment]
> Do you have any example code

Its integrated by default, so any previous code should work.
