### ISSUE TITLE
Can update volume by update_from_tick()? 

### ISSUE THREAD

**Issue by everypreciousday** [louisnw01/lightweight-charts-python#310]
### Question

I would like to update volume by `update_from_tick()`. 
Is it possible? 

The example https://github.com/louisnw01/lightweight-charts-python/tree/main/examples/3_tick_data
is not handling volume.

**Comment by louisnw01** [comment]
You can use the `cumulative_volume` parameter of `update_from_tick`, which adds the given volume onto the latest bar.

Louis
