### ISSUE TITLE
Charts with many bars empty

### ISSUE THREAD

**Issue by vogelo** [louisnw01/lightweight-charts-python#311]
### Question

I’m having trouble with charts with a lot of bars. It depends on the timestamps, but starting from some threshold (just a few hundred for short time intervals, up to 10000 for the largest time intervals between two bars I tested), the charts come out empty.

I would like to load a chart with around 200k bars. Any chance to do that? 

I found someone doing something like that directly in JS: https://jsfiddle.net/TradingView/fg7yez2s/

I would like to work with as many bars, in Python.

**Comment by louisnw01** [comment]
You can use the `chart.events.range_change` event to send a callback into python, within which you could implement dynamic loading functionality.

Louis
