### ISSUE TITLE
Crosshair sync in different timeframe attaches to the nearest candle instead of exact location

### ISSUE THREAD

**Issue by gigasurgeon** [louisnw01/lightweight-charts-python#312]
### Description

Thanks for implementing the crosshair sync in  multiple windows. I am using this code to create two different windows stacked on top of each other ->
```
main_chart = Chart(width=1820, height=980, inner_width=1, inner_height=0.5)
chart2 = main_chart.create_subchart(width=1, height=0.5, sync=True, sync_crosshairs_only=True)
```
![image](https://github.com/louisnw01/lightweight-charts-python/assets/22231261/119f23b0-966d-41dd-b200-1f35ea951348)

When I hover my mouse crosshair in one of the windows, the crosshair in other windows arrive at the correct candle but it always is attached to that candle. If I hover my mouse in the empty region above the candles, the crosshair is still attached to the candle. This makes measuring support and resistance lines tough. If we could make the crosshairs sync in the empty region above and below the candles as well, it would make the MTF analysis much easy. It would be a neat little addition.

**Comment by louisnw01** [comment]
Hey @gigasurgeon,

I'm not sure if this would be wise, as synced charts may have wildly different price values.

Louis
