### ISSUE TITLE
Marker disappearing when zooming in

### ISSUE THREAD

**Issue by Zartexo** [louisnw01/lightweight-charts-python#32]
Hi,

found some weird display bug. When I use two types of markers they sometimes disappear when I zoom in. See code below.:

```
import pandas as pd
import numpy as np
from lightweight_charts import Chart


def calculate_sma(data: pd.DataFrame, period: int = 50):
   def avg(d: pd.DataFrame):
      return d['close'].mean()

   result = []
   for i in range(period - 1, len(data)):
      val = avg(data.iloc[i - period + 1:i])
      result.append({'time': data.iloc[i]['date'], 'value': val})
   return pd.DataFrame(result)


if __name__ == '__main__':
   chart = Chart(maximize=True)

   df = pd.read_csv('ohlcv.csv')
   chart.set(df)

   line = chart.create_line()
   sma_data = calculate_sma(df)
   line.set(sma_data)
   df['Gain'] = df['close'] - df['open']
   longs = df.query('Gain < -20')
   shorts = df.query('Gain > 20')
   for index, row in longs.iterrows():
      chart.marker(row['date'], 'below', 'arrow_up', 'green', 'L')
   for index, row in shorts.iterrows():
      chart.marker(row['date'], 'above', 'arrow_down', 'red', 'S')

   chart.show(block=True)
```

Somehow if I only use the "longs" markers, they will not disappear when zooming in.

Video of the bug:
https://github.com/louisnw01/lightweight-charts-python/assets/104310309/4b7ef48a-002e-41d0-a62b-4f06da46b579

**Comment by louisnw01** [comment]
Hey @Zartexo,

It appears this happens when markers are placed in a non chronological order. You could append each marker to a list and then sort the list by date before placing them:

```python
markers = []
for index, row in longs.iterrows():
markers.append((row['date'], 'below', 'arrow_up', 'green', 'L'))
for index, row in shorts.iterrows():
markers.append((row['date'], 'above', 'arrow_down', 'red', 'S'))

for marker_item in sorted(markers, key=lambda x: x[0]):
   chart.marker(*marker_item)
```

Maybe I could implement auto sorting of the markers, but this could cause long loading times if someone is using a very large dataset.

**Comment by Zartexo** [comment]
Hi @louisnw01 ,

thank you. I adjusted my code and the problem is solved 👍 

I think it is better to keep the loading times small and maybe have a note in the documentation instead.
