### ISSUE TITLE
method to get pointer timestamp 

### ISSUE THREAD

**Issue by Iss-in** [louisnw01/lightweight-charts-python#325]
### Question

This is related to #316 in which i asked for a replay feature, seems like its indeed fairy easy to get it happen via callback function. thanks for the hint. 

but now the issue is that there is no proper way to select a particular timestamp to start replay from. is it possible to get the x axis/timestamp of pointer so that replay can start from there

### Code example

```python
pointer_timestamp = func_get_pointer_timestamp()
n = df.index[df.timestamp >= pointer_timestamp]
for i in range(n ,len(df.index)):
    df2 = df.head(i)
    sleep(1)
    chart.set(df2)
```

**Comment by amirzamli** [comment]
This might help you: https://github.com/louisnw01/lightweight-charts-python/issues/343
