### ISSUE TITLE
Region along with Horizontal line 

### ISSUE THREAD

**Issue by dysai1234** [louisnw01/lightweight-charts-python#33]
Hi, I am trying to draw region around horizontal line is it possible to add that functionality to the horizontal line function

**Comment by louisnw01** [comment]
Hi!

I'm not quite sure what you mean by a region. Could you provide a screenshot of the output you're looking for on the chart?

**Comment by dysai1234** [comment]
![image](https://github.com/louisnw01/lightweight-charts-python/assets/48354881/00fc8989-ef38-4339-8889-6488f58b6df5)

I have attached Image for reference

**Comment by louisnw01** [comment]
You could achieve something like this by first making a horizontal line with a large width, and then another at the same price with a regular width. If you want the region to be translucent, you can use `rgba`:

```python
chart.horizontal_line(162, 'rgba(122, 246, 202, 0.2)', width=10, axis_label_visible=False)
chart.horizontal_line(162)
```

Whilst this lacks precision as you cant set the specific price where the region will end, Lightweight Charts haven't implemented a way to do this properly.

Louis

**Comment by dysai1234** [comment]
Thanks
