### ISSUE TITLE
Multiple Markers at same X Axis(Vertical Level) but Different Y Axis(Horizontal Level)

### ISSUE THREAD

**Issue by mehboob-dev** [louisnw01/lightweight-charts-python#330]
### Question

First and foremost, I would like to extend my gratitude to @louisnw01 for providing such a valuable and resourceful contribution.

I am interested in plotting the entry price along with several levels as follows:

Entry Price - Represented by the First Marker
PT Level 1 - i.e., Entry price +1% - Represented by the Second Marker
PT Level 2 - i.e., Entry price +2% - Represented by the Third Marker
SL Level 1 - i.e., Entry price -1.5% - Represented by the Fourth Marker

**Comment by louisnw01** [comment]
Hey @mehboob-dev,

You could use a combination of ray lines to achieve something very similar.

Louis
