### ISSUE TITLE
Adjustable precision for legend

### ISSUE THREAD

**Issue by Yan-vibeit** [louisnw01/lightweight-charts-python#331]
### Description

Would it be possible to add an option to adjust the precision of custom values presented in chart legends. I have a subchart with a custom line and the legend precision is fixed with 2 decimal places. When working with ATR values, depending on the symbol they will show as 0.00. ohlcv could also benefit from this depending on symbol.

Suggestion,

legend(visible: bool, ohlc: bool, percent: bool, **precision: int**,  lines: bool, color: COLOR, font_size: int, font_family: str, text: str, color_based_on_candle: bool)

Apologies if this is already implemented and i missed it in the docs.

Thanks and keep up the great work you are doing!

**Comment by louisnw01** [comment]
The `chart.precision` method will change the price scale precision as well as the legend's precision. Is this what you're after?

**Comment by nuuritas** [comment]
@louisnw01 
Currently, `chart.precision` only adjusts the price precision for the chart, not for the legend prices. To address this, I propose adding a configurable `legendPrecision` option to allow users to control the precision for legend values as well.

#### Changes:

1. **In `abstract.py`:**  
   Update the `legend` method signature to include `legendPrecision` as a parameter:

   ```python
   legend(self, visible: bool = False, ohlc: bool = True, percent: bool = True, lines: bool = True,
          color: str = 'rgb(191, 195, 203)', font_size: int = 11, font_family: str = 'Monaco',
          text: str = '', color_based_on_candle: bool = False, legendPrecision: int = 4):
   ```

   Below, modify the script to include `legendPrecision`:
   ```python
   self.run_script(f'''
       {l_id}.div.style.display = 'flex'
       {l_id}.ohlcEnabled = {jbool(ohlc)}
       {l_id}.percentEnabled = {jbool(percent)}
       {l_id}.linesEnabled = {jbool(lines)}
       {l_id}.legendPrecision = {legendPrecision}
       {l_id}.colorBasedOnCandle = {jbool(color_based_on_candle)}
       {l_id}.div.style.color = '{color}'
       {l_id}.color = '{color}'
       {l_id}.div.style.fontSize = '{font_size}px'
       {l_id}.div.style.fontFamily = '{font_family}'
       {l_id}.text.innerText = '{text}'
    @''')
   ```

2. **In `js/bundle.js`:**  
   For each OHLC column, replace references to `this.handler.precision` with `this.legendPrecision`:

   ```javascript
   {this.legendItemFormat(s.open, this.legendPrecision)}
   ```

#### Example Usage:
```python
chart.legend(visible=True, color_based_on_candle=True, percent=True, legendPrecision=6)
```

These changes would allow for finer control over the display precision of legend values, ensuring consistency with chart configurations.
