### ISSUE TITLE
Plot discontinuous lines

### ISSUE THREAD

**Issue by TodeDragos** [louisnw01/lightweight-charts-python#332]
### Question

Hello,

I'm currently using the Chart class to plot a line chart for a time series data. However, I've encountered an issue when trying to plot a line that has gaps (i.e., discontinuous line).

Here's a simplified version of my code:
```
chart = Chart()
bid1_line = chart.create_line('bid1_line', width=1, color='#FF0000')
data = df[['time', 'bid1_line']].dropna()
bid1_line.set(data)
```
In my data, there are periods where 'bid1_line' is NaN, and I would like these periods to appear as gaps in the line chart. However, the current implementation seems to connect the points before and after the gap, creating the impression of a continuous line.

I was wondering if there's a way to create a broken line chart using the Chart class? If not, could this feature be considered for a future update?

Thank you for your help.

**Comment by Baili-BL** [comment]
Hi, I also encountered the same situation. I checked and found that when I zoom in, I can occupy non continuous lines, but when I zoom out, it shows continuous lines. By the way, have you solved this problem? If there is a good solution, can you share it?

**Comment by LukeZhuohuiLi** [comment]
I changed the line style, still doesn't solve the problem.

**Comment by TodeDragos** [comment]
nope, unfortunately, I couldn't find any solution for this behavior.

**Comment by LukeZhuohuiLi** [comment]
I just solved this problem by spliting the series and put them into two lists

def splitUpSeriesWithGaps(supertrend_positions,chart):
    Lines_uB = []
    Lines_lB = []
    Index_upper = 0
    Index_lower = 0
    df_length = len(supertrend_positions)

    for i in range(0,df_length):
        if(np.isnan(supertrend_positions["upperband"][i]) == True and np.isnan(supertrend_positions["upperband"][i-1]) == False):
            Index_lower = i
        if(np.isnan(supertrend_positions["lowerband"][i]) == True and np.isnan(supertrend_positions["lowerband"][i-1]) == False):
            Index_upper = i
        if(np.isnan(supertrend_positions["upperband"][i]) == False and np.isnan(supertrend_positions["upperband"][i-1]) == True and i != 0):
            Lines_lB.append(supertrend_positions[Index_lower:i])
        if(np.isnan(supertrend_positions["lowerband"][i]) == False and np.isnan(supertrend_positions["lowerband"][i-1]) == True and i != 0):
            Lines_uB.append(supertrend_positions[Index_upper:i])
        if(i == df_length - 1):
            if(np.isnan(supertrend_positions["lowerband"][i]) == True and np.isnan(supertrend_positions["lowerband"][i-1]) == True):
                Lines_uB.append(supertrend_positions[Index_upper:i])
            elif(np.isnan(supertrend_positions["upperband"][i]) == True and np.isnan(supertrend_positions["upperband"][i-1]) == True):
                Lines_lB.append(supertrend_positions[Index_lower:i])
    for i in range(0,len(Lines_uB)):
        temp = chart.create_line("upperband",color="red",style="solid",price_line=False)
        temp.set(Lines_uB[i])
    for j in range(0,len(Lines_lB)):
        temp2 = chart.create_line("lowerband",color="green",price_line=False)
        temp2.set(Lines_lB[j])


It works fine, I tried to modify the tradingview js code, too hard for me to understand those 8000 lines of code.

**Comment by louisnw01** [comment]
Fixed in latest version.

Louis

**Comment by N1C3P1** [comment]
i have the same issue, but i used it with streamlit. I import the data from a sqlite .db file.  Maybe its my mistake and i forgot something. In the db the gap values are "null"
my code:
```
import streamlit as st
import sqlite3
import pandas as pd
from lightweight_charts.widgets import StreamlitChart

def get_tickers():
    conn = sqlite3.connect("stock_data.db")
    query = "SELECT name FROM sqlite_master WHERE type='table';"
    tables = pd.read_sql(query, conn)
    conn.close()
    return tables['name'].tolist()

def load_data(ticker):
    conn = sqlite3.connect("stock_data.db")
    query = f"SELECT * FROM '{ticker}'"
    data = pd.read_sql_query(query, conn)
    conn.close()

    data['Date'] = pd.to_datetime(data['Datetime'], utc=True)
    return data

def main():
    st.set_page_config(page_title="Stock Dashboard", page_icon="🚀", layout="wide")

    # Sidebar for Ticker
    tickers = get_tickers()
    st.sidebar.title("Select Ticker")
    selected_ticker = st.sidebar.selectbox( "", tickers)

    # load data
    stock_data = load_data(selected_ticker)

    # Streamlit Chart
    chart = StreamlitChart(inner_height=0.6, height=1100, width=2400 , toolbox=False)
    chart.background_color = '#2b2b2b'

    chart.candle_style(
        up_color="green",
        down_color="red",
        border_up_color="darkgreen",
        border_down_color="darkred",
        wick_up_color="green",
        wick_down_color="red"
    )

    chart.volume_config(
        up_color="green",
        down_color="red",
    )

    
    supertrend_up = chart.create_line(name="SuperTrend_Up", color="green", width=1, price_line=False)
    supertrend_down = chart.create_line(name="SuperTrend_Down", color="red", width=1, price_line=False)

    macd_subplot = chart.create_subchart(height=0.2, width=1, sync=True)  # Subplot für MACD
    macd_line = macd_subplot.create_line(name="MACD", color="blue")
    macd_signal_line = macd_subplot.create_line(name="MACD_signal", color="orange")
   
    # PVO Subplot
    pvo_subplot = chart.create_subchart(height=0.2, width=1, sync=True)
    pvo_line = pvo_subplot.create_line(name="PVOfun_10_5", color="green")

    chart.legend(visible=True, ohlc=True, percent=True, lines=True, color_based_on_candle=True, font_size=14, font_family="Arial") 
    macd_subplot.legend(visible=True, ohlc=True, percent=True, lines=True, color_based_on_candle=True, font_size=14, font_family="Arial")
    pvo_subplot.legend(visible=True, ohlc=True, percent=True, lines=True, color_based_on_candle=True, font_size=14, font_family="Arial")

    chart.set(stock_data)
    supertrend_up.set(stock_data)
    supertrend_down.set(stock_data)
    
    macd_line.set(stock_data)
    macd_signal_line.set(stock_data)
    pvo_line.set(stock_data)
    chart.load()

    st.sidebar.subheader("Data overview")
    st.sidebar.dataframe(stock_data.tail())

    # Statistical key figures
    st.sidebar.subheader("Statistical key figures")

    st.sidebar.metric("Current closing price", f"${stock_data['Close'].iloc[-1]:.2f}")
    st.sidebar.metric("Highest price", f"${stock_data['High'].max():.2f}")
    st.sidebar.metric("Lowest price", f"${stock_data['Low'].min():.2f}")

if __name__ == "__main__":
    main()
```

![Image](https://github.com/user-attachments/assets/b93da20a-9221-4b78-97fd-f8481190bdce)
