### ISSUE TITLE
pywebview 5.0 will give random errors > fix pywebview version to 4.3

### ISSUE THREAD

**Issue by bent-verbiage** [louisnw01/lightweight-charts-python#336]
### Question

I just spent 2 days finding and battling random javascript errors (example below) when generating and running sequences of charts (using show_async). I finally tracked it down to an issue with pywebview version 5.x. As soon as I fixed pywebview to version 4.3 all issues disappeared. 

I love this library though: While the documentation and examples could be better, with some effort it's definitely possible to create exactly the same charts as we see in TradingView, while using Python. 

### Code example

```python
[pywebview] {'name': 'TypeError', 'message': "undefined is not an object (evaluating 'line.color')", 'line': 329, 'column': 28, 'sourceURL': 'about:blank', 'stack': 'makeLineRow@about:blank:329:28\neval code@\neval@[native code]\nglobal code@about:blank:4:33'}
```

**Comment by louisnw01** [comment]
Fixed in the latest version.

Louis
