### ISSUE TITLE
Possible in command line only?

### ISSUE THREAD

**Issue by RomulusERC** [louisnw01/lightweight-charts-python#337]
### Question

Hey,
So I have an app and I want to be able to create charts on my ubuntu server, and upload them to a remote server. 
I see the screenshot option, but that requires drawing the chart. My server is a non-gui server and I only use it via command line etc.
Is it possible to use this library via command line only so I can save the chart and then upload it?

Ps: I have tried and i get what one can expect... a ' Gtk-WARNING **: 05:38:43.335: cannot open display:' error on the chart.show(block = False) line.

**Comment by Lejoon** [comment]
I'm wondering the same. My use case is similar to yours. I've tried some stuff like using xvfbwrapper in Python around the chart objects but didn't work. Probably need to change the package itself?

**Comment by wyzdic** [comment]
Same similar issue, I want to host to a server, generate an image via instruction and upload to the location I specify, but I get an error on a non-GUI server, I guess is there a way to not finish the generation of the image through the GUI?

**Comment by Lejoon** [comment]
@louisnw01 is there perhaps a workaround possible using xvfbwrapper or something similar to use a headless method?

**Comment by louisnw01** [comment]
Hey guys,

I don't have access to a linux machine at the moment; could you try something like this and let me know if it works?

```python
import webview
from xvfbwrapper import Xvfb


vdisplay = Xvfb()
vdisplay.start()

window = webview.create_window('', html='<h1>Hello</h1>')
webview.start()

vdisplay.stop()
```

**Comment by wyzdic** [comment]
> Hey guys, hey guys
> 
> I don't have access to a linux machine at the moment; Could you try something like this and let me know if it works? Can you try something like this and let me know if it works?
> 
> ```python
> import webview
> from xvfbwrapper import Xvfb
> 
> 
> vdisplay = Xvfb()
> vdisplay.start()
> 
> window = webview.create_window('', html='<h1>Hello</h1>')
> webview.start()
> 
> vdisplay.stop()
> ```

Doesn't work for me, is there a way to just generate an image (not in the main thread)? My usage is to return a graph of the current specified coin based on the parameters provided by the user, without interaction

**Comment by RomulusERC** [comment]
> Hey guys,
> 
> I don't have access to a linux machine at the moment; could you try something like this and let me know if it works?
> 
> ```python
> import webview
> from xvfbwrapper import Xvfb
> 
> 
> vdisplay = Xvfb()
> vdisplay.start()
> 
> window = webview.create_window('', html='<h1>Hello</h1>')
> webview.start()
> 
> vdisplay.stop()
> ```

It just hangs/does nothing on the `webview.start()` line.

**Comment by louisnw01** [comment]
See #352
