### ISSUE TITLE
Show Dynamic values in legend

### ISSUE THREAD

**Issue by tradinworld** [louisnw01/lightweight-charts-python#338]
### Description

- Is it possible to show dynamic values to legend?
- I know lines, OHLCV are currently shown in legend. But how to show dynamic/arbitrary values in the legend?
- Context: Chart gets ugly if I use more than 3 or 4 markers at the same time. It would be nice if there is a way to show the marker values as a legend instead.

Thanks for your amazing work here!

### Code example

```python
chart.legend(visible=True, data={'enterTrade': True}, time=time)
```

**Comment by tradinworld** [comment]
@louisnw01 FYI , Thanks!

**Comment by mehboob-dev** [comment]
Hey @tradinworld,

Seems like you got the solution, can you share the solution over here.

**Comment by tradinworld** [comment]
@mehboob-dev sorry for late reply. i am yet to find solution for this. i think dynamic updates to legend is not supported for marker(), it is currently supported only for lines and default ohlcv values. 
so i was just proposing to add a new feature to show marker values in the legend . 
thanks !

@louisnw01 Appreciate your help on this!

**Comment by louisnw01** [comment]
I'm not entirely sure what you're after; could you share more information?

Louis
