### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by brusand** [louisnw01/lightweight-charts-python#339]
### Expected Behavior

        self.chart = Chart(toolbox=False, inner_width=1, inner_height=0.5)
        self.chart.legend(visible=True, font_size=14)
        self.chart_ha = self.chart.create_subchart('bottom')
        self.topics = []

    def create_subchart(self, position='bottom'):
        chart2 = self.chart.create_subchart('bottom', width=1, height=0.5)
        return chart2

sub chart on the width 1 take all the width
<img width="831" alt="Capture d’écran 2024-04-22 à 21 01 45" src="https://github.com/louisnw01/lightweight-charts-python/assets/1648561/e06314b5-c735-4f9e-913f-04f7fdfed32d">

### Current Behaviour

only take the half of width

### Reproducible Example

```python
from lightweight_charts import Chart
        
chart = Chart(toolbox=False, inner_width=1, inner_height=0.5)
chart.legend(visible=True, font_size=14)
chart2 = chart.create_subchart('bottom', width=1, height=0.5)
chart.show(block=True)
```

### Environment

```markdown
- OS: mac
- Library: last version
```

**Comment by louisnw01** [comment]
Unable to reproduce, do you get the same result with this code? 

```python
from lightweight_charts import Chart
import pandas as pd

if __name__ == '__main__':
    df = pd.read_csv('path/to/ohlcv.csv')
    chart = Chart(toolbox=False, inner_width=1, inner_height=0.5)
    chart.legend(visible=True, font_size=14)
    chart2 = chart.create_subchart('bottom', width=1, height=0.5)
    chart.set(df)
    chart2.set(df)
    chart.show(block=True)
```
