### ISSUE TITLE
Changing settings for indicators

### ISSUE THREAD

**Issue by Sirut** [louisnw01/lightweight-charts-python#340]
### Description

It's probably already been asked, and maybe it's a feature we'd all like and maybe someone found a workaroud.

But there would be a method to change the settings of an indicator via GUI? Even reloading the entire window. 

I'm currently working with the basic code provided in the examples linked to some dataframes from CSV.
What I'm trying to figure out is how I could change an SMA setting without touching the code every time.

Many thanks to anyone who wants to contribute to the discussion

**Comment by brusand** [comment]
and if you add each indicator on the topbar as button ? then when you click on it you can add dedicated forms no ?

**Comment by Sirut** [comment]
> and if you add each indicator on the topbar as button ? then when you click on it you can add dedicated forms no ?

Well, yes this seems to be a solution. It hadn't occurred to me. I'll try to do some tests and see what comes out. thanks for the advice

**Comment by Tapanhaz** [comment]
You can maintain a dict with the line object and params for this type of indicator.  But I didn't find any subchart delete method (for indicators like rsi.). And not able to show horizontal lines in those charts (using pyqt5).
