### ISSUE TITLE
subscribeClick 

### ISSUE THREAD

**Issue by sbgmicromax** [louisnw01/lightweight-charts-python#343]
### Description

 Need to get the value and time of the series from the point of click, for further calculation purpose in the strategy

**Comment by emma-uw** [comment]
Hey, this been posted previously somewhere around here and I used it since then.
```
def subscribe_click(chart, *, callback):
    js = (
        'function clickHandler(param) {'
        'if (!param.point) {'
        'return;'
        '}'
        f'const time = {chart.id}.chart.timeScale().coordinateToTime(param.point.x);'
        f'const price = {chart.id}.series.coordinateToPrice(param.point.y);'
        'const data = JSON.stringify({time: time, price: price});'
        'window.callbackFunction(`on_click_~_${data}`);'
        '}'
        f'{chart.id}.chart.subscribeClick(clickHandler);'
    )

    def decorated_callback(data):
        data = json.loads(data)
        data = {
            'timestamp': pd.to_datetime(data['time'], unit='s'),
            'price': data['price'],
        }
        return callback(data, chart, chart.candle_data)

    chart.win.handlers['on_click'] = decorated_callback
    chart.win.run_script(js)
```

`subscribe_click(chart, callback=on_chart_click)`

**Comment by Iss-in** [comment]
hey @emma-uw any idea on how to exit that callback state ? 
once i trigger the function using a topbar switcher state, the click feed keep giving information on clicks, even if i change that switcher's state

**Comment by emma-uw** [comment]
@Iss-in Hey. Hard to tell what you meant without looking into the implementation. But there is a new built-in function in version 2.0. Maybe it will work better for you?

```
def on_chart_click(chart, timestamp, price):
    print(chart, timestamp, price)
        
chart.events.click += on_chart_click
```

**Comment by Iss-in** [comment]
can you please explain how this works ?

simply using that code , and clicking on graph doesnt do anything

**Comment by Iss-in** [comment]
@emma-uw  can you please explain how this works ?

simply using that code , and clicking on graph doesnt do anything

**Comment by Iss-in** [comment]
actually scratch that, here is my implementation for a replay of graph 

```
chart.topbar.switcher('click', ('c1', 'c2'), default='c1',
                    func=on_click)
                    

def on_chart_click(chart, timestamp, price):
    print(chart, timestamp, price)
    dt_object = datetime.fromtimestamp(timestamp, tz=timezone.utc)
    dt_string = dt_object.strftime('%Y-%m-%d %H:%M:%S')

    print("Datetime string:", dt_string)
    ind = df[df['date'] == dt_string].index.tolist()[0]
    print(f"index to start replay is {ind} with timestamp {timestamp}")
    for i in range(ind,len(df.index)):
        df2 = df.head(i)
        time.sleep(2)
        chart.set(df2)
        state = chart.topbar['click'].value

        if state == 'c1':
            break
        print(state)

def on_click(chart):
    state = chart.topbar['click'].value
    if state == 'c2':
        print(f"start click")
        chart.events.click += on_chart_click
```

if i select state c2, and then click on graph, replay happens, but when change state back to c1, it doesnt stop
is there a way to accomplish this

**Comment by emma-uw** [comment]
@Iss-in That's because replay is running synchroniously, so until loop is running execution is blocked. You will need your replay function to run seperatly

**Comment by Iss-in** [comment]
thanks a lot, this helped :)
