### ISSUE TITLE
[BUG] PySide6 and Candlestick.update_from_tick

### ISSUE THREAD

**Issue by Nynoko228** [louisnw01/lightweight-charts-python#346]
### Expected Behavior

Hi all.
I'm trying to update my chart, namely the last candle using the update_from_tick() method. I use PySide6 as an alternative GUI and when I try to update the last candle data, my program simply stops working (crashes). I decided to use PyQt5 instead of PySide6 and the update_from_tick() method began to work correctly. I realized that the program tries to execute self.run_script() in the update() method and fails and then exits the program.

### Current Behaviour

Stopping (crashing) the program execution and instead of the updated candle the error: "Process finished with exit code -2147483645"

### Reproducible Example

```python
# ohlc.csv and ticks.csv from example №3 3_tick_data
import threading
from time import sleep

import pandas as pd
from PySide6.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget

from lightweight_charts.widgets import QtChart

def update_candle():
    for i, tick in df2.iterrows():
        chart.update_from_tick(tick)
        sleep(0.03)

app = QApplication([])
window = QMainWindow()
layout = QVBoxLayout()
widget = QWidget()
widget.setLayout(layout)

df1 = pd.read_csv('ohlc.csv') 

# Columns: time | price
df2 = pd.read_csv('ticks.csv')

window.resize(800, 500)
layout.setContentsMargins(0, 0, 0, 0)

chart = QtChart(widget)

chart.set(df1)

layout.addWidget(chart.get_webview())

window.setCentralWidget(widget)
window.show()

thread = threading.Thread(target=update_candle)
thread.start()

app.exec_()
```

### Environment

```markdown
- OS: Windows 10
- Library: 1.0.20
```

**Comment by louisnw01** [comment]
Hey,

Charts are not thread-safe.

You'll have to use asyncio in order to achieve this.

Louis

**Comment by Nynoko228** [comment]
> Hey,
> 
> Charts are not thread-safe.
> 
> You'll have to use asyncio in order to achieve this.
> 
> Louis

**Comment by Nynoko228** [comment]
> Hey,
> 
> Charts are not thread-safe.
> 
> You'll have to use asyncio in order to achieve this.
> 
> Louis

Hi Louis, I am trying my code with PyQt5 and it works but thank you for your comment and one more "bug": if I have PyQt5 and PySide6 downloaded and they are in site-packages and I decide to use PySide6 in my project, then I will receive an error, since the chart will use PyQt5, not PySide6

**Comment by Nynoko228** [comment]
> Hey,
> 
> Charts are not thread-safe.
> 
> You'll have to use asyncio in order to achieve this.
> 
> Louis

And how I can do this? I try this code but the result is just as bad
```
# ohlc.csv and ticks.csv from example №3 3_tick_data
import asyncio

import pandas as pd
from PySide6.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget

from lightweight_charts.widgets import QtChart

async def update_candle():
    for i, tick in df2.iterrows():
        print(tick)
        chart.update_from_tick(tick)
        await asyncio.sleep(0.03)

app = QApplication([])
window = QMainWindow()
layout = QVBoxLayout()
widget = QWidget()
widget.setLayout(layout)

df1 = pd.read_csv('ohlc.csv')

# Columns: time | price
df2 = pd.read_csv('ticks.csv')

window.resize(800, 500)
layout.setContentsMargins(0, 0, 0, 0)

chart = QtChart(widget)

chart.set(df1)

layout.addWidget(chart.get_webview())

window.setCentralWidget(widget)
window.show()

asyncio.run(update_candle())

app.exec_()
```

**Comment by Nynoko228** [comment]
> Hey,
> 
> Charts are not thread-safe.
> 
> You'll have to use asyncio in order to achieve this.
> 
> Louis

And, please, try this code:
```
# ohlc.csv and ticks.csv from example №3 3_tick_data
import threading
from time import sleep

import pandas as pd
from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget

from lightweight_charts.widgets import QtChart

def update_candle():
    for i, tick in df2.iterrows():
        chart.update_from_tick(tick)
        sleep(0.03)

app = QApplication([])
window = QMainWindow()
layout = QVBoxLayout()
widget = QWidget()
widget.setLayout(layout)

df1 = pd.read_csv('ohlc.csv')

# Columns: time | price
df2 = pd.read_csv('ticks.csv')

window.resize(800, 500)
layout.setContentsMargins(0, 0, 0, 0)

chart = QtChart(widget)

chart.set(df1)

layout.addWidget(chart.get_webview())

window.setCentralWidget(widget)
window.show()

thread = threading.Thread(target=update_candle)
thread.start()

app.exec_()
```
This code will work fine and update the Chart, but as soon as I change the module from PyQt5 to PySide6, everything stops working and the program just exits with the error: "Process finished with exit code -2147483645"

**Comment by louisnw01** [comment]
I believe this is what you'll need: https://doc.qt.io/qtforpython-6/PySide6/QtAsyncio/index.html
