### ISSUE TITLE
How are you achieving infinite history?

### ISSUE THREAD

**Issue by amirzamli** [louisnw01/lightweight-charts-python#348]
### Question

Hello, im curious if anyone has been able to achieve the infinite history function from lightweight charts:
https://tradingview.github.io/lightweight-charts/tutorials/demos/infinite-history

I have tried to use Charts.update function but it only works when you add newer data, not data that is older than the earliest bar, then nothing happens as there is a silent error in the javascript environment (I suspect)

Edit: My current approach is using Charts.set and handling the data concatenation myself. It seems however that there should be a more efficient approach to this that im missing?

**Comment by louisnw01** [comment]
Unfortunately not; this is a limitation of the original library.

Louis

**Comment by sebinho** [comment]
@amirzamli I am having issues trying to use the `set` method to prepend data to my pandas frame. Could you share a code sample on how you are doing it?
when I start scrolling past the current valid dataset, it starts looping many times over...

Thanks a lot

**Comment by sebinho** [comment]
@amirzamli I looked at your forked repo and I could find a useful commit you made. It seems to be much more stable on my side now.
Here is the commit for anyone who might encounter similar problems:
https://github.com/louisnw01/lightweight-charts-python/commit/721ec47383d3eb0d27dd0a661917b9e7e3f8ee85

**Comment by amirzamli** [comment]
Happy you found it useful, i never got the infinite history part working fully so that was the hack i went for :)
