### ISSUE TITLE
[BUG] Drawings disappear

### ISSUE THREAD

**Issue by cilindro5432** [louisnw01/lightweight-charts-python#349]
### Expected Behavior

https://github.com/louisnw01/lightweight-charts-python/assets/150294229/8c3d73f5-de4f-4973-86ec-a29bc086c97d

### Current Behaviour

 when I use api for tick data. Static data works well, drawings stay in place

### Reproducible Example

```python
NA
```

### Environment

```markdown
OS: macOS 13.2
Library: 1.0.16.2
```

**Comment by louisnw01** [comment]
Please provide a minimal reproducible example, perhaps based on the `3_tick_data` example.

**Comment by 97-ozzy** [comment]
bro how you even made drawaings? when i set toolbox=True chart doesnt even load

**Comment by Nynoko228** [comment]
Greetings[cilindro5432](https://github.com/cilindro5432). Just like you, I use lightweight-charts-python to create stock charts. I saw your Issue and wanted to know: "How did you add a rectangular shape to the toolbox?" Unfortunately, I don’t know the Java Script programming language well and I can’t do it myself just like you. Could you share the code to create this shape from the toolbox, please?
