### ISSUE TITLE
Request for Python 3.8 Support

### ISSUE THREAD

**Issue by stefanstoeckigt** [louisnw01/lightweight-charts-python#35]
Hello,

I'm writing to request support for Python 3.8 in your Lightweight Charts Python project.

I have been using your project and find it very useful. However, I would like to use it along with QuantConnect, which currently only supports Python 3.8.

I have done some preliminary testing on my local environment, and it seems that the library functions well with Python 3.8. This preliminary testing was not exhaustive though, so it would be great if you could confirm this compatibility.

I believe Python 3.8 support would make your project even more helpful to a broader audience, and I am eager to hear your thoughts on this.

Thank you for your consideration and for all your work on this project.

Best regards

**Comment by louisnw01** [comment]
Hi!

The library should work on 3.8; I had a look through the breaking changes and there doesn't seem to be anything obvious which would prevent it from working.

I'll take a closer look and get back to you, in the mean time if you find any bugs let me know.

Louis

**Comment by louisnw01** [comment]
Hey,

After some tests it appears the library runs fine on 3.8, so I have updated the package to reflect this.

Louis
