### ISSUE TITLE
Hotkey combination with arrow key

### ISSUE THREAD

**Issue by longtu02** [louisnw01/lightweight-charts-python#361]
### Question

Quick question, is there a way to specify hotkey with an arrow key (e.g. Control-Left or Control-Right)? Thanks very much!

**Comment by amirzamli** [comment]
This might help: https://github.com/louisnw01/lightweight-charts-python/issues/308

**Comment by longtu02** [comment]
> This might help: #308

Thank you @amirzamli very much!!!
