### ISSUE TITLE
Flash and then black screen with nothing shown in the chart 

### ISSUE THREAD

**Issue by qfweiwei** [louisnw01/lightweight-charts-python#364]
### Question

Hi Team,

I'm using lightweight-charts-python on Ubuntu 22.04. After I ran the code listed in Code example, it just popped up a window, a quick flash, and then end up with black screen with nothing shown in the chart.
![image](https://github.com/louisnw01/lightweight-charts-python/assets/22325743/31c96481-7168-4146-bd1d-ec55e2c6acbb)

After I closed window, it does not exit the application. I have press Ctrl+C to exit. Below is the output from Ctrl+C:
![image](https://github.com/louisnw01/lightweight-charts-python/assets/22325743/0235c60f-fda6-4f49-bab7-56fa0079c872)

Below is output from pip list:
Package                          Version
------------------                   -----------
bottle                              0.12.25
lightweight-charts       1.0.21
numpy                           1.26.4
packaging                     24.0
pandas                          2.2.2
pip                                  24.0
proxy_tools                   0.1.0
PyQt5                            5.15.10
PyQt5-Qt5                    5.15.2
PyQt5-sip                     12.13.0
PyQtWebEngine         5.15.6
PyQtWebEngine-Qt5  5.15.2
python-dateutil           2.9.0.post0
pytz                               2024.1
pywebview                   5.1
QtPy                              2.4.1
setuptools                   58.1.0
six                                1.16.0
typing_extensions     4.11.0
tzdata                          2024.1

My Python version is 3.9.18. I installed Pywebview with "pip install pywebview[qt]".

Would you please help and let me know if you need more details of the issue?

Thanks,
wei

### Code example

```python
import pandas as pd
from lightweight_charts import Chart

PYWEBVIEW_GUI="qt"

if __name__ == '__main__':
    chart = Chart(debug=True)

    # Columns: time | open | high | low | close | volume
    df = pd.read_csv('ohlcv.csv')

    chart.layout(background_color='#090008', text_color='#FFFFFF', font_size=16,
                 font_family='Helvetica')

    chart.candle_style(up_color='#00ff55', down_color='#ed4807',
                       border_up_color='#FFFFFF', border_down_color='#FFFFFF',
                       wick_up_color='#FFFFFF', wick_down_color='#FFFFFF')

    chart.volume_config(up_color='#00ff55', down_color='#ed4807')

    chart.watermark('1D', color='rgba(180, 180, 240, 0.7)')

    chart.crosshair(mode='normal', vert_color='#FFFFFF', vert_style='dotted',
                    horz_color='#FFFFFF', horz_style='dotted')

    chart.legend(visible=True, font_size=14)

    chart.set(df)

    chart.show(block=True)
```

**Comment by Tapanhaz** [comment]
> ### Question
> 
> Hi Team,
> 
> I'm using lightweight-charts-python on Ubuntu 22.04. After I ran the code listed in Code example, it just popped up a window, a quick flash, and then end up with black screen with nothing shown in the chart. ![image](https://private-user-images.githubusercontent.com/22325743/331768620-31c96481-7168-4146-bd1d-ec55e2c6acbb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMTEyOTMsIm5iZiI6MTcxNjAxMDk5MywicGF0aCI6Ii8yMjMyNTc0My8zMzE3Njg2MjAtMzFjOTY0ODEtNzE2OC00MTQ2LWJkMWQtZWM1NWUyYzZhY2JiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDA1NDMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMDQ0MDVjNGI0NmU5Mjk5NGNiZmIwMzE5NDc0MTE5OTBjNmU2OTQ2N2I0NDBiYzI2ZTQ0NGU5NWVlZTJkYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RgWDFihrg7RFQ9ifpHiGoeqa5GgetNnPjrp1KWfnRis)
> 
> Below is output from pip list: Package Version
> 
> bottle 0.12.25 lightweight-charts 1.0.21 numpy 1.26.4 packaging 24.0 pandas 2.2.2 pip 24.0 proxy_tools 0.1.0 PyQt5 5.15.10 PyQt5-Qt5 5.15.2 PyQt5-sip 12.13.0 PyQtWebEngine 5.15.6 PyQtWebEngine-Qt5 5.15.2 python-dateutil 2.9.0.post0 pytz 2024.1 pywebview 5.1 QtPy 2.4.1 setuptools 58.1.0 six 1.16.0 typing_extensions 4.11.0 tzdata 2024.1
> 
> My Python version is 3.9.18. I installed Pywebview with "pip install pywebview[qt]".
> 
> Would you please help and let me know if you need more details of the issue?
> 
> Thanks, wei
> ### Code example
> 
> ```python
> import pandas as pd
> from lightweight_charts import Chart
> 
> PYWEBVIEW_GUI="qt"
> 
> if __name__ == '__main__':
>     chart = Chart(debug=True)
> 
>     # Columns: time | open | high | low | close | volume
>     df = pd.read_csv('ohlcv.csv')
> 
>     chart.layout(background_color='#090008', text_color='#FFFFFF', font_size=16,
>                  font_family='Helvetica')
> 
>     chart.candle_style(up_color='#00ff55', down_color='#ed4807',
>                        border_up_color='#FFFFFF', border_down_color='#FFFFFF',
>                        wick_up_color='#FFFFFF', wick_down_color='#FFFFFF')
> 
>     chart.volume_config(up_color='#00ff55', down_color='#ed4807')
> 
>     chart.watermark('1D', color='rgba(180, 180, 240, 0.7)')
> 
>     chart.crosshair(mode='normal', vert_color='#FFFFFF', vert_style='dotted',
>                     horz_color='#FFFFFF', horz_style='dotted')
> 
>     chart.legend(visible=True, font_size=14)
> 
>     chart.set(df)
> 
>     chart.show(block=True)
> ```

I got some problem with wayland. Try Xorg

**Comment by Tapanhaz** [comment]
I got some similar problem with wayland. Try Xorg.

**Comment by qfweiwei** [comment]
Actually I am using X11.
![image](https://github.com/louisnw01/lightweight-charts-python/assets/22325743/0e8a2afe-5fdf-4d76-9706-965cef7cb926)

**Comment by amirzamli** [comment]
downgrade pywebview to version 4.3
`pip install pywebview==4.3`

**Comment by Tapanhaz** [comment]
> Actually I am using X11. ![image](https://private-user-images.githubusercontent.com/22325743/331769282-0e8a2afe-5fdf-4d76-9706-965cef7cb926.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMjkxNjIsIm5iZiI6MTcxNjAyODg2MiwicGF0aCI6Ii8yMjMyNTc0My8zMzE3NjkyODItMGU4YTJhZmUtNWZkZi00ZDc2LTk3MDYtOTY1Y2VmN2NiOTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDEwNDEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNTg3ZDdiNTA1MTUzN2M3Zjg2ODA5MTBmMmIyYjAzNzc0NzdhNWUwMDRkMWJhNDZiODVjYTI3ZDliZThhMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ToH53UiR4CLxOp5nvBJb7a747aWvGYUBsT0wFGUgDX8)

Are you installing pyqt5/ pyqtwebengine through pip ? Try uninstalling and install using apt. The pip package of qtwebengine have some known issues.

**Comment by Tapanhaz** [comment]
> Actually I am using X11. ![image](https://private-user-images.githubusercontent.com/22325743/331769282-0e8a2afe-5fdf-4d76-9706-965cef7cb926.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwMjk5MDIsIm5iZiI6MTcxNjAyOTYwMiwicGF0aCI6Ii8yMjMyNTc0My8zMzE3NjkyODItMGU4YTJhZmUtNWZkZi00ZDc2LTk3MDYtOTY1Y2VmN2NiOTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDEwNTMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZGFmMmEyYWRlZTU0MjAwYTU3MmJiZTdkNGM1ZWU0MmUwZGE5ODJmOTllMjFmZWZjZDMzMzEyNmQ1NGY1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.G9g57yr54rSwrhzEDVqKpv_CVVlsviR3Zs99906tWdY)

I am using ubuntu, python version 3.12 .  Try uninstalling the pip packages for everything starts with pyqt and then install pyqt5 + qtwebengine using apt.. The pip package of pyqtwebengine may be causing problem.

**Comment by qfweiwei** [comment]
> downgrade pywebview to version 4.3 `pip install pywebview==4.3`

Thanks for you advice! I tried to downgrade pywebview to version 4.3, and got below error when running code.
![image](https://github.com/louisnw01/lightweight-charts-python/assets/22325743/75c24808-aa99-4ec7-9eb9-1b1141a1297e)

**Comment by amirzamli** [comment]
I havent worked with Qt but you might need to downgrade some Qt packages too is my guess. Try searching for old issues on this projekt and see if anyone has has similar issues

**Comment by qfweiwei** [comment]
Thank you!
