### ISSUE TITLE
Sync crosshair from a subchart to the main chart

### ISSUE THREAD

**Issue by ek-ex** [louisnw01/lightweight-charts-python#365]
### Question

I have 1 chart and 2 subcharts. The 2 sub_charts are set to sync=True. When navigating on the main chart, the crosshairs between the sub_charts are synced without issues. however, when navigating on the sub_charts, there is no crosshairs present on the other charts. 

[Screencast from 05-17-2024 11:28:15 PM.webm](https://github.com/louisnw01/lightweight-charts-python/assets/8320665/582aaf79-d03b-483c-aeed-db39ad775051)

**Comment by ironhak** [comment]
+1

**Comment by louisnw01** [comment]
Closing as dupe of #366
