### ISSUE TITLE
[BUG] horizontal_line takes a long time to render

### ISSUE THREAD

**Issue by ek-ex** [louisnw01/lightweight-charts-python#367]
### Expected Behavior

The chart should load equally fast with or without the horizontal line. 
[Screencast from 05-17-2024 11:53:57 PM.webm](https://github.com/louisnw01/lightweight-charts-python/assets/8320665/651705c9-e408-4e16-9d73-b2a064be7e36)

### Current Behaviour

Setting a horizontal line in the chart causes the chart to take a very long time to render. 

### Reproducible Example

```python
import pandas as pd
from lightweight_charts import Chart

if __name__ == '__main__':
    chart = Chart()
    chart.horizontal_line(price=180)

    df = pd.read_csv('ohlcv.csv')
    chart.set(df)

    chart.show(block=True)
```

### Environment

```markdown
- OS:
- Library:
```

**Comment by louisnw01** [comment]
Hey @ek-ex,

You'll need to downgrade to pywebview 4.4.1 for the timebeing; i have published a hotfix.

Louis
