### ISSUE TITLE
[BUG] Cant add ray_lines to charts with only lines. 

### ISSUE THREAD

**Issue by ek-ex** [louisnw01/lightweight-charts-python#368]
### Expected Behavior

I should be able to add trend_lines and ray_lines to chars with only lines. 

### Current Behaviour

The ray_line is not present on the chart that contain only lines. 
![Screenshot from 2024-05-18 00-12-23](https://github.com/louisnw01/lightweight-charts-python/assets/8320665/47694595-bf9d-4917-ad4f-ecbcd79baa74)

### Reproducible Example

```python
import pandas as pd
from lightweight_charts import Chart

if __name__ == '__main__':
    chart = Chart(inner_width=0.5, inner_height=0.5)
    chart2 = chart.create_subchart(position='right', width=0.5, height=0.5)
    chart3 = chart.create_subchart(position='left', width=0.5, height=0.5)
    chart4 = chart.create_subchart(position='right', width=0.5, height=0.5)

    chart.watermark('1')
    chart2.watermark('2')
    chart3.watermark('3')
    chart4.watermark('4')

    df = pd.read_csv('ohlcv.csv')
    chart.set(df)
    chart2.set(df)
    chart3.set(df)

    open_line = chart4.create_line("open")
    open_line.set(df)

    chart.ray_line(start_time=0, value=180)
    chart4.ray_line(start_time=0, value=180)

    chart.show(block=True)
```

### Environment

```markdown
- OS:
- Library:
```

**Comment by schroederjoa** [comment]
Horizontal lines do not work as well. I noticed when I was trying to plot 30/70 horizontal lines on a RSI pane.
chart4.horizontal_line(price=160, color='yellow')

**Comment by louisnw01** [comment]
Fixed in latest version.

Louis
