### ISSUE TITLE
 chart.marker method throwing error in version 2 whereas in main version it is working fine

### ISSUE THREAD

**Issue by anilwarbhe** [louisnw01/lightweight-charts-python#371]
### Question

 chart.marker method throwing error in version 2 whereas in main version it is working fine

**Comment by anilwarbhe** [comment]
window.szjsndno.markers.push({
                time: 2024-04-18 15:05:00,
                position: 'aboveBar',
                color: 'red',
                shape: 'arrowDown',
                text: 'SEXIT 350.6',
                id: 'window.pvxkbfao'
                });
            window.szjsndno.series.setMarkers(window.szjsndno.markers)

        window.szjsndno.series.applyOptions({
            lastValueVisible: true,
            priceLineVisible: true,
            title: 'PL: 59.7',
        })',
error -> SyntaxError[4:33]
Unexpected number '10'. Expected '}' to end an object literal.

**Comment by louisnw01** [comment]
Fixed in the latest push to 2.0

btw, Thank you for your help with 2.0! I'm trying to roll it out asap and it really helps having people find things i miss.

Louis
