### ISSUE TITLE
Disable volume char/subchart

### ISSUE THREAD

**Issue by LouSparfell** [louisnw01/lightweight-charts-python#372]
### Question

Hi,

How can we disable the volume chart on the "main" chart and on the subcharts?
I have tried volume_enabled=False to Chart() and create_subchart() without success it throws an error.

Any idea how to do it? 

Regards,

Lou

**Comment by MateKristof** [comment]
If you just drop the volume column from the dataframe it will not appear on the chart. This will "disable" the volume. 
```python
df.drop(columns=['volume'], inplace=True)
```
