### ISSUE TITLE
Get data from charts upon mouse move and click

### ISSUE THREAD

**Issue by gokulchittaranjan** [louisnw01/lightweight-charts-python#378]
### Description

The events currently supported in utils.py does not include mouse_move and click.
This is useful, for example, to get the OHLC data upon click, so that external action can be performed.

### Code example

```python
figures[idx].events.click += self.ui_on_graph_click

Should, for example, call the method self.ui_on_graph_click upon clicking the graph.
```

### Method of implementation

Add relevant JS method to utils.py

**Comment by gokulchittaranjan** [comment]
@louisnw01 Created PR https://github.com/louisnw01/lightweight-charts-python/pull/377

**Comment by louisnw01** [comment]
implemented in latest version.

Louis

**Comment by gokulchittaranjan** [comment]
Hi Louis, Thanks for the great package. I did get the latest version. It does not have the entire functionality that's in the PR - please feel free to reject it if it is not in line with your roadmap.

My use case is to get the OHLC data in addition to the price at a particular y-location.
I have merged your changes with mine in my fork at:
https://github.com/gokulchittaranjan/lightweight-charts-python
