### ISSUE TITLE
404 Not Found error when installing version 2.0

### ISSUE THREAD

**Issue by lukaIvanic** [louisnw01/lightweight-charts-python#379]
### Expected Behavior

Following the process of uninstall my lightweight-charts version 1.0.20 and upgrading it to the current latest 1.0.22 and checking that nothing was broken I tried installing the 2.0 version for the needed box plotting functionality. 

With a successful install, the script should've ran normally and it should've displayed a chart.

### Current Behaviour

However, while the script showed no error, the chart window appeared as:
![image](https://github.com/louisnw01/lightweight-charts-python/assets/61480190/5d569ee8-88bb-43ca-bdc5-24a38670b75e)

After closing the faulty chart window, and enabling debug while initializing Chart beforehand, this error message was printed:

`Bottle v0.12.25 server starting up (using ThreadedAdapter())...
Listening on http://127.0.0.1:50602/
Hit Ctrl-C to quit.

127.0.0.1 - - [25/May/2024 15:09:25] "GET /test.html HTTP/1.1" 404 726
127.0.0.1 - - [25/May/2024 15:09:25] "GET /favicon.ico HTTP/1.1" 404 728
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\site-packages\lightweight_charts\chart.py", line 89, in loop
    window.evaluate_js(arg)
  File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\site-packages\webview\window.py", line 50, in wrapper
    return function(self, *args, **kwargs)
  File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\site-packages\webview\window.py", line 455, in evaluate_js
    raise JavascriptException(result)
webview.errors.JavascriptException: {'name': 'SyntaxError', 'stack': 'SyntaxError: Unexpected number\n    at <anonymous>:4:21', 'message': 'Unexpected number'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\site-packages\lightweight_charts\chart.py", line 94, in loop
    raise JavascriptException(f"\n\nscript -> '{arg}',\nerror -> {msg['name']}[{msg['line']}:{msg['column']}]\n{msg['message']}")
KeyError: 'line'
`

### Reproducible Example

```python
The same issue appeared with any chart I used, but it also appeared with this simple sample script:

from lightweight_charts import Chart

def main():

    chart = Chart(debug=True)
    chart.show(block=True)

if __name__ == '__main__':
    main()
```

### Environment

```markdown
- OS: Windows 10
- Library:
```

**Comment by louisnw01** [comment]
This seems to be related to how you have installed the 2.0 branch; try reinstalling inside a clean venv, following the instructions given in the version 2.0 announcement and let me know if you get the same issue.

**Comment by lukaIvanic** [comment]
I tried installing it in a new project, and got some "subprocess issues", but I forgot to mention how I install v2.0 so I will do that first.

I cloned the 2.0 branch (git close -b 2.0 link..)

and then I pip installed it

pip install local/path/to/library

Is this a correct way of doing it?

**Comment by louisnw01** [comment]
> I tried installing it in a new project, and got some "subprocess issues", but I forgot to mention how I installed v2.0 so I will do that first.
> 
> I cloned the 2.0 branch: git clone -b 2.0 htttp..
> 
> and then I pip installed it
> 
> pip install local/path/to/library
> 
> Is this a correct way of doing it?

By pip install do you mean you ran `pip install lightweight_charts` or `pip install -e local/path/to/lightweight_charts`?

You won't want to install the version hosted on pypi, just the local version you cloned.

**Comment by lukaIvanic** [comment]
I used exactly:
pip install -e C:\Users\Luka\Desktop\lightweight-chartsv2\lightweight-charts-python

I tried cloning the v2.0 as a branch from git, and I tried to download zip now and install it like that. I'm still getting the same behaviour, I think the error message is a bit different now tho.

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\site-packages\lightweight_charts\chart.py", line 89, in loop
    window.evaluate_js(arg)
  File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\site-packages\webview\window.py", line 50, in wrapper
    return function(self, *args, **kwargs)
  File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\site-packages\webview\window.py", line 455, in evaluate_js
    raise JavascriptException(result)
webview.errors.JavascriptException: {'name': 'ReferenceError', 'stack': 'ReferenceError: Handler is not defined\n    at eval (eval at <anonymous> (:4:29), <anonymous>:3:23)\n    at <anonymous>:4:29', 'message': 'Handler is not defined'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\site-packages\lightweight_charts\chart.py", line 94, in loop
    raise JavascriptException(f"\n\nscript -> '{arg}',\nerror -> {msg['name']}[{msg['line']}:{msg['column']}]\n{msg['message']}")
KeyError: 'line'

**Comment by louisnw01** [comment]
You need to install the `lightweight_charts` folder within the `lightweight-charts-python` folder.

**Comment by armeya25** [comment]
@lukaIvanic 
Are tou using qt5/qt6 for pywebview or using pygobject,
I was having same issue,
Try pip install pywebview[gtk]

**Comment by lukaIvanic** [comment]
> You need to install the `lightweight_charts` folder within the `lightweight-charts-python` folder.

I believe I am doing that, if I try this: 
pip install C:\Users\Luka\Desktop\lightweight-chartsv2\secondtry\lightweight-charts-python-2.0\lightweight_charts

this occurs:
ERROR: Directory 'C:\\Users\\Luka\\Desktop\\lightweight-chartsv2\\secondtry\\lightweight-charts-python-2.0\\lightweight_charts' is not installable. Neither 'setup.py' nor 'pyproject.toml'
 found.


If I try this:
pip install C:\Users\Luka\Desktop\lightweight-chartsv2\secondtry\lightweight-charts-python-2.0

It is installed without any issues, except the runtime error.







> @lukaIvanic Are you using qt5/qt6 for pywebview or using pygobject, I was having same issue, Try pip install pywebview[gtk]

I tried running the pip install command you provided but it does not seem it fixed the issue. I don't really understand what you're asking me either, meaning I didn't do anything explicitly with pywebview.

**Comment by Tapanhaz** [comment]
> I used exactly: pip install -e C:\Users\Luka\Desktop\lightweight-chartsv2\lightweight-charts-python
> 
> I tried cloning the v2.0 as a branch from git, and I tried to download zip now and install it like that. I'm still getting the same behaviour, I think the error message is a bit different now tho.
> 
> Exception in thread Thread-2: Traceback (most recent call last): File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\site-packages\lightweight_charts\chart.py", line 89, in loop window.evaluate_js(arg) File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\site-packages\webview\window.py", line 50, in wrapper return function(self, *args, **kwargs) File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\site-packages\webview\window.py", line 455, in evaluate_js raise JavascriptException(result) webview.errors.JavascriptException: {'name': 'ReferenceError', 'stack': 'ReferenceError: Handler is not defined\n at eval (eval at (:4:29), :3:23)\n at :4:29', 'message': 'Handler is not defined'}
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner self.run() File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run self._target(*self._args, **self._kwargs) File "C:\Users\Luka\AppData\Local\Programs\Python\Python39\lib\site-packages\lightweight_charts\chart.py", line 94, in loop raise JavascriptException(f"\n\nscript -> '{arg}',\nerror -> {msg['name']}[{msg['line']}:{msg['column']}]\n{msg['message']}") KeyError: 'line'

Can you try it on a recent python version? (3.11/3.12) ..  and first try to make the .whl and install using that wheel (run -> python setup.py bsdist_wheel    it will create the whl under dist folder)

**Comment by armeya25** [comment]
@lukaIvanic for me,
After installing lightweight charts,
I first get " you need to install pyqt or gtk" error,
After installing "pyqt" I also get "module gi not found" error after installing "pygobject" I get "either black black or white scree", after all these hassles  I got "what you are facing now", maybe there is something missing in dependency in your installation,

Also if you install by "pip install -e package" and you remove source from where you installed package you also have error.
For me above pip command it doesn't copy source also,
So may be check all these things
