### ISSUE TITLE
Jupyter chart loading Error But No error while loading normal chart 

### ISSUE THREAD

**Issue by dysai1234** [louisnw01/lightweight-charts-python#38]
``` 
# Yahoo data to show 
import yfinance as yf
from lightweight_charts import Chart,JupyterChart

ticker = 'AAPL'
start = '2022-01-01'
end = '2023-01-01'
df = yf.download(ticker, start=start, end=end)

df.rename(columns = {
                     'Open':'open',
                     'High':'high',
                    'Low':'low',
                    'Close':'close',
                    'Volume':'volume'}, inplace = True)
df['time']=df.index
chart = Chart()

# Columns: | time | open | high | low | close | volume (if volume is enabled) |
chart.set(df)

chart.show()
```

![image](https://github.com/louisnw01/lightweight-charts-python/assets/48354881/133cc4d2-e017-45c6-9504-ab30eba49ef6)

**Comment by dysai1234** [comment]
I was using above code to show chart But It is now working for jupyter chart

**Comment by dysai1234** [comment]
Also can you add some changes so I dont need to rename the columns

**Comment by louisnw01** [comment]
Hi,

Glad you got it working. I'm going to close this thread; if you could open a new issue in regard to the renaming of columns that would be great, as it's best to keep one topic per post.

Thanks!
