### ISSUE TITLE
on_row_click function only has one argument

### ISSUE THREAD

**Issue by Aags26** [louisnw01/lightweight-charts-python#380]
### Question

on_row_click function is a callable called when a row is clicked in the table. The only argument it has is the 'row' object. Is there a way to have 'chart' as a second positional argument?
I am asking this becuase I intend to use chart object as function parameters instead of defining it globally.

### Code example

```python
def on_row_click(row):
   '''Code'''
   '''Cannot access chart object here unless defined globally'''

def init_chart():
   chart = Chart()
   table = chart.create_table(..., func=on_row_click) #Registering a callable
```

**Comment by louisnw01** [comment]
Hey @Aags26,

As tables exist more as their own 'chart' within the window, and they aren't really attached to a chart, I chose not to include it as an argument.

You could get around using a global variable by placing the row click callback within a class, with the chart defined as a class attribute.

Or, use a lambda function which passes the chart to the callback, eg

```python
func=lambda t: handle_row(chart, t)
```


Louis
