### ISSUE TITLE
[BUG] Using multiprocessing makes the chart not load and terminal stuck

### ISSUE THREAD

**Issue by ironhak** [louisnw01/lightweight-charts-python#381]
### Expected Behavior

I need to import multiprocessing for backesting optimisation purposes, when I insert the line
```
mp.set_start_method('fork',force=True) # Enable multi-threading
```
In my code, then the chart will not spawn.

### Current Behaviour

Does not work. 

### Reproducible Example

```python
import multiprocessing as mp

if __name__ == '__main__':
    
    # ------------------------------ Initalise Data ------------------------------ #
    
    mp.set_start_method('fork',force=True) # Enable multi-threading
    ticker = 'SPY'
    df = initialiseData(ticker)
    df = calculateIndicators(df,30)
    #print(df)
    
    df.set_index('Date', inplace=True)
    df.index = pd.to_datetime(df.index)

    
    plotChart(df)
```

### Environment

```markdown
- OS: 
- Library:
```

**Comment by louisnw01** [comment]
Hey @ironhak,

Why specifically do you need to use the `fork` spawn method?

**Comment by ironhak** [comment]
Hello, I'm using [backtesting.py](https://kernc.github.io/backtesting.py/) library to do my backtests, in order to enable multi-threading optimisation I found online that I have ti add that line of code before executing my code.

**Comment by louisnw01** [comment]
What OS are you on?

**Comment by ironhak** [comment]
I'm on MacOs 13 Ventura, sorry if I've not specified it before.

**Comment by louisnw01** [comment]
Ah, then this is unrelated to the lib. the fork spawn process is unsupported on macOS

**Comment by ironhak** [comment]
What do you mean unsupported? It works on my mac, I can clearly see on Activity Monitor the multi-threading in action

**Comment by louisnw01** [comment]
https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://docs.python.org/3/library/multiprocessing.html%23:~:text%3DChild%2520processes%2520no%2520longer%2520inherit,system%2520libraries%2520may%2520start%2520threads.&ved=2ahUKEwif-KL7sbiGAxWMWEEAHUrPCFwQFnoECBEQAw&usg=AOvVaw3Dm7cXeBv8Gt-AQMVRx4Ib
