### ISSUE TITLE
Line clickable legend is showing up without a name. 2.0 [BUG] 

### ISSUE THREAD

**Issue by amirzamli** [louisnw01/lightweight-charts-python#384]
### Expected Behavior

Line clickable legend is showing up with a name. 

### Current Behaviour

Line clickable legend is showing up without a name. 
![image](https://github.com/louisnw01/lightweight-charts-python/assets/13125633/88d2cadb-1a0f-4587-ad66-843389796a7b)

### Reproducible Example

```python
import pandas as pd
from lightweight_charts import Chart


chart = Chart()

df1 = pd.read_csv(f'./data/data2.csv')
chart.set(df1)

line_name = f"line_"
df1[line_name] = df1["high"]
line_ = chart.create_line(line_name)
line_.set(df1[["time", line_name]])


if __name__ == "__main__":
    chart.show(block=True)
```

### Environment

```markdown
- OS:
- Library: 2.0 cloned from: https://github.com/louisnw01/lightweight-charts-python/commit/a8a11efcf605e6a0d1245e8fa1ceec8ad49bbf65
```

**Comment by amirzamli** [comment]
My suggestion is to remove the automatic legend creation, or making it an option. Because I also have interest in making my own line groups that can be toggled together.
Thanks for your work and time!

**Comment by amirzamli** [comment]
I dont think its the name that is the problem, for some reason its not showing the price when the cursor moves either

**Comment by louisnw01** [comment]
Fixed in latest version; you need to use `chart.legend(True)` to view the legend.
