### ISSUE TITLE
In version 2.0 how to remove horizontal lines.

### ISSUE THREAD

**Issue by anilwarbhe** [louisnw01/lightweight-charts-python#389]
### Question

 chart.clear_horizontal_lines() throwing error. How to do it in version 2.0?

**Comment by louisnw01** [comment]
hey @anilwarbhe,

This will be a documentation error; I have removed the `clear_horizontal_lines` and `remove_horizontal_line` methods.

To delete a horizontal line, call its `delete()` method:

```python
horizontal_line = chart.horizontal_line(...)

horizontal_line.delete()
```

**Comment by fabrosky** [comment]
This is not a best practice. 
Imagine you have 4 subcharts and you need 4 horizontal_line in each one that need to be updated on every incoming event just like a bid/ask price.
You need to instantiate 16 horizontal_line every time, managing the objects, checking if they are instantiated or not and eventually delete one by one and recreate it.
With clear_horizontal_lines() you delete all line in one statement but most important you don't need to assign the object to 16 variable for future deletion.

**Comment by Fougl** [comment]
> This is not a best practice. Imagine you have 4 subcharts and you need 4 horizontal_line in each one that need to be updated on every incoming event just like a bid/ask price. You need to instantiate 16 horizontal_line every time, managing the objects, checking if they are instantiated or not and eventually delete one by one and recreate it. With clear_horizontal_lines() you delete all the lines in one statement but most important you don't need to assign the objects to 16 variable for future deletion.

You can save the horizontal lines into a dict, with prices as keys, and then delete them as needed, and create new ones. works for me.

hlines{}
hlines[19300]=chart.horizontal_line(...)
hlines[19300].delete()
etc
etc
