### ISSUE TITLE
[BUG] Characters not displaying properly

### ISSUE THREAD

**Issue by P-Lamont** [louisnw01/lightweight-charts-python#400]
### Expected Behavior

Characters to display properly

### Current Behaviour

![Untitled2](https://github.com/louisnw01/lightweight-charts-python/assets/99668684/069b1277-1012-456d-9d12-225091feeeeb)
![Untitled3](https://github.com/louisnw01/lightweight-charts-python/assets/99668684/dde95cfd-3cfe-47bc-83d2-95b70e05d4c8)

Just updated from version 1.0.20  to 2.01
 os: windows 10

1st image. Issues from complete app
2nd image. Issues from minimal example

### Reproducible Example

```python
import pandas as pd
from PyQt5.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget

from lightweight_charts.widgets import QtChart

app = QApplication([])
window = QMainWindow()
layout = QVBoxLayout()
widget = QWidget()
widget.setLayout(layout)

window.resize(800, 500)
layout.setContentsMargins(0, 0, 0, 0)
def sample(_):
    print(sample)
chart = QtChart(widget,toolbox=True)

df = pd.read_csv('ohlcv.csv')
df['date'] = pd.to_datetime(df['date'],dayfirst=True)
chart.topbar.menu(
    'timeframe', ('1min','3min', '5min', '15min','30min','1H','2H','4H','1D'), default='15min',
    func=sample
)
chart.set(df)

layout.addWidget(chart.get_webview())

window.setCentralWidget(widget)
window.show()

app.exec_()
```

### Environment

```markdown
- OS:10.0.19
- Library:2.01
```

**Comment by louisnw01** [comment]
Appears to be related to utf-8 encoding, which is not set by default on windows. 

Could you clone the latest version of main and test if it works now?

Louis

**Comment by P-Lamont** [comment]
@louisnw01 Thanks. It works
