### ISSUE TITLE
[BUG] Linux black screen

### ISSUE THREAD

**Issue by edofe99** [louisnw01/lightweight-charts-python#412]
### Expected Behavior

Hello, does someone use Linux and as output have a window with a completely black screen?
I used this lib also on mac with no problem, I even tried starting from scratch creating a virtual machine but no luck. 
Anyone have a clue? 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/62611612/1b7d6669-894b-42e0-b3a8-50189c348301)

Thank's. 

### Current Behaviour

Using chart debug I have a white browser page, nothing else. 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/62611612/4f5e7211-8cd1-4ffa-9bb0-7671cd5875bf)

![image](https://github.com/louisnw01/lightweight-charts-python/assets/62611612/a17e8a2b-8b0a-407c-ae35-3d32295e7426)

### Reproducible Example

```python
if __name__ == '__main__':

    startDate = datetime.datetime(2006, 1, 1)    
    endDate = datetime.datetime(2024, 5, 22)
    spy_data = yf.Ticker('SPY')
    spy_df = spy_data.history(start=startDate, end=endDate)

    spy_df.drop(['Volume', 'Dividends', 'Stock Splits','Capital Gains'],axis = 1,inplace = True)

    chart = Chart()
    chart.set(spy_df)    
    chart.show(block=True)
```

### Environment

```markdown
- OS: Linux Mint / MX Linux
- Library: Last version and tried also on 1.0.21
```

**Comment by armeya25** [comment]
Refer https://github.com/louisnw01/lightweight-charts-python/issues/334 this.

**Comment by armeya25** [comment]
export WEBKIT_DISABLE_COMPOSITING_MODE="1" 
Add this to working terminal and hit enter.
