### ISSUE TITLE
[BUG] NO graph being plotted.

### ISSUE THREAD

**Issue by mohittgupta** [louisnw01/lightweight-charts-python#413]
### Expected Behavior

Hello , 

Till yesterday candlestick chart used to be plotted and displayed. But now just a blank screen is being shown. 

### Current Behaviour

Blank screen , no chart is loading. 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/89182070/e0e83f4e-0fcd-4d31-bc41-d97419c2a6d8)

### Reproducible Example

```python
import yfinance as yf
import pandas as pd
from lightweight_charts import Chart

# 1. Fetch TCS Stock Data
ticker = "TCS.NS"
data = yf.download(ticker, period="1y")

# 2. Convert Time Index to Datetime and Format for Charting
df_reset = data.reset_index()

df_reset = df_reset.rename(columns={'index': 'time', 'Open':'open', 'High':'high', 'Close':'close' ,'Low':'low', 'Volume':'volume'})
# 3. Create and Customize the Chart
chart = Chart(toolbox=True, maximize=True, on_top=True)

chart.legend(visible=True, font_size=14)

chart.set(df_reset)

chart.show(block=True)
```

### Environment

```markdown
- OS:
- Library:
```

**Comment by bhavishyagoyal12** [comment]
I am also facing same issue with even simple code

[import pandas as pd
from lightweight_charts import Chart


if __name__ == '__main__':
    
    chart = Chart()
    
    # Columns: time | open | high | low | close | volume 
    df = pd.read_csv('ohlcv.csv')
    chart.set(df)
    
    chart.show(block=True)](url)

**Comment by bhavishyagoyal12** [comment]
Could it because TradingView release new version 

https://github.com/tradingview/lightweight-charts

**Comment by bhavishyagoyal12** [comment]
@louisnw01  Can you please check why this is  not working

**Comment by bhavishyagoyal12** [comment]
@louisnw01 May i request to please check this ?

**Comment by FattyMango** [comment]
I'm not sure where the problem is, everything looks fine.

![image](https://github.com/user-attachments/assets/3484b4f4-d035-4b4a-a0e6-6abba2c62732)

**Comment by S0rushSotoudeh** [comment]
I have same problem

**Comment by bhavishyagoyal12** [comment]
it would work after some time

**Comment by louisnw01** [comment]
dupe
