### ISSUE TITLE
Timestamps in milliseconds

### ISSUE THREAD

**Issue by germangar** [louisnw01/lightweight-charts-python#415]
### Question

Hello,

Just one simple question. It is possible to make lightweight charts work with a dataframe in straight up milliseconds? I tried but only seems to accept the time after doin't the pd.to_datetime conversion.

It's not a big deal, but I would prefer using the raw value elsewhere. If there's a toogle in the chart setup or something I'm not finding it.

Thanks in advance.

**Comment by louisnw01** [comment]
Hey @germangar,

To my knowledge the original lightweight charts library only supports second timestamps, so this wont be possible.
