### ISSUE TITLE
How to use other lightweight-charts plugins

### ISSUE THREAD

**Issue by piotrwoj** [louisnw01/lightweight-charts-python#416]
### Question

I would like to use other plugins, such like volume profile: https://github.com/tradingview/lightweight-charts/tree/master/plugin-examples/src/plugins/volume-profile. I see that the lightweight-charts-python supports plugins in general, but it looks that it's not enough to just copy and paste the plugin code to the project. Could someone explain how to do it, assuming that I know Python and same basics of JS?

**Comment by yakir4123** [comment]
every example of how to use any plugin will be appriciated (than with gpt or something we probably will be able to create a lot more)

**Comment by gl-karunkrishna** [comment]
https://tradingview.github.io/lightweight-charts/plugin-examples/plugins/volume-profile/example/

This feature will be very powerful to implement natively

**Comment by louisnw01** [comment]
Hey @piotrwoj,

All implementations of plugins in this library are custom, so stock ones won't work by themselves.
