### ISSUE TITLE
convert_timeframe 'M' will cause crash 

### ISSUE THREAD

**Issue by ahmedacoding** [louisnw01/lightweight-charts-python#417]
### Question

in file (lightweight_charts/polygon.py)  , when I add 'M' for month in def __init__(timeframe_options: tuple = ('15min','1min','5min','30min','H','D','W','M'), if you click it on chart it will cause it to crash.

### Code example

```python
def __init__(
            self, api_key: str, live: bool = False, num_bars: int = 200, end_date: str = 'now', limit: int = 5_000,
            timeframe_options: tuple = ('15min','1min','5min','30min','H','D','W','M'),
```

**Comment by louisnw01** [comment]
hey @ahmedacoding,

The polygon chart is not setup to pull month timeframes, so you'd need to implement this functionality.
