### ISSUE TITLE
[BUG] [pywebview] MSHTML is deprecated. 

### ISSUE THREAD

**Issue by lukaIvanic** [louisnw01/lightweight-charts-python#419]
### Expected Behavior

On my old pc setup the charts would run normally (on the lightweight-charts v1.x)

### Current Behaviour

Whatever I run I keep getting this error.

[pywebview] MSHTML is deprecated. See https://pywebview.flowrl.com/guide/web_engine.html on details how to use Edge Chromium

### Reproducible Example

```python
/any
```

### Environment

```markdown
- OS: Win
- Library:any
```

**Comment by louisnw01** [comment]
This is a pywebview issue; please refer to their docs.
