### ISSUE TITLE
Line Indicators in Updating bars in real-time

### ISSUE THREAD

**Issue by SecurelyAeroplane** [louisnw01/lightweight-charts-python#42]
Hi!

Is it possible to get a sma indicator while also updating the bars (the sma updates as new bars appear)?

`import pandas as pd
from time import sleep
from lightweight_charts import Chart

if __name__ == '__main__':

    chart = Chart()

    df1 = pd.read_csv('ohlcv.csv')
    df2 = pd.read_csv('next_ohlcv.csv')

    chart.set(df1)

    chart.show()

    last_close = df1.iloc[-1]
    
    for i, series in df2.iterrows():
        chart.update(series)

        if series['close'] > 20 and last_close < 20:
            chart.marker(text='The price crossed $20!')
            
        last_close = series['close']
        sleep(0.1)`

**Comment by SecurelyAeroplane** [comment]
I figured a possible solution that works for me:
`from datetime import datetime as dt2
import datetime
import pandas as pd
from time import sleep
from lightweight_charts import Chart
from lightweight_charts import js

def calculate_sma(data: pd.DataFrame, period = 18):
    def avg(d: pd.DataFrame):
        return d['close'].mean()

    result = []
    for i in range(period - 1, len(data)):
        val = avg(data.iloc[i - period + 1:i])
        #formatted_time = datetime.datetime.utcfromtimestamp(data.iloc[i]['time']).isoformat() + "Z"
        result.append({'time': data.iloc[i]['time'], 'value': val})
    return pd.DataFrame(result)

if __name__ == '__main__':

    chart = Chart()

    csv_part_1 = f'Main_Data/2023-07-13T16.45.00Z/Part 1.csv'
    csv_part_2 = f'Main_Data/2023-07-13T16.45.00Z/Part 2.csv'

    df1 = pd.read_csv(csv_part_1)
    df1_backup = pd.read_csv(csv_part_1)

    df2 = pd.read_csv(csv_part_2)
    chart.set(df1)
    chart.show()


    last_close = df1.iloc[-1]
    for i, series in df2.iterrows():
        row_to_concat = [df2.iloc[i]]
        df1_backup = pd.concat([df1_backup, pd.DataFrame(row_to_concat)], ignore_index=True)
        line = js.Line(chart, color='rgba(255, 0, 51, 1.0)', width=2)
        sma_data = calculate_sma(df1_backup)
        line.set(sma_data)

        chart.update(series)
        last_close = series['close']
        sleep(0.2)`

https://github.com/louisnw01/lightweight-charts-python/assets/138993268/ea3d6516-89e9-43e9-8405-b638e0297030

In the solution, I create new instances of the Line class, is there anyway to hide / remove a line with specific Id, like we do with the markers(remove_marker) and horizonal lines(remove_horizontal_line) ? 


How would I add a remove / hide line in this class?:
![image](https://github.com/louisnw01/lightweight-charts-python/assets/138993268/500fd09b-9f97-4b9d-a606-ab46755c476d)

**Comment by SecurelyAeroplane** [comment]
Updated to 1.0.13 to get the 
`line = chart.create_line(color='rgba(214, 237, 255, 1.0)',price_line=False, price_label=False)`
and delete method in Line

**Comment by ThierryGirod** [comment]
@SecurelyAeroplane Can you give a short demo of the new solution with the update in 1.0.13 on how to create line indicator in real time bars? That would be awesome :)

**Comment by alloc7260** [comment]
@SecurelyAeroplane 
That is happening because you create new line for every loop execution
just take line creation out of the loop and you are good to go.
