### ISSUE TITLE
StreamlitChart: chart.topbar.switcher callback function not triggered on timeframe change

### ISSUE THREAD

**Issue by abdibsc** [louisnw01/lightweight-charts-python#422]
### Question

Hi there,

I'm encountering an issue with the chart.topbar.switcher function in the lightweight_charts.widgets library when used within a Streamlit application. The callback function defined for the switcher doesn't seem to be getting triggered when the user selects a different timeframe option.
I've implemented the code snippet below to create a StreamlitChart with a switcher for selecting timeframes:
When I run this code and launch the Streamlit application, I expect the on_timeframe_selection function to be called whenever the user selects a different timeframe option from the switcher element on the chart's top bar. This function should then print the selected timeframe to the console, indicating that the callback is working.
However, the on_timeframe_selection function is not being called when the user changes the timeframe using the switcher.

### Code example

```python
from lightweight_charts.widgets import StreamlitChart

chart = StreamlitChart(width=1450, height=550, scale_candles_only=False, toolbox=True)
chart.set(ohlcv, keep_drawings=True)

def on_timeframe_selection():
    print(f'Getting data with a {chart.topbar["my_switcher"].value} timeframe.')

chart.topbar.switcher(name='my_switcher', options=('1m', '3m', '5m', '15m', '30m', '1h', '4h', '1d'), default='5m', func=on_timeframe_selection)

chart.load()
```

**Comment by louisnw01** [comment]
Streamlit is a static chart, and does not allow callbacks (ie the topbar)
