### ISSUE TITLE
Adding .update feature for title bar

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#425]
### Description

![image](https://github.com/user-attachments/assets/40c5b44b-9030-428d-862f-3c087c6f29ef)

We would be able to put in realized/unrealized 
Might be worth exposing the pywebview create_windows params to Chart(...)  if users want to customize the behavior of their window

**Comment by louisnw01** [comment]
Hey @karunkrishna,

I won't look to implement this unfortunately; use the `topbar` perhaps?
