### ISSUE TITLE
Issue with loading chart after upgrading to 1.0.14

### ISSUE THREAD

**Issue by EconLQ** [louisnw01/lightweight-charts-python#43]
Hi there! Thank you for the library. Really enjoying the simplicity and elegance of it! However, after the latest upgrade, I tried to launch a chart and got a black screen with only the `toolbox` on the left.

OS: Ubuntu 22.04 LTS
Python version: 3.11.4

![black_screen_toolbox_only](https://github.com/louisnw01/lightweight-charts-python/assets/67261422/e6014eb9-f0fa-4a2f-8811-bcffbdf9cf84)

Here's the code that I've tried to launch for testing purposes and it worked fine with the last update `lightweight-charts==1.0.13.4`:
```python
if __name__ == '__main__':
    
    chart = PolygonChart(timeframe_options=('1min', '5min', '15min', '1H', '4H', 'D', 'W'), api_key='MY_API_KEY', live=True)
    chart.polygon.log(info=True)

    chart.show(block=True)
```
Traceback from the console:
```
Traceback (most recent call last):
  File "/home/econlq/VSCode/realtime_chart_TWS/.venv/lib/python3.11/site-packages/webview/platforms/gtk.py", line 494, in _callback
    value = webview.run_javascript_finish(task)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: WebKitJavascriptError: about:blank:3:31: TypeError: JSON.stringify cannot serialize cyclic structures. (699)
```
There may be an issue with `webview` component on my machine (Ubuntu 22.04 LTS). I haven't programmed in Python for a while, and apologize for bothering if the mistake is too obvious. 
Thank you for your time!

**Comment by louisnw01** [comment]
Hi, glad you're enjoying the library.

The error message your encountering is related to web view, but it shouldn't be raised and the code should still run normally. Does that error raise an exception in python on your machine?

Also, Have you tried running any of the other examples with the toolbox enabled?

**Comment by EconLQ** [comment]
The error raises no exceptions in python. I've also tried to enable the toolbox while instantiating `Chart` object. The script works fine without toolbox, but the same mistake appears with `toolbox=True`

### Example:
```python
import pandas as pd
import pandas_ta as ta
import yfinance as yf
from lightweight_charts import Chart

if __name__ == '__main__':
    
    symbol : str = "AAPL"
    period : str = "3y"

    # toolbox enabled
    chart = Chart(toolbox=True)

    ticker = yf.Ticker(ticker=symbol)
    df = ticker.history(period=period)
    
    # writes data to a file
    df.to_csv(f"./dump/{symbol}_{period}.csv", sep='\t')

    # prepare indicator values
    sma = df.ta.sma(length=20).to_frame()
    sma = sma.reset_index()
    sma = sma.rename(columns={"Date": "time", "SMA_20": "value"})
    sma = sma.dropna()

    df = df.reset_index()
    df.columns = df.columns.str.lower()
    chart.set(df)

    # add sma line
    line = chart.create_line()    
    line.set(sma)

    chart.watermark(symbol)    
    chart.show(block=True)
```

**Comment by louisnw01** [comment]
I just published a fix to prevent the 'cyclic errors' Error.

If thats the culprit, the code should work now.

Let me know!
Louis

**Comment by EconLQ** [comment]
Everything works like a charm! Thanks a lot!
