### ISSUE TITLE
Why is the function to Clear horizontal lines from the chart, no longer supported ?

### ISSUE THREAD

**Issue by Aags26** [louisnw01/lightweight-charts-python#431]
### Question

The function to clear any horizontal lines from the chart is no longer there. Any reason for replacing this functionality with individually deleting each horizontal line using the delete method ?
### Code example

```python
Previously,

# Clear horizontal lines from the chart
chart.clear_horizontal_lines()

# Now,
line = chart.horizontal_line(....)
line.delete()

# Why?
```

**Comment by louisnw01** [comment]
Hey @Aags26,

The reason is simplification; the library no longer tracks/stores all of your drawings, so it is up to you whether you would like to do this/not do this.
