### ISSUE TITLE
Table Scroll doesn't happen

### ISSUE THREAD

**Issue by Aags26** [louisnw01/lightweight-charts-python#432]
### Question

Table Scroll doesn't happen. Used to scroll before updating the local version of the library.

### Code example

```python
chart.create_table(
                width=0.3,
                height=1,
                headings=('Symbol', 'Trades', 'PF', 'Return', 'CAGR'),
                widths=(0.2, 0.2, 0.2, 0.2, 0.2),
                alignments=('center', 'center', 'center', 'center', 'center'),
                position='left',
                func=lambda t: on_row_click(chart, line, t)
            )

# Table scroll doesn't happen with these parameters. By adding a draggable=True param, however, table scroll does happen.
```

**Comment by FattyMango** [comment]
Having the same issue, the scroll will work if `draggable=True`.

**Comment by louisnw01** [comment]
Hey @fattymango ,

For table scrolling you have to use a pixel height value

```python
chart.create_table(width=0.2, height=300)
```

**Comment by Aags26** [comment]
Hey @louisnw01 ,

Why doesn't height = 1 no longer work? The issue with hardcoded values like 300, 600, etc. is that different screens have different heights. So, we cannot rely on a single fixed value.
