### ISSUE TITLE
subchart sync not working when zooming in and out or full screen change or trading time change - live data updates

### ISSUE THREAD

**Issue by esteban2006** [louisnw01/lightweight-charts-python#436]
### Expected Behavior

as the user would zoom in or out in withing the main chart, the subchart should replicate the action mantaining the same position on the time scale, specially.

### Current Behaviour

When zooming in or our or going full screen the subchart loose track of the current time scale and position

https://github.com/user-attachments/assets/6bda6e56-d528-4e6c-9a61-c2a165b03924

### Reproducible Example

```python
import pandas as pd
from lightweight_charts import Chart

if __name__ == '__main__':
    chart = Chart(inner_width=1, inner_height=0.8)
    chart.time_scale(visible=False)

    chart2 = chart.create_subchart(width=1, height=0.2, sync=True)
    line = chart2.create_line()
    
    df = pd.read_csv('ohlcv.csv')
    df2 = pd.read_csv('rsi.csv')

    chart.set(df)
    line.set(df2)

    chart.show(block=True)
```

### Environment

```markdown
- OS: windows
- name='lightweight_charts', version='2.0.1',
- python ='3.1',
```

**Comment by digital-stoic** [comment]
+1 Facing same issue here.

**Comment by nithesh10** [comment]
How did you fix this ?

**Comment by digital-stoic** [comment]
Hi all, FYI how I could fix in my case:

The issue was the number of X data points, that must be the same between the candles/lines of all charts and subcharts, regardless of the Xmin and Xmax after a `fit()`.

**Comment by esteban2006** [comment]
@digital-stoic could you share your solution ?

**Comment by digital-stoic** [comment]
@esteban2006 : It's just a data quality thing, not code per se: Ensure that the number of data points on the X axis is the same between your chart and subcharts.

**Comment by louisnw01** [comment]
Sync is based on the logical index of a datapoint, not the time. In your case, you need to pad the beggining of your indicator with empty values.
