### ISSUE TITLE
Sync among diffrent instances

### ISSUE THREAD

**Issue by esteban2006** [louisnw01/lightweight-charts-python#438]
### Description

@louisnw01 thank you for such an amazing lib, honestly the way webview js, and python mingle together is really outstanding,I wish We could have the time to approach all the benefits of the lightweight chart by TV, but I know it so much, 

Feature: Sync among diffrent instances : Running a chart on separated thread and still be able to to sync on all the open threads 

https://github.com/user-attachments/assets/698921c7-05f2-430f-860d-041ca2138ae7

### Code example

```python
self.chart = Chart(
            toolbox=True,
            width=1400 if self.account != "DEVELOPER MODE" else 600,
            inner_width=self.settings["chart"]["chartWith"],
            inner_height=self.settings["chart"]["chartHeight"],
            title=f"{buildName}",
            thread_id = "main_chart"
        )
```

### Method of implementation

by adding a thread_id on the chart creation maybe zoom and scales position could be trackable ... and then be passed to other instances

**Comment by louisnw01** [comment]
Hey @esteban2006,

This would require a lot of work with the current implementation of the lib, so i'm going to mark as wont do for now.

Apologies!

**Comment by esteban2006** [comment]
Ok, thank you,
