### ISSUE TITLE
Hollow Candles

### ISSUE THREAD

**Issue by martinbouhier** [louisnw01/lightweight-charts-python#439]
### Description

Is there any way to add hollow candles or another type of candles like the tradingview app?

This is what I'm expecting:
<img width="927" alt="image" src="https://github.com/user-attachments/assets/0c961ce9-a9c9-41f9-a45c-02c991124e97">

This is the actual chart
<img width="796" alt="image" src="https://github.com/user-attachments/assets/81feb89c-4c4f-4f88-96c7-1fd0af571e5d">

### Code example

```python
I think we can change here the code to add another validation to convert the candles
    def candle_style(
            self, up_color: str = 'rgba(39, 157, 130, 100)', down_color: str = 'rgba(200, 97, 100, 100)',
            wick_visible: bool = True, border_visible: bool = True, border_up_color: str = '',
            border_down_color: str = '', wick_up_color: str = '', wick_down_color: str = ''):
        """
        Candle styling for each of its parts.\n
        If only `up_color` and `down_color` are passed, they will color all parts of the candle.
        """
        border_up_color = border_up_color if border_up_color else up_color
        border_down_color = border_down_color if border_down_color else down_color
        wick_up_color = wick_up_color if wick_up_color else up_color
        wick_down_color = wick_down_color if wick_down_color else down_color
        self.run_script(f"{self.id}.series.applyOptions({js_json(locals())})")
```

**Comment by EsIstJosh** [comment]
bg_col= '#000000' # Pick Background color
up_col= '#acfb00'  # Pick Green candle color
dn_col= '#ff0000'   # Pick Red candle color


chart.layout(background_color=bg_col) 
chart.candle_style(up_color=bg_col, down_color=bg_col, 
    border_up_color=up_col, border_down_color=dn_col,
    wick_up_color=up_col, wick_down_color=dn_col)  # Set candle up_color and down_color to the same as background_color ?

**Comment by martinbouhier** [comment]
> `bg_col= '#000000' # Pick Background color up_col= '#acfb00' # Pick Green candle color dn_col= '#ff0000' # Pick Red candle color
> 
> chart.layout(background_color=bg_col) chart.candle_style(up_color=bg_col, down_color=bg_col, border_up_color=up_col, border_down_color=dn_col, wick_up_color=up_col, wick_down_color=dn_col) # Set candle up_color and down_color to the same as background_color ?`

I just updated the requirement to be more specific in the definition of Hollow Candles

**Comment by louisnw01** [comment]
> `bg_col= '#000000' # Pick Background color up_col= '#acfb00' # Pick Green candle color dn_col= '#ff0000' # Pick Red candle color
> 
> chart.layout(background_color=bg_col) chart.candle_style(up_color=bg_col, down_color=bg_col, border_up_color=up_col, border_down_color=dn_col, wick_up_color=up_col, wick_down_color=dn_col) # Set candle up_color and down_color to the same as background_color ?`

This works; for transparency you may be able to add another field to your ohlc data (https://tradingview.github.io/lightweight-charts/tutorials/customization/data-points#result)

**Comment by martinbouhier** [comment]
I think we have a confusion here. With the Data we have on OHCL we should build Hollow Candles, we dont need another field on the data set. This is wrong. Please, check another libraries or the Original Trading View Chart>

<img width="726" alt="image" src="https://github.com/user-attachments/assets/b77a2be9-fae5-4431-bf29-ceb504f453ad">

<img width="742" alt="image" src="https://github.com/user-attachments/assets/82e5777c-fcd5-407c-bb19-947d66ef535a">
