### ISSUE TITLE
[BUG] The PyQt6 implementation is not working

### ISSUE THREAD

**Issue by axalon** [louisnw01/lightweight-charts-python#443]
### Expected Behavior

When using the demo code provided in the documentation at https://lightweight-charts-python.readthedocs.io/en/latest/examples/gui_examples.html

I adjusted PyQt5 to PyQt6 in the following code from the documentation above:

```
import pandas as pd
from PyQt6.QtWidgets import QApplication, QMainWindow, QVBoxLayout, QWidget

from lightweight_charts.widgets import QtChart

app = QApplication([])
window = QMainWindow()
layout = QVBoxLayout()
widget = QWidget()
widget.setLayout(layout)

window.resize(800, 500)
layout.setContentsMargins(0, 0, 0, 0)

chart = QtChart(widget)

df = pd.read_csv('ohlcv.csv')
chart.set(df)

layout.addWidget(chart.get_webview())

window.setCentralWidget(widget)
window.show()

app.exec_()
```

### Current Behaviour

When I run the above code I get the following error:

`ModuleNotFoundError: QWebEngineView was not found, and must be installed to use QtChart.`

so I did `pip install QWebEngineView`

after that I now receive the error:

`ImportError: DLL load failed while importing QtWebEngineWidgets: The specified procedure could not be found.`

### Reproducible Example

```python
You can copy the code from above and try run it
```

### Environment

```markdown
- OS: Windows 11
- Library:2.0.1
```

**Comment by louisnw01** [comment]
This is related to your install of PyQt; check their docs for info.

**Comment by LasanthaSudeera** [comment]
I too got this issue. However I found a solution. Create a virtual environment, and follow the exact order to install the packages.

pyqt6 
pyqtwebengine 
pyqt6-webengine 
lightweight-charts

**Comment by LasanthaSudeera** [comment]
Still got this issue:

QWidget: Must construct a QApplication before a QWidget.

Same code works for 5, but not for 6.
