### ISSUE TITLE
Not working in kali linux: Candles not showing, only a black window poping up.

### ISSUE THREAD

**Issue by EryanNeo** [louisnw01/lightweight-charts-python#444]

**Comment by martinbouhier** [comment]
Please, add more details

**Comment by EryanNeo** [comment]
Thank you for taking concern on this issue. Please find below details.

I have a candles2.py file that uses lightweight-charts library.

When I run in ubuntu, it works fine, but in kali linux, it doesn't work well.
Please find attached files below.

File: candles2.py
[ADANIENT_2023-04-10.csv](https://github.com/user-attachments/files/16607646/ADANIENT_2023-04-10.csv)

`import pandas as pd
import requests
import numpy as np
from lightweight_charts import JupyterChart,Chart
import time
import asyncio
import nest_asyncio
from datetime import datetime

nest_asyncio.apply()
df=pd.read_csv('ADANIENT_2023-04-10.csv')
df.columns=['time', 'open', 'high', 'low', 'close', 'volume']
df['time']=pd.to_datetime(df['time'],format='%H:%M')
df1=df[:15]
df2=df[15:]
print('chart')
chart = Chart()
chart.set(df1)
chart.show()
for i,series in df2.iterrows():
    chart.update(series)
    time.sleep(1)
print('chart done')

`

![Screenshot_20240814_100827_Gallery](https://github.com/user-attachments/assets/16fe782b-4da3-4c6e-b4f3-96d7049a3ed2)
![Screenshot_20240814_100800_Gallery](https://github.com/user-attachments/assets/f53f1ce6-e16a-4886-8571-29672cffa1ec)
![Screenshot_20240814_100749_Gallery](https://github.com/user-attachments/assets/57369172-45a1-4423-be84-5ef9c1be5ee5)
![20240808_184011](https://github.com/user-attachments/assets/094997ee-e8b0-45db-a22e-5192e03bf650)
![20240808_183243](https://github.com/user-attachments/assets/3cd05822-7d88-49b7-8474-b18bd42ea07a)


[ADANIENT_2023-04-10.csv](https://github.com/user-attachments/files/16607653/ADANIENT_2023-04-10.csv)



Please let me know if any other clarifications needed.

**Comment by EryanNeo** [comment]
Adding further, both ubuntu and kali are working on the same machine as dual boot, so I guess there is no hardware related issue.

**Comment by martinbouhier** [comment]
I think here is the answer you are looking for: https://github.com/louisnw01/lightweight-charts-python/issues/63#issue-1840409797.

Please, read the docs: https://lightweight-charts-python.readthedocs.io/en/latest/tutorials/getting_started.html

I think this is the same issue you have.

<img width="917" alt="image" src="https://github.com/user-attachments/assets/3e26627c-c2cc-407e-aa7c-50908f6fb199">

**Comment by EryanNeo** [comment]
@martinbouhier I am really thankful to your efforts regarding this issue. 
I'll go through this documentation and apply changes if needed. Let me see if it works.

**Comment by EryanNeo** [comment]
Hey @martinbouhier , As suggested, I tried setting up pywebview, and it seems to be working fine.
Please find webview results below.

![webview](https://github.com/user-attachments/assets/2f8b7e37-fa30-465e-96e8-25b13c010fe2)

Reading the pinned issue, I tried using Chart(debug=True) in my code which gave some results. Please find the error below.

![lightweight-charts](https://github.com/user-attachments/assets/450e0c40-6a4a-4de4-a688-40df22456a8f)

Though I can see the candles, its not smooth and it displays luck-by-chance, I had to zoom out zoom in scroll left scroll right to get a part of chart.

I think there is some issue related to DateTime as indicated in console window. Adding further, while I was not able to display charts in python, I had used Javascript for this task, and there also I was also getting the similar error [DateTime object invalid or something similar].

As suggested in the pinned issue, I also followed some steps to set up locales as per my understandiing. Please find below image for reference.
Please suggest steps that I can follow to rectify this error.
![locales](https://github.com/user-attachments/assets/f33d2838-14e8-4371-8bd3-8d044089865e)

There are some changes made in code to get a view of error. Please find code and necessary data file below.
This file contains time in timestamp format ( previous file contained time in format H:M).
[ADANIENT_2024-01-01.csv](https://github.com/user-attachments/files/16611856/ADANIENT_2024-01-01.csv)

`import pandas as pd
from lightweight_charts import Chart

if __name__ == '__main__':
    
    chart = Chart(debug=True)
    
    # Columns: time | open | high | low | close | volume 
    df = pd.read_csv('ADANIENT_2024-01-01.csv')
    df['time']=pd.to_datetime(df['time']+19800,unit='s')# adding 19800 for Indian Loal Time (+5:30)
    chart.set(df)
    
    chart.show(block=True)`


Thanking you very much for the support. I had been trying for a long time for this issue, seems like I'm getting closer to solution. All because of you. Love this community.

**Comment by EryanNeo** [comment]
Meanwhile when I check ubuntu locales, ilI can see a long list of entries as in the image below.
![20240814_165449](https://github.com/user-attachments/assets/b7a96e4d-17cc-4696-bb0a-417dbc9ff7f8)

**Comment by martinbouhier** [comment]
Great! I'm glad to hear that. Thanks for adding the full explanation on the solution! 🚗

**Comment by EryanNeo** [comment]
Hello Folks, so this issue is solved right now.

Yeaterday I had set up locales, even then chart was not showing properly. Today after I waking up I tried and its working fine. The only minor change I can detect in yesterday and today is that command "locale -a" output is slightly different today.

yesterday's output:
C
C.utf8
POSIX
en_IN
en_IN.utf8
en_US.utf8

today's output:
C
C.utf8
en_IN
en_IN.utf8
en_US.utf8
POSIX

Please note that POSIX line is at the bottom today. God knows how it happened(I had just set up locales).
And candles are working fine. 
![success_light_weight_charts](https://github.com/user-attachments/assets/eff07117-5c06-4ea5-95bb-ec7e4f9c2156)


@martinbouhier I would like to specially thank you for helping me solve this issue.

Let me summarise the solution for this issue:
(1) Check if Webview is working fine, link in the documentation section.
(2) If Webview is fine, use "Chart(debug=True)" for creating chart instance and find out error from the console window.
(3) If errors are as per above, set locales as per needed.

Hope it works for anyone having issues.
Happy Coding.

**Comment by Hckr1123** [comment]
Just adding on what worked for me. Adding POSIX locale (it would then show up in locale -a), and then setting LC_ALL=POSIX (command: export LC_ALL=POSIX) was the step that fixed the issue.
