### ISSUE TITLE
Is it really lightweight?

### ISSUE THREAD

**Issue by x68507** [louisnw01/lightweight-charts-python#446]
### Question

Although this is a port from the JavaScript Lightweight Charts, which comes in at 45Kb, is this really a lightweight Python version?  When I try to compile with PyInstaller, I get a executable of 187Mb due to the dependency of pandas.  Anyway to get this module down to a kilobyte level?

**Comment by louisnw01** [comment]
At present pandas is a dependancy and there is no way around this; however, I may look to remove it in the future.
