### ISSUE TITLE
[BUG] data frame over 20000 record will not display

### ISSUE THREAD

**Issue by esteban2006** [louisnw01/lightweight-charts-python#447]
### Expected Behavior

# All data pass in chart.set() or chart.update() should display on the window chart   

### Current Behaviour

# any data set over 20000 records will not display the chart 

Example with 20000 records 

https://github.com/user-attachments/assets/069997e7-ac27-4934-be2f-626d45d22810

Example with over 20000 records 

https://github.com/user-attachments/assets/bf61c4c6-dec5-4117-b78e-0ba9f3e343e8

### Reproducible Example

```python
if self.chart_first_run or self.makert_has_changed or self.time_has_changed:
                self.chart.set(new_data)
```

### Environment

```markdown
- OS: Windown-s
- Library: v2.0.1
```

**Comment by nithesh10** [comment]
your gui looks great ! , can you share the entire source code

**Comment by muhd360** [comment]
hi can you share the code

**Comment by muhd360** [comment]
@esteban2006

**Comment by louisnw01** [comment]
Hey @esteban2006, This is a limitation of the original Lightweight Charts library unfortunately.

**Comment by muhd360** [comment]
@louisnw01 hi when i am trying to plot ebidta vs date(merging on common date) between two tables there is no output available any idea why?? do you want the csv file im using to plot if you could check it once i would really appreciate it
