### ISSUE TITLE
create_line()  Issue

### ISSUE THREAD

**Issue by hamzagds** [louisnw01/lightweight-charts-python#45]
OS: Ubuntu 22.04
Python version: 3.10

Error:
Traceback (most recent call last):
  File "/home/hamza/.local/lib/python3.10/site-packages/webview/platforms/gtk.py", line 494, in _callback
    value = webview.run_javascript_finish(task)
gi.repository.GLib.GError: WebKitJavascriptError: about:blank:3:31: TypeError: JSON.stringify cannot serialize cyclic structures. (699)

Image:
![Screenshot from 2023-07-18 02-07-31](https://github.com/louisnw01/lightweight-charts-python/assets/124069071/059382dd-9cce-4397-baf2-9581c63e7621)

Example code: 

chart = Chart(debug=True)
chart.legend(visible=True)

df = pd.read_csv('ohlcv.csv')
chart.set(df)

line = chart.create_line()
sma_data = calculate_sma(df, period=50)
line.set(sma_data, name='SMA 50')

After this error, realtime plotting has stopped.

Although, I tried on Ubuntu 20.04 and windows 10 it works perfectly.

**Comment by louisnw01** [comment]
Hi!

The library was updated today (1.0.14.1). If you haven't updated, give that a go and let me know if you still encounter the same issue.

If you are on the latest version, could you provide the code you are using which produces this error?

Thanks!

**Comment by hamzagds** [comment]
@louisnw01 I have updated library but still I am getting this error.

**Comment by louisnw01** [comment]
The error your receiving (JSON.stringify cannot serialise cyclic structures) is most likely an issue with the library; I'll take a closer look later today and get a hotfix out.

Louis

**Comment by louisnw01** [comment]
Hey @hamzagds,

After further inspection, I can't seem to reproduce the web console error with the code you provided.

The latest version has patched a bug which was throwing that error, but it wouldn't have been produced by that code.

Either way, try updating and let me know if anything changes.

Thanks!

**Comment by hamzagds** [comment]
Now it works fine after update thanks
