### ISSUE TITLE
How to Integrate Lightweight Charts into a Python Dashboard Framework?

### ISSUE THREAD

**Issue by yamghani** [louisnw01/lightweight-charts-python#451]
### Question

I'm working on a project where I need to create a dashboard that includes multiple charts, and I want to use lightweight-charts-python for some of them. My main goal is to embed these charts into a web-based dashboard.

Does anyone know if it's possible to integrate lightweight-charts-python with a Python web framework like Dash, Flask, or Streamlit? If so, what would be the best approach to achieve this?

Any examples, suggestions, or references to documentation would be greatly appreciated!

**Comment by esteban2006** [comment]
I would suggest to keep using pywebview as it is alredy mounted in it. i have seen some issues regarding dockerization... so some user have already done half your way, [check this ](https://github.com/louisnw01/lightweight-charts-python/issues/89)

**Comment by louisnw01** [comment]
Streamlit funtionality is already implemented; I may look to implement more (Flask, FastAPI etc) in the future.
