### ISSUE TITLE
How to put markers on the chart efficiently?

### ISSUE THREAD

**Issue by errorreplicator** [louisnw01/lightweight-charts-python#453]
### Question

I have a very simple code and would like to test out markers over or below candle when condition met. 
Do do so, I've got two IF statements. Problem is that if the code is triggered with only one IF it works in seconds but If I add 2nd IF then it runs for couple of minutes and charts pop up empty, 
In below code 'table' is a datafreame. 

### Code example

```python
chart = Chart()
chart.set(table)
for i, series in table.iterrows():
    if series['close'] > 60300:
        chart.marker(time=series['date'],color='#d41c37',position='above',shape='arrow_down')
    if series['low'] < 59900:
        chart.marker(time=series['date'],color='#5fd41c',position='below',shape='arrow_up')
chart.show()
```

**Comment by louisnw01** [comment]
Hey @errorreplicator,

You can use `with chart.bulk_run` to update the chart in one go.
