### ISSUE TITLE
New Windows installation renders no chart.

### ISSUE THREAD

**Issue by dawn-trades** [louisnw01/lightweight-charts-python#456]
### Question

Hello,

since building a new PC and installing Windows and Python through Anaconda the chart doesn't render anymore.
I have seen similar issues been posted about Linux but those fixes didn't help me.

![Screenshot 2024-09-26 152419](https://github.com/user-attachments/assets/0c8ab4f9-4b03-438f-9007-c49daa77af73)

### Code example

```
import pandas as pd
from lightweight_charts import Chart

if __name__ == '__main__':
    df = pd.read_csv(r'C:\Users\Daniel\Documents\coding\code\lw-charts\data\ohlcv.csv')
    print(df.head())  # Check if the data is loaded correctly

    chart = Chart(debug=True)
    chart.set(df)
    chart.show(block=True)
```

**Comment by dawn-trades** [comment]
[ohlcv.csv](https://github.com/user-attachments/files/17149299/ohlcv.csv)

I think it is the csv from the examples i used.
The same code runs fine on my MacBook.

**Comment by esteban2006** [comment]
in my end just rendered with no problem 

![image](https://github.com/user-attachments/assets/5462e3d4-04df-4779-831f-e8fdc5f8ffc8)

maybe is another csv??? because in your image it show only 4 rows ... in the csv file you sent we have 2980 rows

**Comment by dawn-trades** [comment]
It's not an issue with the code or cvs, i have a Mac that runs all the code fine and it did run fine on another windows machine just not on mine.
It has to be some dependency or driver or other issue that i can't figure out.
I already asked GPT for any possible solutions to no avail.

**Comment by dawn-trades** [comment]
When i open the web console it displays this error and the script crashes in the console
![Screenshot 2024-09-26 180634](https://github.com/user-attachments/assets/6e686d31-d280-4c6f-a448-b656450cac74)
![Screenshot 2024-09-26 180846](https://github.com/user-attachments/assets/1b104766-348c-492c-9c99-8ce03c2be682)

**Comment by dawn-trades** [comment]
alright i got it resolved with GPT, was some package issue with conflicting versions
