### ISSUE TITLE
line.update not working

### ISSUE THREAD

**Issue by armeya25** [louisnw01/lightweight-charts-python#457]
### Question

ema and dfx are polars dataframe
i convert them to pandas

but line_ema values not update

### Code example

```python
ema = Static.ema(df1, period=10, return_date=True).to_pandas().set_index('date')

line_ema = chart.create_line(name='ema10', color='rgba(255,0,0,1)', price_line=False, price_label=False)
line_ema.set(ema)

for frame in df2.iter_slices(1):
    dfx = frame.to_pandas().squeeze()
    chart.update(dfx)
        
    e = s.ema(10).to_pandas().set_index('date').squeeze()
    line_ema.update(e)
```

**Comment by esteban2006** [comment]
@armeya25 can you share your ema,  method and your csv?

**Comment by armeya25** [comment]
it works after rewriting code
import polars as pl
from lightweight_charts import Chart

####################################################################################################
class Streaming:
    def __init__(self) -> None:
        self.main_df = pl.DataFrame()
    ####################################################################################################
    def update_old(self, df:pl.DataFrame) -> None:
        df = df.select(['date', 'open', 'high', 'low', 'close'])
        self.main_df.vstack(df, in_place=True)
    ####################################################################################################
    def update_live(self, df:pl.DataFrame) -> None:
        """ update main_df with df
            period  : int           : no of maxiumum rows in main_df
        """
        df = df.select(['date', 'open', 'high', 'low', 'close'])
        if self.main_df.is_empty():
            self.main_df.vstack(df, in_place=True)
        if not self.main_df.is_empty():
            old_df = self.main_df.slice(-1).select(['date', 'open', 'high', 'low', 'close'])
            if not old_df.equals(df):
                self.main_df.vstack(df, in_place=True)
    ####################################################################################################
    def sma(self, period:int, col_name:str='close', return_date:bool=True) -> pl.DataFrame:
        """
            df          : pl.DataFrame  : dataframe to calculate sma of height 1
            period      : int           : no of rows to calculate sma
            col_name    : str           : any column name
            return_date : bool          : if True, return date column
        """
        if self.main_df.height>=period:
            name = f'sma{period}'
            df=(
                    self.main_df
                    .lazy()
                    .select(['date', col_name])
                    .slice(-period)
                    .with_columns(pl.col(col_name).rolling_mean(window_size=period).alias(name)).drop(col_name)
                ).slice(-1).collect()
            if return_date:
                return df.select(['date', name])
            else:
                return df.select(name)
        else:
            return pl.DataFrame()
    ####################################################################################################

####################################################################################################
def sma(df:pl.DataFrame, period:int, col_name='close') -> pl.DataFrame:
    """Calculates the simple moving average"""
    name = f'sma{period}'
    return df.lazy().with_columns(pl.col(col_name).rolling_mean(window_size=period).alias(name)).select(['date', name]).collect()
####################################################################################################

s = Streaming()

df = pl.read_csv('tmp.csv')
df1 = df.slice(1, 30)
df2 = df.slice(30, 100)

s.update_old(df1)

sma = sma(df1, 10).to_pandas().set_index('date')

df1 = df1.to_pandas().set_index('date')
chart = Chart()
chart.set(df1)

sma_line = chart.create_line(name='sma10')
sma_line.set(sma)

chart.show()

for frame in df2.iter_slices(1):
    chart.update(frame.to_pandas().squeeze())
    s.update_live(frame)
    sma = s.sma(10).to_pandas().squeeze()
    sma_line.update(sma)


use your csv file with lower case column names

**Comment by armeya25** [comment]
it worked after rewring code
```
import polars as pl
from lightweight_charts import Chart

####################################################################################################
class Streaming:
    def __init__(self) -> None:
        self.main_df = pl.DataFrame()
    ####################################################################################################
    def update_old(self, df:pl.DataFrame) -> None:
        df = df.select(['date', 'open', 'high', 'low', 'close'])
        self.main_df.vstack(df, in_place=True)
    ####################################################################################################
    def update_live(self, df:pl.DataFrame) -> None:
        """ update main_df with df
            period  : int           : no of maxiumum rows in main_df
        """
        df = df.select(['date', 'open', 'high', 'low', 'close'])
        if self.main_df.is_empty():
            self.main_df.vstack(df, in_place=True)
        if not self.main_df.is_empty():
            old_df = self.main_df.slice(-1).select(['date', 'open', 'high', 'low', 'close'])
            if not old_df.equals(df):
                self.main_df.vstack(df, in_place=True)
    ####################################################################################################
    def sma(self, period:int, col_name:str='close', return_date:bool=True) -> pl.DataFrame:
        """
            df          : pl.DataFrame  : dataframe to calculate sma of height 1
            period      : int           : no of rows to calculate sma
            col_name    : str           : any column name
            return_date : bool          : if True, return date column
        """
        if self.main_df.height>=period:
            name = f'sma{period}'
            df=(
                    self.main_df
                    .lazy()
                    .select(['date', col_name])
                    .slice(-period)
                    .with_columns(pl.col(col_name).rolling_mean(window_size=period).alias(name)).drop(col_name)
                ).slice(-1).collect()
            if return_date:
                return df.select(['date', name])
            else:
                return df.select(name)
        else:
            return pl.DataFrame()
    ####################################################################################################

####################################################################################################
def sma(df:pl.DataFrame, period:int, col_name='close') -> pl.DataFrame:
    """Calculates the simple moving average"""
    name = f'sma{period}'
    return df.lazy().with_columns(pl.col(col_name).rolling_mean(window_size=period).alias(name)).select(['date', name]).collect()
####################################################################################################

s = Streaming()

df = pl.read_csv('tmp.csv')
df1 = df.slice(1, 30)
df2 = df.slice(30, 100)

s.update_old(df1)

sma = sma(df1, 10).to_pandas().set_index('date')

df1 = df1.to_pandas().set_index('date')
chart = Chart()
chart.set(df1)

sma_line = chart.create_line(name='sma10')
sma_line.set(sma)

chart.show()

for frame in df2.iter_slices(1):
    chart.update(frame.to_pandas().squeeze())
    s.update_live(frame)
    sma = s.sma(10).to_pandas().squeeze()
    sma_line.update(sma)
```

**Comment by armeya25** [comment]
use your .csv file with lower case column names

**Comment by armeya25** [comment]
maybe my mistake to overlook something
