### ISSUE TITLE
Enhancement update method

### ISSUE THREAD

**Issue by Zartexo** [louisnw01/lightweight-charts-python#46]
Hi,

i just noticed that the enhancement for the set method were not done for the update method. I think it should work the same way.

`when using set, the column names can now be capitalised, and the date column can be the index.`

BR

**Comment by louisnw01** [comment]
Fixed in v1.0.14.2

Thanks!

**Comment by louisnw01** [comment]
"time" or "date" still needs to be given, but it won't be case sensitive.

**Comment by Zartexo** [comment]
Oh, i see.

Since you changed the set method so the 'time'/'date' column can be the index I think it would be intuitive to be able to use the same type of dataframe with the update method.

**Comment by Zartexo** [comment]
@louisnw01 can you have another look at this? Would be very thankful.



> Oh, i see.
> 
> Since you changed the set method so the 'time'/'date' column can be the index I think it would be intuitive to be able to use the same type of dataframe with the update method.

**Comment by louisnw01** [comment]
> > Oh, i see.
> > Since you changed the set method so the 'time'/'date' column can be the index I think it would be intuitive to be able to use the same type of dataframe with the update method.

Hey @Zartexo,

Sorry, I must have missed your response! This will be implemented in the next update.

Louis
