### ISSUE TITLE
legend handling

### ISSUE THREAD

**Issue by armeya25** [louisnw01/lightweight-charts-python#460]
### Question

is there way to hide "specific"  legend from within python code rather than manualy hiding from chart

say i have "sma_100" line and its legend
if want to hide it from python code how do i do it ?

**Comment by louisnw01** [comment]
`line.hide_data()`

**Comment by armeya25** [comment]
@louisnw01 i just want to hide legend not whole line

**Comment by armeya25** [comment]
@louisnw01  is there event to handle that ?

**Comment by armeya25** [comment]
@louisnw01  also how do i change Chart's height after seting it befor
like this

chart = Chart(inner_width=1, inner_height=0.5, position='top')

if some condition met then
chart = Chart(height=1)

like this
