### ISSUE TITLE
Up/Down Trade Symbology

### ISSUE THREAD

**Issue by DROBNJAK** [louisnw01/lightweight-charts-python#47]
Can we please have full trade entry exit symbology, like Long, Short, Stop Loss and Profit Target, with Labels.

That way one can **place trades directly from Python** onto a TradingView chart, which would be mind-boggling.

**Comment by louisnw01** [comment]
Hi, What do you mean by symbology?

**Comment by louisnw01** [comment]
> Hi, What do you mean by symbology?

To add to this, the next major update will include an `add_hotkey` method, which will let you set your own key commands within the chart to run python functions; is this the sort of thing your after?

**Comment by DROBNJAK** [comment]
What I meant I want to program my strategy in Python and then post entries to the TradingView Lite. So, TradingView Lite will need some symbology to mark Long & Short trades. Most trading programs use blue up arrow for long trades, and red down arrow for short trades. As well as white arrow for hiring stop-loss.

**Comment by louisnw01** [comment]
> What I meant I want to program my strategy in Python and then post entries to the TradingView Lite. So, TradingView Lite will need some symbology to mark Long & Short trades. Most trading programs use blue up arrow for long trades, and red down arrow for short trades. As well as white arrow for hiring stop-loss.

The `marker` method of Chart will let you do this.
