### ISSUE TITLE
Add functionality for applyOptions

### ISSUE THREAD

**Issue by vashzero** [louisnw01/lightweight-charts-python#48]
Hi, first of all, great job on this awesome solution which is a great tool for all of us traders!

I would like to know if it is possible for us to be able to personalize our chart with the applyOptions option.

For instance, I need to change the precision on the price because at this moment it is showing only two decimal digits.

For instance, EURUSD or other currencies, we need to see at least 6 digits.

Thanks for all the great work!

**Comment by emma-uw** [comment]
@vashzero Hey, you can change the precision for EURUSD  using `chart.precision(6)` option.
