### ISSUE TITLE
Integrating chart in a custom window.

### ISSUE THREAD

**Issue by EryanNeo** [louisnw01/lightweight-charts-python#480]
### Question

Hello All,

I would like to know if there is a way that we can integrate cahrt in a custom window( PyQt window preferably).

I'm thinking of a window where I can select some oprions and depending on the values, the app will fetch data from database and show chart using the fetched data.

**Comment by mcanavarros** [comment]
Hi @EryanNeo, that's definitely possible. I'm doing something similar in plutus-terminal, have a look here:
 https://github.com/plutus-terminal/plutus-terminal/blob/develop/plutus_terminal%2Fui%2Fwidgets%2Ftrading_chart.py

**Comment by plutus-terminal** [comment]
Hi @EryanNeo that's definitely possible, I'm doing something similar in Plutus Termin using pyside6. Have a look here:

https://github.com/plutus-terminal/plutus-terminal/blob/develop/plutus_terminal/ui/widgets/trading_chart.py

**Comment by EryanNeo** [comment]
@plutus-terminal  Though it seems to be a bit too advanced for me at my current skills, still I will have a detailed look at the implementation.
It seems like its exactly what I'm thinking of. 
Thank you for sharing the resource. I will have a deep look at it and find out ways of implementing it.

**Comment by EryanNeo** [comment]
Closing the issue for now.
