### ISSUE TITLE
Black screen when using lightweight-charts

### ISSUE THREAD

**Issue by rajkshinde** [louisnw01/lightweight-charts-python#489]
### Question

Hello,
I'm facing a similar challenge mentioned on below stackoverflow query, where even the simple plot chart throws up black screen.
https://stackoverflow.com/questions/79037251/black-screen-when-launching-lightweight-charts-on-windows-11

So even below starting snippet doesnt show output.
I did further checks and if I use Qt charts then it works fine.
Could you please help with this. Let me know if any further info is needed on this

Using: py 3.9 and Windows 11

Thanks in advance!

### Code example

```python
import pandas as pd
from lightweight_charts import Chart


if __name__ == '__main__':
    
    chart = Chart()
    
    # Columns: time | open | high | low | close | volume 
    df = pd.read_csv('ohlcv.csv')
    chart.set(df)
    
    chart.show(block=True)
```

**Comment by EsIstJosh** [comment]
Try python 3.10.6 or 3.11.9, I had a similar issue and switching versions fixed it.

**Comment by rajkshinde** [comment]
yes able to see output after switching to py3.11.9.
Thank you very much for the info
