### ISSUE TITLE
[BUG] blank canvas

### ISSUE THREAD

**Issue by bso0123** [louisnw01/lightweight-charts-python#494]
### Expected Behavior

The chart is blank, expected to see the bars on the chart for a legal csv file of real data

### Current Behaviour

The chart is blank, 
[2024_fix.csv](https://github.com/user-attachments/files/18053291/2024_fix.csv)
![image](https://github.com/user-attachments/assets/c8dd1466-1c44-44de-a7cc-a34582e35063)

### Reproducible Example

```python
import pandas as pd
from lightweight_charts import Chart

if __name__ == '__main__':
    chart = Chart()
    chart.legend(visible=True)

    df = pd.read_csv("./ib_strategy/data/1D/RTH/UPRO/2024_fix.csv")
    df['date'] = pd.to_datetime(df['date'], utc=True)

    chart.set(df)
    chart.show(block=True)
```

### Environment

```markdown
- OS: windows 10 Pro
```

**Comment by bso0123** [comment]
python: 3.9

**Comment by armeya25** [comment]
> python: 3.9

Try casting DATE to 'ns' datetime format.
Or set_index to 'DATE'

**Comment by italodamato** [comment]
`df['time'] = df['time'].astype('datetime64[ns]')` worked for me

**Comment by armeya25** [comment]
If it's working then close issue

**Comment by bso0123** [comment]
@italodamato  Thank you for your suggestion. Unfortunately, its not working. 
My original code works with the example file ohlcv.csv. But in any case I tried your suggestion on my data file provided in my original post.  Nothing helps. It is a valid data fetched from IB for 2024 (not data that I created), it includes all days in order. Cant understand why this data is not shown. 

When I tried to debug :
Here:
![image](https://github.com/user-attachments/assets/1b1e52be-a787-4990-8833-623bc4b31993)
    def on_js_load(self):
        if self.loaded:
            return
        self.loaded = True

        if hasattr(self, '_return_q'):
            while not self.run_script_and_get('document.readyState == "complete"'):
                continue    # scary, but works

        initial_script = ''
        self.scripts.extend(self.final_scripts)
        for script in self.scripts:
            initial_script += f'\n{script}'
        self.script_func(initial_script)

I see that my data is seen in the constructed "initial_script" string, so it seems it was parsed but from that point not sure why the canvas is blank: 

"initial_script":

window.callbackFunction = pywebview.api.callback
window.xlabxbpv = new Lib.Handler("window.xlabxbpv", 1.0, 1.0, "left", true)

        window.xlabxbpv.legend.div.style.display = 'flex'
        window.xlabxbpv.legend.ohlcEnabled = true
        window.xlabxbpv.legend.percentEnabled = true
        window.xlabxbpv.legend.linesEnabled = true
        window.xlabxbpv.legend.colorBasedOnCandle = false
        window.xlabxbpv.legend.div.style.color = 'rgb(191, 195, 203)'
        window.xlabxbpv.legend.color = 'rgb(191, 195, 203)'
        window.xlabxbpv.legend.div.style.fontSize = '11px'
        window.xlabxbpv.legend.div.style.fontFamily = 'Monaco'
        window.xlabxbpv.legend.text.innerText = ''
        
window.xlabxbpv.series.setData([
  {
    "Unnamed: 0": 0,
    "time": 1704153600,
    "open": 53.63,
    "high": 54.13,
    "low": 53.04,
    "close": 53.75,
    "volume": 5720908.0
  },
  {
    "Unnamed: 0": 1,
    "time": 1704240000,
    "open": 53.01,
    "high": 53.27,
    "low": 52.24,
    "close": 52.45,
    "volume": 6604827.0
  },
 ....

**Comment by bso0123** [comment]
I found the problem, the data fetched from IB had duplicate records (same date). removing dup lines solved this. 
df = df.drop_duplicates(subset=['date'], keep='first')

Thanks
