### ISSUE TITLE
chart.marker not set marker with date format ("%Y-%m-%d %H:%M%S)

### ISSUE THREAD

**Issue by alkis-d** [louisnw01/lightweight-charts-python#5]
hi,
chart.marker not set marker with format ("%Y-%m-%d %H:%M%S) - on axis data/time , just works with "1d" interval  or ("%Y-%m-%d)

**Comment by louisnw01** [comment]
Hi, 

This is a bug; a fix has been found, and will be published with the next release.

Thank you for bringing this up!

Louis

**Comment by louisnw01** [comment]
This bug has been fixed in the latest version 1.0.5 :)
