### ISSUE TITLE
Add a topbar Button widget

### ISSUE THREAD

**Issue by Zartexo** [louisnw01/lightweight-charts-python#52]
Hello,

i'm trying to implement show_async to have a more flexible chart. I am using the Callbacks example.

I'm wondering about two things.
1.) Accessing subcharts
When using the Callbacks example I want to create a chart including subcharts. I am struggling to access the subcharts (including their lines) after creating them in the main function. What is the best way to access them?

2.) Setting the switcher widget current option programmatically
In the example the topbar text is set
`self.chart.topbar['symbol'].set(searched_string)`
I am wondering if I can do the same for a switcher widget? I couldn't find any similiar way to change the current option programmatically

BR

**Comment by louisnw01** [comment]
Hey

In your API callback class, the attribute `chart` will be dynamically updated to the chart or subchart that was responsible for emitting the callback.

There is no way to programatically change a switcher after the chart has been loaded, however you can set the inital value of the switcher when defining it.

**Comment by Zartexo** [comment]
Thank you @louisnw01 for the reply. It makes sense to have it like that.

In my case I am using the switcher widget to move my "chart area" one day further. It's not working as intended because it can only be triggered once.

**Comment by louisnw01** [comment]
Ah I see. So I think you want to be able to click a switcher more than once?

Perhaps a seperate 'button' widget may be of benefit.

**Comment by Zartexo** [comment]
Yes, basicly I want to use it as a button. Another widget of that kind would be perfect.
