### ISSUE TITLE
Open in browser

### ISSUE THREAD

**Issue by Rizhiy** [louisnw01/lightweight-charts-python#54]
Hi, awesome project.

Is it possible to open the created chart in browser rather than QT/GTK?

If that functionality currently doesn't exist, do you have a recommended approach?
I was thinking something along the lines of FastAPI+Uvicorn.

**Comment by Rizhiy** [comment]
I guess streamlit works well enough

**Comment by Rizhiy** [comment]
I tried using streamlit, but the chart doesn't update when I try pass in new data, which is strange given that streamlit supposed to execute all code from the start

**Comment by louisnw01** [comment]
Hi, could you post some example code of what you're trying to do?
Thanks

**Comment by Rizhiy** [comment]
@louisnw01 Here is the code
```python
st.set_page_config(layout="wide")

with st.sidebar:
    market = Market[st.radio("Market", [str(m.name) for m in Market])]
    ticker = get_ticker_info(st.text_input("Ticker", "BTCUSDT"), market)

    resolution = Resolution[st.radio("Resolution", [str(r.name) for r in Resolution])]

    start_dt = st.date_input("Start date", dt.datetime(2020, 1, 1, tzinfo=dt.timezone.utc))
    end_dt = st.date_input("End date", start_dt + dt.timedelta(days=1))

    if (end_dt - start_dt) // resolution.timespan > 10_000:
        st.warning("Too many candles to display, please select a smaller range")
        st.stop()
df = get_quotes_df(ticker, resolution, start_dt, end_dt)

chart = StreamlitChart(height=800)
chart.set(df)

chart.load()
```

**Comment by Rizhiy** [comment]
I want to display the chart on a webpage with ability to change what is displayed on it.
I don't need to use Streamlit, but I need an easy way to launch a webserver, so I can access the charts from the web.

**Comment by Rizhiy** [comment]
Hmm, I tried to create a reproducible example and it is working fine. Will try to identify where my bug can be.

**Comment by Rizhiy** [comment]
Not sure what was the bug, but it is working now.

**Comment by isshin1** [comment]
@Rizhiy looking for the same, how do you embed charts in a webapp?
