### ISSUE TITLE
Is it possible to draw Rectangle?

### ISSUE THREAD

**Issue by IlanKalendarov** [louisnw01/lightweight-charts-python#59]
Hey!

Is it possible to draw more complex stuff other then horizontal lines?
Similar to TV long or short positions
Something like the picture below.

<img width="654" alt="image" src="https://github.com/louisnw01/lightweight-charts-python/assets/43996999/3db67db3-d793-44e1-9d0e-4334060e22b1">

Also is there a way to calculate a rsi graph to a given csv without the need to load a different csv?
And is it possible to adjust the rsi values?

<img width="650" alt="image" src="https://github.com/louisnw01/lightweight-charts-python/assets/43996999/bb51c67c-5045-4f69-b197-f315117b6d0b">

Thanks! I really like your work

**Comment by louisnw01** [comment]
Hey @IlanKalendarov,

Unfortunately rectangles are impossible to achieve without modifying the source code of Lightweight Charts.

As for RSI, you can calculate it using its formula.

**Comment by lisbravo** [comment]
What about:
[](https://github.com/tradingview/lightweight-charts/pull/1064)
( kinda noob in python, not sure how hard is to implement this)
