### ISSUE TITLE
Window needs to be resized in order to display subcharts

### ISSUE THREAD

**Issue by pizikuan** [louisnw01/lightweight-charts-python#6]
thanks

**Comment by DEKAGATO** [comment]
new feature subchart and multi panel are supported

**Comment by louisnw01** [comment]
Hi, 2 examples can be found [here](https://lightweight-charts-python.readthedocs.io/en/latest/docs.html#subchart)

**Comment by alkis-d** [comment]
> Hi, 2 examples can be found [here](https://lightweight-charts-python.readthedocs.io/en/latest/docs.html#subchart)

i used the same code in example but it's only show panel 1

**Comment by alkis-d** [comment]
ah~ i need to change the size of the display frame

**Comment by louisnw01** [comment]
Hi, was it that you needed to drag the window to a new size? If so, this is a bug, and it will be fixed.

Thanks!

**Comment by alkis-d** [comment]
yes, i needed drag the window to a new size

**Comment by louisnw01** [comment]
This bug has now been fixed in the latest version.
