### ISSUE TITLE
chart.exit() issue

### ISSUE THREAD

**Issue by mash420** [louisnw01/lightweight-charts-python#60]
I upgraded to the latest version and now when using chart.exit(), the window does close now but it doesnt let me open a new window with new symbol asynchronously.

**Comment by louisnw01** [comment]
When you use `exit`, it destroys that instance of pywebview. That means you will need to make a new `Chart` object after `exit` has been called.

**Comment by mash420** [comment]
`  async def run(self):
        try:
            if self.symbol.startswith('$'):
                df = await self.fetch_stock_data()
            else:
                df = await self.fetch_crypto_data()
            chart = await self.generate_chart(df)
            chart.show(block=False)
            img = chart.screenshot()
            chart.hide()
            filename = f'{self.symbol}-{self.time_now}.png'
            valid_filename = re.sub(r'[^\w\-\. ]', '', filename)
            with open(valid_filename, 'wb') as f:
                f.write(img)
            chart_image = Image.open(valid_filename)
            emblem_image = Image.open('dragon.png')

            emblem_size = (100, 100)  # Adjust the size as needed
            emblem_image = emblem_image.resize(emblem_size)
            position = (10, 10)  # Adjust the position as needed
            chart_image.paste(emblem_image, position, emblem_image)
            chart_image.save(valid_filename)
            chart.exit()

        except KeyboardInterrupt:
            print("Program interrupted. Exiting...")


if __name__ == '__main__':
    symbol = input()
    timeframe = input()
    indicators = input("Indicators: ").split()
    try:
        loop = asyncio.get_event_loop()
        while True:
            analyzer = DragonChart(symbol, timeframe)
            loop.run_until_complete(analyzer.run())
    except:
        print('Error')`
        
      my code is here. we chatted on discord about this before. when i revert to previous version and just use chart.hide() it works fine.

**Comment by mash420** [comment]
async def run(self):
        try:
            if self.symbol.startswith('$'):
                df = await self.fetch_stock_data()
            else:
                df = await self.fetch_crypto_data()
            chart = await self.generate_chart(df)
            chart.show(block=False)
            img = chart.screenshot()
            filename = f'{self.symbol}-{self.time_now}.png'
            valid_filename = re.sub(r'[^\w\-\. ]', '', filename)
            with open(valid_filename, 'wb') as f:
                f.write(img)
            chart_image = Image.open(valid_filename)
            emblem_image = Image.open('dragon.png')

            emblem_size = (100, 100)  # Adjust the size as needed
            emblem_image = emblem_image.resize(emblem_size)
            position = (10, 10)  # Adjust the position as needed
            chart_image.paste(emblem_image, position, emblem_image)
            chart_image.save(valid_filename)
            chart.exit()

        except KeyboardInterrupt:
            print("Program interrupted. Exiting...")


if __name__ == '__main__':
    symbol = input()
    timeframe = input()
    indicators = input("Indicators: ").split()
    try:
        loop = asyncio.get_event_loop()
        while True:
            analyzer = DragonChart(symbol, timeframe)
            loop.run_until_complete(analyzer.run())
    except:
        print('Error')`
`
if i revert back to the previous version and swap out exit for hide() it works fine, but now with new version, this doesnt work correctly anymore.

**Comment by louisnw01** [comment]
I can't seem to see how you are reopening a new window in this code; Could you provide me with a minimal reproducible example?

**Comment by mash420** [comment]
I am using the library to screenshot charts and send to discord, which has its own asyncio loops. Hard to give a working example that way.

After first chart exits, the newly opened chart with different ticker runs but it will not screenshot. Something is breaking there.

**Comment by louisnw01** [comment]
Hey,

The discord/screenshot side of things probably isn't why it is breaking. I just need a very basic example, using a `ohlcv.csv` file that reproduces only the `exit` error, then I will better be able to assist you.

Louis

**Comment by mash420** [comment]
[ohlcv.csv](https://github.com/louisnw01/lightweight-charts-python/files/12270433/ohlcv.csv)

the first chart/screenshot works but the second request gets an error

**Comment by mash420** [comment]
`2023-08-06 14:11:39 WARNING  discord.gateway Shard ID None heartbeat blocked for more than 180 seconds.
Loop thread traceback (most recent call last):
  File "C:\Users\blake\Desktop\DragonChart\main.py", line 167, in <module>
    bot.run('MTEyMTg1MDg0OTAzMTkwMTMxOA.GY_zro.gd6LzSUHlBlERqRbLe0wlPz0NyqWBU04XiGrZw')
  File "C:\Users\blake\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 860, in run
    asyncio.run(runner())
  File "C:\Users\blake\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\blake\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\blake\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\blake\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\blake\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\blake\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\blake\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\blake\Desktop\DragonChart\main.py", line 65, in on_message
    await process_user_request(message)
  File "C:\Users\blake\Desktop\DragonChart\main.py", line 123, in process_user_request
    await process_next_request()
  File "C:\Users\blake\Desktop\DragonChart\main.py", line 137, in process_next_request
    await box(channel, symbol, timeframe, time_now, author, indicators)
  File "C:\Users\blake\Desktop\DragonChart\main.py", line 148, in box
    await analyzer.run()
  File "C:\Users\blake\Desktop\DragonChart\chart.py", line 268, in run
    chart.show(block=False)
  File "C:\Users\blake\AppData\Local\Programs\Python\Python310\lib\site-packages\lightweight_charts\chart.py", line 100, in show
    self._loaded.wait()
  File "C:\Users\blake\AppData\Local\Programs\Python\Python310\lib\multiprocessing\synchronize.py", line 349, in wait
    self._cond.wait(timeout)
  File "C:\Users\blake\AppData\Local\Programs\Python\Python310\lib\multiprocessing\synchronize.py", line 261, in wait
    return self._wait_semaphore.acquire(True, timeout)
`
this is the error i get when a user requests a second chart

**Comment by mash420** [comment]
`import asyncio
import re
from datetime import datetime
import time

from chart import DragonChart

async def box(symbol, timeframe, time_now, indicators=None):
    analyzer = DragonChart(symbol, timeframe, time_now, indicators)
    await analyzer.run()
    # analyzer.exit()
async def test_box():
    symbol = 'BTC/USDT'
    timeframe = '5m'
    time_now = datetime.now()
    indicators = None

    # Run the analysis asynchronously
    await box(symbol, timeframe, time_now, indicators)
    time.sleep(10)
    await box(symbol='ETH/USDT', timeframe=timeframe, time_now=time_now, indicators=indicators)

# Use the main module idiom
if __name__ == '__main__':
    asyncio.run(test_box())`
    
   if you can mock something up like this, the error can be replicated

**Comment by louisnw01** [comment]
Thanks for the code; this is a bug, and will be fixed in the next update.

Louis

**Comment by louisnw01** [comment]
Fixed in the latest version (1.0.16).

Louis

**Comment by mash420** [comment]
`  File "C:\Users\blake\AppData\Local\Programs\Python\Python310\lib\site-packages\lightweight_charts\chart.py", line 18, in callback
    name, args = message.split('_~_')
ValueError: too many values to unpack (expected 2)`

getting this error when setting the chart()

`        chart = Chart()
        chart.time_scale(right_offset=20)
        chart.legend(visible=True, percent=True)
        chart.price_scale(scale_margin_top=0.1, scale_margin_bottom=0.1)
        chart.grid(False)
        chart.volume_config(scale_margin_top=0.88)
        chart.crosshair(vert_visible=False, horz_visible=False)`

**Comment by mash420** [comment]
yeah the chart loads then prints that error.
I narrowed it down to this:
`            chart = await self.generate_chart(df)
            chart.show(block=False)
            time.sleep(1)
            img = chart.screenshot()
            `
once i include the screenshot method, it crashes.

**Comment by louisnw01** [comment]
Yes it was to do with the screenshot method; I just published a hotfix (1.0.16.1) to address.

Let me know if it works,

Louis

**Comment by mash420** [comment]
fixed! thanks
