### ISSUE TITLE
Line/Tick charting does not work

### ISSUE THREAD

**Issue by c0mm0d0re** [louisnw01/lightweight-charts-python#61]
Send you an email on this but haven't heard so...

When we have time and price columns, this lib breaks. Not sure if you are in finance but your main priority should be showing simple line charts not candle charts that require ohlc. Candle charts embed a system within (you can also call it an interpretation if you will) signifying what has happened in a non-objective way. 

This is a great start for a great lib and you must take this into account. Example code below to show what happens:

```
import yfinance as yf
from lightweight_charts import Chart
if __name__ == '__main__':
    df = yf.Ticker("spy").history(start="2023-01-02", interval="1d")
    df = df.reset_index().rename(columns = {"Date": "time", "Open": "open", "High": "high", "Low": "low", "Close": "close", "Volume": "volume"})
    chart = Chart(volume_enabled=False)
    chart.legend(visible=True)
    chart.set(df[['time','close']]) # if you just put df, everything works just fine.
    chart.show(block=True)

```

**Comment by louisnw01** [comment]
Hey @c0mm0d0re,

I'd greatly appreciate it if you read the documentation before raising issues; see [here](https://lightweight-charts-python.readthedocs.io/en/latest/common_methods.html#create-line-line) and [here](https://github.com/louisnw01/lightweight-charts-python/blob/main/examples/4_line_indicators/line_indicators.py)

**Comment by c0mm0d0re** [comment]
No. did you copy/paste what i did and see what happens? Do it with a df that does not have ohlc. or show me with a code with yfinance like i did...

**Comment by louisnw01** [comment]
> No. did you copy/paste what i did and see what happens? Do it with a df that does not have ohlc. or show me with a code with yfinance like i did...

Yes; your attempting to put line data into the `set` function, which only takes candle data. Again, please read the docs, or, if you're new to coding, work your way up from the example I linked.

Louis
