### ISSUE TITLE
QtChart support for PySide6

### ISSUE THREAD

**Issue by kasoob** [louisnw01/lightweight-charts-python#62]
Hello louis,
Thank you for this amazing tv charts module. Couldn't have asked for anything better.

I am trying to create my own Qt application that incorporates lightweight charts. However, my app runs using PySide6 due to better licensing options and the fact that it is the latest Qt version. I understand that the QtChart class runs on PyQt5, which works perfectly, but of course is incompatible with PySide6, which is a major downside.

I have had hard time trying to incorporate your QtCharts into my PySide6 application with all sorts of errors, till I finally decided to take a look on your widgets source code. I switched up the modules and had to change 'pyqtSlot' to 'Slot' as you can see in the code below. Everything seems to work fine with my attempt to trasnfer it to PySide6.

Perhaps consider adding PySide6 functionality to lighteright-charts as an additional option?

Here's the PySide6 version of the widgets code:
```
try:
    from PySide6.QtWebEngineWidgets import QWebEngineView
    from PySide6.QtWebChannel import QWebChannel
    from PySide6.QtCore import QObject, Slot

    class Bridge(QObject):
        def __init__(self, chart):
            super().__init__()
            self.chart = chart

        @Slot(str)
        def callback(self, message):
            _widget_message(self.chart, message)
except ImportError:
    raise
    QWebEngineView = None
```

I made no other changes. However one thing that is bothering of course is the fact that it prints the following into the terminal as the chart is being created, which I will attempt to supress later on:

```
qt.webenginecontext:

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name python
  *  browser-subprocess-path C:\Users\abdel\AppData\Local\Programs\Python\Python311\Lib\site-packages\PySide6\.\QtWebEngineProcess.exe
  *  create-default-gl-context
  *  disable-es3-gl-context
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture       
  *  disable-speech-api
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess
  *  enable-threaded-compositing
  *  in-process-gpu
  *  use-gl desktop
```

What do you think? That would definitely be a neat addition to the functionalities of your module :)

**Comment by louisnw01** [comment]
Hey @kasoob,

Great work; I'll get this implemented for the next update. Let me know if you find a fix for the logging.

Louis

**Comment by kasoob** [comment]
Suppressing the logging is simple, just use the following:
`from PySide6.QtCore import QLoggingCategory
QLoggingCategory("qt.webenginecontext").setFilterRules("*.info=false")`

**Comment by kasoob** [comment]
Additionally, I found a bug regarding updates showing up when using the QtChart in complex applications.

It is strange since it works perfectly fine when the chart is being shown in its own window, however when it comes to a QStackedWidget (i.e. multiple pages interface) changes to the chart seem to only update when the layout of the current page changes in any way or if the page is changed then switched back.

I haven't determined exactly why this is so, however, through several tests I can tell that the issue is related to the event loop of the Qt application not picking up on changes to the Javascript in order to update it, when it comes to a QWebEngineView widget inside a QStackedWidget.

My initial thoughts were to connect mouse movement and mouse click event signals to the repaint method of the QWebEngineView widget, however, that did not work since the cursor directly interacts directly with the Javascript rather than the QWebEngineView widget.

My solution was to set a QTimer that updates the view of the QWebEngineView through the repaint method of the QWebEngineView after a custom interval, I used 50 milliseconds below inside my custom class:
```
        self.timer = QTimer()
        self.timer.timeout.connect(lambda: self.webview.repaint())
        self.timer.start(50)
```
This method works fine for overcoming the bug, however I understand it is not as efficient as resolving the bug. Perhaps the issue is with communicating updates back to the bridge between the python and javascript. I don't know much javascript so I couldn't look deeper into it, but it would be great if this was resolved in the upcoming update. I think what we should implement is calling webview.repaint() whenever the javascript of the webview changes, or perhaps whenever the cursor interacting with the javascript moves or is clicked.

**Comment by kasoob** [comment]
Additionally, I found a bug regarding updates showing up on the QtChart widget on complex applications.

It is strange since it works perfectly fine when the chart is being shown in its own window, however when it comes to a QStackedWidget (i.e. multiple pages interface) changes to the chart seem to only update when if the layout of the current page changes in any way or if the page is changed then switched back.

I haven't determined exactly why this is so, however, through several tests I can tell that the issue is related to the event loop of the Qt application not picking up on changes to the Javascript in order to update it, when it comes to a QWebEngineView widget inside a QStackedWidget.

My inital thoughts were to connect mouse movement and mouse click event signals to the repaint method of the QWebEngineView object, however, that did not work since the 

My solution was to set a QTimer that updates the view of the QWebEngineView through the repaint method of the QWebEngineView after a custom interval, I used 50 milliseconds below inside my custom class:
```
        self.timer = QTimer()
        self.timer.timeout.connect(lambda: self.webview.repaint())
        self.timer.start(50)
```
This method works fine for overcoming the bug, however I understand it is not as efficient as resolving the bug. Perhaps the issue is with communicating updates back to the bridge between the python and javascript. I don't know much javascript so I couldn't look deeper into it, but it would be great if this was resolved in the upcoming update. I think what we should implement is calling webview.repaint() whenever the javascript of the webview changes, or perhaps whenever the cursor interacting with the javascript moves or is clicked.

**Comment by kasoob** [comment]
Hello Louis,

Would it be possible to address this issue in the next update?

Using QTimer as an alternative is really slowing my program due to taking up my main event loop, it would be great if this bug is addressed.

**Comment by kasoob** [comment]
Hello Louis,

Would it be possible to address this issue in the next update?

Using QTimer as an alternative is really slowing my program due to taking up my main event loop, it would be great if this bug is addressed.

**Comment by louisnw01** [comment]
This feature has been added in the latest version; QtChart will work with either PySide6 or PyQt5.

As for the QTimer issue, this seems like a bug with PySide rather than this library; Your best bet would be to make a minimal reproducible example using the QWebEngineView and raise an issue to the devs.

Louis
