### ISSUE TITLE
black screen with some components in the chart

### ISSUE THREAD

**Issue by vck777** [louisnw01/lightweight-charts-python#63]
Hello,

I'm using lightweight-charts-python on docker container and get the view on the host machine which is Ubuntu 22.04. It was not easy to get some result but it seems I can see a bit of light. I think the chart works but have some graphic issues. As you can see an image below, I can see the ohlc (but no volume?) and cross-hair. Even I can adjust the right side (price) and bottom (date) with my mouse cursor even though I can't see it. 
The thing is that I can't see the candles and volume bar on the chart.
 
![Screenshot of Microsoft Remote Desktop (8-8-23, 9-54-22 AM)](https://github.com/louisnw01/lightweight-charts-python/assets/140236823/26f1b265-fe09-458c-b9b6-7b71faa8d15b)

I've tried already the pywebview's example view and have no problem with that as you can see the image below. 

![Screenshot of Microsoft Remote Desktop (8-8-23, 10-10-51 AM)](https://github.com/louisnw01/lightweight-charts-python/assets/140236823/5d55084b-7959-473c-baea-becd2fdb7e63)

I tried it on both python3.11 and 3.10 in docker container, but the results are the same. I'm not sure what the problem is. Any thoughts? Thank you.

**Comment by louisnw01** [comment]
Hi, could you send over the code you are using and the data you are using.

Thanks!

**Comment by vck777** [comment]
I used the code from your example with data from my db server. 

Now I just tried with ohlcv.csv you provided in the example to check just in case of wrong pandas df settings. Even though I use the code and data exactly same with you provided, the result is the same.



import pandas as pd
from lightweight_charts import Chart

if __name__ == '__main__':
    
    chart = Chart(debug=True)

    df = pd.read_csv('ohlcv.csv')

    chart.layout(background_color='#090008', text_color='#FFFFFF', font_size=16,
                 font_family='Helvetica')

    chart.candle_style(up_color='#00ff55', down_color='#ed4807',
                       border_up_color='#FFFFFF', border_down_color='#FFFFFF',
                       wick_up_color='#FFFFFF', wick_down_color='#FFFFFF')

    chart.volume_config(up_color='#00ff55', down_color='#ed4807')

    chart.watermark('1D', color='rgba(180, 180, 240, 0.7)')

    chart.crosshair(mode='normal', vert_color='#FFFFFF', vert_style='dotted',
                    horz_color='#FFFFFF', horz_style='dotted')

    chart.legend(visible=True, font_size=14)

    chart.set(df)

    chart.show(block=True)


![Screenshot of Microsoft Remote Desktop (8-9-23, 3-57-34 AM)](https://github.com/louisnw01/lightweight-charts-python/assets/140236823/a29b532c-f45b-4fe6-a71d-698c90ae5e8c)


Thanks!

**Comment by vck777** [comment]
by the way, I use v1.0.15 for lightweight-charts-python

**Comment by louisnw01** [comment]
Hey,

Can you enable debug (`chart = Chart(debug=True)`), right click on the window and send a screenshot of the web console?

Thanks!

**Comment by louisnw01** [comment]
In your docker file, try adding this:

```
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
```

**Comment by vck777** [comment]
Thanks for your advice!

You gave me a good clue to figure out the issue. The problem was that the locale setting for my host machine was in en_US.UTF-8 but only C.UTF-8 was available in the docker container. So I guess when the container send the chart to host machine, it was in C.UTF-8 and that's why I got the error.

So I added below ENVs and RUNs in my Dockerfile to align locales between host and container, then it works like a charm! 

ENV     LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8 
    
RUN apt-get install -y locales && \
    sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen en_US.UTF-8 && \
    update-locale LANG=en_US.UTF-8

![Screenshot of Microsoft Remote Desktop (8-9-23, 9-02-13 AM)](https://github.com/louisnw01/lightweight-charts-python/assets/140236823/28eb4360-8e42-497f-978f-bc54c765ad8a)

Thank for this great project!

**Comment by Harsh-Maheshwari** [comment]
How to Solve this issue for WSL2 ?

**Comment by fmigch** [comment]
> How to Solve this issue for WSL2 ?

This [page ](https://askubuntu.com/questions/359753/gtk-warning-locale-not-supported-by-c-library-when-starting-apps-from-th) helped me a lot. For me it was resolved as soon as I entered the following into the terminal: 'export LC_ALL="en_US.UTF-8"'.
