### ISSUE TITLE
Issue with Rays

### ISSUE THREAD

**Issue by mash420** [louisnw01/lightweight-charts-python#64]
`async def generate_chart(self, df):
    chart = Chart(x=0, y=0, width=1200, height=800)  # Set the chart window title
    chart.time_scale(right_offset=20)
    chart.legend(visible=True, percent=True)
    chart.price_scale(scale_margin_top=0.1, scale_margin_bottom=0.1)
    chart.grid(False)
    chart.volume_config(scale_margin_top=0.88)
    chart.crosshair(vert_visible=False, horz_visible=False)
    if self.indicators is not None:
        if 'nv' in self.indicators:
            chart.volume_enabled = False

    chart.set(df)
    chart.run_script(f'''
    window.logicalRange = {chart.id}.chart.timeScale().getVisibleLogicalRange()
    ''')
    symbol = str(self.symbol.replace('/USDT:USDT', ''))
    chart.watermark(text=f'{symbol}, {self.timeframe}')

`
![BTCUSDT-2023-08-08 080836 127801](https://github.com/louisnw01/lightweight-charts-python/assets/81828831/99e65260-71d8-42d9-9375-63075aa7cca7)

there is still a bug for rendering rays to the chart. I had to include the chart.run_script() code to get it to work

**Comment by louisnw01** [comment]
Thanks @mash420, this bug is really annoying. Aiming to patch for the next update.
