### ISSUE TITLE
Apply chart numerical precision to legend OHLC overlay

### ISSUE THREAD

**Issue by robustify** [louisnw01/lightweight-charts-python#65]
Hello! Thanks for all your effort; it is greatly appreciated.

I saw issue https://github.com/louisnw01/lightweight-charts-python/issues/34 and was able to use the new `precision` method to set the numerical precision of the chart. I'm wondering if it is easy enough to pass that same precision to the OHLC overlay, which still uses 2 decimal places as shown below.

![EUR_USD_chart](https://github.com/louisnw01/lightweight-charts-python/assets/8763875/fd1921c9-7dd3-4c28-a990-bc35eee0c315)

**Comment by louisnw01** [comment]
Hey @robustify,

Great idea; I'll aim to add it for the next update.

Louis

**Comment by louisnw01** [comment]
Legend precision will now follow the chart precision in the latest version (1.0.16).

Louis

**Comment by nickbell52** [comment]
I don't think this is fixed! Tried 1.0.16...to no avail, and I'm now on 2.1 with the same problem. I'm developing my software on Ubuntu Visual Code. Thanks for all the effort in providing us with this python option. It's working wonderfully for me on Raspberry Pi 4 and 5 apart from the above.

If anyone has any tips please pass them on!

**Comment by robustify** [comment]
Hi @nickbell52,

I just looked into this, and it seems to work fine for any 1.0.x version, but starting in 2.0 it regressed to its 2-digit precision regardless of what you pass to the `precision` method.

I tracked it down and opened a PR to the latest `main` branch to restore the functionality:
https://github.com/louisnw01/lightweight-charts-python/pull/500

**Comment by nickbell52** [comment]
Thanks Micho!

Running this on my desktop using VS Code, as well as on a couple of
Raspberry Pis with Lightweight-Charts downloaded from piWheels.
I spent a week or two trying to get the charts to work on the Pis and
obviously got muddled with the versions along the way and hadn't noticed
versions 1.0.x were OK.

Regards,
Nick
