### ISSUE TITLE
Style candles/bars individually using logic conditions

### ISSUE THREAD

**Issue by matthewjarman** [louisnw01/lightweight-charts-python#67]
Hello Louis,

Thank you for your amazing work here - it's awesome!

Is there a way to style bars individually using logic conditions, overriding the overall general candle_style settings?  The end result would look like:
https://tradingview.github.io/lightweight-charts/tutorials/customization/data-points

For example, I want to style a "3 up" engulfing candle (h>h1 & l<l1 & o<c, where h is today's high and h1 is yesterday's high, etc) in a certain way.  The "3 up" would be have specific up/down color, up/down border, and up/down wick properties to distinguish it visually from the other 7 candle pattern styles I would implement.

I did this successfully using mplfinance already:
https://github.com/matplotlib/mplfinance/blob/master/examples/marketcolor_overrides.ipynb (for reference)

But your library is noticeably faster and superior in multiples ways, so I'm hoping there is a way to do this.

Many thanks!

**Comment by jlixfeld** [comment]
#thestrat?

**Comment by louisnw01** [comment]
Hey @matthewjarman,

Thank you!

I took a look at that example you linked and it seems all the code does it add a 'color' column to the dataset.

I added a color column to a normal `ohlcv.csv` with `df['color'] = 'orange'` and that will give you an entirely orange candle series( you can also add `borderColor`, `wickColor` as columns to style those too).

In order to style individual ones, you'll need to fill your candle data with the normal up/down colors, and then add in your specific colouring. For example:

```python
import pandas as pd
from lightweight_charts import Chart

df = pd.read_csv('ohlcv.csv')

if __name__ == '__main__':
    chart = Chart()

    for column in ('color', 'wickColor', 'borderColor'):
        df[column] = 'red'
        df.loc[df['close'] > df['open'], column] = 'green'
        df.loc[df.index[-10]:df.index[-1], column] = 'orange'

    chart.set(df)
    chart.show(block=True)

```

I had no idea this was a feature in Lightweight Charts; thanks for pointing it out.

Louis

**Comment by matthewjarman** [comment]
Hi Louis,

Thank you for quick reply!  I appreciate it!

When I try the code snippet above, it appears only the body color ('color )is being recognized/processed, and not the wickColor or borderColor. 

 I also encoded a price DataFrame using a separate method with exactly the colors combos I want, and noticed the same thing when the chart was rendered.

In the pic below, I took your code snippet and then changed the body colors to make this issue easier to see - the chart is of AAPL though 8/9.  Orange is now yellow and green is now purple.  This makes seeing the green wicks and green borders for up days & red wicks and red borders for down days easier to see.  By observation, looks like up days are close > open, and down days the opposite.

Any ideas on why this happens?  It's pretty cool that this is so close to working!

<img width="1056" alt="Screenshot 2023-08-12 at 22 25 29" src="https://github.com/louisnw01/lightweight-charts-python/assets/108485277/aa5c8aad-7d66-4335-8a1c-8c453ef63bcc">

**Comment by louisnw01** [comment]
Does that occur when using one of the `ohlcv.csv`'s from the examples? Its working on my end (version 1.0.15).

**Comment by matthewjarman** [comment]
Figured it out by comparing the ohlcv.csv columns to my df columns and doing some tinkering.  For the individual coloring to work, the df cannot have the date as the index.  Once the index is reset, the 'date' column must be named 'date' and not 'Date'.  I had my df setup correctly otherwise.  

It works perfectly now.  Very cool.

Many thanks!

**Comment by nipunshrivastava** [comment]
@matthewjarman Can we even color the volume candles?

**Comment by matthewjarman** [comment]
@nipunshrivastava you can, but you need to create a subchart to do it.  I have not figured out a way to manipulate the volume colors when the volume is plotted in the main chart window.  If interested you can create a colored volume subchart with the following steps:

(1) Transform the volume data: take the single "array" of volume values and convert them into an OHLC DataFrame (now a histogram) where open = 0, low = 0, high = volume[x], close = volume[x], where x is the current position in the index.  

(2) Add colors as desired: you can add any or all of these three columns to the DataFrame - 'color', 'wickColor', 'borderColor'.  Loop through the DataFrame and assign colors like 'red' (etc) or RGB or RGBA values to whichever of these columns you want to add.

Here's what I did to create the subchart according to my visual preferences - I called it chart2 since it's below the main chart window (chart1).

```
# Create chart #2: volume
chart2 = chart.create_subchart(width=1, height=0.5/num_sub_charts, sync=True)
chart2.precision(0)
chart2.legend(visible=True, font_family='Trebuchet MS', ohlc=False, percent=False)
chart2.price_line(line_visible=False)
chart2.price_scale(text_color='grey')
chart2.time_scale(time_visible=False, visible=False)
chart2.grid(vert_enabled=False, horz_enabled=False)
chart2.run_script(f'{chart2.id}.series.applyOptions({{priceFormat: {{type: "volume"}}}})')
volume = test.xform_vol_ohlc_df(ticker)
chart2.set(volume)
```

Here's the code for xform_vol_ohlc_df().  It performs steps (1) and (2) from above.  It written to be easy to understand and not optimized for speed.  As FYI, the color scheme is for the Strat candle patterns (by Rob Smith), which is how I look at candle patterns on charts.  It's a personal preference, so color the volume bars according to whatever scheme you desire.

```
def xform_vol_ohlc_df(self, ticker_param):
    """
    'create_vol_ohlc_df' creates a ohlc DataFrame for volume
    """
    try:
        data = self.load_price_data(ticker_param.upper())
        opens = np.zeros(shape=data.shape[0], dtype=float)
        highs = np.zeros(shape=data.shape[0], dtype=float)
        lows = np.zeros(shape=data.shape[0], dtype=float)
        closes = np.zeros(shape=data.shape[0], dtype=float)

        for i in range(1, data.shape[0]):
            highs[i] = data.at[data.index[i], 'Volume']
            closes[i] = data.at[data.index[i], 'Volume']

        tmp_df = pd.DataFrame()
        tmp_df['date'] = data.index
        tmp_df['open'] = opens
        tmp_df['high'] = highs
        tmp_df['low'] = lows
        tmp_df['close'] = closes

        bodyColor = np.empty(shape=data.shape[0], dtype=np.chararray)
        bodyColor.fill('red')
        wickColor = np.empty(shape=data.shape[0], dtype=np.chararray)
        wickColor.fill('red')
        borderColor = np.empty(shape=data.shape[0], dtype=np.chararray)
        borderColor.fill('red')

        for i in range(1, tmp_df.shape[0]):
            cur_date = data.index[i]
            o = data.at[data.index[i], 'Adj_Open']
            h = data.at[data.index[i], 'Adj_High']
            l = data.at[data.index[i], 'Adj_Low']
            c = data.at[data.index[i], 'Adj_Close']
            o1 = data.at[data.index[i-1], 'Adj_Open']
            h1 = data.at[data.index[i-1], 'Adj_High']
            l1 = data.at[data.index[i-1], 'Adj_Low']
            c1 = data.at[data.index[i-1], 'Adj_Close']

            if h <= h1 and l >= l1 and c > o:
                bodyColor[i] = 'black'
                wickColor[i] = 'yellow'
                borderColor[i] = 'yellow'
            elif h <= h1 and l >= l1 and c <= o:
                bodyColor[i] = 'yellow'
                wickColor[i] = 'yellow'
                borderColor[i] = 'yellow'
            elif h > h1 and l < l1 and c > o:
                bodyColor[i] = 'black'
                wickColor[i] = 'cyan'
                borderColor[i] = 'cyan'
            elif h > h1 and l < l1 and c <= o:
                bodyColor[i] = 'cyan'
                wickColor[i] = 'cyan'
                borderColor[i] = 'cyan'
            elif h > h1 and l >= l1 and c > o:
                bodyColor[i] = 'black'
                wickColor[i] = 'green'
                borderColor[i] = 'green'
            elif h > h1 and l >= l1 and c <= o:
                bodyColor[i] = 'green'
                wickColor[i] = 'green'
                borderColor[i] = 'green'
            elif h <= h1 and l < l1 and c > o:
                bodyColor[i] = 'black'
                wickColor[i] = 'red'
                borderColor[i] = 'red'
            else:  # h <= h1 and l < l1 and c <= o:
                bodyColor[i] = 'red'
                wickColor[i] = 'red'
                borderColor[i] = 'red'

        tmp_df['color'] = bodyColor
        tmp_df['wickColor'] = wickColor
        tmp_df['borderColor'] = borderColor

        self.last_op = 'create_vol_ohlc_df'
        self.last_outcome = 'SUCCESS'
        return tmp_df

    except Exception as e:
        self.last_op = 'create_vol_ohlc_df'
        self.last_outcome = 'FAIL: {:s}'.format(str(e))
        traceback.print_exc()
        return None

```

Hope this helps.
