### ISSUE TITLE
Is it possible to access lineStyle in LineStyleOptions & type in PriceFormatBuiltIn?

### ISSUE THREAD

**Issue by matthewjarman** [louisnw01/lightweight-charts-python#68]
Hi Louis,

I want to access the 'lineStyle' property from the LineStyleOptions interface for a line indicator so that I can set it dashed, dotted, etc - I tried adding a 'lineStyle' column to the indicator df, hoping it would work like to coloring did earlier, but to no avail.  Is it possible to access/set this property?
https://tradingview.github.io/lightweight-charts/docs/api/interfaces/LineStyleOptions
https://tradingview.github.io/lightweight-charts/docs/api/enums/LineStyle

Also, I want to access the 'type' property through the PriceFormatBuiltIn interface, so that I can set price axis for an indicator to use 12.7M vs 12700000 (for example) by specifying the type to 'volume'. Is there a way to do this?
https://tradingview.github.io/lightweight-charts/docs/api/interfaces/PriceFormatBuiltIn

Your library is awesome in how quickly a more complicated chart can be created.  Using 70 lines so far, I have created one chart and 2 sub charts (all sync'ed), looking exactly how I want pending the above questions.  Doing the same using mplfinance or other approaches I have tried takes 100s & 100s of lines of codes to achieve.  This is really well done.

Thanks!

**Comment by louisnw01** [comment]
Added the `style` parameter to `create_line` in the latest version (1.0.16).

Louis

**Comment by matthewjarman** [comment]
style parameter for lineStyle works great - thanks!

Is the other request ('type' property through the PriceFormatBuiltIn interface) hard to do?  I ask b/c I have no idea, and if it is, I'll find a workaround for not having it.  In part the reason for asking for it is to fix the issue in the screenshot below, where the right hand sides of the time scales on the three charts don't line up since the units on the price axes are sufficiently different lengths/sizes.  Is there another way to address this?

Also - I feel like this is a stupid question, but I'm having trouble drawing a horizontal line on cci_chart (bottom one).  If I want a basic h-line at 0, should it just be: cci_chart.horizontal_line(0) ?  I feel like I am missing something simple here.

Many thanks!
<img width="944" alt="Screenshot 2023-08-14 at 13 15 26" src="https://github.com/louisnw01/lightweight-charts-python/assets/108485277/9d7093e3-a8c2-4ce2-aaf2-17469b9d324c">

**Comment by louisnw01** [comment]
Hey,

The `type` can be set using this for now:

```python
chart.run_script(f'{chart.id}.series.applyOptions({{priceFormat: {{type: "volume"}}}})')
```

Let me know if you are able to get your price scales aligned; this is an issue with the original Lightweight Charts library as they don't officially support multipane charts.

As for setting the horizontal line, you'll want to use `horizontal_line` on the line object:

```python
line = chart.create_line('ema')
line.horizontal_line(0)
```

Louis

**Comment by matthewjarman** [comment]
Hi Louis,

Thank you for showing me how to run a script - didn't know how to do that - works great!

I can get the horizontal line to work only on charts/subcharts where there is OHLC data in the DataFrame.  Not a big deal since I can transform any line indicator into OHLC to create a histogram.  On the line indicator charts, I tried combinations of chart.set(df) and line.set(df), but could't figure it out.  The line indicator renders perfectly, but not the h-line.

I've been toying with various settings (and OHLC vs line data) to get the charts to line up on the right-hand-side.  It's still a work-in-progress.  It's better with the 'volume' type for priceFormat, and interestingly not affected by OHLC vs line data.  I would have thought have equally sized and equally spaced bars would help, but it doesn't have any effect.  Some series are narrower or wider than others visually - I'll keep investigating and tinkering.

One final question - is there a way to remove the default dot in the crosshair as it moves across a series when the cursor is moved left/right?  It's not present on the main chart crosshairs, but is present on all of the sub chart crosshairs.

Appreciate all of the help!

**Comment by louisnw01** [comment]
I havent implemented removal of the crosshair marker yet; however you can use:

```python
line.run_script(f'{line.id}.series.applyOptions({crosshairMarkerVisible: false})')
```

As for the horizontal line on a line series with no ohlc, could you provide a minimal reproducible example and i'll take a look, as it seems to work fine on my end.

Louis
