### ISSUE TITLE
Jupyter lab enhancement!! 

### ISSUE THREAD

**Issue by Morakhiyasaiyam** [louisnw01/lightweight-charts-python#69]
Purely great work ! But I can getting problem with jupyter lab

1. It's working only if I plot candles as soon as I add any other lines to chart it doesn't show anything in widget
2. If everything works perfectly then can you make it to load in real-time for jupyter because now it's only static ?

**Comment by louisnw01** [comment]
Hey @Morakhiyasaiyam,

Could you send over a minimal reproducible example, that uses one of the `ohlcv.csv` in regard to lines not working?

As for real-time, this isn't a possibility in Jupyter to my knowledge.

Louis

**Comment by Morakhiyasaiyam** [comment]
Hey yes I was but busy I will give you example in mean time !!
