### ISSUE TITLE
RSI / MACD panel

### ISSUE THREAD

**Issue by mash420** [louisnw01/lightweight-charts-python#71]
Any way/plan to add a panel to main chart window?
I get a lot of use from the screenshot function so would be nice to have it all be in one window.

**Comment by louisnw01** [comment]
Documentation has an example [here](https://lightweight-charts-python.readthedocs.io/en/latest/common_methods.html#synced-line-chart-example).

When you screenshot however, it will only screenshot one of the panes. So you'll have to use some python magic to stitch the two screenshots of each panel together.

Louis

**Comment by mash420** [comment]
I see.

do the columns for the rsi need to be named anything specific?

**Comment by mash420** [comment]
`                   time       close
1   2023-08-16 10:45:00  116381.835
2   2023-08-16 10:50:00  116423.881
3   2023-08-16 10:55:00  116438.337
4   2023-08-16 11:00:00  116466.773
5   2023-08-16 11:05:00  116459.337
..                  ...         ...
96  2023-08-16 18:40:00  117374.671
97  2023-08-16 18:45:00  117458.638
98  2023-08-16 18:50:00  117454.446
99  2023-08-16 18:55:00  117448.049
100 2023-08-16 19:00:00  117524.918`

cant get it to print this line

**Comment by louisnw01** [comment]
Column should be named whatever the name of the line is.

Louis
