### ISSUE TITLE
Any datetime support

### ISSUE THREAD

**Issue by OdinLin** [louisnw01/lightweight-charts-python#73]
It seen that whether marker or line, they only display within the max bar datetime, Can It support this widget put at any datetime?

**Comment by louisnw01** [comment]
Hey @OdinLin,

I'm unsure as to why you would need markers to be placed after the last bar as there is nothing to 'mark'.

By line i'm assuming your referring to `create_line`; this can be displayed further than the last candle bar.

If i've misunderstood, could you provide a minimal reproducible example, describing what you would expect to happen and what actually happens?

Louis

**Comment by louisnw01** [comment]
You could place a marker after the last candle by first creating a line and then placing a marker on that line:

```python
import pandas as pd

from lightweight_charts import Chart

if __name__ == '__main__':
    chart = Chart()

    df = pd.read_csv('ohlcv.csv', parse_dates=['date'])

    line = chart.create_line()

    marker_line = pd.DataFrame([
        {'time': df.iloc[-1]['date']+pd.Timedelta(days=1), 'value': 200},
        {'time': df.iloc[-1]['date']+pd.Timedelta(days=2), 'value': 200},
    ])
    line.set(marker_line)
    line.marker(marker_line.iloc[0]['time'])
    chart.set(df)
    chart.show(block=True)

```
