### ISSUE TITLE
"list index out of range" error after updating to the new release version

### ISSUE THREAD

**Issue by premkn** [louisnw01/lightweight-charts-python#74]
File "/venv/lib/python3.9/site-packages/lightweight_charts/chart.py", line 73, in __init__
    self._loaded = chart._loaded_list[num_charts]
IndexError: list index out of range

-------------------------------------
Receiving this error on the Chart initialization 

        self.chart = Chart()

**Comment by premkn** [comment]
Debug Output
--------------------
2023-08-18 18:12:35.846 Python[12533:2777991] NSWindow warning: adding an unknown subview: <WKInspectorWKWebView: 0x1247bea20>. Break on NSLog to debug.
2023-08-18 18:12:35.849 Python[12533:2777991] Call stack:
(
        0   AppKit                              0x0000000198353b58 -[NSThemeFrame addSubview:] + 116
        1   AppKit                              0x0000000198353838 -[NSView addSubview:positioned:relativeTo:] + 176
        2   AppKit                              0x0000000198353704 -[NSThemeFrame addSubview:positioned:relativeTo:] + 52
        3   WebKit                              0x00000001b614fc5c _ZN6WebKit19WebInspectorUIProxy14platformAttachEv + 340
        4   WebKit                              0x00000001b632de00 _ZN6WebKit19WebInspectorUIProxy4openEv + 156
        5   WebKit                              0x00000001b65921a4 _ZN6WebKit19WebInspectorUIProxy17didReceiveMessageERN3IPC10ConnectionERNS1_7DecoderE + 184
        6   WebKit                              0x00000001b668a600 _ZN3IPC18MessageReceiverMap15dispatchMessageERNS_10ConnectionERNS_7DecoderE + 264
        7   WebKit                              0x00000001b62d3574 _ZN6WebKit15WebProcessProxy17didReceiveMessageERN3IPC10ConnectionERNS1_7DecoderE + 40
        8   WebKit                              0x00000001b6685df0 _ZN3IPC10Connection15dispatchMessageENSt3__110unique_ptrINS_7DecoderENS1_14default_deleteIS3_EEEE + 332
        9   WebKit                              0x00000001b668629c _ZN3IPC10Connection24dispatchIncomingMessagesEv + 284
        10  JavaScriptCore                      0x00000001af50dcf4 _ZN3WTF7RunLoop11performWorkEv + 200
        11  JavaScriptCore                      0x00000001af50ebc0 _ZN3WTF7RunLoop11performWorkEPv + 36
        12  CoreFoundation                      0x000000019511263c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
        13  CoreFoundation                      0x00000001951125d0 __CFRunLoopDoSource0 + 176
        14  CoreFoundation                      0x0000000195112340 __CFRunLoopDoSources0 + 244
        15  CoreFoundation                      0x0000000195110f48 __CFRunLoopRun + 828
        16  CoreFoundation                      0x00000001951104b8 CFRunLoopRunSpecific + 612
        17  HIToolbox                           0x000000019e95ac40 RunCurrentEventLoopInMode + 292
        18  HIToolbox                           0x000000019e95aa7c ReceiveNextEventCommon + 648
        19  HIToolbox                           0x000000019e95a7d4 _BlockUntilNextEventMatchingListInModeWithFilter + 76
        20  AppKit                              0x0000000198331d44 _DPSNextEvent + 636
        21  AppKit                              0x0000000198330ee0 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 716
        22  AppKit                              0x0000000198325344 -[NSApplication run] + 464
        23  libffi.dylib                        0x00000001a4f1c050 ffi_call_SYSV + 80
        24  libffi.dylib                        0x00000001a4f24af8 ffi_call_int + 1208
        25  _objc.cpython-39-darwin.so          0x000000011bcafd84 PyObjCFFI_Caller + 1232
        26  _objc.cpython-39-darwin.so          0x000000011bcd1148 objcsel_vectorcall + 428
        27  Python3                             0x0000000102a3a604 _PyEval_EvalFrameDefault + 34596
        28  Python3                             0x0000000102a37754 _PyEval_EvalFrameDefault + 22644
        29  Python3                             0x0000000102969010 _PyFunction_Vectorcall + 420
        30  Python3                             0x0000000102a3a604 _PyEval_EvalFrameDefault + 34596
        31  Python3                             0x0000000102a37730 _PyEval_EvalFrameDefault + 22608
        32  Python3                             0x0000000102a3b4ac _PyEval_EvalFrameDefault + 38348
        33  Python3                             0x0000000102968f58 _PyFunction_Vectorcall + 236
        34  Python3                             0x0000000102a3a604 _PyEval_EvalFrameDefault + 34596
        35  Python3                             0x0000000102a377d0 _PyEval_EvalFrameDefault + 22768
        36  Python3                             0x0000000102a3b4ac _PyEval_EvalFrameDefault + 38348
        37  Python3                             0x0000000102968f58 _PyFunction_Vectorcall + 236
        38  Python3                             0x0000000102a3a604 _PyEval_EvalFrameDefault + 34596
        39  Python3                             0x0000000102a37754 _PyEval_EvalFrameDefault + 22644
        40  Python3                             0x0000000102a3b4ac _PyEval_EvalFrameDefault + 38348
        41  Python3                             0x0000000102968f58 _PyFunction_Vectorcall + 236
        42  Python3                             0x0000000102a3a604 _PyEval_EvalFrameDefault + 34596
        43  Python3                             0x0000000102a3784c _PyEval_EvalFrameDefault + 22892
        44  Python3                             0x0000000102969010 _PyFunction_Vectorcall + 420
        45  Python3                             0x00000001029685f0 _PyObject_FastCallDictTstate + 272
        46  Python3                             0x0000000102969338 _PyObject_Call_Prepend + 148
        47  Python3                             0x00000001029cd75c _PyType_Lookup + 38048
        48  Python3                             0x00000001029c4bb8 _PyType_Lookup + 2300
        49  Python3                             0x0000000102968d98 _PyObject_Call + 172
        50  Python3                             0x0000000102a37a28 _PyEval_EvalFrameDefault + 23368
        51  Python3                             0x0000000102969010 _PyFunction_Vectorcall + 420
        52  Python3                             0x0000000102a3a604 _PyEval_EvalFrameDefault + 34596
        53  Python3                             0x0000000102a37730 _PyEval_EvalFrameDefault + 22608
        54  Python3                             0x0000000102a3b4ac _PyEval_EvalFrameDefault + 38348
        55  Python3                             0x0000000102968f58 _PyFunction_Vectorcall + 236
        56  Python3                             0x0000000102a3a604 _PyEval_EvalFrameDefault + 34596
        57  Python3                             0x0000000102a37730 _PyEval_EvalFrameDefault + 22608
        58  Python3                             0x0000000102969010 _PyFunction_Vectorcall + 420
        59  Python3                             0x0000000102a3a604 _PyEval_EvalFrameDefault + 34596
        60  Python3                             0x0000000102a377d0 _PyEval_EvalFrameDefault + 22768
        61  Python3                             0x0000000102a3b4ac _PyEval_EvalFrameDefault + 38348
        62  Python3                             0x0000000102968f58 _PyFunction_Vectorcall + 236
        63  Python3                             0x0000000102a3a604 _PyEval_EvalFrameDefault + 34596
        64  Python3                             0x0000000102a3784c _PyEval_EvalFrameDefault + 22892
        65  Python3                             0x0000000102a3b4ac _PyEval_EvalFrameDefault + 38348
        66  Python3                             0x0000000102a31e18 PyEval_EvalCode + 80
        67  Python3                             0x0000000102a75e54 PyParser_ASTFromStringObject + 500
        68  Python3                             0x0000000102a74a1c PyRun_StringFlags + 152
        69  Python3                             0x0000000102a74928 PyRun_SimpleStringFlags + 64
        70  Python3                             0x0000000102a90e78 Py_RunMain + 524
        71  Python3                             0x0000000102a91720 Py_Main + 372
        72  Python3                             0x0000000102a917c0 Py_BytesMain + 40
        73  dyld                                0x0000000194cdbf28 start + 2236
)

**Comment by louisnw01** [comment]
Hey @premkn,

Are you trying to display more than 10 charts in separate windows?

**Comment by premkn** [comment]
Hi @louisnw01 ,

Thanks for your response. 

The idea is to run parallel algo for individual stocks and display real-time charts for them. Error is occurring at the first chart load itself, the threads load one after the other load is completed and I am running the chart for 4 stocks. Not sure why it is loading 10 charts. 

This same logic used to work fine with 1.0.14.3

Regards,
Prem

**Comment by premkn** [comment]
Hi @louisnw01 ,

The issue is in my code, there are multiple strategies that get loaded and I run one Strategy for one script. On initializing the strategies they also initialize the chart. Due to this, the number of charts initializing is exceeding 10. 

Removed the Chart initialization from Statergy init, this solved the issue. 

Thanks,
Premkumar
