### ISSUE TITLE
Line hide icon persist in legend beyond delete

### ISSUE THREAD

**Issue by algotrader-au** [louisnw01/lightweight-charts-python#75]
Great package, thanks for your work. Really!

When I delete a line it doesn't appear to delete from the legend, or at least the hide icon persists beyond delete.  I'm calling the line.delete() function.   If I delete/add a bunch of lines, I end up with a very large number of open eyes in the legend.

Am I missing something?

**Comment by louisnw01** [comment]
Hey @algotrader-au,

Thanks!

This is a bug; will be fixed in the next update.

**Comment by algotrader-au** [comment]
Thanks @louisnw01, much appreciated.
