### ISSUE TITLE
Chart wont launch from VSCode (i.e. freezes indefinitely) , but creating webview window works fine

### ISSUE THREAD

**Issue by xemltil** [louisnw01/lightweight-charts-python#76]
Hello - I am having issue launching Chart() from VSCode.  No error, just freezes.

Py code (that works):
---------------------------------------------------
import webview
webview.create_window('', 'https://www.google.com')
webview.start()

Jupyter output from within VSCode (window launches fine):
------------------------------------------------------
15:38:56.057 [info] Process Execution: ~\anaconda3\python.exe c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.7.1002162226-win32-x64\pythonFiles\normalizeSelection.py
15:38:56.172 [info] Generated code for 1 = <ipython-input-1-85448249188f> with 4 lines
15:38:56.179 [info] Kernel acknowledged execution of cell 21 @ 1692560336176
15:39:11.626 [info] End cell 21 execution @ 1692560351621, started @ 1692560336176, elapsed time = 15.445s

Py code using lightweight_charts (that does not run):
---------------------------------------------------
import yfinance as yf
df = yf.Ticker("aapl").history(start="2020-06-02", end="2020-06-07", interval="1d")
df = df.reset_index().rename(columns = {"Date": "time", "Open": "open", "High": "high", "Low": "low", "Close": "close", "Volume": "volume"})
import pandas as pd
from lightweight_charts import Chart
chart = Chart()  # <------ chokes heres
chart.set(df)
chart.show(block=False)

Jupyter output from within VSCode (window does not launch):
------------------------------------------------------
15:42:02.847 [info] Process Execution: ~\anaconda3\python.exe c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.7.1002162226-win32-x64\pythonFiles\normalizeSelection.py   
15:42:02.951 [info] Generated code for 2 = <ipython-input-2-cb7628dce2d8> with 6 lines
15:42:02.967 [info] Kernel acknowledged execution of cell 22 @ 1692560522960
15:42:04.274 [warn] StdErr from Kernel Process Traceback (most recent call last):
  File "<string>", line 1, in <module>
15:42:04.274 [warn] StdErr from Kernel Process File "c:\Users\<username>\anaconda3\envs\fincode\lib\multiprocessing\spawn.py", line 116, in spawn_main
15:42:04.275 [warn] StdErr from Kernel Process exitcode = _main(fd, parent_sentinel)
  File "c:\Users\<username>\anaconda3\envs\fincode\lib\multiprocessing\spawn.py", line 125, in _main
15:42:04.275 [warn] StdErr from Kernel Process prepare(preparation_data)
  File "c:\Users\<username>\anaconda3\envs\fincode\lib\multiprocessing\spawn.py", line 236, in prepare
15:42:04.276 [warn] StdErr from Kernel Process _fixup_main_from_path(data['init_main_from_path'])
  File "c:\Users\<username>\anaconda3\envs\fincode\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
15:42:04.276 [warn] StdErr from Kernel Process main_content = runpy.run_path(main_path,
  File "c:\Users\<username>\anaconda3\envs\fincode\lib\runpy.py", line 288, in run_path
15:42:04.277 [warn] StdErr from Kernel Process code, fname = _get_code_from_file(run_name, path_name)
  File "c:\Users\<username>\anaconda3\envs\fincode\lib\runpy.py", line 252, in _get_code_from_file

Please note installed library version:
------------------------------------------------------
lightweight-charts        1.0.16.1                 pypi_0    pypi

Additional notes: 
------------------------------------------------------
- I can successfully launch the lightweight_charts from this python environment if I use SPYDER

**Comment by louisnw01** [comment]
Hey @xemltil,

Due to the `Chart` object's use of sub-processing, it must be enclosed within an `if __name__ == '__main__'` conditional. 

Let me know if this works.

Louis

**Comment by xemltil** [comment]
Hi - Thanks for the quick reply.  This code works when run from Spyder, but not when run from VSCode.


New py code (still no dice):
-------------------------------------------------------------------
import yfinance as yf
import pandas as pd
from lightweight_charts import Chart

if __name__ == "__main__":
    df = yf.Ticker("aapl").history(start="2020-06-02", end="2020-06-07", interval="1d")
    df = df.reset_index().rename(
        columns={
            "Date": "time",
            "Open": "open",
            "High": "high",
            "Low": "low",
            "Close": "close",
            "Volume": "volume",
        }
    )

    chart = Chart()
    chart.set(df)
    chart.show(block=False)

Jupyter output from within VSCode (window does not launch):
-------------------------------------------------------------------
17:31:31.279 [info] Process Execution: ~\anaconda3\python.exe c:\Users\<username>\.vscode\extensions\ms-toolsai.jupyter-2023.7.1002162226-win32-x64\pythonFiles\normalizeSelection.py
17:31:31.381 [info] Generated code for 1 = <ipython-input-1-e88a2330adf0> with 19 lines
17:31:31.400 [info] Kernel acknowledged execution of cell 67 @ 1692567091391
17:31:32.807 [warn] StdErr from Kernel Process Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\<username>\anaconda3\envs\fincode\lib\multiprocessing\spawn.py", line 116, in spawn_main
17:31:32.808 [warn] StdErr from Kernel Process exitcode = _main(fd, parent_sentinel)
  File "c:\Users\<username>\anaconda3\envs\fincode\lib\multiprocessing\spawn.py", line 125, in _main
17:31:32.808 [warn] StdErr from Kernel Process prepare(preparation_data)
  File "c:\Users\<username>\anaconda3\envs\fincode\lib\multiprocessing\spawn.py", line 236, in prepare
17:31:32.809 [warn] StdErr from Kernel Process _fixup_main_from_path(data['init_main_from_path'])
  File "c:\Users\<username>\anaconda3\envs\fincode\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
17:31:32.809 [warn] StdErr from Kernel Process main_content = runpy.run_path(main_path,
  File "c:\Users\<username>\anaconda3\envs\fincode\lib\runpy.py", line 288, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "c:\Users\<username>\anaconda3\envs\fincode\lib\runpy.py", line 252, in _get_code_from_file
17:31:32.810 [warn] StdErr from Kernel Process with io.open_code(decoded_path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\Users\\<username>\\Documents\\FinancialCoding\\prep_fin_data.py'

**Comment by louisnw01** [comment]
Error appears unrelated to this library:

```
FileNotFoundError: [Errno 2] No such file or directory: 'c:\Users\\Documents\FinancialCoding\prep_fin_data.py'
```

Check your paths perhaps?

Louis

**Comment by xemltil** [comment]
Cool, worked.  

Nothing in the code was explicitly calling that "prep_fin_dat.py" file, but somehow \multiprocessing\spawn.py was iterating for files looking for that archival *.py file.  I created and inserted a dummy file "prep_fin_dat.py" that doesnt do anything.  Its working now and I will trouble shoot bug later..

**Comment by xemltil** [comment]
Oh man.  This is amazing.  SO MUCH QUICKER TO GOAL in python than JS.  You are a saint kind Sir!!
