### ISSUE TITLE
Table and 

### ISSUE THREAD

**Issue by xemltil** [louisnw01/lightweight-charts-python#77]
Follow-up questions:

1.  Do you have an example of Tables and Row class usage? i.e. create_table() Will is be implemented like Pine Code in TV where you create a Table object and subsequently add row object to it?
2.  Do you have an example of how to plot two times series on the same plot using subchart?  i.e. create_subchart()

Many thanks.  I will send donation your way after this week,

Example Pine Code:
------------------------------------
var tbl = table.new(position.top_left, 4, 40, frame_color=#151715, frame_width=1, border_width=2, border_color=color.new(color.white, 95))

if barstate.islast
    
    table.cell(tbl, 0, 0, text = " Long>>>                  VWAP AA Scanner                  <<<Short ", bgcolor = color.new(color.black, 85), text_color = #1fbaee) 
    table.merge_cells(tbl, 0, 0, 8, 0)
    table.cell(tbl, 0, 1, '-DMI',  width = col_width,     text_halign = text.align_center, bgcolor = color.new(color.black, 85), text_color =#1fbaee, text_size = size.normal)
    table.cell(tbl, 1, 1, '-3SD',  width = col_width,     text_halign = text.align_center, bgcolor = color.new(color.black, 85), text_color =#1fbaee, text_size = size.normal)
    table.cell(tbl, 2, 1, '-2SD',  width = col_width,     text_halign = text.align_center, bgcolor = color.new(color.black, 85), text_color =#1fbaee, text_size = size.normal)

**Comment by xemltil** [comment]
Ah, ok.  I think I figured out the 'create_table()' mechanics to generate a floating TV-styled table.

But I could probably benefit most from a create_subchart() example.  Appreciate any thoughts.

Example create_table() functional call:
---------------------------------------------------
if __name__ == "__main__":
    chart = Chart(toolbox=True)
    chart.legend(True)
    chart.events.search += on_search
    chart.events.search += on_tick
    chart.topbar.textbox("symbol", "SPY")
    chart.topbar.switcher(
        "timeframe",
        ("1mn", "15mn", "1hr", "4hr"),
        default="1mn",
        func=on_timeframe_selection,
    )
    df = get_bar_data("SPY", "1mn")

    table = chart.create_table(
        width=800,
        height=200,
        headings=["Time", "Open", "High", "Low", "Close", "Volume"],
        position="right",
        draggable=True,
    )

    # Update the table with the initial data
    for _, row in df.tail(10).iterrows():
        table.new_row(
            row["time"],
            row["open"],
            row["high"],
            row["low"],
            row["close"],
            row["volume"],
        )

    table.visible(visible=True)

    # subchart = chart.create_subchart(position="bottom", sync=True)

    chart.set(df)
    chart.show(block=True)

**Comment by louisnw01** [comment]
Read [here](https://lightweight-charts-python.readthedocs.io/en/latest/common_methods.html#synced-line-chart-example) for the subchart examples.

Louis

**Comment by xemltil** [comment]
Perfect.  Crystal clear. This is a really complete port from JS.  I love the clarity and options you provided.  Any more complex builds are still possible from the JS function option.  Thank you and really appreciate your hardwork!!!
