### ISSUE TITLE
Line update not working

### ISSUE THREAD

**Issue by Lucifer-lab74** [louisnw01/lightweight-charts-python#78]
Hey, so I am trying to update line. There is no error but line data doesn't show on chart when updated. I am passing pd.series object with same column name as used when setting up the line.

**Comment by louisnw01** [comment]
Hey, please provide a minimal reproducible example including any data.

Louis

**Comment by Lucifer-lab74** [comment]
Sorry for late response:

import pandas as pd
import pandas_ta as ta
from time import sleep
from lightweight_charts import Chart

if __name__ == '__main__':

    chart = Chart()
    line = chart.create_line(color='#ffffff', price_line=False, price_label=False, width=3)

    df1 = pd.read_csv('ohlcv.csv')
    df2 = pd.read_csv('next_ohlcv.csv')

    sma = ta.sma(df1['close'], 2)
    sma = pd.DataFrame(sma)
    sma = sma.fillna(0)
    sma['date'] = df1['date']
    chart.set(df1)
    line.set(sma, 'SMA_2')

    chart.show()

    last_close = df1.iloc[-1]

    for i, series in df2.iterrows():
        chart.update(series)
        if series['close'] > 20 > last_close:
            chart.marker(text='The price crossed $20!')
        line.update(pd.Series({'date': series['date'], 'SMA_2': 30}))
        last_close = series['close']
        sleep(0.1)


you can use any ohlcv data provided examples

**Comment by louisnw01** [comment]
Hey,

line names are now declared in `create_line`:

```python
line = chart.create_line(name='SMA_2')
```

Which means the name does not need to be provided to `line.set`.

Louis

**Comment by Lucifer-lab74** [comment]
Okay thanks will try that
