### ISSUE TITLE
How do you fill a region between 2 horizontal lines? i.e. Pine Script: fill(upband, bullzoneband, color=#1fbaee, transp=85)

### ISSUE THREAD

**Issue by xemltil** [louisnw01/lightweight-charts-python#79]
Hello - 

I am trying to create a sub_chart with the RSI Indicator and would like to color different threshold regions of the subchart.  I include the corresponding TradingView Pine Script below.  I am looking for an analogous  Pine Scrip "fill()" function in the new Python lightweight-charts library.

Questions:
(1) Do you have any strategies on how to fill a region between 2 horizontal lines with a certain color? 
(2) Does that currently require using javascript functions from lightweight charts? If so can you point me to a minimal example?

Many thanks!!!

Example RSI Code from Pine Script in Trading View:
------------------------------------------------------------------
study(title="RSI+EMA", shorttitle="RSI+EMA", overlay=false)

//RSI
src = close, len = input(14, minval=1, title="RSI Length")

up = rma(max(change(src), 0), len)
down = rma(-min(change(src), 0), len)

bullzoneband= hline(65,"Bull Line",color=#1fbaee)
upband = hline(80,"Upper Band",color=#1fbaee)
fill(upband, bullzoneband, color=#1fbaee, transp=85)

middlelinecolor = color(white, 50)
bearzoneband= hline(35,"Bear Line",color=#d41d6d)
downband = hline(20,"Lower Line",color=#d41d6d)
mband = hline(50, "Middle Line", color=middlelinecolor)
fill(bearzoneband, downband, color=#d41d6d, transp=85)

rsi = down == 0 ? 100 : up == 0 ? 0 : 100 - (100 / (1 + up / down))
plot(rsi, color=#cfff83,linewidth=3,transp=0)

//RSIEMA
lenema = input(12, minval=1, title="RSI EMA Length")
out = ema(rsi, lenema)
col=out >= out[1] ? #1fbaee : #d41d6d
plot(out, title="RSI EMA", color=col, linewidth=2,style=line,transp=30)

**Comment by louisnw01** [comment]
Hey @xemltil,

Unfortunately Lightweight Charts has not integrated a way to to draw along the Y axis, meaning shading between lines and boxes are not possible.

**Comment by yakir4123** [comment]
Is there an update about this maybe? an alternative way that is better than just 2 lines?
