### ISSUE TITLE
Polygon.io Time stamps come in at UTC/GMT, how to access Polygon Charts data to manually format to EST?

### ISSUE THREAD

**Issue by xemltil** [louisnw01/lightweight-charts-python#80]
Context:  Polygon.io Time stamps come in at UTC/GMT.  Would be nice to reformat to mimic markets.

Question:  Is there a way to directly access the Polygon.io Polygon Chart data after it is pulled in, so as to modify or reformat the time & OLHC data?

Source:
https://polygon.io/knowledge-base/article/what-timezone-are-polygon-timestamps-in

**Comment by louisnw01** [comment]
Hey @xemltil,

The current version of the library does not support this behaviour, but I would be happy to integrate something like this.

I'm just trying to think of a way users could access the data after it has been pulled from polygon, but before setting the chart. Perhaps a generic `polygon.get_bar_data` which returns a dataframe?



For now, you could edit the source in `polygon.py`:

Line 175, `df['time']` (Static data)
```python
df['time'] = pd.to_datetime(df['time'], unit='ms')
```

Line 262 `data['t']` (Live data)

```python
data['t'] = pd.to_datetime(data.pop('s'), unit='ms') if 't' not in data else pd.to_datetime(data['t'], unit='ms')
```

**Comment by xemltil** [comment]
Thanks!!!  I inserted a simple timedelta snippet to the code, at the specified locations, that subtracted 4 hours from UTC to make it into EST market hours.

Line 175:
df['time'] = pd.to_datetime(df['time'], unit='ms')
df['time'] = df['time'] - pd.Timdelta('-4 hours')

Line 262: 
data['t'] = pd.to_datetime(data.pop('s'), unit='ms') if 't' not in data else pd.to_datetime(data['t'], unit='ms')
df['t'] = df['t'] - pd.Timdelta('-4 hours')

Note.  Going at it the other way of setting the timezone of the pandas dataframe is trickier becuase it require the timestamp to be assigned to dataframe index.  It change down stream calls on the time column.

Ex. df.index.tz_localize("UTC").tz_convert("America/New_York").strftime("%Y-%m-%d %H:%M:%S")

Many thanks!!!  The python lightweight-charts is amazing.  Its gonna be a popular module,

**Comment by krazatchu** [comment]
My fix, polygon.py, inside _set:

# df['time'] = pd.to_datetime(df['time'], unit='ms')
df['time'] = pd.to_datetime(df['time'], unit='ms', origin='unix', utc=True).dt.tz_convert(self.eastern).dt.tz_localize(None)

And an import:
from pytz import timezone
self.eastern = timezone('US/Eastern')

**Comment by louisnw01** [comment]
Hey,

Added the `get_bar_data` module function in the latest version.

Louis
