### ISSUE TITLE
Table scroll

### ISSUE THREAD

**Issue by daladaysoft** [louisnw01/lightweight-charts-python#81]
Hi,
Thanks for the job and this nice implementation! 
Used with QtChart and Chart, works very well.
Just a question, is there any chance for Table objects to manage a scroll in the future?

**Comment by louisnw01** [comment]
Hey @daladaysoft,

This is a great idea; i'll aim to implement in the next update.

Louis

**Comment by daladaysoft** [comment]
Hello @louisnw01 
Super :-) And thanks for the very fast reply!

**Comment by louisnw01** [comment]
Implemented in the latest version.

Louis
