### ISSUE TITLE
Table on click callback are not working

### ISSUE THREAD

**Issue by AnveshMora** [louisnw01/lightweight-charts-python#82]
Hi,
I was trying the library for the first time and chart are loading very fast and awesome. All the implementations are done on streamlit.

So I was trying implement tables, for some reason func calling is not getting called.

is it a issue with Streamlit or anything i'm missing the library.

I've use this example code and try load the chart using chart.load() function instead of show():
https://github.com/louisnw01/lightweight-charts-python/blob/34ce3f7199b894e53b9cb07fc78adfb728eb2edf/docs/source/tables.md?plain=1#L83-L118

**Comment by louisnw01** [comment]
Hey @AnveshMora,

Unfortunately Streamlit is static, meaning data cannot be passed to and from and the charts cannot be updated after calling `load`.

See [here](https://lightweight-charts-python.readthedocs.io/en/latest/charts.html#streamlitchart).

Louis
