### ISSUE TITLE
Volume up_color and down_color not working, scaling works though

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#83]
![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/0c24d8b5-14b3-4ff8-be93-c7ae642975d8)

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/1655cc63-20aa-4b6a-a1d8-111e2cdecc4f)

Unlesss you overide these values, the down_color and up_color for the volume does not work

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/021efe51-2bde-484a-9c58-75d62b4be480)

**Comment by louisnw01** [comment]
Hey @karunkrishna ,
Unable to reproduce; have you tried the `5_styling` example?

**Comment by karunkrishna** [comment]
![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/8295df21-f052-4a12-9d23-fb5fcf125b7b)

Tried that just now and just changed the up_color....seems to still use the default. 
I'll try reinstalling the package. 
What version are you using?

**Comment by louisnw01** [comment]
Did you try the example exactly? (just the script, `ohlcv.csv` etc.)

**Comment by karunkrishna** [comment]
![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/f12bd011-07d9-48f6-ade4-45ec6b66dfba)

Yeah that seems to work, I'll double check if I messed up anything on my-end. 
Great pacakge!

**Comment by metph86** [comment]
looks like the colors are hard-coded into the pandas df so for anyone having the same issue, you need to call chart.volume_config() before setting the dataframe with chart.set(df):

`chart.volume_config(up_color='#cccccc', down_color='#CCCCCC')`
`chart.set(df)`
