### ISSUE TITLE
Bars over Candles

### ISSUE THREAD

**Issue by krazatchu** [louisnw01/lightweight-charts-python#87]
If you prefer bars to candles - line 48 of func.js can be changed to:

`chart.series = chart.chart.addBarSeries({`

Most of the style options are not required for bars.
And they don't seem to render as nicely as they do on the non-lightweight tv, they fade out rather quickly when zooming out.
Setting the style thinBars: false, is not very visually pleasing.

**Comment by louisnw01** [comment]
If more people request this I will look into implementing, but not planned as of now.

Louis
