### ISSUE TITLE
Adding horizontal lines for SubChart

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#88]
Can't seem to apply horizontal line on subchart

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/cf391ee0-d67b-41eb-bec3-d7c73d949b5d)

**Comment by louisnw01** [comment]
Horizontal lines are plotted based on a series (candles, lines etc), and `chart.horziontal_line` places the line relative to candle data. So you'll need to use `line.horizontal_line` on a chart without candle data.

Louis

**Comment by karunkrishna** [comment]
Is there an example of this, can't seem to figure out how a chart that does not have candles just lines to create a horizontal line

**Comment by karunkrishna** [comment]
nvm,  I see what you mean. I need to find the overlaying line object and then apply the horizontal line to that. 
![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/87dbcf00-d388-4d2a-95e0-75288c8dce59)

Will also see if trendline behaves in the same manner

**Comment by germangar** [comment]
I'm trying to figure this same thing out and I'm so confused. Do you have to create them using a method in the rsi line object?

**Comment by jamesbal2015** [comment]
does anyone respond ?

can anyone help with  running the program full charting ,  seem to not work
now ?

**Comment by germangar** [comment]
I just got it to work. It's weird, but yeah, it's just that.

You create your, let's say rsi line, and in the object of the rsi line you call the horizontal_line(value) method to add the horizontal line.

This is my code. It there are shenanigans made in between, but you I hope it helps getting the point
```
rsi = calcRSI( 'close', 14 )
    rsiplot = plot( rsi.name, rsi.getSeries(), context.bottomPanel )
    if( rsiplot != None ):
        rsiplot.line.horizontal_line(30)
```

**Comment by jamesbal2015** [comment]
do you know how to get the whale charting up and running,   no responses
from anyone ?    cant seem to work out how to laid and run from the guhub
whole download of the charting program .

any ideas?,
