### ISSUE TITLE
Plot window is showing but no charts is drawn on WSL

### ISSUE THREAD

**Issue by Yogalholic** [louisnw01/lightweight-charts-python#89]
> ```python
> import pandas as pd
> from lightweight_charts import Chart
> 
> 
> if __name__ == '__main__':
>     
>     chart = Chart()
>     
>     # Columns: | time | open | high | low | close | volume (if volume is enabled) |
>     df = pd.read_csv('ohlcv.csv', index_col=0).iloc[:100]
>     print(df)
>     chart.set(df)
>     
>     chart.show(block=True)
> ```
python 3.10.12

The output:
![webview](https://github.com/louisnw01/lightweight-charts-python/assets/64720683/d0f71add-f396-4e89-8fda-41a6b9139103)
I can move the cursor (it's not a still image) but no charts is drawn

I have try this:
> ```python
> import webview
> 
> webview.create_window('', 'https://www.google.com')
> webview.start()
> ```
and it's working fine
The window wasn't showing at the beginning so I have installed many packages related to pywebview and Qt so maybe there is a conflict.
Thanks

edit: I'm sorry I've failed to add a label

**Comment by louisnw01** [comment]
Hey @Yogalholic,

can you confirm that you are using the same data as provided in the `1_setting_data` example? If the issue still persists with this data, could you provide a screenshot of the web console (`Chart(debug=True)`, right click to open inspector)

**Comment by Yogalholic** [comment]
> Hey @Yogalholic,
> 
> can you confirm that you are using the same data as provided in the `1_setting_data` example? If the issue still persists with this data, could you provide a screenshot of the web console (`Chart(debug=True)`, right click to open inspector)

Thanks

![Screenshot 2023-08-31 063142](https://github.com/louisnw01/lightweight-charts-python/assets/64720683/787c75cb-db6b-4c6d-885c-bb2d5186a672)

**Comment by louisnw01** [comment]
Seems like the same problem as #63.

**Comment by Yogalholic** [comment]
It works thanks. I did the same mistake of not adding a label on the issue, sorry again. I think it would useful if you add a warning about using the library with docker or WSL.
