### ISSUE TITLE
Go to Timestamp feature

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#91]
Not sure if this exists already :

1. If we create a table with historical trades with a _start_ and _end_ period 
2. By clicking on the table row, is it possible to move the Primary and Subchart to that start/end period

Looking to quickly review historical trade signals without having to re-render

**Comment by louisnw01** [comment]
Hey @karunkrishna,

At the moment this is not possible, but Lightweight Charts does offer this with `setVisibleRange`. I'll look to implement in the next update.

Louis

**Comment by louisnw01** [comment]
Implemented the `set_visible_range` method in the latest version.
