### ISSUE TITLE
Dynamic charts width and height

### ISSUE THREAD

**Issue by blitz1939** [louisnw01/lightweight-charts-python#92]
Hello,

May I know if there is any way to modify the chart or subchart height and width? For example: when a topbar button is clicked, the main chart inner height can be set to 0.6 from 1 to create a subchart of height = 0.4, and when another button is clicked the subchart height can again be reduced to 0.2 to introduce a new subchart of height = 0.2.

Please let me know if I'm missing something as I had gone through the documents but couldn't find any related information.

Thanks.

**Comment by louisnw01** [comment]
Hey @blitz1939,

At the moment there is no way to do this, but this is a great idea.

How about a `resize` method for charts and subcharts?

**Comment by karunkrishna** [comment]
Just like you are able to hide the create_line indicators to reduce noise....this will open up the possibility to hide subcharts 
I assume if main chart height is set to 1; that would result in the subchart(s) to be hidden? Are they still rendering behind the scene?

**Comment by louisnw01** [comment]
Implemented the `resize` method in the latest version.

@karunkrishna for your use case, you would need to set the main chart height to 1, and the subchart height to 0.

Louis
