### ISSUE TITLE
clearing line data with set()

### ISSUE THREAD

**Issue by julianstannard** [louisnw01/lightweight-charts-python#93]
In reference to this:
#51 

I cant get this to work. - is there somthing i am doing wrong?
I have tried both giving it no arguments and an empty data frame. Both dont clear the line data that is already in there, but when i dont give it any arguments it complains:

"
TypeError: Line.set() missing 1 required positional argument: 'df'
"
using v1.0.17

Cheers

**Comment by louisnw01** [comment]
Hey @julianstannard,

Either of these should work:
```python
line.set(pd.DataFrame())
line.set(None)
```

Louis

**Comment by julianstannard** [comment]
thank you
