### ISSUE TITLE
Circle and Square marker shapes not working

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#94]
![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/7eb42162-1fe9-4008-8fd1-969e02fa9ccf)

Are we able to add  \n for the text parameter?
Preferably if we can do f-string text alignment https://www.geeksforgeeks.org/string-alignment-in-python-f-string/

**Comment by louisnw01** [comment]
Fixed in the latest version.
