### ISSUE TITLE
line.update sync with chart.update_from_tick

### ISSUE THREAD

**Issue by MarcellThoth** [louisnw01/lightweight-charts-python#96]
First of all great work Louis! Love what you have done.

May I ask how would you go about updating the chart with tick data and also updating the indicators, lets say for example a simple moving average on a 1 minute chart. I see the update_from_tick arranges itself into 1 minute bars as stated in the documents. Should i be calling for new data at each minute for the indicator to keep it up to data?

**Comment by louisnw01** [comment]
Hey @MarcellThoth,

This would be my preference as updating the indicator after each tick can be quite expensive.

You could use the new_bar event (`chart.events.new_bar += update_indicator`) which would emit at each 1min interval in your case.

**Comment by MarcellThoth** [comment]
Great! Perfect! Thanks! Keep up the good work!

**Comment by louisnw01** [comment]
You're welcome. And thank you for the sponsor!
