### ISSUE TITLE
Scroll horizontal  seems to be broke on latest  version

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#98]
In latest version, clicking on the main chart to scroll left results in the entire MS window to move

**Comment by louisnw01** [comment]
Unable to reproduce on macOS; could you provide a screenshot of the web console using `debug`?

**Comment by karunkrishna** [comment]
There looks to be no logging in the Chart(debug=True)
However I have attached a video on the issue. Basically trying to click and scroll to the left or right results in the entire window moving

Pinch to zoom on the time axis also results in the window moving instead of the chart 

https://github.com/louisnw01/lightweight-charts-python/assets/2157606/e4c38ebf-cb96-466f-85d6-313903b7aa65

**Comment by louisnw01** [comment]
Thanks for the video; could you do a minimal pywebview example using `create_window` and see if it has similar behaviour?

**Comment by karunkrishna** [comment]
Great upgrading to pywebview 4.3.2 fixed the issue
![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/1803050c-8877-45b3-ab47-b06192dea7b7)
