### ISSUE TITLE
Drawing line style + rounding start and end dates

### ISSUE THREAD

**Issue by karunkrishna** [louisnw01/lightweight-charts-python#99]
What are your thoughts on this issue?
1. Seems like the marker works regardless of  start or end time matching a bar close time
2. However if the start_time or end_time for trendlines does not reference a bar's closing time the trendline fails to render

This is a bit problematic for two reason:
- What if we draw trendline on a 1 minute bar chart, but then switch view to TICK or larger frequency bar (i.e 1 Min to 5 Min) then this trendline disappears
- Say you are drawing the trendline to indicate your trade entry price and exit price that may not always align with the bar close time (i.e on your broker the trade could have filled during the bar)

I believe in the past you mentioned that there are two ways to draw line, (1) on chart-obj which requires ohlcv bar data, or using  (2) line-obj which does not need underling bar to draw. Is this feature also available for trendlines? 

Also do you know if trendline support dash, dotted style? Seems like solid is default without option to change....

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/e22a7e50-3eb6-4db4-9a8c-d91cdd467d3b)

**Comment by louisnw01** [comment]
Hey @karunkrishna,

Originally, the trendline `start_date` and `end_date` were rounded to the nearest interval to prevent this, however this caused issues for irregular timeframes. In order to mitigate this, you will need to round your `start_date` and `end_date` to the nearest interval time. (eg. 10:46:50 would become 10:45:00 for a 5min chart)

When switching timeframes, for example 1min to 5min, the `render_drawings` parameter of `chart.set` should be set to `True`, which will automatically recalculate the necessary datapoints based on the new timeframe to draw the trendline.

Louis

**Comment by louisnw01** [comment]
As for drawing trendlines without candle data, this is not possible at the moment; can I ask what the usecase of this would be?

And dotted/dash styles have not been implemented for trend lines, but i'll look to add it in the future.

**Comment by karunkrishna** [comment]
It was an assumption.....it might be an option to draw trend without being very specific of the start_time and end_time.
I think drawing trendlines on line overlay (indicators) are very niche and not worth implementing

**Comment by louisnw01** [comment]
I'll look into adding a `round` parameter to `trend_line` and `ray_line`, so you have the option.

Louis

**Comment by louisnw01** [comment]
Styles are now implemented in the latest version.

Louis

**Comment by karunkrishna** [comment]
There is something that I noticed with my implementation which was just to round the pandas pnl entry and exit. 

If I round the time but the time is not on the Chart the line does not complete correctly. For example the timestamp for exit trade is 17:00 but if you look at the first two plots. The time jumps from 16:55 to 18:00 therefore does not have the corresponding  17:00 bar. The line in this situation seems to pick an arbitrary end-time

Will test on the latest release once out. 

![image](https://github.com/louisnw01/lightweight-charts-python/assets/2157606/2fe26258-f490-427f-bb71-01036d8a4ee9)

**Comment by louisnw01** [comment]
Added the `round` parameter in the latest version.

Louis
